[usb] add HAS_IOMEM dependency to USB_ISP116X_HCD
Message-id: <1465525749-9195-86-git-send-email-torez@redhat.com>
Patchwork-id: 150005
O-Subject: [RHEL7 BZ1332712 v2 085/196] usb: add HAS_IOMEM dependency to USB_ISP116X_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit ca23d3b747f8ed294fe9e809dca0ed518fffc8cc
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:36 2016 +0100

    usb: add HAS_IOMEM dependency to USB_ISP116X_HCD

    drivers/usb/host/isp116x-hcd.c: In function isp116x_remove:
    drivers/usb/host/isp116x-hcd.c:1552:2: error: implicit declaration of function iounmap [-Werror=implicit-function-declaration]
      iounmap(isp116x->data_reg);
      ^
    drivers/usb/host/isp116x-hcd.c: In function isp116x_probe:
    drivers/usb/host/isp116x-hcd.c:1604:2: error: implicit declaration of function ioremap [-Werror=implicit-function-declaration]
      addr_reg = ioremap(addr->start, resource_size(addr));
      ^
    drivers/usb/host/isp116x-hcd.c:1604:11: warning: assignment makes pointer from integer without a cast [enabled by default]
      addr_reg = ioremap(addr->start, resource_size(addr));
               ^
    drivers/usb/host/isp116x-hcd.c:1613:11: warning: assignment makes pointer from integer without a cast [enabled by default]
      data_reg = ioremap(data->start, resource_size(data));
               ^

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>