[tools] perf intel pt decoder: clang has no -Wno-override-init
Message-id: <20170807084247.7531-65-jolsa@redhat.com>
Patchwork-id: 182004
O-Subject: [PATCH RHEL7.5 64/94] perf intel pt decoder: clang has no -Wno-override-init
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 35670dd0c9b421f1bb6ca69f389aa6b657b57d49
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 16:18:02 2017 -0300

description
===========
So set it only for other compilers, allowing us to overcome yet another
build failure due to an inexistent clang -W option:

  error: unknown warning option '-Wno-override-init'; did you mean '-Wno-override-module'? [-Werror,-Wunknown-warning-option]

Signed-off-by: Rafael Aquini <aquini@redhat.com>