[infiniband] i40iw: avoid potential uninitialized variable use
Message-id: <1470233085-12276-22-git-send-email-sassmann@redhat.com>
Patchwork-id: 156422
O-Subject: [RHEL7.3 PATCH 21/55] i40iw: avoid potential uninitialized variable use
Bugzilla: 1283405
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1283405
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11481250

gcc finds that the i40iw_make_cm_node() function in the recently added
i40iw driver uses an uninitilized variable as an index into an array
if CONFIG_IPV6 is disabled and the driver uses IPv6 mode:

drivers/infiniband/hw/i40iw/i40iw_cm.c: In function 'i40iw_make_cm_node':
drivers/infiniband/hw/i40iw/i40iw_cm.c:2206:52: error: 'arpindex' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  ether_addr_copy(cm_node->rem_mac, iwdev->arp_table[arpindex].mac_addr);

As far as I can tell, this code path can not be used because the ipv4
variable is always set with CONFIG_IPV6 is disabled, but it's better
to be sure and prevent the undefined behavior, as well as shut up
that warning in a proper way.

This adds an 'else' clause for the case we get the warning about,
causing the function to return an error in a controlled way.
To avoid adding extra mess with combined io()/#ifdef clauses,
I'm also converting the existing #ifdef into a more readable
if(IS_ENABLED()) check.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: f27b4746f378 ("i40iw: add connection management code")
Acked-by: Mustafa Ismail <Mustafa.ismail@intel.com>
Signed-off-by: Doug Ledford <dledford@redhat.com>
Signed-off-by: Stefan Assmann <sassmann@redhat.com>
(cherry picked from commit 2fe7857176ad6b70e8b2a318506525410e774f34)
Signed-off-by: Rafael Aquini <aquini@redhat.com>