[usb] add HAS_IOMEM dependency to USB_SL811_HCD
Message-id: <1465525749-9195-90-git-send-email-torez@redhat.com>
Patchwork-id: 150054
O-Subject: [RHEL7 BZ1332712 v2 089/196] usb: add HAS_IOMEM dependency to USB_SL811_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit cfa33eaeeeb89ec90ea7062b0e4035552b8dbb56
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:43 2016 +0100

    usb: add HAS_IOMEM dependency to USB_SL811_HCD

      CC      drivers/usb/host/xhci-mtk.o
    drivers/usb/host/xhci-mtk.c:135:12: warning: xhci_mtk_host_disable defined but not used [-Wunused-function]
     static int xhci_mtk_host_disable(struct xhci_hcd_mtk *mtk)
                ^
    drivers/usb/host/xhci-mtk.c:313:13: warning: usb_wakeup_enable defined but not used [-Wunused-function]
     static void usb_wakeup_enable(struct xhci_hcd_mtk *mtk)
                 ^
    drivers/usb/host/xhci-mtk.c:321:13: warning: usb_wakeup_disable defined but not used [-Wunused-function]
     static void usb_wakeup_disable(struct xhci_hcd_mtk *mtk)
                 ^
      CC      drivers/usb/host/sl811-hcd.o
    drivers/usb/host/sl811-hcd.c: In function sl811h_remove:
    drivers/usb/host/sl811-hcd.c:1607:3: error: implicit declaration of function iounmap [-Werror=implicit-function-declaration]
       iounmap(sl811->data_reg);
       ^
    drivers/usb/host/sl811-hcd.c: In function sl811h_probe:
    drivers/usb/host/sl811-hcd.c:1669:3: error: implicit declaration of function ioremap [-Werror=implicit-function-declaration]
       addr_reg = ioremap(addr->start, 1);
       ^
    drivers/usb/host/sl811-hcd.c:1669:12: warning: assignment makes pointer from integer without a cast [enabled by default]
       addr_reg = ioremap(addr->start, 1);
                ^
    drivers/usb/host/sl811-hcd.c:1675:12: warning: assignment makes pointer from integer without a cast [enabled by default]
       data_reg = ioremap(data->start, 1);
                ^

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>