[usb] host: ehci.h: move pointer operator to name side
Message-id: <1465525749-9195-38-git-send-email-torez@redhat.com>
Patchwork-id: 150001
O-Subject: [RHEL7 BZ1332712 v2 037/196] usb: host: ehci.h: move pointer operator to name side
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit c021170f1da3448d398614b6bc546f3dee256979
Author: Geyslan G. Bem <geyslan@gmail.com>
Date:   Mon Jan 25 22:44:51 2016 -0300

    usb: host: ehci.h: move pointer operator to name side

    The pointer operator must be sticked to name.

    Caught by checkpatch:
    ERROR: "foo * bar" should be "foo *bar"

    Signed-off-by: Geyslan G. Bem <geyslan@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>