[iommu] Disable on !MMU builds
Message-id: <20160214180901.7579.31469.stgit@amt.stowe>
Patchwork-id: 134275
O-Subject: [RHEL7.3 PATCH 27/29] iommu: Disable on !MMU builds
Bugzilla: 1299036
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1299036
Upstream Status: e5144c9375851948f50e13db80c3150e3a7521b8

Signed-off-by: Rafael Aquini <aquini@redhat.com>

Conflicts:
    Only took Hunk #1's content (the remaining hunks were related to ARM).

commit e5144c9375851948f50e13db80c3150e3a7521b8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 28 15:45:53 2015 +0100

    iommu: Disable on !MMU builds

    A lot of the IOMMU support code does not build if the CPU does
    not have an MMU itself, and it's not clear if there is any
    use case for it, so let's just disable it and wait for anybody
    to need it.

    This avoids randconfig errors like

    ../arch/arm/mm/dma-mapping.c: In function '__iommu_alloc_remap':
    ../arch/arm/mm/dma-mapping.c:1278:34: error: 'VM_ARM_DMA_CONSISTENT' undeclared (first use in this function)
      area = get_vm_area_caller(size, VM_ARM_DMA_CONSISTENT | VM_USERMAP,
                                      ^
    ../arch/arm/mm/dma-mapping.c:1278:34: note: each undeclared identifier is reported only once for each function it appears in
    ../arch/arm/mm/dma-mapping.c: In function '__atomic_get_pages':
    ../arch/arm/mm/dma-mapping.c:1358:27: error: 'atomic_pool' undeclared (first use in this function)
      struct dma_pool *pool = &atomic_pool;

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>