[net] ipv6: provide stubs for ip6_set_txhash and ip6_make_flowlabel
Message-id: <1434393559-27736-8-git-send-email-ivecera@redhat.com>
Patchwork-id: 119050
O-Subject: [RHEL7.2 PATCH net 7/9] net: provide stubs for ip6_set_txhash and ip6_make_flowlabel
Bugzilla: 1215920
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>

BZ: #1215920

Upstream commit(s):
commit a37934fc0d0c087dd120dba229077048f1abfd37
Author: Florian Fainelli <f.fainelli@gmail.com>
Date:   Tue Jul 8 11:15:03 2014 -0700

    net: provide stubs for ip6_set_txhash and ip6_make_flowlabel

    Commit cb1ce2ef387b ("ipv6: Implement automatic flow label generation
    on transmit") introduced ip6_make_flowlabel, while commit b73c3d0e4f0e
    ("net: Save TX flow hash in sock and set in skbuf on xmit") introduced
    ip6_set_txhash.

    ip6_set_tx_hash() uses sk_v6_daddr which references
    __sk_common.skc_v6_daddr from struct sock_common, which is gated with
    IS_ENABLED(CONFIG_IPV6).

    ip6_make_flowlabel() uses the ipv6 member from struct net which is
    also gated with IS_ENABLED(CONFIG_IPV6).

    When CONFIG_IPV6 is disabled, we will hit a build failure that looks
    like this when the compiler attempts inlining these functions:

      CC [M]  drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.o
    In file included from include/net/inet_sock.h:27:0,
                     from include/net/ip.h:30,
                     from drivers/net/ethernet/broadcom/cnic.c:37:
    include/net/ipv6.h: In function 'ip6_set_txhash':
    include/net/sock.h:327:33: error: 'struct sock_common' has no member named 'skc_v6_daddr'
     #define sk_v6_daddr  __sk_common.skc_v6_daddr
                                     ^
    include/net/ipv6.h:696:49: note: in expansion of macro 'sk_v6_daddr'
      keys.dst = (__force __be32)ipv6_addr_hash(&sk->sk_v6_daddr);
                                                     ^
    In file included from include/net/inetpeer.h:15:0,
                     from include/net/route.h:28,
                     from include/net/ip.h:31,
                     from drivers/net/ethernet/broadcom/cnic.c:37:
    include/net/ipv6.h: In function 'ip6_make_flowlabel':
    include/net/ipv6.h:706:37: error: 'struct net' has no member named 'ipv6'
      if (!flowlabel && (autolabel || net->ipv6.sysctl.auto_flowlabels)) {
                                         ^

    Fixes: cb1ce2ef387b ("ipv6: Implement automatic flow label generation on transmit")
    Fixes: b73c3d0e4f0e ("net: Save TX flow hash in sock and set in skbuf on xmit")
    Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>