[net] bridge: mcast: fix br_multicast_dev_del warn when igmp snooping is not defined
Message-id: <20170127151821.20722-54-ivecera@redhat.com>
Patchwork-id: 163468
O-Subject: [RHEL7.4 net PATCH 053/119] bridge: mcast: fix br_multicast_dev_del warn when igmp snooping is not defined
Bugzilla: 1352289
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

BZ#1352289

Upstream commit(s):
commit a7ce45a74bedd0ed80b956b3e14f8bc6dec85327
Author: Nikolay Aleksandrov <razor@blackwall.org>
Date:   Mon Jul 20 23:03:45 2015 +0200

    bridge: mcast: fix br_multicast_dev_del warn when igmp snooping is not defined

    Fix:
    net/bridge/br_if.c: In function 'br_dev_delete':
    >> net/bridge/br_if.c:284:2: error: implicit declaration of function
    >> 'br_multicast_dev_del' [-Werror=implicit-function-declaration]
         br_multicast_dev_del(br);
         ^
       cc1: some warnings being treated as errors

    when igmp snooping is not defined.

    Signed-off-by: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>