[x86] perf/x86/msr: Fix the MSR driver build
Message-id: <20171004125551.7635-7-jolsa@redhat.com>
Patchwork-id: 187477
O-Subject: [PATCH RHEL7.5 BZ1457458 06/14] perf/x86/msr: Fix the MSR driver build
Bugzilla: 1457458
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1457458
https://bugzilla.redhat.com/show_bug.cgi?id=1457458

upstream
========
commit 82819ffb42fb45197bacf3223191deca31d3eb91
Author: Ingo Molnar <mingo@kernel.org>
Date: Fri Aug 21 08:14:46 2015 +0200

description
===========
The new MSR PMU driver made use of rdtsc() which does not exist (yet) in
this tree:

  arch/x86/kernel/cpu/perf_event_msr.c:91:3: error: implicit declaration of function 'rdtsc'

Use the old rdtscll() primitive for now.

Signed-off-by: Rafael Aquini <aquini@redhat.com>