[kernel] devlink: fix trace format string
Message-id: <20170314164348.17024-6-ivecera@redhat.com>
Patchwork-id: 174228
O-Subject: [RHEL7.4 net PATCH 05/23] devlink: fix trace format string
Bugzilla: 1382040
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1382040

Upstream commit(s):
commit caeccd5180930eb8586771bb1935f4f2e456a8e8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jul 14 11:37:29 2016 +0200

    devlink: fix trace format string

    Including devlink.h on ARM and probably other 32-bit architectures results in
    a harmless warning:

    In file included from ../include/trace/define_trace.h:95:0,
                     from ../include/trace/events/devlink.h:51,
                     from ../net/core/devlink.c:30:
    include/trace/events/devlink.h: In function 'trace_raw_output_devlink_hwmsg':
    include/trace/events/devlink.h:42:12: error: format '%lu' expects argument of type 'long unsigned int', but argument 10 has type 'size_t {aka unsigned int}' [-Werror=format=]

    The correct format string for 'size_t' is %zu, not %lu, this works on all
    architectures.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: e5224f0fe2ac ("devlink: add hardware messages tracing facility")
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>