[usb] phy: msm: reset controller is mandatory now
Message-id: <1457470219-37147-223-git-send-email-dzickus@redhat.com>
Patchwork-id: 137990
O-Subject: [RHEL7 PATCH 222/423] usb: phy: msm: reset controller is mandatory now
Bugzilla: 1303209
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303209

commit c5ab571f81905568a59dce306df0181f33e00932
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 13 21:46:52 2014 +0200

    usb: phy: msm: reset controller is mandatory now

    Commit a27345434134 "usb: phy: msm: Use reset framework for LINK
    and PHY resets" introduced a mandatory call to reset_control_get
    into the msm usb phy driver, which means we have to add a Kconfig
    dependency on the API to avoid this build error:

    phy/phy-msm-usb.c: In function 'msm_otg_read_dt':
    phy/phy-msm-usb.c:1461:2: error: implicit declaration of function 'devm_reset_control_get' [-Werror=implicit-function-declaration]
      motg->link_rst = devm_reset_control_get(&pdev->dev, "link");
      ^

    Since the usb-ehci-msm driver currently selects the OTG driver,
    we could still get a broken dependency here. To solve that,
    this patch also removes the 'select', which turns out to be
    unnecessary.

    Reviewed-by: Ivan T. Ivanov <iivanov@mm-sol.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Felipe Balbi <balbi@ti.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>