[tools] perf python: Add missing files to binding link list
Message-id: <1460038562-19641-254-git-send-email-jolsa@redhat.com>
Patchwork-id: 140585
O-Subject: [PATCH RHEL7.3 BZ1323852 253/311] perf python: Add missing files to binding link list
Bugzilla: 1323852
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1323852
https://bugzilla.redhat.com/show_bug.cgi?id=1323852

upstream
========
commit 372b212263998ae8e3b2f80ce52af3168d749158
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Jan 7 16:47:11 2016 -0300

description
===========
Fixing this problem, introduced recently:

  $ perf test python
  16: Try 'import perf' in python, checking link problems      : FAILED!

In verbose mode we find out what is missing:

  $ perf test -v python
  16: Try 'import perf' in python, checking link problems      :
  --- start ---
  test child forked, pid 24894
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: /tmp/build/perf/python/perf.so: undefined symbol: find_next_bit
  test child finished with -1
  ---- end ----
  Try 'import perf' in python, checking link problems: FAILED!
  $

Fixes: f77b57ad4fc4 ("perf cpu_map: Add cpu_map__new_event function")
Signed-off-by: Rafael Aquini <aquini@redhat.com>