[tools] Fix shadowed declaration in err.h
Message-id: <1456127829-13546-122-git-send-email-jolsa@redhat.com>
Patchwork-id: 135374
O-Subject: [PATCH BZ1308570 121/260] tools: Fix shadowed declaration in err.h
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit 45633a169571e81835ec53fe0c089dd20f3195f1
Author: Jiri Olsa <jolsa@redhat.com>
Date: Tue Sep 29 16:53:12 2015 +0200

description
===========
The error variable breaks build on CentOS 6.7, due to collision with
global error symbol:

    CC       util/evlist.o
  cc1: warnings being treated as errors
  In file included from util/evlist.c:28:
  tools/include/linux/err.h: In function ERR_PTR:
  tools/include/linux/err.h:34: error: declaration of error shadows a global declaration
  util/util.h:135: error: shadowed declaration is here

Using 'error_' name instead to fix it.

[ Use 'error_' instead of 'err' to, visually, not diverge too much from include/linux/err.h ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>