[usb] add HAS_IOMEM dependency to USB_XHCI_HCD
Message-id: <1465525749-9195-92-git-send-email-torez@redhat.com>
Patchwork-id: 150017
O-Subject: [RHEL7 BZ1332712 v2 091/196] usb: add HAS_IOMEM dependency to USB_XHCI_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 8f2abe808dbfe4f84412aa3bb40f97f464727641
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:46 2016 +0100

    usb: add HAS_IOMEM dependency to USB_XHCI_HCD

    drivers/built-in.o: In function `xhci_plat_probe':
    /home/vegard/linux/drivers/usb/host/xhci-plat.c:160: undefined reference to `devm_ioremap_resource'

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>