[tools] perf: Fix build breakage on arm64 targets
Message-id: <1418163608-7772-306-git-send-email-jolsa@redhat.com>
Patchwork-id: 101516
O-Subject: [PATCH RHEL7.1 BZ1169436 305/359] perf tools: Fix build breakage on arm64 targets
Bugzilla: 1169436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1169436
https://bugzilla.redhat.com/show_bug.cgi?id=1169436

upstream
========
commit 660d13296bbbe79635d1d9d700080b88061faffb
Author: Will Deacon <will.deacon@arm.com>
Date: Tue Sep 30 12:27:12 2014 +0100

description
===========
Attempting to build the perf tool for an arm64 target results in the
following failure:

  arch/arm64/util/unwind-libunwind.c: In function 'libunwind__arch_reg_id':
  arch/arm64/util/unwind-libunwind.c:77:3: error: implicit declaration of function 'pr_err'
     pr_err("unwind: invalid reg id %d\n", regnum);
     ^
  arch/arm64/util/unwind-libunwind.c:77:3: error: nested extern declaration of 'pr_err'

This is due to commit 84f5d36f4866 ("perf tools: Move pr_* debug macros
into debug object") moving the pr_* macros into a new header file, but
failing to update architectures other than x86.

This patch adds the missing include, and fixes the build again.
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>