[usb] fix build error when CONFIG_PM_SLEEP isn't enabled
Message-id: <1381413926-15908-653-git-send-email-vfalico@redhat.com>
Patchwork-id: 69267
O-Subject: [RHEL7 PATCH 652/820] USB: fix build error when CONFIG_PM_SLEEP isn't enabled
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 9d8924297cd9c256c23c02abae40202563452453
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=9d8924297cd9c256c23c02abae40202563452453
Stable: 94cc662c4bd9f8487d54262bbfc2307d9b1fc6b1
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=94cc662c4bd9f8487d54262bbfc2307d9b1fc6b1

Description
----------------------------
Backport from linux-3.10.y stable.

From: Alan Stern <stern@rowland.harvard.edu>
Subject: USB: fix build error when CONFIG_PM_SLEEP isn't enabled

commit 9d8924297cd9c256c23c02abae40202563452453 upstream.

This patch fixes a build error that occurs when CONFIG_PM is enabled
and CONFIG_PM_SLEEP isn't:

>> drivers/usb/host/ohci-pci.c:294:10: error: 'usb_hcd_pci_pm_ops' undeclared here (not in a function)
      .pm = &usb_hcd_pci_pm_ops

Since the usb_hcd_pci_pm_ops structure is defined and used when
CONFIG_PM is enabled, its declaration should not be protected by
CONFIG_PM_SLEEP.

Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 94cc662c4bd9f8487d54262bbfc2307d9b1fc6b1)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>