[perf] probe: Fix to get ummapped symbol address on kernel
Message-id: <1431774138-14330-244-git-send-email-jolsa@redhat.com>
Patchwork-id: 112464
O-Subject: [PATCH RHEL7.2 BZ1222189 243/327] perf probe: Fix to get ummapped symbol address on kernel
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit e6d7c91c8c5ea532584056f3e8bf1643310c8ef7
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Sun Mar 22 20:40:22 2015 +0900

description
===========
Fix to get correctly unmapped symbol address on kernel.  This allows us
to probe on syscall symbols which are aliases of SyS_ functions with
using debuginfo.

Without this fix:
  ----
  # ./perf probe -a sys_write
  Failed to find debug information for address 3b0100
  Probe point 'sys_write' not found.
    Error: Failed to add events.
  ----
The address 0x3b0100 is a mapped address, and not usable
in debuginfo.

With this fix:
  ----
  # ./perf probe -a sys_write
  Added new event:
    probe:sys_write      (on sys_write)

  You can now use it in all perf tools, such as:

          perf record -e probe:sys_write -aR sleep 1
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>