[netdrv] cxgb4: unexport cxgb4_dcb_enabled
Message-id: <1487828466-9959-179-git-send-email-ddutile@redhat.com>
Patchwork-id: 167178
O-Subject: [PATCH RHEL-7.4 178/348] cxgb4: unexport cxgb4_dcb_enabled
Bugzilla: 1385866 1417285
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417285
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385866

commit 7c70c4f8b2bf5ed777120f3d70efe35e64930c10
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Sep 30 18:15:33 2016 +0200

    cxgb4: unexport cxgb4_dcb_enabled

    A recent cleanup marked cxgb4_dcb_enabled as 'static', which is correct, but this ignored
    how the symbol is also exported. In addition, the export can be compiled out when modules
    are disabled, causing a harmless compiler warning in configurations for which it is not
    used at all:

    drivers/net/ethernet/chelsio/cxgb4/cxgb4_main.c:282:12: error: 'cxgb4_dcb_enabled' defined but not used [-Werror=unused-function]

    This removes the export and moves the function into the correct #ifdef so we only build
    it when there are users.

    Fixes: 50935857f878 ("cxgb4: mark symbols static where possible")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>