[vfio] pci: make an array larger
Message-id: <20161219191401.27009.66967.stgit@amt.stowe>
Patchwork-id: 161664
O-Subject: [RHEL7.4 PATCH 20/20] vfio/pci: make an array larger
Bugzilla: 1405700
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1405700
Upstream Status: 222e684ca762e9288108fcf852eb5d08cbe10ae3

commit 222e684ca762e9288108fcf852eb5d08cbe10ae3
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Mon Nov 9 15:24:55 2015 +0300

    vfio/pci: make an array larger

    Smatch complains about a possible out of bounds error:

        drivers/vfio/pci/vfio_pci_config.c:1241 vfio_cap_init()
        error: buffer overflow 'pci_cap_length' 20 <= 20

    The problem is that pci_cap_length[] was defined as large enough to
    hold "PCI_CAP_ID_AF + 1" elements.  The code in vfio_cap_init() assumes
    it has PCI_CAP_ID_MAX + 1 elements.  Originally, PCI_CAP_ID_AF and
    PCI_CAP_ID_MAX were the same but then we introduced PCI_CAP_ID_EA in
    commit f80b0ba95964 ("PCI: Add Enhanced Allocation register entries")
    so now the array is too small.

    Let's fix this by making the array size PCI_CAP_ID_MAX + 1.  And let's
    make a similar change to pci_ext_cap_length[] for consistency.  Also
    both these arrays can be made const.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Alex Williamson <alex.williamson@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>