[perf] symbols: Define STT_GNU_IFUNC for glibc 2.9 and older
Message-id: <1431774138-14330-60-git-send-email-jolsa@redhat.com>
Patchwork-id: 112281
O-Subject: [PATCH RHEL7.2 BZ1222189 059/327] perf symbols: Define STT_GNU_IFUNC for glibc 2.9 and older.
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 4e31050f482c02c822b150d71cf1ea5be7c9d6e4
Author: Vinson Lee <vlee@twitter.com>
Date: Mon Feb 9 16:29:37 2015 -0800

description
===========
The token STT_GNU_IFUNC is not available with glibc 2.9 and older.
Define this token if it is not already defined.

This patch fixes this build errors with older versions of glibc.

  CC       util/symbol-elf.o
util/symbol-elf.c: In function elf_sym__is_function:
util/symbol-elf.c:75: error: STT_GNU_IFUNC undeclared (first use in this function)
util/symbol-elf.c:75: error: (Each undeclared identifier is reported only once
util/symbol-elf.c:75: error: for each function it appears in.)
make: *** [util/symbol-elf.o] Error 1

Signed-off-by: Rafael Aquini <aquini@redhat.com>