[tools] tools build: Fixup sched_getcpu feature test
Message-id: <20170830160540.26618-215-jolsa@redhat.com>
Patchwork-id: 183618
O-Subject: [PATCH RHEL7.5 BZ1480522 214/248] tools build: Fixup sched_getcpu feature test
Bugzilla: 1480522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1480522
https://bugzilla.redhat.com/show_bug.cgi?id=1480522

upstream
========
commit 1e6e7eae8a3a66f5fee4f44ef165ffcf31f0c40e
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu May 4 10:30:40 2017 -0300

description
===========
We have tools/build/feature/test-all.c to speed up feature testing,
doing all tests at once, but then all tests in this file should normally
pass.

That is not the case with the sched-getcpu one, that wasn't passing when
included from test-all.c because it needs to have _GNU_SOURCE defined
before including sched.h, but _GNU_SOURCE is defined by a header
included from another feature test included earlier in test-all.d,
test-libpython.c, resulting in:

  $ cat /tmp/build/perf/feature/test-all.make.output
  In file included from test-all.c:121:0:
  test-sched_getcpu.c:1:0: error: "_GNU_SOURCE" redefined [-Werror]
   #define _GNU_SOURCE

  In file included from /usr/include/python2.7/pyconfig.h:6:0,
                   from /usr/include/python2.7/Python.h:8,
                   from test-libpython.c:1,
                   from test-all.c:13:
  /usr/include/python2.7/pyconfig-64.h:1177:0: note: this is the location of the previous definition
   #define _GNU_SOURCE 1

  cc1: all warnings being treated as errors

Which would trigger testing the tests individually, when that
_GNU_SOURCE redefinition would not take place, and the whole process
would continue, just slower... Fix it.

Fixes: 120010cb1eea ("tools build: Add test for sched_getcpu()")
Signed-off-by: Rafael Aquini <aquini@redhat.com>