[tools] perf: Sharpen the libaudit dependencies test
Message-id: <1389109877-9395-196-git-send-email-jolsa@redhat.com>
Patchwork-id: 73497
O-Subject: [PATCH RHEL7.0 BZ1036665 195/226] perf tools: Sharpen the libaudit dependencies test
Bugzilla: 1036665
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1036665
https://bugzilla.redhat.com/show_bug.cgi?id=1036665

upstream
========
commit 33cbbdccf39f6d7e01c282c4320d818a75b67d54
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Sep 12 15:27:06 2013 +0200

description
===========
There are older libaudit versions that don't have an
audit_errno_to_name() method, resulting in a builtin-trace.c build
error:

  builtin-trace.c: In function 'trace__sys_exit':
  builtin-trace.c:794: warning: implicit declaration of function 'audit_errno_to_name'

Expand the libaudit test to detect this.

[ Fix the test by escaping the double quotes ]

Signed-off-by: Jarod Wilson <jarod@redhat.com>