[net] ipv4: Fix compilation errors in fib_rebalance
Message-id: <d242321a149e938dc6e3b17f59bc0ec8d1dddff8.1445939014.git.pabeni@redhat.com>
Patchwork-id: 125917
O-Subject: [RHEL7.3 net PATCH 3/3] ipv4: Fix compilation errors in fib_rebalance
Bugzilla: 1275573
RH-Acked-by: Phil Sutter <psutter@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Hannes Frederic Sowa <hannes@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1275573

Upstream net-next commit:
commit 0a837fe4724713ef701e47d6bfab98a5efaff3eb
Author: Peter Norlund <pch@ordbogen.com>
Date:   Tue Oct 6 07:24:47 2015 +0200

    ipv4: Fix compilation errors in fib_rebalance

    This fixes

    net/built-in.o: In function `fib_rebalance':
    fib_semantics.c:(.text+0x9df14): undefined reference to `__divdi3'

    and

    net/built-in.o: In function `fib_rebalance':
    net/ipv4/fib_semantics.c:572: undefined reference to `__aeabi_ldivmod'

    Fixes: 0e884c78ee19 ("ipv4: L3 hash-based multipath")

    Signed-off-by: Peter Norlund <pch@ordbogen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Palo Abeni <pabeni@redahat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>