[mips] Expose missing pci_io{map, unmap} declarations
Message-id: <1381413926-15908-423-git-send-email-vfalico@redhat.com>
Patchwork-id: 68935
O-Subject: [RHEL7 PATCH 422/820] MIPS: Expose missing pci_io{map, unmap} declarations
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 78857614104a26cdada4c53eea104752042bf5a1
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=78857614104a26cdada4c53eea104752042bf5a1
Stable: 5954bd0f29212194f0beb6dab03f9c26a482c560
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=5954bd0f29212194f0beb6dab03f9c26a482c560

Description
----------------------------
Backport from linux-3.10.y stable.

From: Markos Chandras <markos.chandras@imgtec.com>
Subject: MIPS: Expose missing pci_io{map,unmap} declarations

commit 78857614104a26cdada4c53eea104752042bf5a1 upstream.

The GENERIC_PCI_IOMAP does not depend on CONFIG_PCI so move
it to the CONFIG_MIPS symbol so it's always selected for MIPS.
This fixes the missing pci_iomap declaration for MIPS.
Moreover, the pci_iounmap function was not defined in the
io.h header file if the CONFIG_PCI symbol is not set,
but it should since MIPS is not using CONFIG_GENERIC_IOMAP.

This fixes the following problem on a allyesconfig:

drivers/net/ethernet/3com/3c59x.c:1031:2: error: implicit declaration of
function 'pci_iomap' [-Werror=implicit-function-declaration]
drivers/net/ethernet/3com/3c59x.c:1044:3: error: implicit declaration of
function 'pci_iounmap' [-Werror=implicit-function-declaration]

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Acked-by: Steven J. Hill <Steven.Hill@imgtec.com>
Patchwork: https://patchwork.linux-mips.org/patch/5478/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Cc: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 5954bd0f29212194f0beb6dab03f9c26a482c560)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>