[scsi] lpfc: use div_u64 for 64-bit division
Message-id: <1507670879-17640-30-git-send-email-dkennedy@redhat.com>
Patchwork-id: 191046
O-Subject: [RHEL7.5 e-stor PATCH 029/170] scsi: lpfc: use div_u64 for 64-bit division
Bugzilla: 1385844 1461977 1387768
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The new debugfs output causes a link error on 32-bit architectures:

ERROR: "__aeabi_uldivmod" [drivers/scsi/lpfc/lpfc.ko] undefined!

This code is not performance critical, so we can simply use div_u64().

[mkp: fixed up whitespace]

Fixes: bd2cdd5e400f ("scsi: lpfc: NVME Initiator: Add debugfs support")
Fixes: 2b65e18202fd ("scsi: lpfc: NVME Target: Add debugfs support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 90ec7c9dff07d676c0b9b499286b931005c6b051)
Signed-off-by: Rafael Aquini <aquini@redhat.com>