[hwmon] ibmpowernv: Fix build error seen for some configurations
Message-id: <1433369228-16410-17-git-send-email-gduarte@redhat.com>
Patchwork-id: 115434
O-Subject: [RHEL7.2 PATCH BZ 1224367 16/19] hwmon: (ibmpowernv) Fix build error seen for some configurations
Bugzilla: 1224367
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>

BZ 1224367
Upstream Status: 8416915c16d4335980c5d5d6d39957adbfe40b55

commit 8416915c16d4335980c5d5d6d39957adbfe40b55
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Wed Apr 8 21:02:47 2015 -0700

    hwmon: (ibmpowernv) Fix build error seen for some configurations

    Fix
    drivers/hwmon/ibmpowernv.c: In function 'get_logical_cpu':
    drivers/hwmon/ibmpowernv.c:121:3:
    	error: implicit declaration of function 'get_hard_smp_processor_id'

    seen for some configurations, possibly if SMP is not configured.

    Fixes: 3df2f59f0aae ("hwmon: (ibmpowernv) pretty print labels")
    Cc: Cdric Le Goater <clg@fr.ibm.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>

Signed-off-by: Rafael Aquini <aquini@redhat.com>