[ntb] perf test: fix address space confusion
Message-id: <1486718506-16087-94-git-send-email-ssuthiku@redhat.com>
Patchwork-id: 165692
O-Subject: [RHEL7.4 PATCH BZ 1303727 093/147] ntb: perf test: fix address space confusion
Bugzilla: 1303727
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303727

commit 1985a88107b5330b2a911ad4d279e1bd7e4deb24
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 26 10:31:45 2016 +0100

    ntb: perf test: fix address space confusion

    The ntb driver assigns between pointers an __iomem tokens, and
    also casts them to 64-bit integers, which results in compiler
    warnings on 32-bit systems:

    drivers/ntb/test/ntb_perf.c: In function 'perf_copy':
    drivers/ntb/test/ntb_perf.c:213:10: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      vbase = (u64)(u64 *)mw->vbase;
              ^
    drivers/ntb/test/ntb_perf.c:214:14: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      dst_vaddr = (u64)(u64 *)dst;
                  ^

    This adds __iomem annotations where needed and changes the temporary
    variables to iomem pointers to avoid casting them to u64. I did not
    see the problem in linux-next earlier, but it show showed up in
    4.5-rc1.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Dave Jiang <dave.jiang@intel.com>
    Fixes: 8a7b6a778a85 ("ntb: ntb perf tool")
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

Cc: Suravee Suthikulpanit <ssuthiku@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>