[usb] ohci: remove bogus #error
Message-id: <1383331633-194322-45-git-send-email-dzickus@redhat.com>
Patchwork-id: 70176
O-Subject: [RHEL7 PATCH 044/311] USB: OHCI: remove bogus #error
Bugzilla: 895641
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=895641

commit 358e91175cac9398b152ad9adc2391ebce34011c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jun 4 16:46:00 2013 +0200

    USB: OHCI: remove bogus #error

    The OHCI host controller driver can be built standalone now,
    without enabling any of the available bus glue drivers, so
    there is not really a reason to error out here:

    drivers/usb/host/ohci-hcd.c:1258: error:
     #error "missing bus glue for ohci-hcd"  #error "missing bus glue for ohci-hcd"

    This follows the same change done in ehci recently as 843e56c0
    "USB: EHCI: remove bogus #error" and hopefully avoids future
    merge conflicts in this list.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Alan Stern <stern@rowland.harvard.edu>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>