[netdrv] qede: Fix net-next "make ARCH=x86_64"
Message-id: <1465316705-7370-51-git-send-email-hpatil@redhat.com>
Patchwork-id: 149480
O-Subject: [PATCH v2 RHEL 7.3 050/107] qede: Fix net-next "make ARCH=x86_64"
Bugzilla: 1275807 1275811
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Manish Chopra <manish.chopra@qlogic.com>

BZ 1275811

net commit id 88f09bd5b9875a0fbf2075221590d9c4418cdbbc

'commit 55482edc25f0606851de42e73618f813f310d009
("qede: Add slowpath/fastpath support and enable hardware GRO")'
introduces below error when compiling net-next with "make ARCH=x86_64"

drivers/built-in.o: In function `qede_rx_int':
qede_main.c:(.text+0x6101a0): undefined reference to `tcp_gro_complete'

Signed-off-by: Manish Chopra <manish.chopra@qlogic.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Rafael Aquini <aquini@redhat.com>