[tools] perf tests: Fix build on older systems where 'signal' is reserved
Message-id: <1463569977-29479-133-git-send-email-jolsa@redhat.com>
Patchwork-id: 145713
O-Subject: [PATCH RHEL7.3 BZ1336447 132/324] perf tests: Fix build on older systems where 'signal' is reserved
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit 1ad826bad5bd0b6ccfb203f78c70302b764df0be
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Feb 12 18:30:01 2016 -0300

description
===========
fixing the following problems, for instance, on RHEL6.7:

    CC       /tmp/build/perf/tests/bp_signal.o
  cc1: warnings being treated as errors
  tests/bp_signal.c: In function __event:
  tests/bp_signal.c:106: error: declaration of signal shadows a global declaration
  /usr/include/signal.h:101: error: shadowed declaration is here
  tests/bp_signal.c: In function bp_event:
  tests/bp_signal.c:144: error: declaration of signal shadows a global declaration
  /usr/include/signal.h:101: error: shadowed declaration is here
  tests/bp_signal.c: In function wp_event:
  tests/bp_signal.c:149: error: declaration of signal shadows a global declaration
  /usr/include/signal.h:101: error: shadowed declaration is here
  mv: cannot stat `/tmp/build/perf/tests/.bp_signal.o.tmp': No such file or directory
  make[3]: *** [/tmp/build/perf/tests/bp_signal.o] Error 1
  make[2]: *** [tests] Error 2
  make[1]: *** [/tmp/build/perf/perf-in.o] Error 2
  make[1]: *** Waiting for unfinished jobs....

Fixes: 8fd34e1cce18 ("perf test: Improve bp_signal")
Signed-off-by: Rafael Aquini <aquini@redhat.com>