[netdrv] fm10k: Add CONFIG_FM10K_VXLAN configuration option
Message-id: <1435083281-4515-72-git-send-email-nhorman@redhat.com>
Patchwork-id: 120602
O-Subject: [RHEL7.2 PATCHv3 71/73] fm10k: Add CONFIG_FM10K_VXLAN configuration option
Bugzilla: 1173790
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

Compiling with CONFIG_FM10K=y and VXLAN=m resulting in linking error:

   drivers/built-in.o: In function `fm10k_open':
   (.text+0x1f9d7a): undefined reference to `vxlan_get_rx_port'
   make: *** [vmlinux] Error 1

The fix follows the same strategy as I40E.

Signed-off-by: Andy Zhou <azhou@nicira.com>
Acked-by: Alexander Duyck <alexander.h.duyck@intel.com>
Tested-by: Aaron Brown <aaron.f.brown@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
(cherry picked from commit f6b03c10a1b3f2c98ed23813997cdebef8aabeba)

BZ: 1173790
Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=9407876
Testing: Tested by Intel
Signed-off-by: Rafael Aquini <aquini@redhat.com>