[usb] add HAS_IOMEM dependency to USB_C67X00_HCD
Message-id: <1465525749-9195-89-git-send-email-torez@redhat.com>
Patchwork-id: 150011
O-Subject: [RHEL7 BZ1332712 v2 088/196] usb: add HAS_IOMEM dependency to USB_C67X00_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 149737a7870170a48a17b5a4a7feba14f43d4a06
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:42 2016 +0100

    usb: add HAS_IOMEM dependency to USB_C67X00_HCD

      CC      drivers/usb/c67x00/c67x00-drv.o
    drivers/usb/c67x00/c67x00-drv.c: In function c67x00_drv_probe:
    drivers/usb/c67x00/c67x00-drv.c:148:2: error: implicit declaration of function ioremap [-Werror=implicit-function-declaration]
      c67x00->hpi.base = ioremap(res->start, resource_size(res));
      ^
    drivers/usb/c67x00/c67x00-drv.c:148:19: warning: assignment makes pointer from integer without a cast [enabled by default]
      c67x00->hpi.base = ioremap(res->start, resource_size(res));
                       ^
    drivers/usb/c67x00/c67x00-drv.c:185:2: error: implicit declaration of function iounmap [-Werror=implicit-function-declaration]
      iounmap(c67x00->hpi.base);
      ^

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>