[powerpc] powernv: Add support for Nvlink NPUs
Message-id: <1455893954-28433-43-git-send-email-gduarte@redhat.com>
Patchwork-id: 135023
O-Subject: [RHEL7.3 PATCH BZ 1275657 42/46] powerpc/powernv: Add support for Nvlink NPUs
Bugzilla: 1275657
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ 1275657
Upstream Status: 5d2aa710e697244f5504125e4aa6e2cfcf6c4791

Backport note: added forward declaration in pci.h to fix compile breakage

In file included from arch/powerpc/platforms/powernv/npu-dma.c:22:0:
arch/powerpc/platforms/powernv/pci.h:112:32: error: struct msi_msg declared inside parameter list [-Werror]
     unsigned int is_64, struct msi_msg *msg);
Signed-off-by: Cdric Le Goater <clg@fr.ibm.com>

commit 5d2aa710e697244f5504125e4aa6e2cfcf6c4791
Author: Alistair Popple <alistair@popple.id.au>
Date:   Thu Dec 17 13:43:13 2015 +1100

    powerpc/powernv: Add support for Nvlink NPUs

    NVLink is a high speed interconnect that is used in conjunction with a
    PCI-E connection to create an interface between CPU and GPU that
    provides very high data bandwidth. A PCI-E connection to a GPU is used
    as the control path to initiate and report status of large data
    transfers sent via the NVLink.

    On IBM Power systems the NVLink processing unit (NPU) is similar to
    the existing PHB3. This patch adds support for a new NPU PHB type. DMA
    operations on the NPU are not supported as this patch sets the TCE
    translation tables to be the same as the related GPU PCIe device for
    each NVLink. Therefore all DMA operations are setup and controlled via
    the PCIe device.

    EEH is not presently supported for the NPU devices, although it may be
    added in future.

    Signed-off-by: Alistair Popple <alistair@popple.id.au>
    Signed-off-by: Gavin Shan <gwshan@linux.vnet.ibm.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Rafael Aquini <aquini@redhat.com>