[usb] add HAS_IOMEM dependency to USB_ISP1362_HCD
Message-id: <1465525749-9195-97-git-send-email-torez@redhat.com>
Patchwork-id: 150035
O-Subject: [RHEL7 BZ1332712 v2 096/196] usb: add HAS_IOMEM dependency to USB_ISP1362_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 4a6d9f87209908fb5909c9957597e4df9c3c56fc
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:54 2016 +0100

    usb: add HAS_IOMEM dependency to USB_ISP1362_HCD

    drivers/built-in.o: In function `isp1362_probe':
    /home/vegard/linux/drivers/usb/host/isp1362-hcd.c:2668: undefined reference to `devm_ioremap_resource'

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>