[usb] xhci: add missing dma-mapping.h includes
Message-id: <1383331633-194322-174-git-send-email-dzickus@redhat.com>
Patchwork-id: 70297
O-Subject: [RHEL7 PATCH 173/311] usb: xhci: add missing dma-mapping.h includes
Bugzilla: 895641
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=895641

commit 008eb957dafea32bac993be5cbeaf4ca0ee8b0aa
Author: James Hogan <james.hogan@imgtec.com>
Date:   Fri Jul 26 13:34:43 2013 +0100

    usb: xhci: add missing dma-mapping.h includes

    A randconfig build hit the following build errors because xhci.c and
    xhci-mem.c use dma mapping functions but don't include
    <linux/dma-mapping.h>. Add the missing includes to fix the build errors.

    drivers/usb/host/xhci.c In function 'xhci_gen_setup':
    drivers/usb/host/xhci.c +4872 : error: implicit declaration of function 'dma_set_mask'
    drivers/usb/host/xhci.c +4872 : error: implicit declaration of function 'DMA_BIT_MASK'

    drivers/usb/host/xhci-mem.c In function 'xhci_free_stream_ctx':
    drivers/usb/host/xhci-mem.c +435 : error: implicit declaration of function 'dma_free_coherent'
    drivers/usb/host/xhci-mem.c In function 'xhci_alloc_stream_ctx':
    drivers/usb/host/xhci-mem.c +463 : error: implicit declaration of function 'dma_alloc_coherent'

    Signed-off-by: James Hogan <james.hogan@imgtec.com>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: linux-usb@vger.kernel.org
    Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>