[net] fix a compile error when CONFIG_NET_LL_RX_POLL is not set
Message-id: <1386354865-26865-2-git-send-email-mschmidt@redhat.com>
Patchwork-id: 71746
O-Subject: [RHEL7.0 PATCH 1/3] net: fix a compile error when CONFIG_NET_LL_RX_POLL is not set
Bugzilla: 1038631
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1038631

Upstream commit:
commit dfcefb0be1231982784df2152213103ad33c1cfd
Author: Cong Wang <amwang@redhat.com>
Date:   Thu Aug 1 11:10:24 2013 +0800

    net: fix a compile error when CONFIG_NET_LL_RX_POLL is not set

    When CONFIG_NET_LL_RX_POLL is not set, I got:

    net/socket.c: In function 'sock_poll':
    net/socket.c:1165:4: error: implicit declaration of function 'sk_busy_loop' [-Werror=implicit-function-declaration]

    Fix this by adding a nop when !CONFIG_NET_LL_RX_POLL.

    Cc: Eliezer Tamir <eliezer.tamir@linux.intel.com>
    Cc: David S. Miller <davem@davemloft.net>
    Signed-off-by: Cong Wang <amwang@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>