[tools] perf: Include tools/lib/api/ in MANIFEST
Message-id: <1408953210-26343-244-git-send-email-jolsa@redhat.com>
Patchwork-id: 89009
O-Subject: [PATCH RHEL7.1 BZ1133083 243/322] perf tools: Include tools/lib/api/ in MANIFEST
Bugzilla: 1133083
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1133083
https://bugzilla.redhat.com/show_bug.cgi?id=1133083

upstream
========
commit c023f534c31f69a658fc21d619116ad12c7be464
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Jan 10 16:25:05 2014 -0300

description
===========
When 553873e1df63 renamed tools/lib/lk to tools/lib/api we forgot to
do the switch in tools/perf/MANIFEST, breaking tarball building:

  [acme@ssdandy linux]$ make perf-targz-src-pkg
    TAR
  [acme@ssdandy linux]$ tar xf perf-3.13.0-rc4.tar.gz -C /tmp/tmp.OgdYyvp77p/
  [acme@ssdandy linux]$ make -C /tmp/tmp.OgdYyvp77p/perf-3.13.0-rc4/tools/perf
  make: Entering directory
  `/tmp/tmp.OgdYyvp77p/perf-3.13.0-rc4/tools/perf'
    BUILD:   Doing 'make -j8' parallel build
    FLEX     util/pmu-flex.c
    CC       util/evlist.o
    CC       util/evsel.o
  util/evsel.c:12:28: fatal error: api/fs/debugfs.h: No such file or directory compilation terminated.
  In file included from util/cache.h:5:0,
  <SNIP>

Fix it.
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>