[tools] perf tools: Fix build break on powerpc
Message-id: <1463569977-29479-310-git-send-email-jolsa@redhat.com>
Patchwork-id: 145865
O-Subject: [PATCH RHEL7.3 BZ1336447 309/324] perf tools: Fix build break on powerpc
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit 379649cfeafef29b77d29860741f4d1c5870b65f
Author: Sukadev Bhattiprolu <sukadev@linux.vnet.ibm.com>
Date: Mon Mar 28 09:31:41 2016 -0300

description
===========
Commit 531d2410635c ("perf tools: Do not include stringify.h from the
kernel sources") seems to have accidentially removed the inclusion of
"util/header.h" from "arch/powerpc/util/header.c".

"util/header.h" provides the prototype for get_cpuid() and is needed to
build perf on Powerpc:

	arch/powerpc/util/header.c:17:1: error: no previous prototype for 'get_cpuid' [-Werror=missing-prototypes]

Fixes: 531d2410635c ("perf tools: Do not include stringify.h from the kernel sources")
[ Included "util.h" too, to get the scnprintf() prototype ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>