[fs] btrfs: fix static checker warnings
Message-id: <1407179109-13714-39-git-send-email-sandeen@redhat.com>
Patchwork-id: 87024
O-Subject: [RHEL7.1 PATCH 038/422] btrfs: fix static checker warnings
Bugzilla: 1071179
RH-Acked-by: Zach Brown <zab@redhat.com>

From: Jeff Mahoney <jeffm@suse.com>

commit 1b8e5df6d9b676f6d31fb098ffdc7d18732729d7
Author: Jeff Mahoney <jeffm@suse.com>
Date:   Wed Nov 20 16:50:23 2013 -0500

    btrfs: fix static checker warnings

    This patch fixes the following warnings:
    fs/btrfs/extent-tree.c:6201:12: sparse: symbol 'get_raid_name' was not declared. Should it be static?
    fs/btrfs/extent-tree.c:8430:9: error: format not a string literal and no format arguments [-Werror=format-security] get_raid_name(index));

    Signed-off-by: Jeff Mahoney <jeffm@suse.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Josef Bacik <jbacik@fb.com>
    Signed-off-by: Chris Mason <clm@fb.com>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>