[net] pktgen: add needed include file
Message-id: <20170316201403.13690-1-ivecera@redhat.com>
Patchwork-id: 174448
O-Subject: [RHEL7.4 net PATCH 32/32] pktgen: add needed include file
Bugzilla: 1382040
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1382040

Upstream commit(s):
commit 73d94e9481a20817abe2f1b41ee441bb4f6461f7
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Mon Jul 29 16:21:26 2013 +1000

    pktgen: add needed include file

    Fixes this on PowerPC (at least):

    net/core/pktgen.c: In function 'fill_packet_ipv6':
    net/core/pktgen.c:2906:3: error: implicit declaration of function 'csum_ipv6_magic' [-Werror=implicit-function-declaration]
       udph->check = ~csum_ipv6_magic(&iph->saddr, &iph->daddr, udplen, IPPROTO_UDP, 0);
       ^

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>