[net] fix compile error in skb_orphan_partial()
Message-id: <20171008224128.1458-341-ivecera@redhat.com>
Patchwork-id: 190424
O-Subject: [RHEL7.5 net PATCH 340/466] net: fix compile error in skb_orphan_partial()
Bugzilla: 1445420
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ#1445420

Upstream commit(s):
commit 9142e9007f2d7ab58a587a1e1d921b0064a339aa
Author: Eric Dumazet <edumazet@google.com>
Date:   Tue May 16 13:27:53 2017 -0700

    net: fix compile error in skb_orphan_partial()

    If CONFIG_INET is not set, net/core/sock.c can not compile :

    net/core/sock.c: In function 'skb_orphan_partial':
    net/core/sock.c:1810:2: error: implicit declaration of function
    'skb_is_tcp_pure_ack' [-Werror=implicit-function-declaration]
      if (skb_is_tcp_pure_ack(skb))
      ^

    Fix this by always including <net/tcp.h>

    Fixes: f6ba8d33cfbb ("netem: fix skb_orphan_partial()")
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Reported-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>