[s390] perf: fix compile error (undefined reference sie_exit)
Message-id: <1385724380-19826-34-git-send-email-brueckner@redhat.com>
Patchwork-id: 71534
O-Subject: [RHEL7.0 PATCH 33/33] [s390x] s390/perf: fix compile error (undefined reference sie_exit)
Bugzilla: 1035261
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Radim Krcmar <rkrcmar@redhat.com>

Description
-----------
commit 198b1bf8c3a06de42a88ad7f9d664f18d740a418
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Thu Jul 25 11:16:48 2013 +0200

    s390/perf: fix compile error (undefined reference sie_exit)

    The perf_event code references sie_exit even if KVM is not available.
    So add proper ifdefs to fix this one:

    arch/s390/built-in.o: In function `sys_call_table_emu':
    (.rodata+0x2b98): undefined reference to `sie_exit'
    arch/s390/built-in.o: In function `sys_call_table_emu':
    (.rodata+0x2ba0): undefined reference to `sie_exit'
    make: *** [vmlinux] Error 1

    Reported-by: Zhouping Liu <zliu@redhat.com>
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

Bugzilla
--------
BZ 1035261
https://bugzilla.redhat.com/show_bug.cgi?id=1035261

Upstream status of the patch
----------------------------
The patch is upstream as of kernel version v3.11-rc5
http://git.kernel.org/?p=linux/kernel/git/torvalds/linux-2.6.git;a=commitdiff;h=198b1bf8c3a06de42a88ad7f9d664f18d740a418

Brew
----
https://brewweb.devel.redhat.com/taskinfo?taskID=6658820

Test status
-----------
The patch has been tested and fixes the problem.
The fix has been verified by the IBM test department.

---
Please ACK.

With best regards,

	Hendrik

Signed-off-by: Jarod Wilson <jarod@redhat.com>