[tools] perf tools: Add missing parse_events_error() prototype
Message-id: <20170807084247.7531-67-jolsa@redhat.com>
Patchwork-id: 182000
O-Subject: [PATCH RHEL7.5 66/94] perf tools: Add missing parse_events_error() prototype
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 34a0548f01626b01c9e98d9627812c3c9f6b6f7d
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Feb 15 10:09:11 2017 -0300

description
===========
As pointed out by clang, we were not providing a prototype for a
function before using it:

  util/parse-events.y:699:6: error: conflicting types for 'parse_events_error'
  void parse_events_error(YYLTYPE *loc, void *data,
       ^
  /tmp/build/perf/util/parse-events-bison.c:2224:7: note: previous implicit declaration is here
        yyerror (&yylloc, _data, scanner, YY_("syntax error"));
        ^
  /tmp/build/perf/util/parse-events-bison.c:65:25: note: expanded from macro 'yyerror'
  #define yyerror         parse_events_error

  1 error generated.

One line fix it.

Signed-off-by: Rafael Aquini <aquini@redhat.com>