[net] ipvs: handle ip_vs_fill_iph_skb_off failure
Message-id: <c9d28b095d9d66be7ddfcf6165fa901abc93402c.1459783301.git.pabeni@redhat.com>
Patchwork-id: 140242
O-Subject: [RHEL7.3 net PATCH 2/5] ipvs: handle ip_vs_fill_iph_skb_off failure
Bugzilla: 1322716
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1322716
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10762960
Tested: on local VM

conflicts: ip_vs_fill_iph_skb() takes only 3 parameters on rhel7 since we
lack 4fd9beef37f ("ipvs: Add hdr_flags to iphdr")

Upstream commit:
commit 3f20efba41916ee17ce82f0fdd02581ada2872b2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 27 14:52:02 2016 +0100

    ipvs: handle ip_vs_fill_iph_skb_off failure

    ip_vs_fill_iph_skb_off() may not find an IP header, and gcc has
    determined that ip_vs_sip_fill_param() then incorrectly accesses
    the protocol fields:

    net/netfilter/ipvs/ip_vs_pe_sip.c: In function 'ip_vs_sip_fill_param':
    net/netfilter/ipvs/ip_vs_pe_sip.c:76:5: error: 'iph.protocol' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      if (iph.protocol != IPPROTO_UDP)
         ^
    net/netfilter/ipvs/ip_vs_pe_sip.c:81:10: error: 'iph.len' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      dataoff = iph.len + sizeof(struct udphdr);
              ^

    This adds a check for the ip_vs_fill_iph_skb_off() return code
    before looking at the ip header data returned from it.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: b0e010c527de ("ipvs: replace ip_vs_fill_ip4hdr with ip_vs_fill_iph_skb_off")
    Acked-by: Julian Anastasov <ja@ssi.bg>
    Signed-off-by: Simon Horman <horms@verge.net.au>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>