[x86] trace: Add config option checking to the definitions of mce handlers
Message-id: <1373324810-26361-8-git-send-email-saguchi@redhat.com>
Patchwork-id: 61309
O-Subject: [RHEL7.0 PATCH v2 7/8] x86/tracing: Add config option checking to the definitions of mce handlers
Bugzilla: 741673
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=741673

Commit: 33e5ff634f07dec26b7ed1fd7f9e32978fe1f2b2
Author: Seiji Aguchi <seiji.aguchi@hds.com>
Date: Sat, 22 Jun 2013 07:33:30 -0400

In case CONFIG_X86_MCE_THRESHOLD and CONFIG_X86_THERMAL_VECTOR
are disabled, kernel build fails as follows.

   arch/x86/built-in.o: In function `trace_threshold_interrupt':
   (.entry.text+0x122b): undefined reference to `smp_trace_threshold_interrupt'
   arch/x86/built-in.o: In function `trace_thermal_interrupt':
   (.entry.text+0x132b): undefined reference to `smp_trace_thermal_interrupt'

In this case, trace_threshold_interrupt/trace_thermal_interrupt
are not needed to define.

So, add config option checking to their definitions in entry_64.S.

Signed-off-by: Seiji Aguchi <seiji.aguchi@hds.com>
Cc: rostedt@goodmis.org
Link: http://lkml.kernel.org/r/51C58B8A.2080808@hds.com
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Signed-off-by: Jarod Wilson <jarod@redhat.com>