[infiniband] ib/hfi1: use size_t for passing array length
Message-id: <20171011200214.23764-182-ddutile@redhat.com>
Patchwork-id: 191525
O-Subject: [PATCH RHEL-7.5 v2 181/233] IB/hfi1: use size_t for passing array length
Bugzilla: 1385309 1385649 1386645 1409099 1456667 1456687
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit 64b2ae74e83c0294f66ab8db9c99c274fa1a5f1a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 14 22:23:07 2017 +0100

    IB/hfi1: use size_t for passing array length

    gcc-7 produces a mysterious warning about the size argument being potentially out
    of range:

    drivers/infiniband/hw/hfi1/verbs.c: In function 'init_cntr_names':
    drivers/infiniband/hw/hfi1/verbs.c:1644:2: error: 'memcpy': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

    This seems to refer to a the case where an 64-bit size_t gets truncated
    into a negative 'int' and subsequently turned into a high 64-bit number
    again.

    The fix is clearly to use size_t here, which matches the type that gets
    used for this value elsewhere.

    Fixes: b7481944b06e ("IB/hfi1: Show statistics counters under IB stats interface")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>