[sound] alsa: atmel: Fix possible array overflow
Message-id: <1507829954160572-255-patchset-jkysela@redhat.com>
Patchwork-id: 192161
O-Subject: [RHEL 7.5 PATCH v2 0254/1088] ALSA: atmel: Fix possible array overflow
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The static checker found a possible array overflow in atmel/abdac.c:
  static checker warning: "sound/atmel/abdac.c:373 set_sample_rates()
        error: buffer overflow 'dac->rates' 6 <= 6"

This patch papers over the buggy point, by ensuring that dac->rates[]
update not overflowing the actual array size.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit e4de211cd31665c167351a428e08199ee6355e46)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>