[net] ip6_tunnel: make ip6tunnel_xmit definition conditional
Message-id: <1463509420-12020-178-git-send-email-lrichard@redhat.com>
Patchwork-id: 145544
O-Subject: [RHEL7.3 net PATCH v2 177/232] net: make ip6tunnel_xmit definition conditional
Bugzilla: 1283886
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1283886
Upstream Status: linus commit 0efeff2905d0ea14f2ee83e6cefbda35ee8cf6fc

commit 0efeff2905d0ea14f2ee83e6cefbda35ee8cf6fc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jan 1 13:18:48 2016 +0100

    net: make ip6tunnel_xmit definition conditional

    Moving the caller of iptunnel_xmit_stats causes a build error in
    randconfig builds that disable CONFIG_INET:

    In file included from ../net/xfrm/xfrm_input.c:17:0:
    ../include/net/ip6_tunnel.h: In function 'ip6tunnel_xmit':
    ../include/net/ip6_tunnel.h:93:2: error: implicit declaration of function 'iptunnel_xmit_stats' [-Werror=implicit-function-declaration]
      iptunnel_xmit_stats(dev, pkt_len);

    The reason is that the iptunnel_xmit_stats definition is hidden
    inside #ifdef CONFIG_INET but the caller is not. We can change
    one or the other to fix it, and this patch adds a second #ifdef
    around ip6tunnel_xmit() to avoid seeing the invalid call.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 039f50629b7f ("ip_tunnel: Move stats update to iptunnel_xmit()")
    Acked-by: Pravin B Shelar <pshelar@nicira.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Lance Richardson <lrichard@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>