[net] openvswitch: fix a compilation error when CONFIG_INET is not set
Message-id: <70dbe433bd15265f001b15f801c89b3ff5292c42.1434713811.git.jbenc@redhat.com>
Patchwork-id: 120058
O-Subject: [RHEL7.2 net PATCH 007/110] openvswitch: fix a compilation error when CONFIG_INET is not set
Bugzilla: 1156461 1211348
RH-Acked-by: Flavio Leitner <fbl@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1211348
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1156461

commit 7c5df8fa1921450d2210db9928f43cf4f414982c
Author: Andy Zhou <azhou@nicira.com>
Date:   Mon Oct 6 15:15:14 2014 -0700

    openvswitch: fix a compilation error when CONFIG_INET is not setW!

    Fix a openvswitch compilation error when CONFIG_INET is not set:

    =====================================================
       In file included from include/net/geneve.h:4:0,
                           from net/openvswitch/flow_netlink.c:45:
    		          include/net/udp_tunnel.h: In function 'udp_tunnel_handle_offloads':
    			  >> include/net/udp_tunnel.h:100:2: error: implicit declaration of function 'iptunnel_handle_offloads' [-Werror=implicit-function-declaration]
    			  >>      return iptunnel_handle_offloads(skb, udp_csum, type);
    			  >>           ^
    			  >>           >> include/net/udp_tunnel.h:100:2: warning: return makes pointer from integer without a cast
    			  >>           >>    cc1: some warnings being treated as errors

    =====================================================

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Andy Zhou <azhou@nicira.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>