[usb] core: Allow compilation on platforms where NO_DMA=y
Message-id: <1465525749-9195-106-git-send-email-torez@redhat.com>
Patchwork-id: 150139
O-Subject: [RHEL7 BZ1332712 v2 105/196] usb: core: Allow compilation on platforms where NO_DMA=y
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 58f2266f4019b9d023979de31950d34cce23b43c
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Tue Feb 16 16:10:57 2016 +0100

    usb: core: Allow compilation on platforms where NO_DMA=y

    Some platforms don't have DMA, but we should still be able to build USB
    drivers for these platforms. They could still be used through vhci_hcd,
    usbip_host, or maybe something like USB passthrough in UML from a
    capable host.

    If NO_DMA=y:

        ERROR: "dma_pool_destroy" [drivers/usb/core/usbcore.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/core/usbcore.ko] undefined!
        ERROR: "dma_pool_free" [drivers/usb/core/usbcore.ko] undefined!
        ERROR: "dma_pool_alloc" [drivers/usb/core/usbcore.ko] undefined!
        ERROR: "dma_pool_create" [drivers/usb/core/usbcore.ko] undefined!

    Add a few checks for CONFIG_HAS_DMA to fix this.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>