[pinctrl] pinconf: fix comparison of different types
Message-id: <1481818262-15690-8-git-send-email-darcari@redhat.com>
Patchwork-id: 161439
O-Subject: [RHEL7.4 PATCH BZ 1383814 06/15] pinctrl: pinconf: fix comparison of different types
Bugzilla: 1383814
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1383814

commit 9b6803542e1bd544289d605c84233a0e0a46ac7d
Author: Jingoo Han <jg1.han@samsung.com>
Date:   Tue Aug 6 18:10:20 2013 +0900

    pinctrl: pinconf: fix comparison of different types

    Fix the following sparse warning:

    drivers/pinctrl/pinconf.c:521:20: error: incompatible types in comparison expression (different type sizes)

    Signed-off-by: Jingoo Han <jg1.han@samsung.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

Cc: David Arcari <darcari@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>