[infiniband] hfi1: Remove inline from trace functions
Message-id: <1440002030-2889-52-git-send-email-dsowa@redhat.com>
Patchwork-id: 124170
O-Subject: [RHEL 7.2 PATCH bz1173291 51/57] IB/hfi1: Remove inline from trace functions
Bugzilla: 1173291
RH-Acked-by: Doug Ledford <dledford@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Dennis Dalessandro <dennis.dalessandro@intel.com>

Inline in trace functions causes the following build error when
CONFIG_OPTIMIZE_INLINING is not defined in the kernel config:
error: function can never be inlined because it uses
variable argument lists

Reported by 0-day build:
https://lists.01.org/pipermail/kbuild-all/2015-August/011215.html

This patch converts to a non-inline version of the hfi1 trace functions

Reviewed-by: Jubin John <jubin.john@intel.com>
Reviewed-by: Mike Marciniszyn <mike.marciniszyn@intel.com>
Signed-off-by: Dennis Dalessandro <dennis.dalessandro@intel.com>
Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 0a30409b399e563ec32070104c83374fc563c721)
Signed-off-by: David Sowa <dsowa@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>