[usb] devio: remove assignment from if condition
Message-id: <1462578743-3088-106-git-send-email-torez@redhat.com>
Patchwork-id: 143357
O-Subject: [RHEL7 PATCH BZ1303955 105/364] usb: devio: remove assignment from if condition
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 135551ea1abd5038d14825514df7e259fd500033
Author: Kris Borer <kborer@gmail.com>
Date:   Tue Aug 4 08:39:31 2015 -0400

    usb: devio: remove assignment from if condition

    Fix five occurrences of the checkpatch.pl error:

    ERROR: do not use assignment in if condition

    The semantic patch that makes this change is:

    // <smpl>
    @@
    identifier i;
    expression E;
    statement S1, S2;
    @@

    + i = E;
      if (
    - (i = E)
    + i
      ) S1 else S2

    @@
    identifier i;
    expression E;
    statement S;
    constant c;
    binary operator b;
    @@

    + i = E;
      if (
    - (i = E)
    + i
      b
      c ) S
    // </smpl>

    Signed-off-by: Kris Borer <kborer@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>