[tools] perf scripting perl: Fix compile error with some perl5 versions
Message-id: <20170807084247.7531-48-jolsa@redhat.com>
Patchwork-id: 181984
O-Subject: [PATCH RHEL7.5 47/94] perf scripting perl: Fix compile error with some perl5 versions
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit d7dd112ea5cacf91ae72c0714c3b911eb6016fea
Author: Wang YanQing <udknight@gmail.com>
Date: Sun Feb 12 10:46:55 2017 +0800

description
===========
Fix below compile error:

  CC       util/scripting-engines/trace-event-perl.o
  In file included from /usr/lib/perl5/5.22.2/i686-linux/CORE/perl.h:5673:0,
                   from util/scripting-engines/trace-event-perl.c:31:
  /usr/lib/perl5/5.22.2/i686-linux/CORE/inline.h: In function 'S__is_utf8_char_slow':
  /usr/lib/perl5/5.22.2/i686-linux/CORE/inline.h:270:5: error: nested extern declaration of 'Perl___notused' [-Werror=nested-externs]
          dTHX;   /* The function called below requires thread context */
			     ^
  cc1: all warnings being treated as errors

After digging perl5 repository, I find out that we will meet this
compile error with perl from v5.21.1 to v5.25.4

Signed-off-by: Rafael Aquini <aquini@redhat.com>