[fs] nfs4: fix missing-braces warning
Message-id: <20170310150235.10315-161-steved@redhat.com>
Patchwork-id: 173141
O-Subject: [RHEL7.4 fs PATCH 160/167] nfs4: fix missing-braces warning
Bugzilla: 1349668
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Benjamin Coddington <bcodding@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

A bugfix introduced a harmless warning for update_open_stateid:

fs/nfs/nfs4proc.c:1548:2: error: missing braces around initializer [-Werror=missing-braces]

Removing the zero in the initializer will do the right thing here
and initialize the entire structure to zero.

Fixes: 1393d9612ba0 ("NFSv4: Fix a race when updating an open_stateid")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
(cherry picked from commit 83aa3e0f791d458a28f91d7a50f92926f971ef7c)
Bugzilla: 1349668
Signed-off-by: Rafael Aquini <aquini@redhat.com>