[tools] perf probe: Fix list result when address is zero
Message-id: <1455542356-29341-186-git-send-email-jolsa@redhat.com>
Patchwork-id: 134553
O-Subject: [PATCH RHEL7.3 BZ1306834 185/237] perf probe: Fix list result when address is zero
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1306834
https://bugzilla.redhat.com/show_bug.cgi?id=1306834

upstream
========
commit be07afe92a09638db9159d2c0794487d66a437a2
Author: Wang Nan <wangnan0@huawei.com>
Date: Wed Aug 26 10:57:43 2015 +0000

description
===========
When manually added uprobe point with zero address, 'perf probe -l'
reports error. For example:

  # echo p:probe_libc/abs_0 /path/to/lib.bin:0x0 arg1=%ax > \
           /sys/kernel/debug/tracing/uprobe_events

  # perf probe -l
  Error: Failed to show event list.

Probing at 0x0 is possible and useful when lib.bin is not a normal
shared object but is manually mapped. However, in this case kernel
report:

  # cat /sys/kernel/debug/tracing/uprobe_events
  p:probe_libc/abs_0 /path/to/lib.bin:0x          (null) arg1=%ax

This patch supports the above kernel output.

Signed-off-by: Rafael Aquini <aquini@redhat.com>