[usb] add HAS_IOMEM dependency to USB_R8A66597_HCD
Message-id: <1465525749-9195-88-git-send-email-torez@redhat.com>
Patchwork-id: 150143
O-Subject: [RHEL7 BZ1332712 v2 087/196] usb: add HAS_IOMEM dependency to USB_R8A66597_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit e37a6c920ac1c22206350492b7d229f05c0849e4
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:40 2016 +0100

    usb: add HAS_IOMEM dependency to USB_R8A66597_HCD

      CC      drivers/usb/host/r8a66597-hcd.o
    drivers/usb/host/r8a66597-hcd.c: In function r8a66597_remove:
    drivers/usb/host/r8a66597-hcd.c:2401:2: error: implicit declaration of function iounmap [-Werror=implicit-function-declaration]
      iounmap(r8a66597->reg);
      ^
    drivers/usb/host/r8a66597-hcd.c: In function r8a66597_probe:
    drivers/usb/host/r8a66597-hcd.c:2447:2: error: implicit declaration of function ioremap [-Werror=implicit-function-declaration]
      reg = ioremap(res->start, resource_size(res));
      ^
    drivers/usb/host/r8a66597-hcd.c:2447:6: warning: assignment makes pointer from integer without a cast [enabled by default]
      reg = ioremap(res->start, resource_size(res));
          ^

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>