[acpi] nfit: fix smatch "use after null check" report
Message-id: <1464212242-20208-111-git-send-email-sandeen@redhat.com>
Patchwork-id: 147568
O-Subject: [RHEL7 PATCH 110/126] nfit: fix smatch "use after null check" report
Bugzilla: 1028649 1269626 1271953 1274043
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

From: Dan Williams <dan.j.williams@intel.com>

BZ: 1269626 1028649 1271953 1274043

commit 193ccca43850d2355e7690a93ab9d7d78d38f905
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Tue Jun 30 16:09:39 2015 -0400

    nfit: fix smatch "use after null check" report

    drivers/acpi/nfit.c:1224 acpi_nfit_blk_region_enable()
             error: we previously assumed 'nfit_mem' could be null (see line 1223)

    drivers/acpi/nfit.c
      1222          nfit_mem = nvdimm_provider_data(nvdimm);
      1223          if (!nfit_mem || !nfit_mem->dcr || !nfit_mem->bdw) {
                         ^^^^^^^^
    Check.

      1224                  dev_dbg(dev, "%s: missing%s%s%s\n", __func__,
      1225                                  nfit_mem ? "" : " nfit_mem",
      1226                                  nfit_mem->dcr ? "" : " dcr",
                                            ^^^^^^^^^^^^^
    Unchecked dereference.

    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Ross Zwisler <ross.zwisler@linux.intel.com>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>