[redhat] makefile, spec: add support for kABI duplist checking
Message-id: <20170411144017.GA29906@localhost.localdomain>
Patchwork-id: 5511
O-Subject: [kernel team] [RHEL7 PATCH V2] redhat: add support for kABI duplist checking
Bugzilla:
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

There is a request from the DUP team to be notified as soon as possible
about DUP symbol breakage, so they can act properly. This should be used by
zstreams only. Once DUP team prepares driver update for customer, they can
add all symbols used by the driver to the duplist. In future if one of
these symbols is changed, it will cause the zstream build to fail. Based
on this info the DUP team can propose a different patch to avoid the
breakage or at least they will know that they will have to rebuild the
driver. This works for dist-git builds, but more importantly also for
scratch builds, so we get the possible breakage info asap. By default the
duplist symbol files are empty and this should not affect ystream at
all, except that there will be four new empty files. The duplist
checking uses the same approach as kabi whitelist for rhel7.

There are four new files

Module.kabi_dup_x86_64
Module.kabi_dup_ppc64
Module.kabi_dup_ppc64le
Module.kabi_dup_s390x

with the kabi dup info generated by the rh-kabi-dup target. These files
are by default empty. If new symbol needs to be added to the kabi
duplist you need to create proper kabi-dup-module directories.

For example this will add the "panic" symbol to the kabi dup for x86_64.
 # cwd is rhel7 git source tree
 # create proper dir for x86_64
$ mkdir -p redhat/kabi/kabi-dup-module/kabi_x86_64
 # for testing copy panic symbol from kabi
$ cp redhat/kabi/kabi-module/kabi_x86_64/panic redhat/kabi/kabi-dup-module/kabi_x86_64/panic
 # generate kabi dup files
$ make rh-kabi-dup

There is rh-check-kabi-dup target as a complement to rh-check-kabi. As
stated above the kabi dup files are empty by default and no directories
exist for the kabi dup symbols in git source tree.

The kernel.spec contains new with_kabidupchk macro, which is by default
disabled. If kabi check is disabled, the kabi dup check is disabled
also.

The kabi dup checking is managed by the KABIDUPCHK define in
redhat/Makefile. By default it's set to "no" and is enabled once the
zstream takes over. It can be enabled at will if necessary even for
ystream builds.

 # start rhel7 scratch build with kabi dup check enabled
$ make rh-brew KABIDUPCHK=yes
 # create srpm with kabi dup check enables
$ make rh-srpm KABIDUPCHK=yes
 # disable kabi dup check
$ make rh-brew KABIDUPCHK=no
 # disable kabi dup check even if zstream is enabled
 # this may be helpfull if we really need to bypass the check
$ make rh-brew ZSTREAM=yes KABIDUPCHK=no

You can easily test this with the following commands. For example change
the panic symbol checksum for kabi dup, so the build fails.
 # create the panic symbol
$ mkdir -p redhat/kabi/kabi-dup-module/kabi_x86_64
$ cp redhat/kabi/kabi-module/kabi_x86_64/panic redhat/kabi/kabi-dup-module/kabi_x86_64/panic
 # change panic symbol checksum
$ vim redhat/kabi/kabi-dup-module/kabi_x86_64/panic
 # start the build with kabi dup check
$ make rh-brew KABIDUPCHK=yes

This will fail with the following message

**** kABI DUP checking is enabled in kernel SPEC file. ****
+ '[' -e /builddir/build/SOURCES/Module.kabi_dup_x86_64 ']'
+ cp /builddir/build/SOURCES/Module.kabi_dup_x86_64 /builddir/build/BUILDROOT/kernel-3.10.0-541.el7.test.x86_64/Module.kabi
+ /builddir/build/SOURCES/check-kabi -k /builddir/build/BUILDROOT/kernel-3.10.0-541.el7.test.x86_64/Module.kabi -s Module.symvers
*** ERROR - ABI BREAKAGE WAS DETECTED ***
The following symbols have been changed (this will cause an ABI breakage):
panic
+ exit 1
error: Bad exit status from /var/tmp/rpm-tmp.xus3xn (%build)

Note that this message is generated by check-kabi. We can add something
before or after it. Otherwise we need to change check-kabi also.

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>