[tools] Work around BITS_PER_LONG related build failure in objtool
Message-id: <1477399629-8377-230-git-send-email-jolsa@redhat.com>
Patchwork-id: 159638
O-Subject: [PATCH RHEL7.4 BZ1387909 229/322] tools: Work around BITS_PER_LONG related build failure in objtool
Bugzilla: 1387909
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1387909
https://bugzilla.redhat.com/show_bug.cgi?id=1387909

upstream
========
commit 7b39cafb7aa68ef8e32a9f51fbe737d96084ca74
Author: Ingo Molnar <mingo@kernel.org>
Date: Wed Jul 13 09:37:43 2016 +0200

description
===========
The objtool build fails with the recent changes to the bits-per-long
headers:

  tools/include/linux/bitops.h:12:0: error: "BITS_PER_LONG" redefined [-Werror]

Which got introduced by:

  bb9707077b4e tools: Copy the bitsperlong.h files from the kernel

Work it around for the time being.

Signed-off-by: Rafael Aquini <aquini@redhat.com>