[usb] kconfig: let USB_ULPI_BUS depends on USB_COMMON
Message-id: <1489393527-9024-264-git-send-email-torez@redhat.com>
Patchwork-id: 173737
O-Subject: [RHEL7.4 PATCH BZ1383823 263/467] usb: Kconfig: let USB_ULPI_BUS depends on USB_COMMON
Bugzilla: 1383823
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1383823
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12744255
Testing: on local desktop and Dell Precision 5510 laptop

commit 6406c3d226374c28d452b11db3b5ac241ce26191
Author: Peter Chen <peter.chen@nxp.com>
Date:   Mon Sep 12 16:38:46 2016 +0800

    usb: Kconfig: let USB_ULPI_BUS depends on USB_COMMON

    Since ulpi bus driver is located at usb/common/ulpi.c, whether it
    is compiled or not depends on CONFIG_USB_COMMON which needs either
    USB Host or USB Gadget is enabled, so even CONFIG_USB_ULPI_BUS is
    chosen, its source may still not be compiled when both USB HOST
    and USB gadget are disabled.

    It fixed compile error with below configurations:
    - # CONFIG_USB is not set
    - # CONFIG_USB_GADGET is not set
    - CONFIG_PHY_TUSB1210=m
    - CONFIG_USB_ULPI_BUS=m

    >> All errors (new ones prefixed by >>):
    >>
    >> ERROR: "ulpi_unregister_driver" [drivers/phy/phy-tusb1210.ko] undefined!
    >> ERROR: "__ulpi_register_driver" [drivers/phy/phy-tusb1210.ko] undefined!
    >> ERROR: "ulpi_write" [drivers/phy/phy-tusb1210.ko] undefined!

    Fixes: ad764c49f65a ("usb: Kconfig: move ulpi bus support out of host")
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Peter Chen <peter.chen@nxp.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>