[char] tpm: fix tpm_bios_log_setup stub prototype
Message-id: <20170302161601.26456-22-jsnitsel@redhat.com>
Patchwork-id: 169229
O-Subject: [RHEL7.4 PATCH BZ1383554 21/80] tpm: fix tpm_bios_log_setup stub prototype
Bugzilla: 1383554
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1383554,1384800
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12570603
Testing: https://beaker.engineering.redhat.com/jobs/1721553

Upstream commit: 796d803070c91f6e469e212acfdd618180f59e01
Original Author: Arnd Bergmann <arnd@arndb.de>
Commit Date:   Wed Mar 16 09:19:48 2016 +0100

A cleanup patch changed the prototype of the regular tpm_bios_log_setup
function, but not that of the stub that is used when the TPM is disabled,
causing a harmless build warning:

drivers/char/tpm/tpm-chip.c: In function 'tpm1_chip_register':
drivers/char/tpm/tpm-chip.c:287:38: error: passing argument 1 of 'tpm_bios_log_setup' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  chip->bios_dir = tpm_bios_log_setup(dev_name(&chip->dev));
In file included from ../drivers/char/tpm/tpm-chip.c:30:0:
../drivers/char/tpm/tpm_eventlog.h:83:31: note: expected 'char *' but argument is of type 'const char *'
 static inline struct dentry **tpm_bios_log_setup(char *name)

This changes the stub function to match the normal prototype,
avoiding that warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: aca8db8088c3 ("tpm: Get rid of devname")
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>

(imported from commit 796d803070c91f6e469e212acfdd618180f59e01)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>