[mmc] MMC_MTK should depend on HAS_DMA
Message-id: <1463503488-149391-611-git-send-email-dzickus@redhat.com>
Patchwork-id: 145223
O-Subject: [RHEL7 PATCH 610/725] mmc: MMC_MTK should depend on HAS_DMA
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit c2b22fff7186f8a6bd6dbfe960ad00421ba82a52
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Fri Jun 26 14:09:26 2015 +0200

    mmc: MMC_MTK should depend on HAS_DMA

    If NO_DMA=y:

        ERROR: "dma_alloc_coherent" [drivers/mmc/host/mtk-sd.ko] undefined!
        ERROR: "dma_unmap_sg" [drivers/mmc/host/mtk-sd.ko] undefined!
        ERROR: "dma_map_sg" [drivers/mmc/host/mtk-sd.ko] undefined!
        ERROR: "dma_free_coherent" [drivers/mmc/host/mtk-sd.ko] undefined!

    Add a dependency on HAS_DMA to fix this.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>