[tools] perf/callchains: Disable unwind libraries when libelf isn't found
Message-id: <1410181752-25631-121-git-send-email-jolsa@redhat.com>
Patchwork-id: 91787
O-Subject: [PATCH RHEL7.1 BZ1134356 120/307] perf callchains: Disable unwind libraries when libelf isn't found
Bugzilla: 1134356
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1134356
https://bugzilla.redhat.com/show_bug.cgi?id=1134356

upstream
========
commit 945895574873101c72a2d90a8cf1e09922378968
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Mar 25 09:35:11 2014 -0300

description
===========
I.e. do the same as when NO_LIBELF is explicitely passed in the 'make'
command line, fixing this:

  Auto-detecting system features:
  ...                         dwarf: [ OFF ]
  ...                         glibc: [ on  ]
  ...                          gtk2: [ OFF ]
  ...                      libaudit: [ OFF ]
  ...                        libbfd: [ OFF ]
  ...                        libelf: [ OFF ]
  ...                     libunwind: [ OFF ]
  ...            libdw-dwarf-unwind: [ OFF ]
  ...     DWARF post unwind library: libdw
<SNIP>
    CC       /tmp/build/perf/util/symbol-minimal.o
    CC       /tmp/build/perf/util/unwind-libdw.o
  arch/x86/util/unwind-libdw.c:1:30: fatal error: elfutils/libdwfl.h: No such file or directory
  compilation terminated.
    CC       /tmp/build/perf/tests/keep-tracking.o
  util/unwind-libdw.c:2:28: fatal error: elfutils/libdw.h: No such file or directory
  compilation terminated.
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>