[drm] bridge: ptn3460: Include linux/gpio/consumer.h
Message-id: <1441058380-15150-16-git-send-email-rclark@redhat.com>
Patchwork-id: 124604
O-Subject: [RHEL7 drm 15/52] drm/bridge: ptn3460: Include linux/gpio/consumer.h
Bugzilla: 1249805
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Ben Skeggs <bskeggs@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1249805
Upstream: since v4.1.4

commit db4d9159da3f595b964d986cb53d33fd24e5774c

Author:     Geert Uytterhoeven <geert@linux-m68k.org>
AuthorDate: Tue May 5 18:32:17 2015 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Mon Aug 3 09:29:08 2015 -0700

    drm/bridge: ptn3460: Include linux/gpio/consumer.h

    commit dad3c3503462f59c6bec7edfa19dbde1857962c0 upstream.

    If GPIOLIB=n and asm-generic/gpio.h is not used:

        drivers/gpu/drm/bridge/ptn3460.c: In function ptn3460_pre_enable:
        drivers/gpu/drm/bridge/ptn3460.c:135: error: implicit declaration of function gpiod_set_value
        drivers/gpu/drm/bridge/ptn3460.c: In function ptn3460_probe:
        drivers/gpu/drm/bridge/ptn3460.c:333: error: implicit declaration of function devm_gpiod_get
        drivers/gpu/drm/bridge/ptn3460.c:333: warning: assignment makes pointer from integer without a cast
        drivers/gpu/drm/bridge/ptn3460.c:340: error: implicit declaration of function gpiod_direction_output
        drivers/gpu/drm/bridge/ptn3460.c:346: warning: assignment makes pointer from integer without a cast

    Add the missing #include <linux/gpio/consumer.h> to fix this.

    Fixes: af478d8823 ("drm/bridge: ptn3460: use gpiod interface")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Cc: David Airlie <airlied@linux.ie>
    Cc: dri-devel@lists.freedesktop.org
    Signed-off-by: Thierry Reding <treding@nvidia.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>