[usb] endpoint: convert spaces to tabs
Message-id: <1462578743-3088-120-git-send-email-torez@redhat.com>
Patchwork-id: 143345
O-Subject: [RHEL7 PATCH BZ1303955 119/364] usb: endpoint: convert spaces to tabs
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 3290b1b818934a517a593159f39a3651dcf34518
Author: Kris Borer <kborer@gmail.com>
Date:   Mon Aug 10 09:13:15 2015 -0400

    usb: endpoint: convert spaces to tabs

    Fix one occurrence of the checkpatch error:

    ERROR: code indent should use tabs where possible

    Signed-off-by: Kris Borer <kborer@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>