[tools] peeksiginfo: add PAGE_SIZE definition
Message-id: <20141209194937.11634.76679.sendpatchset@ibm-p7r2-01.lab.bos.redhat.com>
Patchwork-id: 101204
O-Subject: [PATCH RHEL7.1 BZ1172250] tools/testing/selftests/ptrace/peeksiginfo.c: add PAGE_SIZE definition
Bugzilla: 1172250
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

RHBZ#:
------
https://bugzilla.redhat.com/show_bug.cgi?id=1172250

Description:
------------
On IBM powerpc where multiple page size value are supported, current
ppc64 and ppc64el distro don't define the PAGE_SIZE variable in
/usr/include as this is a dynamic value retrieved by the getpagesize()
or sysconf() defined in unistd.h.  The PAGE_SIZE variable sounds defined
when only one value is supported by the kernel.

As such, when the PAGE_SIZE definition doesn't exist system should
retrieve the dynamic value.

Signed-off-by: Thierry Fauck <thierry@linux.vnet.ibm.com>
Cc: Andrey Vagin <avagin@openvz.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Brew:
-----
BE: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=8352966
LE: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=8352992

Upstream:
---------
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=8b6aaf65d3b001ec9b5dcba0992b3b68cbf6057f

Test Status:
------------
Tested by me.

Before the patch there is a compiler error

[root@ibm-p8-kvm-lt-guest-03 ptrace]# make
cc -iquote../../../../include/uapi -Wall    peeksiginfo.c   -o peeksiginfo
peeksiginfo.c: In function ‘check_error_paths’:
peeksiginfo.c:49:27: error: ‘PAGE_SIZE’ undeclared (first use in this function)
  addr_rw = mmap(NULL, 2 * PAGE_SIZE, PROT_READ | PROT_WRITE,
                           ^
peeksiginfo.c:49:27: note: each undeclared identifier is reported only once for each function it appears in
make: *** [peeksiginfo] Error 1

after the patch no compiler error and the test will pass

[root@ibm-p8-kvm-lt-guest-03 ptrace]# make
cc -iquote../../../../include/uapi -Wall    peeksiginfo.c   -o peeksiginfo
[root@ibm-p8-kvm-lt-guest-03 ptrace]# ls
Makefile  peeksiginfo  peeksiginfo.c
[root@ibm-p8-kvm-lt-guest-03 ptrace]# ./peeksiginfo
PASS

---------------------------------------------------------------
Steve Best

Proposed Patch:
---------------

Signed-off-by: Jarod Wilson <jarod@redhat.com>