[tools] perf tools: Fix shadowed declaration in parse-events.c
Message-id: <1456127829-13546-123-git-send-email-jolsa@redhat.com>
Patchwork-id: 135397
O-Subject: [PATCH BZ1308570 122/260] perf tools: Fix shadowed declaration in parse-events.c
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit 272ed29a91aea4397c05157dea7210dd7e81557a
Author: Jiri Olsa <jolsa@redhat.com>
Date: Tue Sep 29 17:05:31 2015 +0200

description
===========
The error variable breaks build on CentOS 6.7, due to a collision with a
global error symbol:

    CC       util/parse-events.o
  cc1: warnings being treated as errors
  util/parse-events.c:419: error: declaration of error shadows a global
  declaration
  util/util.h:135: error: shadowed declaration is here
  util/parse-events.c: In function add_tracepoint_multi_event:
  ...

Using different argument names instead to fix it.

[ Fix one more case, at line 770 ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>