[perf] probe: Check kprobes blacklist when adding new events
Message-id: <1431774138-14330-126-git-send-email-jolsa@redhat.com>
Patchwork-id: 112347
O-Subject: [PATCH RHEL7.2 BZ1222189 125/327] perf probe: Check kprobes blacklist when adding new events
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 9aaf5a5f479bd68699f2e6f6e5e5f1253377b6da
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Thu Feb 19 23:31:13 2015 +0900

description
===========
Recent linux kernel provides a blacklist of the functions which can not
be probed. perf probe can now check this blacklist before setting new
events and indicate better error message for users.

Without this patch,
  ----
  # perf probe --add vmalloc_fault
  Added new event:
  Failed to write event: Invalid argument
    Error: Failed to add events.
  ----
With this patch
  ----
  # perf probe --add vmalloc_fault
  Added new event:
  Warning: Skipped probing on blacklisted function: vmalloc_fault
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>