[tools] perf: Fix pmu object compilation error
Message-id: <1410181752-25631-158-git-send-email-jolsa@redhat.com>
Patchwork-id: 91900
O-Subject: [PATCH RHEL7.1 BZ1134356 157/307] perf tools: Fix pmu object compilation error
Bugzilla: 1134356
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1134356
https://bugzilla.redhat.com/show_bug.cgi?id=1134356

upstream
========
commit 7c2f8164e5415ef48954f6929f4acae5764afdb4
Author: Jiri Olsa <jolsa@redhat.com>
Date: Wed Apr 16 20:49:02 2014 +0200

description
===========
After applying some patches got another shadowing error:

  CC       util/pmu.o
util/pmu.c: In function 'pmu_alias_terms':
util/pmu.c:287:35: error: declaration of 'clone' shadows a global declaration [-Werror=shadow]

Renaming clone to cloned.

Signed-off-by: Jarod Wilson <jarod@redhat.com>