[netdrv] mlxfw: Properly handle dependancy with non-loadable mlx5
Message-id: <20171111045127.10299-51-ddutile@redhat.com>
Patchwork-id: 197617
O-Subject: [PATCH RHEL-7.5 050/251] net/mlxfw: Properly handle dependancy with non-loadable mlx5
Bugzilla: 1499363 1466367
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit c1c1d86bdea45880c1843087d40498127d4293c9
Author: Or Gerlitz <ogerlitz@mellanox.com>
Date:   Sun Jul 2 18:57:28 2017 +0300

    net/mlxfw: Properly handle dependancy with non-loadable mlx5

    If mlx5 is set to be built-in and mlxfw as a module, we
    get a link error:

    drivers/built-in.o: In function `mlx5_firmware_flash':
    (.text+0x5aed72): undefined reference to `mlxfw_firmware_flash'

    Since we don't want to mandate selecting mlxfw for mlx5 users, we
    use the IS_REACHABLE macro to make sure that a stub is exposed
    to the caller.

    Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>
    Reported-by: Jakub Kicinski <kubakici@wp.pl>
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1466367

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>