[sound] alsa: asoc: cht_bsw_max98090_ti: Remove unused function cht_get_codec_dai()
Message-id: <1507829954160572-638-patchset-jkysela@redhat.com>
Patchwork-id: 193110
O-Subject: [RHEL 7.5 PATCH v2 0637/1088] ALSA: ASoC: cht_bsw_max98090_ti: Remove unused function cht_get_codec_dai()
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Looks like the function has never been used since it was added by commit
17119a465706 ("ASoC: Intel: Add Cherrytrail & Braswell machine driver
cht_bsw_max98090_ti"). Removing it fixes the following warning when
building with clang:

sound/soc/intel/boards/cht_bsw_max98090_ti.c:42:35: error: unused
function 'cht_get_codec_dai' [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 140385d87adce8d00864667f5132770ac5a13dac)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>