[infiniband] sunrpc: fix build errors when linux/phy*.h is removed from sa.h
Message-id: <20171011200214.23764-117-ddutile@redhat.com>
Patchwork-id: 191459
O-Subject: [PATCH RHEL-7.5 v2 116/233] net: sunrpc: fix build errors when linux/phy*.h is removed from net/dsa.h
Bugzilla: 1385309 1385649 1386645 1409099 1456667 1456687
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit f39b2dde4886450b965ccd0a6defe8bc33fcc938
Author: Russell King <rmk+kernel@armlinux.org.uk>
Date:   Tue Feb 7 15:02:54 2017 -0800

    net: sunrpc: fix build errors when linux/phy*.h is removed from net/dsa.h

    Removing linux/phy.h from net/dsa.h reveals a build error in the sunrpc
    code:

    net/sunrpc/xprtrdma/svc_rdma_backchannel.c: In function 'xprt_rdma_bc_put':
    net/sunrpc/xprtrdma/svc_rdma_backchannel.c:277:2: error: implicit declaration of function 'module_put' [-Werror=implicit-function-declaration]
    net/sunrpc/xprtrdma/svc_rdma_backchannel.c: In function 'xprt_setup_rdma_bc':
    net/sunrpc/xprtrdma/svc_rdma_backchannel.c:348:7: error: implicit declaration of function 'try_module_get' [-Werror=implicit-function-declaration]

    Fix this by adding linux/module.h to svc_rdma_backchannel.c

    Signed-off-by: Russell King <rmk+kernel@armlinux.org.uk>
    Acked-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>