[ethernet] bnx2x: Fix build with SRIOV disabled
Message-id: <1389196831-1765-20-git-send-email-mschmidt@redhat.com>
Patchwork-id: 73606
O-Subject: [RHEL7.0 PATCH 19/29] bnx2x: Fix build with SRIOV disabled.
Bugzilla: 1038666
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Veaceslav Falico <vfalico@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1038666

Upstream commit:
commit fcf93a0a2f9d317c0bffc430ddf8950041d13265
Author: David S. Miller <davem@davemloft.net>
Date:   Thu Dec 26 18:33:10 2013 -0500

    bnx2x: Fix build with SRIOV disabled.

    drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.c: In function 'bnx2x_drv_info_ether_stat':
    drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.c:3302:46: error: dereferencing pointer to incomplete type
    make[6]: *** [drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.o] Error 1

    Reported-by: Eric Dumazet <eric.dumazet@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jarod Wilson <jarod@redhat.com>