[include] gpiolib: include gpio/consumer.h in of_gpio.h for desc_to_gpio()
Message-id: <1463503488-149391-101-git-send-email-dzickus@redhat.com>
Patchwork-id: 144777
O-Subject: [RHEL7 PATCH 100/725] gpiolib: include gpio/consumer.h in of_gpio.h for desc_to_gpio()
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 335d7a7d63aa3a6da4d4903ef6e64de4a88f27da
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Tue Oct 29 20:10:13 2013 +1100

    gpiolib: include gpio/consumer.h in of_gpio.h for desc_to_gpio()

    Fixes this build error on sparc:

    In file included from drivers/spi/spi.c:33:0:
    include/linux/of_gpio.h: In function 'of_get_named_gpio_flags':
    include/linux/of_gpio.h:93:3: error: implicit declaration of function 'desc_to_gpio' [-Werror=implicit-function-declaration]

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>