[scsi] cxgbi: fix build with EXTRA_CFLAGS
Message-id: <1505805574-20488-3-git-send-email-avynipad@redhat.com>
Patchwork-id: 185562
O-Subject: [RHEL7.5 PATCH BZ 1458307 2/3] drivers/scsi/cxgbi: fix build with EXTRA_CFLAGS
Bugzilla: 1458307
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1458307

commit ce1fb04153e6d27b5f0e23a30bacaacfcae8195f
Author: Jiri Slaby <jslaby@suse.cz>
Date:   Mon Nov 9 14:58:21 2015 -0800

    drivers/scsi/cxgbi: fix build with EXTRA_CFLAGS

    EXTRA_CFLAGS are intended to be used on the command line, not by Kbuild.
    In case of cxgbi drivers, use of EXTRA_CFLAGS results in a compilation
    failure:

      drivers/scsi/cxgbi/cxgb4i/cxgb4i.c:24:21: fatal error: t4_regs.h: No such file or directory

    when building like:

    $ make drivers/scsi/cxgbi/ EXTRA_CFLAGS=-Wwhatever

    Use ccflags-y instead of EXTRA_CFLAGS.

    Signed-off-by: Jiri Slaby <jslaby@suse.cz>
    Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
    Cc: James Bottomley <James.Bottomley@HansenPartnership.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Cc: David Milburn <dmilburn@redhat.com>
Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Sai Vemuri <svemuri@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>