[netdrv] mlx5e: fix build error without CONFIG_SYSFS
Message-id: <20171109065423.8574-115-ddutile@redhat.com>
Patchwork-id: 197096
O-Subject: [PATCH RHEL-7.5 v2 114/468] net/mlx5e: fix build error without CONFIG_SYSFS
Bugzilla: 1456694 1499362
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit 053ee0a7035781a27eedb2b06cac638c8c65ce83
Author: Tobias Regnery <tobias.regnery@gmail.com>
Date:   Wed Apr 5 11:11:10 2017 +0200

    net/mlx5e: fix build error without CONFIG_SYSFS

    Commit 9008ae074885 ("net/mlx5e: Minimize mlx5e_{open/close}_locked")
    copied the calls to netif_set_real_num_{tx,rx}_queues from
    mlx5e_open_locked to mlx5e_activate_priv_channels and wraps them in an
    if condition to test for netdev->real_num_{tx,rx}_queues.

    But netdev->real_num_rx_queues is conditionally compiled in if CONFIG_SYSFS
    is set. Without CONFIG_SYSFS the build fails:

    drivers/net/ethernet/mellanox/mlx5/core/en_main.c: In function 'mlx5e_activate_priv_channels':
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2515:12: error: 'struct net_device' has no member named 'real_num_rx_queues'; did you mean 'real_num_tx_queues'?

    Fix this by unconditionally call netif_set_real_num{tx,rx}_queues like before
    commit 9008ae074885.

    Fixes: 9008ae074885 ("net/mlx5e: Minimize mlx5e_{open/close}_locked")
    Signed-off-by: Tobias Regnery <tobias.regnery@gmail.com>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456694

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>