[net] netfilter: ipt_CLUSTERIP: fix build error without procfs
Message-id: <cfe8e08ea3a0bad298ce544a31af947cdc68ee99.1500931861.git.sbrivio@redhat.com>
Patchwork-id: 181104
O-Subject: [RHEL7.5 net 2/3] netfilter: ipt_CLUSTERIP: fix build error without procfs
Bugzilla: 1472892
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1472892

commit 3fd0b634de7d6b9a85f34a4cf9d8afc1df465cc9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jan 13 16:41:03 2017 +0100

    netfilter: ipt_CLUSTERIP: fix build error without procfs

    We can't access c->pde if CONFIG_PROC_FS is disabled:

    net/ipv4/netfilter/ipt_CLUSTERIP.c: In function 'clusterip_config_find_get':
    net/ipv4/netfilter/ipt_CLUSTERIP.c:147:9: error: 'struct clusterip_config' has no member named 'pde'

    This moves the check inside of another #ifdef.

    Fixes: 6c5d5cfbe3c5 ("netfilter: ipt_CLUSTERIP: check duplicate config when initializing")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>