[mmc] simplify SDHCI Kconfig dependencies
Message-id: <1463503488-149391-310-git-send-email-dzickus@redhat.com>
Patchwork-id: 144758
O-Subject: [RHEL7 PATCH 309/725] mmc: simplify SDHCI Kconfig dependencies
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 5d01b7684b7ebade6d9ea9c94a31357aec731ecd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jun 5 23:14:41 2014 +0200

    mmc: simplify SDHCI Kconfig dependencies

    We have a number of front-end drivers for SDHCI_PLTFM, some of them
    use 'select MMC_SDHCI_PLTFM', others use 'depends on'. This is
    inconsistent and confusing, and in one case has also led to a
    build error because of incomplete dependencies:

    warning: (MMC_SDHCI_PXAV3 && MMC_SDHCI_PXAV2 && MMC_SDHCI_BCM_KONA) selects MMC_SDHCI_PLTFM which has unmet direct dependencies (MMC && MMC_SDHCI)
    drivers/built-in.o: In function `sdhci_sirf_resume':
    :(.text+0xaaacb4): undefined reference to `sdhci_resume_host'
    drivers/built-in.o: In function `sdhci_sirf_suspend':
    :(.text+0xaaacf8): undefined reference to `sdhci_suspend_host'
    drivers/built-in.o: In function `sdhci_sirf_probe':
    :(.text+0xaaaf44): undefined reference to `sdhci_add_host'
    :(.text+0xaaaf50): undefined reference to `sdhci_remove_host'

    This changes Kconfig to use 'depends on MMC_SDHCI_PLTFM' for all these
    cases, to fix the build error and make the logic more logical.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>