[tools] perf top: Use __fallthrough
Message-id: <20170807084247.7531-37-jolsa@redhat.com>
Patchwork-id: 181977
O-Subject: [PATCH RHEL7.5 36/94] perf top: Use __fallthrough
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 7b0214b702ad8e124e039a317beeebb3f020d125
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Feb 8 17:01:46 2017 -0300

description
===========
The implicit fall through case label here is intended, so let us inform
that to gcc >= 7:

    CC       /tmp/build/perf/builtin-top.o
  builtin-top.c: In function 'display_thread':
  builtin-top.c:644:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
      if (errno == EINTR)
         ^
  builtin-top.c:647:3: note: here
     default:
   ^~~~~~~

Signed-off-by: Rafael Aquini <aquini@redhat.com>