[net] netfilter: nft_reject_bridge: Fix powerpc build error
Message-id: <9d061ad2658492df3516f2d0198f6bfa7c779e1c.1465290493.git.pabeni@redhat.com>
Patchwork-id: 149210
O-Subject: [RHEL7.3 net PATCH 025/165] netfilter: nft_reject_bridge: Fix powerpc build error
Bugzilla: 1331757
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1331757
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11141575
Tested: nftables test-suite and basic functional tests

Upstream commit:
commit c1207c049b204b0a96535dc5416aee331b51e0e1
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Sun Nov 2 18:19:15 2014 -0800

    netfilter: nft_reject_bridge: Fix powerpc build error

    Fix:
    net/bridge/netfilter/nft_reject_bridge.c:
    In function 'nft_reject_br_send_v6_unreach':
    net/bridge/netfilter/nft_reject_bridge.c:240:3:
    	error: implicit declaration of function 'csum_ipv6_magic'
       csum_ipv6_magic(&nip6h->saddr, &nip6h->daddr,
       ^
    make[3]: *** [net/bridge/netfilter/nft_reject_bridge.o] Error 1

    Seen with powerpc:allmodconfig.

    Fixes: 523b929d5446 ("netfilter: nft_reject_bridge: don't use IP stack to reject traffic")
    Cc: Pablo Neira Ayuso <pablo@netfilter.org>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>