[ethernet] mlx4: Select PTP_1588_CLOCK
Message-id: <8f8a897b70faccc4bfe200fff92e700bf29b4f43.1410425016.git.avadai@redhat.com>
Patchwork-id: 93608
O-Subject: [Patch RHEL7.1 V1 042/197] mlx4_en: Select PTP_1588_CLOCK
Bugzilla: 1107617 1107618 1107619 1107620
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

From: Shawn Bohrer <sbohrer@rgmadvisors.com>

Now that mlx4_en includes a PHC driver it must select PTP_1588_CLOCK.

   drivers/built-in.o: In function `mlx4_en_get_ts_info':
>> en_ethtool.c:(.text+0x391a11): undefined reference to `ptp_clock_index'
   drivers/built-in.o: In function `mlx4_en_remove_timestamp':
>> (.text+0x397913): undefined reference to `ptp_clock_unregister'
   drivers/built-in.o: In function `mlx4_en_init_timestamp':
>> (.text+0x397b20): undefined reference to `ptp_clock_register'

Fixes: ad7d4eaed995d ("mlx4_en: Add PTP hardware clock")
Signed-off-by: Shawn Bohrer <sbohrer@rgmadvisors.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 74b9c3ea847f060c784e86453f1ad77dd05a7a8f)
Signed-off-by: Amir Vadai <avadai@redhat.com>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>