[net] tso: Export symbols for modular build
Message-id: <1465404903-10572-12-git-send-email-ivecera@redhat.com>
Patchwork-id: 149814
O-Subject: [RHEL7.3 net PATCH 11/22] net: tso: Export symbols for modular build
Bugzilla: 1268334
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Lance Richardson <lrichard@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ#1268334

Upstream commit(s):
commit 484611e53047b55163822bfe60424a55a31775b3
Author: Sachin Kamat <sachin.kamat@linaro.org>
Date:   Mon May 26 14:52:46 2014 +0530

    net: tso: Export symbols for modular build

    Export the symbols to fix the below errors when built as modules:
    ERROR: "tso_build_data" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
    ERROR: "tso_build_hdr" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
    ERROR: "tso_start" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
    ERROR: "tso_count_descs" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
    ERROR: "tso_build_data" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!
    ERROR: "tso_build_hdr" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!
    ERROR: "tso_start" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!
    ERROR: "tso_count_descs" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!

    Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
    Acked-by: Ezequiel Garcia <ezequiel.garcia@free-electrons.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>