[acpi] button: fix button driver compile error when CONFIG_PM_SLEEP is undefined
Message-id: <1494358442-16174-2-git-send-email-lszubowi@redhat.com>
Patchwork-id: 178001
O-Subject: [RHEL 7.4 PATCH BZ 1246944 1/2] ACPI / button: fix button driver compile error when CONFIG_PM_SLEEP is undefined
Bugzilla: 1246944
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1246944

Upstream Status: 2de9fd17c0359fea0c2ab5ae393c40d6d299bcaf

Description:
    Including this simple upstream patch to eliminate a merge conflict
    with the next patch in this set.

Build Info:
    https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=13152668

commit 2de9fd17c0359fea0c2ab5ae393c40d6d299bcaf
Author: Shuah Khan <shuah.kh@samsung.com>
Date:   Wed Feb 12 20:19:07 2014 -0700

    ACPI / button: fix button driver compile error when CONFIG_PM_SLEEP is undefined

    The ACPI button driver defines acpi_button_resume() when
    CONFIG_PM_SLEEP is defined. This results in the following
    compile error when CONFIG_PM_SLEEP is undefined:

    drivers/acpi/button.c:85:8: error: 'acpi_button_resume' undeclared here (not in a function)

    Signed-off-by: Shuah Khan <shuah.kh@samsung.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>