[tools] perf tools: Fix build failure on 32-bit arch
Message-id: <1455060817-26852-256-git-send-email-jolsa@redhat.com>
Patchwork-id: 134045
O-Subject: [PATCH RHEL7.3 BZ1305882 255/360] perf tools: Fix build failure on 32-bit arch
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 6ba29c2fa5adcc33b201faec99057b6a72bd5029
Author: He Kuang <hekuang@huawei.com>
Date: Thu Jun 11 12:44:24 2015 +0000

description
===========
Failed in 32bit arch build like this:

    CC       /opt/h00206996/output/perf/arm32/builtin-record.o
  util/session.c: In function perf_session__warn_about_errors:
  util/session.c:1304:9: error: format %lu expects argument of type long unsigned int,
                         but argument 2 has type long long unsigned int [-Werror=format=]

  builtin-report.c: In function perf_evlist__tty_browse_hists:
  builtin-report.c:323:2: error: format %lu expects argument of type long unsigned int,
                          but argument 3 has type u64 [-Werror=format=]

Replace %lu format strings in warning message with PRIu64 for u64
'total_lost_samples' to fix this problem.

Signed-off-by: Rafael Aquini <aquini@redhat.com>