[powerpc] kvm: Fix ppc64_defconfig + PPC_POWERNV=n build error
Message-id: <1449160858-3612-4-git-send-email-thuth@redhat.com>
Patchwork-id: 128327
O-Subject: [RHEL7.3 kvm PATCH 3/4] powerpc/kvm: Fix ppc64_defconfig + PPC_POWERNV=n build error
Bugzilla: 1287973
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>

From: "Shreyas B. Prabhu" <shreyas@linux.vnet.ibm.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1287973
Upstream Status: a7e73e711e48e138a25265c156cca9a1ed109b50

This fix has been included so that the next patch applies properly.

commit a7e73e711e48e138a25265c156cca9a1ed109b50
Author: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
Date:   Thu Apr 16 16:28:09 2015 +0530

    powerpc/kvm: Fix ppc64_defconfig + PPC_POWERNV=n build error

    kvm_no_guest() calls power7_wakeup_loss() to put the thread into the
    deepest supported idle state. power7_wakeup_loss() is defined in
    arch/powerpc/kernel/idle_power7.S, which is compiled only when
    PPC_P7_NAP=y.

    And PPC_P7_NAP is selected when PPC_POWERNV=y.

    Hence in cases where PPC_POWERNV=n and KVM_BOOK3S_64_HV=y we see the
    following error:

      arch/powerpc/kvm/built-in.o: In function `kvm_no_guest':
      arch/powerpc/kvm/book3s_hv_rmhandlers.o:(.text+0x42c): undefined reference to `power7_wakeup_loss'

    Fix this by adding PPC_POWERNV as a dependency for KVM_BOOK3S_64_HV.

    Signed-off-by: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Rafael Aquini <aquini@redhat.com>