[net] netfilter: bridge: use rcu hook to resolve br_netfilter dependency
Message-id: <8ed64aa93764c79d5864f9ddafb6734327bd3536.1447088666.git.pabeni@redhat.com>
Patchwork-id: 126466
O-Subject: [RHEL7.3 net PATCH 30/64] netfilter: bridge: use rcu hook to resolve br_netfilter dependency
Bugzilla: 1265259
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1265259
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10081936
Tested on: local VM

Upstream linux-net commit:
commit 1a4ba64d16a42c1b31d52b671accd7f9103e2626
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Tue Mar 10 10:27:18 2015 +0100

    netfilter: bridge: use rcu hook to resolve br_netfilter dependency

    e5de75b ("netfilter: bridge: move DNAT helper to br_netfilter") results
    in the following link problem:

    net/bridge/br_device.c:29: undefined reference to `br_nf_prerouting_finish_bridge`

    Moreover it creates a hard dependency between br_netfilter and the
    bridge core, which is what we've been trying to avoid so far.

    Resolve this problem by using a hook structure so we reduce #ifdef
    pollution and keep bridge netfilter specific code under br_netfilter.c
    which was the original intention.

    Reported-by: Simon Horman <simon.horman@netronome.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>