[tools] perf tools: Fix bison-related build failure on CentOS 6
Message-id: <1455060817-26852-86-git-send-email-jolsa@redhat.com>
Patchwork-id: 133875
O-Subject: [PATCH RHEL7.3 BZ1305882 085/360] perf tools: Fix bison-related build failure on CentOS 6
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 539f3aa2ebb42a409bc9028e38af091a86087165
Author: Namhyung Kim <namhyung@kernel.org>
Date: Wed Apr 29 12:55:00 2015 -0300

description
===========
The YYLTYPE_IS_TRIVIAL is defined in the Build file, but unlike
pmu-bison.c, gcc complained about it for parse-events-bison.c:

    CC       util/parse-events-bison.o
  In file included from util/parse-events.y:16:
  util/parse-events-bison.h:101:1: error: "YYLTYPE_IS_TRIVIAL" redefined
  <command-line>: error: this is the location of the previous definition
  make[3]: *** [util/parse-events-bison.o] Error 1

Comments from Jiri Olsa:

"Reason is the parse error handling that was added just recently: it
adds YYLTYPE type (which is not present in pmu-bison.h), so
YYLTYPE_IS_TRIVIAL gets redefined, which is ok in F20 that handle the
error via '-w' option, but it's not ok for RHEL6 where the '-w' does not
work for this kind of error."

Signed-off-by: Rafael Aquini <aquini@redhat.com>