[include] usb: fix build error without CONFIG_USB_PHY
Message-id: <1457470219-37147-13-git-send-email-dzickus@redhat.com>
Patchwork-id: 137612
O-Subject: [RHEL7 PATCH 012/423] usb: fix build error without CONFIG_USB_PHY
Bugzilla: 1303209
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303209

commit 848d5b9121e52f63847bf9e156f836db001f51c7
Author: Peter Chen <peter.chen@freescale.com>
Date:   Mon Jun 24 09:25:59 2013 +0800

    usb: fix build error without CONFIG_USB_PHY

    on i386:

    drivers/built-in.o: In function `ci_hdrc_probe':
    core.c:(.text+0x20446b): undefined reference to `of_usb_get_phy_mode'

    Signed-off-by: Peter Chen <peter.chen@freescale.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Alexander Shishkin <alexander.shishkin@linux.intel.com>
    Acked-by: Felipe Balbi <balbi@ti.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>