[sound] alsa: ymfpci: Use common error handling code in snd_card_ymfpci_probe()
Message-id: <1507829954160572-251-patchset-jkysela@redhat.com>
Patchwork-id: 192158
O-Subject: [RHEL 7.5 PATCH v2 0250/1088] ALSA: ymfpci: Use common error handling code in snd_card_ymfpci_probe()
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

* Add a jump target so that a bit of exception handling can be better
reused at the end of this function.

This issue was detected by using the Coccinelle software.

* The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix a few source code places.

[ This also fixed a potential use-after-free at error path of
snd_opl3_hwdep_new(), too -- tiwai ]

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 1f5ca8ec58eaa9d42a2474ecae335ead3f845ba1)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>