[x86] boot: Refuse to build with data relocations
Message-id: <1487170014-11002-89-git-send-email-bhe@redhat.com>
Patchwork-id: 166273
O-Subject: [RHEL7.4 PATCH v2 088/105] x86/boot: Refuse to build with data relocations
Bugzilla: 1290840
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Xunlei Pang <xpang@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

This is back ported from upstream directly. There's conflict
because commit be1fb0e ("kbuild: delete unnecessary "@:"")
has not been back ported yet.

commit 98f78525371b55ccd1c480207ce10296c72fa340
Author: Kees Cook <keescook@chromium.org>
Date:   Wed May 25 15:45:30 2016 -0700

    x86/boot: Refuse to build with data relocations

    The compressed kernel is built with -fPIC/-fPIE so that it can run in any
    location a bootloader happens to put it. However, since ELF relocation
    processing is not happening (and all the relocation information has
    already been stripped at link time), none of the code can use data
    relocations (e.g. static assignments of pointers). This is already noted
    in a warning comment at the top of misc.c, but this adds an explicit
    check for the condition during the linking stage to block any such bugs
    from appearing.

    If this was in place with the earlier bug in pagetable.c, the build
    would fail like this:

      ...
        CC      arch/x86/boot/compressed/pagetable.o
        DATAREL arch/x86/boot/compressed/vmlinux
      error: arch/x86/boot/compressed/pagetable.o has data relocations!
      make[2]: *** [arch/x86/boot/compressed/vmlinux] Error 1
      ...

    A clean build shows:

      ...
        CC      arch/x86/boot/compressed/pagetable.o
        DATAREL arch/x86/boot/compressed/vmlinux
        LD      arch/x86/boot/compressed/vmlinux
      ...

    Suggested-by: Ingo Molnar <mingo@kernel.org>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Andrey Ryabinin <aryabinin@virtuozzo.com>
    Cc: Andy Lutomirski <luto@kernel.org>
    Cc: Baoquan He <bhe@redhat.com>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Brian Gerst <brgerst@gmail.com>
    Cc: Denys Vlasenko <dvlasenk@redhat.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Cc: H. Peter Anvin <hpa@zytor.com>
    Cc: H.J. Lu <hjl.tools@gmail.com>
    Cc: Josh Poimboeuf <jpoimboe@redhat.com>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Yinghai Lu <yinghai@kernel.org>
    Link: http://lkml.kernel.org/r/1464216334-17200-2-git-send-email-keescook@chromium.org
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>