[net] sctp: fix checkpatch errors with open brace '{' and trailing statements
Message-id: <963ffc6dcbe763ac662bac179f95546b38cca632.1465943899.git.mleitner@redhat.com>
Patchwork-id: 153223
O-Subject: [RHEL7.3 PATCH net 19/55] sctp: fix checkpatch errors with open brace '{' and trailing statements
Bugzilla: 1337639
RH-Acked-by: Xin Long <lxin@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1337639
Backport of upstream commit: 8d72651d86e9c702d37dd9ef9f084ce027af90a7

 commit 8d72651d86e9c702d37dd9ef9f084ce027af90a7
 Author: wangweidong <wangweidong1@huawei.com>
 Date:   Mon Dec 23 12:16:53 2013 +0800

    sctp: fix checkpatch errors with open brace '{' and trailing statements

    fix checkpatch errors below:
    ERROR: that open brace { should be on the previous line
    ERROR: open brace '{' following function declarations go on the next line
    ERROR: trailing statements should be on next line

    Signed-off-by: Wang Weidong <wangweidong1@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>