[mtd] omap2: allow bulding as a module
Message-id: <1381413926-15908-422-git-send-email-vfalico@redhat.com>
Patchwork-id: 69002
O-Subject: [RHEL7 PATCH 421/820] mtd: omap2: allow bulding as a module
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 930d800bded771b26d9944c47810829130ff7c8c
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=930d800bded771b26d9944c47810829130ff7c8c
Stable: ddb2a2d9e0b2c87696d1a81b57edf545e201c143
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=ddb2a2d9e0b2c87696d1a81b57edf545e201c143

Description
----------------------------
Backport from linux-3.10.y stable.

From: Arnd Bergmann <arnd@arndb.de>
Subject: mtd: omap2: allow bulding as a module

commit 930d800bded771b26d9944c47810829130ff7c8c upstream.

The omap2 nand device driver calls into the the elm code, which can
be a loadable module, and in that case it cannot be built-in itself.
I can see no reason why the omap2 driver cannot also be a module,
so let's make the option "tristate" in Kconfig to fix this allmodconfig
build error:

ERROR: "elm_config" [drivers/mtd/nand/omap2.ko] undefined!
ERROR: "elm_decode_bch_error_page" [drivers/mtd/nand/omap2.ko] undefined!

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Tony Lindgren <tony@atomide.com>
Cc: David Woodhouse <dwmw2@infradead.org>
Cc: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
Cc: Afzal Mohammed <afzal@ti.com>
Cc: Russell King <rmk+kernel@arm.linux.org.uk>
Cc: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit ddb2a2d9e0b2c87696d1a81b57edf545e201c143)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>