[scsi] lpfc: avoid an unused function warning
Message-id: <1507670879-17640-146-git-send-email-dkennedy@redhat.com>
Patchwork-id: 191173
O-Subject: [RHEL7.5 e-stor PATCH 145/170] scsi: lpfc: avoid an unused function warning
Bugzilla: 1385844 1461977 1387768
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

The only reference to lpfc_nvmet_replenish_context() is inside of an
disabled:

drivers/scsi/lpfc/lpfc_nvmet.c:1457:1: error: 'lpfc_nvmet_replenish_context' defined but not used [-Werror=unused-function]

This replaces the preprocessor conditional with a C condition, so the
compiler can see that the function is intentionally unused.

Fixes: 9a38e4f1c82f ("scsi: lpfc: Fix MRQ > 1 context list handling")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 7362617319fd2273c7fe5a5f8f8b5fb059a85015)
Signed-off-by: Rafael Aquini <aquini@redhat.com>