[net] bridge: move maybe_deliver_addr() inside #ifdef
Message-id: <20171013200423.15136-12-ivecera@redhat.com>
Patchwork-id: 193293
O-Subject: [RHEL7.5 net PATCH 11/57] bridge: move maybe_deliver_addr() inside #ifdef
Bugzilla: 1500896
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1500896

Upstream commit(s):
commit 5b9d6b154a622d0481123c1b149afdf377264268
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 25 23:29:33 2017 +0100

    bridge: move maybe_deliver_addr() inside #ifdef

    The only caller of this new function is inside of an #ifdef checking
    for CONFIG_BRIDGE_IGMP_SNOOPING, so we should move the implementation
    there too, in order to avoid this harmless warning:

    net/bridge/br_forward.c:177:13: error: 'maybe_deliver_addr' defined but not used [-Werror=unused-function]

    Fixes: 6db6f0eae605 ("bridge: multicast to unicast")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Stephen Hemminger <stephen@networkplumber.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>