[perf] kmem: Consistently use PRIu64 for printing u64 values
Message-id: <1431774138-14330-318-git-send-email-jolsa@redhat.com>
Patchwork-id: 112538
O-Subject: [PATCH RHEL7.2 BZ1222189 317/327] perf kmem: Consistently use PRIu64 for printing u64 values
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 6145c259cd454bcb7a1288f7bbb7b4fbc18175dd
Author: Will Deacon <will.deacon@arm.com>
Date: Thu Apr 23 14:40:37 2015 +0100

description
===========
Building the perf tool for 32-bit ARM results in the following build
error due to a combination of an incorrect conversion specifier and
compiling with -Werror:

  builtin-kmem.c: In function print_page_summary:
  builtin-kmem.c:644:9: error: format %lu expects argument of type long unsigned int, but argument 3 has type u64 [-Werror=format=]
           nr_alloc_freed, (total_alloc_freed_bytes) / 1024);
           ^
  builtin-kmem.c:647:9: error: format %lu expects argument of type long unsigned int, but argument 3 has type u64 [-Werror=format=]
           (total_page_alloc_bytes - total_alloc_freed_bytes) / 1024);
           ^
  cc1: all warnings being treated as errors

This patch fixes the problem by consistently using PRIu64 for printing
out u64 values.

Signed-off-by: Rafael Aquini <aquini@redhat.com>