[nvme] nvme-loop: add configfs dependency
Message-id: <1489790877-16541-36-git-send-email-dmilburn@redhat.com>
Patchwork-id: 174669
O-Subject: [RHEL7.4 PATCH 035/158] nvme-loop: add configfs dependency
Bugzilla: 1384526 1389755 1366753 1374291 1383834
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

CONFIG_NVME_TARGET has a correct CONFIG_CONFIGFS_FS dependency, but the
newly added NVME_TARGET_LOOP is missing this, resulting in a link
failure:

drivers/nvme/built-in.o: In function `nvmet_init_configfs':
loop.c:(.init.text+0x2a0): undefined reference to `config_group_init'
loop.c:(.init.text+0x2c0): undefined reference to `config_group_init_type_name'
loop.c:(.init.text+0x318): undefined reference to `configfs_register_subsystem'
drivers/nvme/built-in.o: In function `nvmet_exit_configfs':
loop.c:(.exit.text+0x9c): undefined reference to `configfs_unregister_subsystem'

This adds the same dependency here.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 3a85a5de29ea ("nvme-loop: add a NVMe loopback host driver")
Signed-off-by: Jens Axboe <axboe@fb.com>
(cherry picked from commit 1fb470408497382a0cf5311d9fa362202b537ebf)
Signed-off-by: David Milburn <dmilburn@redhat.com>

BZ 1383834
BZ 1374291
BZ 1366753

Signed-off-by: Rafael Aquini <aquini@redhat.com>