[net] lwtunnel: Fix the sparse warnings in fib_encap_match
Message-id: <1463509420-12020-101-git-send-email-lrichard@redhat.com>
Patchwork-id: 145421
O-Subject: [RHEL7.3 net PATCH v2 100/232] lwtunnel: Fix the sparse warnings in fib_encap_match
Bugzilla: 1283886
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1283886
Upstream Status: linus commit 824e7383e92815cb591793c74cc836aa5165f7f8

commit 824e7383e92815cb591793c74cc836aa5165f7f8
Author: Ying Xue <ying.xue@windriver.com>
Date:   Wed Aug 19 15:46:17 2015 +0800

    lwtunnel: Fix the sparse warnings in fib_encap_match

    When CONFIG_LWTUNNEL config is not enabled, the lwtstate_free() is not
    declared in lwtunnel.h at all. However, even in this case, the function
    is still referenced in fib_semantics.c so that there appears the
    following sparse warnings:

    net/ipv4/fib_semantics.c:553:17: error: undefined identifier 'lwtstate_free'
      CC      net/ipv4/fib_semantics.o
      net/ipv4/fib_semantics.c: In function 'fib_encap_match':
      net/ipv4/fib_semantics.c:553:3: error: implicit declaration of function 'lwtstate_free' [-Werror=implicit-function-declaration]
      cc1: some warnings being treated as errors
      make[1]: *** [net/ipv4/fib_semantics.o] Error 1
      make: *** [net/ipv4/fib_semantics.o] Error 2

    To eliminate the error, we define an empty function for lwtstate_free()
    in lwtunnel.h when CONFIG_LWTUNNEL is disabled.

    Fixes: df383e6240ef ("lwtunnel: fix memory leak")
    Cc: Jiri Benc <jbenc@redhat.com>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Ying Xue <ying.xue@windriver.com>
    Acked-by: Jiri Benc <jbenc@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Lance Richardson <lrichard@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>