[unisys] Fix broken build when ARCH=um
Message-id: <1437612954-15087-5-git-send-email-earfvids@redhat.com>
Patchwork-id: 122340
O-Subject: [RHEL7.2 PATCH BZ 1245362 04/11] staging: unisys: Fix broken build when ARCH=um
Bugzilla: 1245362
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1245362

commit 2164be191e3d627dd7744b7224daf9ad9495c9af
Author: Ken Cox <jkc@redhat.com>
Date:   Thu Jul 9 13:28:56 2015 -0400

    staging: unisys: Fix broken build when ARCH=um

    When building with ARCH=um you get the following error:

    arch/x86/include/asm/cpufeature.h:252:42: error: 'REQUIRED_MASK0'
    	undeclared

    The Unisys drivers should not be compiled for UML, so this patch addresses
    that by adding a dependency to kconfig for !UML.

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Tested-by: Ken Cox <jkc@redhat.com>
    Signed-off-by: Ken Cox <jkc@redhat.com>
    Signed-off-by: Benjamin Romer <benjamin.romer@unisys.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Cc: Erik Arfvidson <earfvids@redhat.com>
Cc: Ken Cox <jkc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>