[net] ipv4: udp_offload: Handle static checker complaints
Message-id: <156279bf93146510c4dba1649d219f9a0c6a665e.1392219754.git.tgraf@redhat.com>
Patchwork-id: 76750
O-Subject: [RHEL7.0 PATCH net 34/37] net/udp_offload: Handle static checker complaints
Bugzilla: 1051111
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Mark Langsdorf <mlangsdo@redhat.com>

Upstream commit:
commit a1d0cd8ed5d315a1f2e9dec54920b73b9b30147b
Author: Shlomo Pongratz <shlomop@mellanox.com>
Date:   Wed Jan 22 15:23:29 2014 +0200

    net/udp_offload: Handle static checker complaints

    Fixed few issues around using __rcu prefix and rcu_assign_pointer, also
    fixed a warning print to use ntohs(port) and not htons(port).

    net/ipv4/udp_offload.c:112:9: error: incompatible types in comparison expression (different address spaces)
    net/ipv4/udp_offload.c:113:9: error: incompatible types in comparison expression (different address spaces)
    net/ipv4/udp_offload.c:176:19: error: incompatible types in comparison expression (different address spaces)

    Signed-off-by: Shlomo Pongratz <shlomop@mellanox.com>
    Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Thomas Graf <tgraf@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>