[tools] perf tests record: No need to test an array against NULL
Message-id: <20170807084247.7531-53-jolsa@redhat.com>
Patchwork-id: 181986
O-Subject: [PATCH RHEL7.5 52/94] perf tests record: No need to test an array against NULL
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 9ef6839bcce7ca944c1ace4a7247cf13ca92a28f
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Feb 13 17:04:05 2017 -0300

description
===========
It will always evaluate to 'true', as clang warns:

    CC       /tmp/build/perf/tests/perf-record.o
    CC       /tmp/build/perf/tests/evsel-roundtrip-name.o
  tests/perf-record.c:69:24: error: comparison of array 'argv' equal to a null pointer is always false [-Werror,-Wtautological-pointer-compare]
          if (evlist == NULL || argv == NULL) {
                                ^~~~    ~~~~
  1 error generated.

Signed-off-by: Rafael Aquini <aquini@redhat.com>