[scsi] lpfc: fix "integer constant too large" error on 32bit archs
Message-id: <1507670879-17640-144-git-send-email-dkennedy@redhat.com>
Patchwork-id: 191148
O-Subject: [RHEL7.5 e-stor PATCH 143/170] scsi: lpfc: fix "integer constant too large" error on 32bit archs
Bugzilla: 1385844 1461977 1387768
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Maurizio Lombardi <mlombard@redhat.com>

cc1: warnings being treated as errors
drivers/scsi/lpfc/lpfc_init.c: In function 'lpfc_get_wwpn':
drivers/scsi/lpfc/lpfc_init.c:3253: error: integer constant is too large for 'long' type

Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>
Signed-off-by: James Smart <james.smart@broadcom.com>
Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 286871a6667c3d4d27a4cf1ee519e629527dfc9d)
Signed-off-by: Rafael Aquini <aquini@redhat.com>