[infiniband] rdma/hfi1: fix 0-day syntax error
Message-id: <20160614194050.23159.64740.stgit@dhcp187-101.khw.lab.eng.bos.redhat.com>
Patchwork-id: 152900
O-Subject: [RHEL-7.3 BZs 1273170 1272062 PATCH 279/431] staging/rdma/hfi1: fix 0-day syntax error
Bugzilla: 1272062 1273170
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Mike Marciniszyn <mike.marciniszyn@intel.com>

Bugzilla: 1273170
Upstream: (imported from commit 6b5c5213e57453c228f7695d5d889aa4c84272c3)

Setting CONFIG_HFI1_DEBUG_SDMA_ORDER causes a syntax error:
sdma.c: In function complete_tx:
sdma.c:370: error: txp undeclared (first use in
this function)
sdma.c:370: error: (Each undeclared identifier is reported only once
sdma.c:370: error: for each function it appears in.)

Adjust code under ifdef to reference the tx properly.

Reviewed-by: Dennis Dalessandro <dennis.dalessandro@intel.com>
Signed-off-by: Mike Marciniszyn <mike.marciniszyn@intel.com>
Signed-off-by: Doug Ledford <dledford@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>