[sound] alsa: of: Explicitly linux/types.h in of_graph.h
Message-id: <1507829954160572-472-patchset-jkysela@redhat.com>
Patchwork-id: 192381
O-Subject: [RHEL 7.5 PATCH v2 0471/1088] ALSA: of: Explicitly include linux/types.h in of_graph.h
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

In current -next of_graph.h fails to build due to it relying on
linux/types.h without explicitly including it:

../include/linux/of_graph.h:43:71: error: unknown type name 'u32'

caused by bfe446e37c4e (of: Add of_graph_get_port_by_id function).  Add
an explicit inclusion to fix this.

Signed-off-by: Mark Brown <broonie@kernel.org>
Acked-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Acked-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Rob Herring <robh@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 01218bf14ee60d4a2d6c667ebdbba3ae9a7a1d66)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>