[tools] perf session: Fix DEBUG=1 build with clang
Message-id: <20170807084247.7531-77-jolsa@redhat.com>
Patchwork-id: 182006
O-Subject: [PATCH RHEL7.5 76/94] perf session: Fix DEBUG=1 build with clang
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 8074bf51fe5af68dcbc12bd7fa72dc4be8f41dde
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Feb 17 12:27:26 2017 -0300

description
===========
The struct branch_stack->branch_stack.cycles field is a u64 :16
bitfield, and this somehow confuses clang 4.0 when checking the
arguments of a printf format, so cast the :16 to unsigned short to help
it.

Silences this:

  util/session.c:935:4: error: format specifies type 'unsigned short' but the argument has type 'u64' (aka 'unsigned long') [-Werror,-Wformat]
                          e->flags.cycles,
                          ^~~~~~~~~~~~~~~
  1 error generated.

Signed-off-by: Rafael Aquini <aquini@redhat.com>