[netdrv] kalmia: avoid potential uninitialized variable use
Message-id: <1489393527-9024-316-git-send-email-torez@redhat.com>
Patchwork-id: 174007
O-Subject: [RHEL7.4 PATCH BZ1383823 315/467] kalmia: avoid potential uninitialized variable use
Bugzilla: 1383823
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1383823
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12744255
Testing: on local desktop and Dell Precision 5510 laptop

commit e30520c2b075fae3977d482a31b54b0256160a57
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 24 17:54:18 2016 +0200

    kalmia: avoid potential uninitialized variable use

    The kalmia_send_init_packet() returns zero or a negative return
    code, but gcc has no way of knowing that there cannot be a
    positive return code, so it determines that copying the ethernet
    address at the end of kalmia_bind() will access uninitialized
    data:

    drivers/net/usb/kalmia.c: In function kalmia_bind:
    arch/x86/include/asm/string_32.h:78:22: error: *((void *)&ethernet_addr+4) may be used uninitialized in this function [-Werror=maybe-uninitialized]
       *((short *)to + 2) = *((short *)from + 2);
                          ^
    drivers/net/usb/kalmia.c:138:5: note: *((void *)&ethernet_addr+4) was declared here

    This warning is harmless, but for consistency, we should make
    the check for the return code match what the driver does everywhere
    else and just progate it, which then gets rid of the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>