[mmc] MMC_OMAP_HS should depend on HAS_DMA
Message-id: <1463503488-149391-325-git-send-email-dzickus@redhat.com>
Patchwork-id: 144869
O-Subject: [RHEL7 PATCH 324/725] mmc: MMC_OMAP_HS should depend on HAS_DMA
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit c00c594d8882c64258150dbbf5ff1c328400c65a
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed Jul 9 20:52:40 2014 +0200

    mmc: MMC_OMAP_HS should depend on HAS_DMA

    If NO_DMA=y:

        drivers/built-in.o: In function `omap_hsmmc_pre_dma_transfer':
        omap_hsmmc.c:(.text+0x5a0928): undefined reference to `dma_map_sg'
        drivers/built-in.o: In function `omap_hsmmc_dma_cleanup':
        omap_hsmmc.c:(.text+0x5a0e8e): undefined reference to `dma_unmap_sg'
        drivers/built-in.o: In function `omap_hsmmc_dma_callback':
        omap_hsmmc.c:(.text+0x5a1f58): undefined reference to `dma_unmap_sg'
        drivers/built-in.o: In function `omap_hsmmc_post_req':
        omap_hsmmc.c:(.text+0x5a2082): undefined reference to `dma_unmap_sg'

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>