[x86] i2c-designware: use div_u64 to fix link
Message-id: <1467295392-9015-83-git-send-email-prarit@redhat.com>
Patchwork-id: 154406
O-Subject: [RHEL7.3 PATCH BZ 1331018 082/104] i2c-designware: use div_u64 to fix link
Bugzilla: 1331018
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1331018

commit 97191d734f6ac028e5e6dcd574378c1544a16c0b
Author: Vincent Stehl <vincent.stehle@freescale.com>
Date:   Tue Jul 2 11:46:54 2013 +0200

    i2c-designware: use div_u64 to fix link

    This fixes the following link error:

      drivers/built-in.o: In function `dw_i2c_probe':
      of_iommu.c:(.text+0x18c8f0): undefined reference to `__aeabi_uldivmod'
      make: *** [vmlinux] Error 1

    Signed-off-by: Vincent Stehl <vincent.stehle@freescale.com>
    Tested-by: Kevin Hilman <khilman@linaro.org>
    Reviewed-by: Christian Ruppert <christian.ruppert@abilis.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Wolfram Sang <wsa@the-dreams.de>

Signed-off-by: Rafael Aquini <aquini@redhat.com>