[fs] xfs: call roundup_64() to calculate the min_logblks
Message-id: <1379494347-28456-88-git-send-email-dchinner@redhat.com>
Patchwork-id: 67363
O-Subject: [RHEL 7.0 PATCH 087/155] xfs: call roundup_64() to calculate the min_logblks
Bugzilla: 1001861
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jie Liu <jeff.liu@oracle.com>

RH BZ: 1001861
Upstream commit 2c2bcc0735f4ab052559b539f3fcab4087187232
--

From: Jie Liu <jeff.liu@oracle.com>

Replace roundup() with roundup_64() as we calculate min_logblks
with 64-bit divisions.  Hence, call roundup() will cause the
following error while compiling a 32-bit kernel:

fs/built-in.o: In function `xfs_log_calc_minimum_size':
fs/xfs/xfs_log_rlimit.c:140: undefined reference to `__udivdi3'

Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Cc: Dave Chinner <dchinner@redhat.com>
Signed-off-by: Jie Liu <jeff.liu@oracle.com>
Reviewed-by: Dave Chinner <dchinner@redhat.com>
Signed-off-by: Ben Myers <bpm@sgi.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>