[redhat] makefile: Add user option to fail when building dirty tree
Message-id: <1493211777-24223-1-git-send-email-prarit@redhat.com>
Patchwork-id: 177154
O-Subject: [RHEL7.4 PATCH INTERNAL v3] redhat/Makefile: Add user option to fail when building dirty tree
Bugzilla:
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Jon Masters <jcm@redhat.com>

Bugzilla: http://bugzilla.redhat.com/faildirtytree

When building a dirty git tree, the build currently warns and continues
with a three line message indicating that the tree is dirty.  This is
almost always what we don't want to happen and it is annoying when you
forget to commit your changes to the tree you are trying to build.

Modify the code so that a user can execute

git config --add [--global] rhel.faildirtytree true

to fail a 'rh-*' make command when the tree is dirty.

With a dirty tree, 'make rh-srpm' will

fail with rhel.faildirtytree true
pass with rhel.faildirtytree undefined
pass with rhel.faildirtytree false

With a clean tree, 'make rh-srpm' will pass in all cases.

Also ... add a period to the existing warning.

v2: add better description, add rh-git-dirtytree target so the build failure
occurs immediately:

[root@intel-purley-02 rhel7]# make rh-srpm
make -C redhat rh-srpm
BUILDID is ".test". Update '/home/rhel7/localversion' to change.
TEST is "None". Update '/home/rhel7/tests' to change.
make[1]: Entering directory `/home/rhel7/redhat'
Gathering new log entries since kernel-3.10.0-656.el7
ERROR: There are uncommitted changes in your tree or the changes are not
in sync with linux-kernel-test.patch. Either commit the changes or run
make rh-test-patch.
make[1]: *** [rh-git-dirtytree] Error 1
make[1]: Leaving directory `/home/rhel7/redhat'
make: *** [rh-srpm] Error 2
[root@intel-purley-02 rhel7]#
[root@intel-purley-02 rhel7]# make rh-help
<snip>
  rh-git-dirtytree  - Test to see if git tree is dirty.  Will fail if
                      git config value rhel.faildirtytree is true.

v3: cleanup superflous touch, and make "rh-git-dirtytree" consistent

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Cc: Rafael Aquini <aquini@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Frantisek Hrbata <fhrbata@redhat.com>
Cc: dzickus@redhat.com
Cc: darcari@redhat.com

Cc: Rafael Aquini <aquini@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Frantisek Hrbata <fhrbata@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>