[tools] perf tests: Synthesize struct instead of using field after variable sized type
Message-id: <20170807084247.7531-60-jolsa@redhat.com>
Patchwork-id: 181992
O-Subject: [PATCH RHEL7.5 59/94] perf tests: Synthesize struct instead of using field after variable sized type
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 423d856a4d6ab26a50309fd051f2bdf0e5d00fd6
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 15:04:48 2017 -0300

description
===========
End result is the same, its an ABI, so the struct won't change, avoid
using a GNU extension, so that we can catch other cases that may be bugs.

Caught when building with clang:

  tests/parse-no-sample-id-all.c:53:20: error: field 'attr' with variable sized type 'struct attr_event' not at the end of a struct or class is a GNU extension
        [-Werror,-Wgnu-variable-sized-type-not-at-end]
          struct attr_event attr;
                            ^
  1 error generated.

Testing it:

  # perf test sample_id
  24: Parse with no sample_id_all bit set        : Ok
  #

Signed-off-by: Rafael Aquini <aquini@redhat.com>