[include] sparse: fix misplaced __pmem definition
Message-id: <1464212242-20208-108-git-send-email-sandeen@redhat.com>
Patchwork-id: 147605
O-Subject: [RHEL7 PATCH 107/126] sparse: fix misplaced __pmem definition
Bugzilla: 1028649 1269626 1271953 1274043
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

From: Dan Williams <dan.j.williams@intel.com>

BZ: 1269626 1028649 1271953 1274043

commit 31f02455455d405320e2f749696bef4e02903b35
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Tue Jun 30 12:07:17 2015 -0400

    sparse: fix misplaced __pmem definition

    Move the definition of __pmem outside of CONFIG_SPARSE_RCU_POINTER to fix:

    drivers/nvdimm/pmem.c:198:17: sparse: too many arguments for function __builtin_expect
    drivers/nvdimm/pmem.c:36:33: sparse: expected ; at end of declaration
    drivers/nvdimm/pmem.c:48:21: sparse: void declaration

    ...due to __pmem failing to be defined in some configurations when
    CONFIG_SPARSE_RCU_POINTER=y.

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>