[usb] otg_whitelist: remove whitespace
Message-id: <1462578743-3088-119-git-send-email-torez@redhat.com>
Patchwork-id: 143344
O-Subject: [RHEL7 PATCH BZ1303955 118/364] usb: otg_whitelist: remove whitespace
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 31b92d81e5d4574eb3d038642c7ba6ec66ea7db1
Author: Kris Borer <kborer@gmail.com>
Date:   Sun Aug 9 21:48:18 2015 -0400

    usb: otg_whitelist: remove whitespace

    Fix one occurrence of the checkpatch error:

    ERROR: space prohibited before open square bracket '['

    Signed-off-by: Kris Borer <kborer@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>