[tools] perf bench: Use named initializers in the trailer too
Message-id: <1456127829-13546-198-git-send-email-jolsa@redhat.com>
Patchwork-id: 135478
O-Subject: [PATCH BZ1308570 197/260] perf bench: Use named initializers in the trailer too
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit a4c6a3e8bbb675a601f529881c51ff226f83c3f1
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Oct 19 18:17:25 2015 -0300

description
===========
To avoid this splat with gcc 4.4.7:

  cc1: warnings being treated as errors
  bench/mem-functions.c:273: error: missing initializer
  bench/mem-functions.c:273: error: (near initialization for memcpy_functions[4].desc)
  bench/mem-functions.c:366: error: missing initializer
  bench/mem-functions.c:366: error: (near initialization for memset_functions[4].desc)

Signed-off-by: Rafael Aquini <aquini@redhat.com>