[usb] add HAS_IOMEM dependency to USB_EHCI_HCD
Message-id: <1465525749-9195-91-git-send-email-torez@redhat.com>
Patchwork-id: 150029
O-Subject: [RHEL7 BZ1332712 v2 090/196] usb: add HAS_IOMEM dependency to USB_EHCI_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit aaa98db7181f99784c900618f9c1c8b0bcab43a0
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:45 2016 +0100

    usb: add HAS_IOMEM dependency to USB_EHCI_HCD

    drivers/built-in.o: In function `ehci_platform_probe':
    /home/vegard/linux/drivers/usb/host/ehci-platform.c:282: undefined reference to `devm_ioremap_resource'
    drivers/built-in.o: In function `oxu_drv_probe':
    /home/vegard/linux/drivers/usb/host/oxu210hp-hcd.c:3821: undefined reference to `devm_ioremap_resource'
    drivers/built-in.o: In function `isp1362_probe':
    /home/vegard/linux/drivers/usb/host/isp1362-hcd.c:2668: undefined reference to `devm_ioremap_resource'

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>