[kernel] audit: fix type of sessionid in audit_set_loginuid()
Message-id: <ae75d8dd002bdbfafc7268ae4c911e1822ba2f59.1389385575.git.rgb@redhat.com>
Patchwork-id: 74006
O-Subject: [RHEL7 PATCH 7/9] audit: fix type of sessionid in audit_set_loginuid()
Bugzilla: 1045670
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Eric Paris <eparis@redhat.com>

From: Eric Paris <eparis@redhat.com>

sfr pointed out that with CONFIG_UIDGID_STRICT_TYPE_CHECKS set the audit
tree would not build.  This is because the oldsessionid in
audit_set_loginuid() was accidentally being declared as a kuid_t.  This
patch fixes that declaration mistake.

Example of problem:
kernel/auditsc.c: In function 'audit_set_loginuid':
kernel/auditsc.c:2003:15: error: incompatible types when assigning to
type 'kuid_t' from type 'int'
  oldsessionid = audit_get_sessionid(current);

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Eric Paris <eparis@redhat.com>
Signed-off-by: Richard Guy Briggs <rgb@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>