[usb] move assignment out of if condition
Message-id: <1462578743-3088-92-git-send-email-torez@redhat.com>
Patchwork-id: 143319
O-Subject: [RHEL7 PATCH BZ1303955 091/364] usb: move assignment out of if condition
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 0faaad461547e2412e9b519cd757a99b3ebc1302
Author: Kris Borer <kborer@gmail.com>
Date:   Tue Jul 14 09:28:30 2015 -0400

    usb: move assignment out of if condition

    Fix four occurrences of checkpatch.pl error:

    ERROR: do not use assignment in if condition

    The semantic patch that makes this change is:

    // <smpl>
    @@
    identifier i;
    expression E;
    statement S;
    constant c;
    binary operator b;
    @@

    + i = E;
      if (
    - (i = E)
    + i
      b
      c ) S

    @@
    identifier i, i2;
    expression E1, E2;
    constant c;
    @@

    + if( E1->i ) {
    +  	i2 = E2;
    + 	if (i2 < c) {
    - if( E1->i && (i2 = E2) < c ) {
      ...
    - }
    + 	}
    + }
    // </smpl>

    Signed-off-by: Kris Borer <kborer@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>