[tools] tools lib traceevent: Add correct header for ipv6 definitions
Message-id: <1477399629-8377-243-git-send-email-jolsa@redhat.com>
Patchwork-id: 159812
O-Subject: [PATCH RHEL7.4 BZ1387909 242/322] tools lib traceevent: Add correct header for ipv6 definitions
Bugzilla: 1387909
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1387909
https://bugzilla.redhat.com/show_bug.cgi?id=1387909

upstream
========
commit ca575ad2093d7ca94238146c3c9267c61d2523bc
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Jul 14 11:23:25 2016 -0300

description
===========
We need to include netinet/in.h to get the in6_addr struct definition, needed to
build it on the Android NDK:

  In file included from event-parse.c:36:0:
  /home/acme/android/android-ndk-r12/platforms/android-24/arch-arm/usr/include/netinet/ip6.h:82:18: error: field 'ip6_src' has incomplete type
    struct in6_addr ip6_src; /* source address */

And it is the canonical way of getting IPv6 definitions, as described,
for instance, in Linux's 'man ipv6'

Doing that uncovers another problem: this source file uses PRIu64 but
doesn't include it, depending on it being included by chance via the now
replaced header (netinet/ip6.h), fix it.

Signed-off-by: Rafael Aquini <aquini@redhat.com>