[x86] intel_rdt: Select KERNFS when enabling INTEL_RDT_A
Message-id: <20170925122043.19483-3-jolsa@redhat.com>
Patchwork-id: 186400
O-Subject: [PATCH RHEL7.5 02/42] x86/intel_rdt: Select KERNFS when enabling INTEL_RDT_A
Bugzilla: 1457533
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1457533
https://bugzilla.redhat.com/show_bug.cgi?id=1457533

upstream
========
commit 59fe5a77d473f3519dbee8ef5e77c69897a838f9
Author: Thomas Gleixner <tglx@linutronix.de>
Date: Tue Nov 15 15:17:12 2016 +0100

description
===========
arch/x86/kernel/cpu/intel_rdt_rdtgroup.c: In function 'rdtgroup_kn_lock_live':
arch/x86/kernel/cpu/intel_rdt_rdtgroup.c:658:2: error: implicit declaration of
function 'kernfs_break_active_protection' [-Werror=implicit-function-declaration]

Signed-off-by: Rafael Aquini <aquini@redhat.com>