[nvdimm] libnvdimm, pmem: fix ia64 build, use PHYS_PFN
Message-id: <20160805000156.29576-21-jmoyer@redhat.com>
Patchwork-id: 156530
O-Subject: [RHEL7 PATCH 20/82] libnvdimm, pmem: fix ia64 build, use PHYS_PFN
Bugzilla: 1271957 1278621 1343736 1349587 1349702 1353614 1355792
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

From: Dan Williams <dan.j.williams@intel.com>

BZ: 1343736, 1349587, 1349702, 1353614, 1355792, 1271957, 1278621

commit 45f68802f2542a6ad1550dab9c07004de6e0df40
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Sun Mar 6 08:04:12 2016 -0800

    libnvdimm, pmem: fix ia64 build, use PHYS_PFN

       drivers/nvdimm/pmem.c: In function 'nvdimm_namespace_attach_pfn':
       drivers/nvdimm/pmem.c:367:3: error: implicit declaration of function
            '__phys_to_pfn' [-Werror=implicit-function-declaration]
       .base_pfn = __phys_to_pfn(nsio->res.start),

    ia64 does not provide __phys_to_pfn(), just use the PHYS_PFN() alias.

    Cc: Guenter Roeck <linux@roeck-us.net>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>