[mmc] dw_mmc: add missing MFD_SYSCON dependency for SOCFPGA
Message-id: <1463503488-149391-147-git-send-email-dzickus@redhat.com>
Patchwork-id: 145013
O-Subject: [RHEL7 PATCH 146/725] mmc: dw_mmc: add missing MFD_SYSCON dependency for SOCFPGA
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit e33c2025c0c2f8a20054c3e031877ff595d1c31f
Author: Jingoo Han <jg1.han@samsung.com>
Date:   Thu Aug 1 09:28:13 2013 +0900

    mmc: dw_mmc: add missing MFD_SYSCON dependency for SOCFPGA

    Added missing MFD_SYSCON dependency for SOCFPGA in order to fix
    the following link error.

    drivers/mmc/host/dw_mmc-socfpga.c:49: undefined reference to `syscon_regmap_lookup_by_compatible'

    Signed-off-by: Jingoo Han <jg1.han@samsung.com>
    Acked-by: Jaehoon Chung <jh80.chung@samsung.com>
    Acked-by: Seungwon Jeon <tgih.jun@samsung.com>
    Signed-off-by: Chris Ball <cjb@laptop.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>