[include] gpiolib: provide a declaration of seq_file in gpio/driver.h
Message-id: <1463503488-149391-67-git-send-email-dzickus@redhat.com>
Patchwork-id: 144623
O-Subject: [RHEL7 PATCH 066/725] gpiolib: provide a declaration of seq_file in gpio/driver.h
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit f3ed0b66482fa2a0403280174a998487e9054867
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Tue Oct 29 01:06:23 2013 +1100

    gpiolib: provide a declaration of seq_file in gpio/driver.h

    Fixes this build error:

    In file included from include/asm-generic/gpio.h:13:0,
                     from include/linux/gpio.h:51,
                     from include/linux/of_gpio.h:20,
                     from arch/powerpc/sysdev/ppc4xx_gpio.c:29:
    include/linux/gpio/driver.h:85:14: error: 'struct seq_file' declared inside=
     parameter list [-Werror]
    include/linux/gpio/driver.h:85:14: error: its scope is only this definition=
     or declaration, which is probably not what you want [-Werror]

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>