[fs] btrfs: Use __u64 in exported linux/btrfs.h
Message-id: <20170403153759.31393-1-billodo@redhat.com>
Patchwork-id: 176004
O-Subject: [RHEL7.4 fs PATCH BZ 1437489] btrfs: Use __u64 in exported linux/btrfs.h.
Bugzilla: 1437489
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

Bugzilla: 1437489
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=12931637
Tested: Locally with fstests

Backport of the following upstream commit:

    commit 1691cf160048c0753036d0b3fad7f239234dab56
    Author: Vinson Lee <vlee@freedesktop.org>
    Date:   Sat May 28 07:04:38 2016 +0000

    btrfs: Use __u64 in exported linux/btrfs.h.

    This patch fixes this build error.

    /usr/include/linux/btrfs.h:121:3: error: unknown type name 'u64'
       u64 devid;
       ^~~

    Fixes: 6b526ed70cf1 ("btrfs: introduce device delete by devid")
    Signed-off-by: Vinson Lee <vlee@freedesktop.org>
    Signed-off-by: David Sterba <dsterba@suse.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>