[net] fix build break when DEBUG is enabled
Message-id: <1465919547-5818-2-git-send-email-ivecera@redhat.com>
Patchwork-id: 152040
O-Subject: [RHEL7.3 net PATCH 24/37] dev-core: fix build break when DEBUG is enabled
Bugzilla: 1268334
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Lance Richardson <lrichard@redhat.com>

BZ#1268334

Upstream commit(s):
commit 8ef2d6511f7eba89ef5fe41cc83008ae63368aa2
Author: Dmitry Kasatkin <d.kasatkin@samsung.com>
Date:   Tue Aug 27 17:47:34 2013 +0300

    dev-core: fix build break when DEBUG is enabled

    When DEBUG is defined, dev_dbg_ratelimited uses dynamic debug data
    structures even when CONFIG_DYNAMIC_DEBUG is not defined.
    It leads to build break.
    For example, when I try to use dev_dbg_ratelimited in USB code and
    CONFIG_USB_DEBUG is enabled, but CONFIG_DYNAMIC_DEBUG is not, I get:

      CC [M]  drivers/usb/host/xhci-ring.o
      drivers/usb/host/xhci-ring.c: In function 'xhci_queue_intr_tx':
      drivers/usb/host/xhci-ring.c:3059:3: error: implicit declaration of function 'DEFINE_DYNAMIC_DEBUG_METADATA' [-Werror=implicit-function-declaration]
      drivers/usb/host/xhci-ring.c:3059:3: error: 'descriptor' undeclared (first use in this function)
      drivers/usb/host/xhci-ring.c:3059:3: note: each undeclared identifier is reported only once for each function it appears in
      drivers/usb/host/xhci-ring.c:3059:3: error: implicit declaration of function '__dynamic_pr_debug' [-Werror=implicit-function-declaration]
      drivers/usb/host/xhci-ring.c: In function 'xhci_queue_isoc_tx_prepare':
      drivers/usb/host/xhci-ring.c:3847:3: error: 'descriptor' undeclared (first use in this function)
      cc1: some warnings being treated as errors
      make[2]: *** [drivers/usb/host/xhci-ring.o] Error 1
      make[1]: *** [drivers/usb/host] Error 2
      make: *** [drivers/usb/] Error 2

    This patch separates definition for CONFIG_DYNAMIC_DEBUG and DEBUG cases.

    [Note, Sarah moved the comment above the macro to avoid checkpatch
    warnings.]

    Signed-off-by: Dmitry Kasatkin <d.kasatkin@samsung.com>
    Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
    Acked-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>