[usb] add HAS_IOMEM dependency to USB_FOTG210_HCD
Message-id: <1465525749-9195-93-git-send-email-torez@redhat.com>
Patchwork-id: 150018
O-Subject: [RHEL7 BZ1332712 v2 092/196] usb: add HAS_IOMEM dependency to USB_FOTG210_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit eaa86229ff32a9aea80d7aa24289754e2eed8a76
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:47 2016 +0100

    usb: add HAS_IOMEM dependency to USB_FOTG210_HCD

    drivers/built-in.o: In function `fotg210_hcd_probe':
    /home/vegard/linux/drivers/usb/host/fotg210-hcd.c:5637: undefined reference to `devm_ioremap_resource'

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>