[usb] devio: fix spacing
Message-id: <1462578743-3088-113-git-send-email-torez@redhat.com>
Patchwork-id: 143348
O-Subject: [RHEL7 PATCH BZ1303955 112/364] usb: devio: fix spacing
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit f355e830a54ebe1601613d78a8d5b85eeafde358
Author: Kris Borer <kborer@gmail.com>
Date:   Fri Aug 7 07:22:44 2015 -0400

    usb: devio: fix spacing

    Fix two occurrences of the checkpatch.pl error:

    ERROR: space prohibited before that ',' (ctx:WxW)

    Fix one occurrence of the checkpatch error:

    ERROR: space required before the open parenthesis '('

    Signed-off-by: Kris Borer <kborer@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>