[net] netfilter: tee: select NF_DUP_IPV6 unconditionally
Message-id: <c8a0a3dca3ca89fe8321d0ccb0e69e1f27927542.1465290494.git.pabeni@redhat.com>
Patchwork-id: 149315
O-Subject: [RHEL7.3 net PATCH 124/165] netfilter: tee: select NF_DUP_IPV6 unconditionally
Bugzilla: 1331757
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1331757
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11141575
Tested: nftables test-suite and basic functional tests

Upstream commit:
commit 08a7f5d3f5c38ed745c3e99ee91975f20562d272
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Feb 5 10:20:21 2016 +0100

    netfilter: tee: select NF_DUP_IPV6 unconditionally

    The NETFILTER_XT_TARGET_TEE option selects NF_DUP_IPV6 whenever
    IP6_NF_IPTABLES is enabled, and it ensures that it cannot be
    builtin itself if NF_CONNTRACK is a loadable module, as that
    is a dependency for NF_DUP_IPV6.

    However, NF_DUP_IPV6 can be enabled even if IP6_NF_IPTABLES is
    turned off, and it only really depends on IPV6. With the current
    check in tee_tg6, we call nf_dup_ipv6() whenever NF_DUP_IPV6
    is enabled. This can however be a loadable module which is
    unreachable from a built-in xt_TEE:

    net/built-in.o: In function `tee_tg6':
    :(.text+0x67728): undefined reference to `nf_dup_ipv6'

    The bug was originally introduced in the split of the xt_TEE module
    into separate modules for ipv4 and ipv6, and two patches tried
    to fix it unsuccessfully afterwards.

    This is a revert of the the first incorrect attempt to fix it,
    going back to depending on IPV6 as the dependency, and we
    adapt the 'select' condition accordingly.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: bbde9fc1824a ("netfilter: factor out packet duplication for IPv4/IPv6")
    Fixes: 116984a316c3 ("netfilter: xt_TEE: use IS_ENABLED(CONFIG_NF_DUP_IPV6)")
    Fixes: 74ec4d55c4d2 ("netfilter: fix xt_TEE and xt_TPROXY dependencies")
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>