[lib] rhashtable: fix missing header
Message-id: <1455572815-13933-19-git-send-email-psutter@redhat.com>
Patchwork-id: 134655
O-Subject: [RHEL7.3 net v2 018/129] rhashtable: fix missing header
Bugzilla: 1238749
RH-Acked-by: Hannes Frederic Sowa <hannes@redhat.com>
RH-Acked-by: Robert S Peterson <rpeterso@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1238749
Upstream Status: commit 86b35b64ed7b6

commit 86b35b64ed7b6b38305dee67a0f2ddff2ca5455d
Author: Ying Xue <ying.xue@windriver.com>
Date:   Sun Jan 4 15:25:09 2015 +0800

    rhashtable: fix missing header

    Fixup below build error:

    include/linux/rhashtable.h: At top level:
    include/linux/rhashtable.h:118:34: error: field 'mutex' has incomplete type

    Signed-off-by: Ying Xue <ying.xue@windriver.com>
    Acked-by: Thomas Graf <tgraf@suug.ch>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Phil Sutter <psutter@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>