[drm] i915/gvt: exclude cfg space from failsafe mode
Message-id: <20170427191649.3361-95-rclark@redhat.com>
Patchwork-id: 177443
O-Subject: [RHEL7 drm 094/132] drm/i915/gvt: exclude cfg space from failsafe mode
Bugzilla: 1380115
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Lyude Paul <lyude@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1380115
Upstream: since next-20170404

commit f85726905745fb4f6e15c68e2ade9da5390f8d89

Author:     Changbin Du <changbin.du@intel.com>
AuthorDate: Thu Mar 30 11:32:05 2017 +0800
Commit:     Zhenyu Wang <zhenyuw@linux.intel.com>
CommitDate: Thu Mar 30 17:47:39 2017 +0800

    drm/i915/gvt: exclude cfg space from failsafe mode

    When test GVTg as below scenario:
      VM boot --> failsafe --> kill qemu --> VM boot.
    Qemu report error at the second boot:
      ERROR: PCI region size must be pow2 type=0x0, size=0x1fa1000

    Qemu need access PCI_ROM_ADDRESS reg to determine the size of expansion
    PCI rom. The mechanism just like the BAR reg (write-read) and we should
    return the size 0 since we have no rom. If we reject the write to
    PCI_ROM_ADDRESS, Qemu cannot get the correct size of rom.

    Essentially, GVTg failsafe mode should not break PCI function. So we
    exclude cfg space from failsafe mode. This can fix above issue.

    v2: add Fixes and Bugzilla link.

    Fixes: fd64be636708d ("drm/i915/gvt: introduced failsafe mode into vgpu")
    Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=100296
    Signed-off-by: Changbin Du <changbin.du@intel.com>
    Signed-off-by: Zhenyu Wang <zhenyuw@linux.intel.com>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>