[tools] perf lock: Subcommands should include common options
Message-id: <20170830160540.26618-58-jolsa@redhat.com>
Patchwork-id: 183472
O-Subject: [PATCH RHEL7.5 BZ1480522 057/248] perf lock: Subcommands should include common options
Bugzilla: 1480522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1480522
https://bugzilla.redhat.com/show_bug.cgi?id=1480522

upstream
========
commit 249eed53152167c64c6dc66fa269a1d8b415a7b4
Author: Changbin Du <changbin.du@intel.com>
Date: Fri Mar 17 13:53:42 2017 +0800

description
===========
When I use -i option for report subcommand, it doesn't accept it.  We
need add common options using OPT_PARENT macro.

perf lock report -i lock_perf.data
  Error: unknown switch `i'

  Usage: perf lock report [<options>]

    -f, --force           don't complain, do it
    -k, --key <acquired>  key for sorting ...

Signed-off-by: Rafael Aquini <aquini@redhat.com>