[tools] perf dwarf: Guard !x86_64 definitions under #ifdef else clause
Message-id: <1463569977-29479-320-git-send-email-jolsa@redhat.com>
Patchwork-id: 145885
O-Subject: [PATCH RHEL7.3 BZ1336447 319/324] perf dwarf: Guard !x86_64 definitions under #ifdef else clause
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit 62aa0e177d278462145a29c30d3c8501ae57e200
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Apr 8 12:04:29 2016 -0300

description
===========
To fix the build on Fedora Rawhide (gcc 6.0.0 20160311 (Red Hat 6.0.0-0.17):

    CC       /tmp/build/perf/arch/x86/util/dwarf-regs.o
  arch/x86/util/dwarf-regs.c:66:36: error: 'x86_32_regoffset_table' defined but not used [-Werror=unused-const-variable=]
   static const struct pt_regs_offset x86_32_regoffset_table[] = {
                                      ^~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Signed-off-by: Rafael Aquini <aquini@redhat.com>