[tools] perf: Fix compile of util/tsc.c
Message-id: <1389109877-9395-86-git-send-email-jolsa@redhat.com>
Patchwork-id: 73383
O-Subject: [PATCH RHEL7.0 BZ1036665 085/226] perf tools: Fix compile of util/tsc.c
Bugzilla: 1036665
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1036665
https://bugzilla.redhat.com/show_bug.cgi?id=1036665

upstream
========
commit 602bab1b883090ffd125ed1253fe8ec127c048b1
Author: David Ahern <dsahern@gmail.com>
Date: Fri Jul 26 08:27:23 2013 -0600

description
===========
On Fedora 18, with gcc 4.6.4 compile fails with:

arch/x86/util/tsc.c: In function 'perf_time_to_tsc':
arch/x86/util/tsc.c:13:6: error: declaration of 'time' shadows a global declaration [-Werror=shadow]
cc1: all warnings being treated as errors
make: *** [/tmp/junk/arch/x86/util/tsc.o] Error 1
make: *** Waiting for unfinished jobs....

Fix by renaming the local variable.

Signed-off-by: Jarod Wilson <jarod@redhat.com>