[net] netfilter: combine IPv4 and IPv6 nf_nat_redirect code in one module
Message-id: <51638ac15e3aac7541fa903407f20f7e08bc16e1.1465290493.git.pabeni@redhat.com>
Patchwork-id: 149223
O-Subject: [RHEL7.3 net PATCH 036/165] netfilter: combine IPv4 and IPv6 nf_nat_redirect code in one module
Bugzilla: 1331757
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1331757
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11141575
Tested: nftables test-suite and basic functional tests

Upstream commit:
commit b59eaf9e2871735ea7cc7e3dbf8bf83bddd786b9
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Wed Nov 26 12:46:50 2014 +0100

    netfilter: combine IPv4 and IPv6 nf_nat_redirect code in one module

    This resolves linking problems with CONFIG_IPV6=n:

    net/built-in.o: In function `redirect_tg6':
    xt_REDIRECT.c:(.text+0x6d021): undefined reference to `nf_nat_redirect_ipv6'

    Reported-by: Andreas Ruprecht <rupran@einserver.de>
    Reported-by: Or Gerlitz <ogerlitz@mellanox.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>