[perf] probe: Improve detection of file/function name in the probe: pattern
Message-id: <1433890415-28530-3-git-send-email-gduarte@redhat.com>
Patchwork-id: 117275
O-Subject: [RHEL7.2 PATCH BZ 1223850 2/9] perf probe: Improve detection of file/function name in the probe pattern
Bugzilla: 1223850
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>

BZ 1223850
Upstream Status: 3099c026002e97b8c173d9d0bbdfc39257d14402

commit 3099c026002e97b8c173d9d0bbdfc39257d14402
Author: Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
Date:   Tue Apr 28 17:35:34 2015 +0530

    perf probe: Improve detection of file/function name in the probe pattern

    Currently, perf probe considers patterns including a '.' to be a file.
    However, this causes problems on powerpc ABIv1 where all functions have
    a leading '.':

      $ perf probe -F | grep schedule_timeout_interruptible
      .schedule_timeout_interruptible
      $ perf probe .schedule_timeout_interruptible
      Semantic error :File always requires line number or lazy pattern.
        Error: Command Parse Error.

    Fix this:
    - by checking the probe pattern in more detail, and
    - skipping leading dot if one exists when creating/deleting events.

    Signed-off-by: Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
    Reviewed-by: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
    Acked-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
    Cc: Ananth N Mavinakayanahalli <ananth@in.ibm.com>
    Cc: Michael Ellerman <mpe@ellerman.id.au>
    Cc: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
    Cc: Sukadev Bhattiprolu <sukadev@linux.vnet.ibm.com>
    Cc: linuxppc-dev@lists.ozlabs.org
    Link: http://lkml.kernel.org/r/db680f7cb11c4452b632f908e67151f3aa0f4602.1430217967.git.naveen.n.rao@linux.vnet.ibm.com
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>