[tools] perf config: Fix build with older toolchain
Message-id: <1474556776-20705-51-git-send-email-jolsa@redhat.com>
Patchwork-id: 158123
O-Subject: [PATCH RHEL7.3 BZ1373817 050/252] perf config: Fix build with older toolchain.
Bugzilla: 1373817
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1373817
https://bugzilla.redhat.com/show_bug.cgi?id=1373817

upstream
========
commit d8e28654f28de74951ab1b7e59d2bebb442972aa
Author: Vinson Lee <vlee@freedesktop.org>
Date: Mon Apr 4 22:07:39 2016 +0000

description
===========
Fix build error on Ubuntu 12.04.5 with GCC 4.6.3.

    CC       util/config.o
  util/config.c: In function perf_buildid_config:
  util/config.c:384:15: error: declaration of dirname shadows a global declaration [-Werror=shadow]

Fixes: 9cb5987c8227 ("perf config: Rework buildid_dir_command_config to perf_buildid_config")
Signed-off-by: Rafael Aquini <aquini@redhat.com>