[usb] uas: fix GFP_NOIO under spinlock
Message-id: <1410887463-20674-376-git-send-email-dzickus@redhat.com>
Patchwork-id: 95433
O-Subject: [RHEL7 PATCH 375/591] uas: fix GFP_NOIO under spinlock
Bugzilla: 1110939
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1110939

commit e7eda9329372f5e436e5a9291eb115eab0feae02
Author: Oliver Neukum <oneukum@suse.de>
Date:   Fri Mar 28 11:10:30 2014 +0100

    uas: fix GFP_NOIO under spinlock

    Quote Dan:

    The patch e36e64930cff: "uas: Use GFP_NOIO rather then GFP_ATOMIC
    where possible" from Nov 7, 2013, leads to the following static
    checker warning:

            drivers/usb/storage/uas.c:806 uas_eh_task_mgmt()
            error: scheduling with locks held: 'spin_lock:lock'

    Some other allocations under spinlock are not caught.
    The fix essentially reverts e36e64930cffd94e1c37fdb82f35989384aa946b

    Signed-off-by: Oliver Neukum <oliver@neukum.org>
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Acked-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>