[netdrv] vmxnet3: fix lock imbalance in vmxnet3_tq_xmit()
Message-id: <1463061190-613-11-git-send-email-nhorman@redhat.com>
Patchwork-id: 144299
O-Subject: [RHEL7.3 PATCH 10/11] vmxnet3: fix lock imbalance in vmxnet3_tq_xmit()
Bugzilla: 1329403
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

A recent bug fix rearranged the code in vmxnet3_tq_xmit() in a
way that left the error handling for oversized headers unlock
a lock that had not been taken yet. Gcc warns about the incorrect
use of the 'flags' variable because of that:

drivers/net/vmxnet3/vmxnet3_drv.c: In function 'vmxnet3_tq_xmit.constprop':
include/linux/spinlock.h:246:3: error: 'flags' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This changes the error handling path to 'goto' the end of the function
beyond the lock/unlock pair.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: cec05562fb1d ("vmxnet3: avoid calling pskb_may_pull with interrupts disabled")
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit efc21d95067f658a20e51e24c4c86d68f23b7f7f)

BZ: 1329403
BREW: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10963229
TEST: Tested by myself and Vmware
Signed-off-by: Rafael Aquini <aquini@redhat.com>