[tools] perf sched: Make common options cascading
Message-id: <1487851678-22505-127-git-send-email-jolsa@redhat.com>
Patchwork-id: 167514
O-Subject: [PATCH RHEL7.4 BZ1425612 126/298] perf sched: Make common options cascading
Bugzilla: 1425612
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1425612
https://bugzilla.redhat.com/show_bug.cgi?id=1425612

upstream
========
commit 77f02f44460ab1480af2ae6145a1a85b9fe0b8ac
Author: Namhyung Kim <namhyung@kernel.org>
Date: Mon Oct 24 12:00:03 2016 +0900

description
===========
The -i and -v options can be used in subcommands so enable cascading the
sched_options.  This fixes the following inconvenience in 'perf sched':

  $ perf sched -i perf.data.sched  map
  ... (it works well) ...

  $ perf sched map  -i perf.data.sched
    Error: unknown switch `i'

   Usage: perf sched map [<options>]

          --color-cpus <cpus>
                            highlight given CPUs in map
          --color-pids <pids>
                            highlight given pids in map
          --compact         map output in compact mode
          --cpus <cpus>     display given CPUs in map

With this patch, the second command line works with the perf.data.sched
data file.

Signed-off-by: Rafael Aquini <aquini@redhat.com>