[gpio] gpio_msm: Fix build error due to missing err.h
Message-id: <1463503488-149391-24-git-send-email-dzickus@redhat.com>
Patchwork-id: 144617
O-Subject: [RHEL7 PATCH 023/725] gpio_msm: Fix build error due to missing err.h
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 011b2039dfd46fa030138b2e2ed3c55c8341151d
Author: Stephen Boyd <sboyd@codeaurora.org>
Date:   Wed Jul 24 13:20:48 2013 -0700

    gpio_msm: Fix build error due to missing err.h

    drivers/gpio/gpio-msm-v1.c: In function 'gpio_msm_v1_probe':
    drivers/gpio/gpio-msm-v1.c:656:2:
    error: implicit declaration of function 'IS_ERR'
    [-Werror=implicit-function-declaration]
    drivers/gpio/gpio-msm-v1.c:657:3:
    error: implicit declaration of function 'PTR_ERR'
    [-Werror=implicit-function-declaration]

    This driver failed to compile after commit 68515bb
    (gpio_msm: Convert to use devm_ioremap_resource,
    2013-06-10).

    Acked-by: Tushar Behera <tushar.behera@linaro.org>
    Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>