[kernel] provide a __smp_call_function_single stub for !CONFIG_SMP
Message-id: <1393557215-27663-6-git-send-email-snitzer@redhat.com>
Patchwork-id: 77649
O-Subject: [RHEL7 PATCH 05/42] kernel: provide a __smp_call_function_single stub for !CONFIG_SMP
Bugzilla: 1071014
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ: 1071014

Combine the fix with the original change (which needs the fix).

Upstream commit 40c01e8bd5575e32633192513e09eac7155d6926
Author: Christoph Hellwig <hch@infradead.org>
Date:   Thu Nov 14 14:32:08 2013 -0800

    kernel: provide a __smp_call_function_single stub for !CONFIG_SMP

    Signed-off-by: Christoph Hellwig <hch@lst.de>
    Cc: Jan Kara <jack@suse.cz>
    Cc: Jens Axboe <axboe@kernel.dk>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Upstream commit 7cf64f861b7a43b395f0855994003254b06a7e5a
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Thu Nov 14 14:32:09 2013 -0800

    kernel-provide-a-__smp_call_function_single-stub-for-config_smp-fix

    x86_64 allnoconfig:

      kernel/up.c:25: error: redefinition of '__smp_call_function_single'
      include/linux/smp.h:154: note: previous definition of '__smp_call_function_single' was here

    Cc: Christoph Hellwig <hch@infradead.org>
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Jan Kara <jack@suse.cz>
    Cc: Jens Axboe <axboe@kernel.dk>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>