[net] vxlan: include net/ip6_checksum.h for csum_ipv6_magic()
Message-id: <1378198104-7223-36-git-send-email-amwang@redhat.com>
Patchwork-id: 66017
O-Subject: [RHEL7 PATCH net 35/36] vxlan: include net/ip6_checksum.h for csum_ipv6_magic()
Bugzilla: 970585
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>

(cherry picked from commit 660d98cae0a474887bb5d66e60422addb4c6532c)
	Fengguang reported a compile warning:

	   drivers/net/vxlan.c: In function 'vxlan6_xmit_skb':
	   drivers/net/vxlan.c:1352:3: error: implicit declaration of function 'csum_ipv6_magic' [-Werror=implicit-function-declaration]
	   cc1: some warnings being treated as errors

	this patch fixes it.

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Cong Wang <amwang@redhat.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Cong Wang <amwang@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>