[netdrv] net: fix cdc-phonet.c dependency and build error
Message-id: <1462578743-3088-178-git-send-email-torez@redhat.com>
Patchwork-id: 143395
O-Subject: [RHEL7 PATCH BZ1303955 177/364] net: fix cdc-phonet.c dependency and build error
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 37d2dbcdcca88e392009d7cbe8617d5af0ebcb32
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Wed Sep 16 11:32:41 2015 -0700

    net: fix cdc-phonet.c dependency and build error

    Fix build error caused by missing Kconfig dependency:

    ERROR: "cdc_parse_cdc_header" [drivers/net/usb/cdc-phonet.ko] undefined!

    Reported-by: Fengguang Wu <fengguang.wu@intel.com>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>