[hv] x86/hyperv: Hide unused label
Message-id: <20170822130235.25834-15-vkuznets@redhat.com>
Patchwork-id: 183080
O-Subject: [RHEL7.5 KERNEL PATCH v2 14/17] x86/hyperv: Hide unused label
Bugzilla: 1410023
RH-Acked-by: Cathy Avery <cavery@redhat.com>
RH-Acked-by: Mohammed Gamal <mgamal@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

commit 73667e31a153a66da97feb1584726222504924f8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 14 22:17:17 2017 +0100

    x86/hyperv: Hide unused label

    This new 32-bit warning just showed up:

    arch/x86/hyperv/hv_init.c: In function 'hyperv_init':
    arch/x86/hyperv/hv_init.c:167:1: error: label 'register_msr_cs' defined but not used [-Werror=unused-label]

    The easiest solution is to move the label up into the existing #ifdef that
    has the goto.

    Fixes: dee863b571b0 ("hv: export current Hyper-V clocksource")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Stephen Hemminger <sthemmin@microsoft.com>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: Haiyang Zhang <haiyangz@microsoft.com>
    Cc: devel@linuxdriverproject.org
    Cc: Vitaly Kuznetsov <vkuznets@redhat.com>
    Cc: "K. Y. Srinivasan" <kys@microsoft.com>
    Link: http://lkml.kernel.org/r/20170214211736.2641241-1-arnd@arndb.de
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>