[perf] probe: Fix compiles due to declarations using perf_probe_point
Message-id: <1431774138-14330-178-git-send-email-jolsa@redhat.com>
Patchwork-id: 112398
O-Subject: [PATCH RHEL7.2 BZ1222189 177/327] perf probe: Fix compiles due to declarations using perf_probe_point
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 6d4a48968bfb5c67002f253fbaeb5acd41d7897a
Author: David Ahern <david.ahern@oracle.com>
Date: Wed Mar 11 10:36:20 2015 -0400

description
===========
perf fails to build with gcc "(GCC) 4.4.7 20120313 (Red Hat
4.4.7-4.0.9)" (a.k.a., RHEL6 / CentOS 6 / OL 6):

  cc1: warnings being treated as errors
  util/probe-event.c: In function get_alternative_line_range:
  util/probe-event.c:359: error: missing initializer
  util/probe-event.c:359: error: (near initialization for pp.file)
  util/probe-event.c:359: error: missing initializer
  util/probe-event.c:359: error: (near initialization for result.function)

Fix by bringing in initializers to declaration.

Signed-off-by: Rafael Aquini <aquini@redhat.com>