[redhat] sound: Fix compilation for !CONFIG_ACPI for s390 and ppc64
Message-id: <14639865805-42-patchset-jkysela@redhat.com>
Patchwork-id: 151447
O-Subject: [RHEL 7.3 PATCH 40/39] Fix compilation for !CONFIG_ACPI for s390 and ppc64 (2nd version)
Bugzilla: 1220299
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

The patch "ACPI: Add support for device specific properties" causes
a compilation issue for the s390 platform where CONFIG_ACPI is not used.

  In file included from init/main.c:27:0:
  include/linux/acpi.h:691:24: error: unknown type name 'acpi_object_type'
      const char *name, acpi_object_type type,
                        ^
  include/linux/acpi.h:698:12: error: unknown type name 'acpi_object_type'
            acpi_object_type type,
            ^
  make[1]: *** [init/main.o] Error 1
  make: *** [init] Error 2

Also, define an empty acpi_object union for the ppc64 platform:

  In file included from init/main.c:27:0:
  include/linux/acpi.h:702:18: error: 'union acpi_object' declared inside parameter list [-Werror]
      const union acpi_object **obj)

rhbz#1220299
Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>