[usb] xhci-mtk: use __maybe_unused to hide pm functions
Message-id: <1465525749-9195-121-git-send-email-torez@redhat.com>
Patchwork-id: 150055
O-Subject: [RHEL7 BZ1332712 v2 120/196] usb: xhci-mtk: use __maybe_unused to hide pm functions
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 8dac5300c251263cc91f49713d64b5ca85a76d53
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Mar 2 16:24:04 2016 +0100

    usb: xhci-mtk: use __maybe_unused to hide pm functions

    The mediatek XHCI glue driver uses SET_SYSTEM_SLEEP_PM_OPS() to
    conditionally set the correct suspend/resume options, and
    also puts both the dev_pm_ops and the functions inside of
    an #ifdef testing for CONFIG_PM_SLEEP, but those functions
    then call other code that becomes unused:

    drivers/usb/host/xhci-mtk.c:135:12: error: 'xhci_mtk_host_disable' defined but not used [-Werror=unused-function]
    drivers/usb/host/xhci-mtk.c:313:13: error: 'usb_wakeup_enable' defined but not used [-Werror=unused-function]
    drivers/usb/host/xhci-mtk.c:321:13: error: 'usb_wakeup_disable' defined but not used [-Werror=unused-function]

    This replaces the #ifdef with __maybe_unused annotations so the
    compiler knows it can silently drop them instead of warning.

    For the DEV_PM_OPS definition, we can use an IS_ENABLED() check
    to avoid defining the structure when CONFIG_PM is not set without
    the #ifdef.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>