[infiniband] ib/rxe: avoid putting a large struct rxe_qp on stack
Message-id: <1488853076-16738-178-git-send-email-ddutile@redhat.com>
Patchwork-id: 171849
O-Subject: [PATCH RHEL-7.4 177/340] IB/rxe: avoid putting a large struct rxe_qp on stack
Bugzilla: 1384574 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1384574

commit a0fa72683e78979ef1123d679b1c40ae28bd9096
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 19 13:57:26 2016 +0200

    IB/rxe: avoid putting a large struct rxe_qp on stack

    A race condition fix added an rxe_qp structure to the stack in order
    to be able to perform rollback in rxe_requester(), but the structure
    is large enough to trigger the warning for possible stack overflow:

    drivers/infiniband/sw/rxe/rxe_req.c: In function 'rxe_requester':
    drivers/infiniband/sw/rxe/rxe_req.c:757:1: error: the frame size of 2064 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    This changes the rollback function to only save the psn inside
    the qp, which is the only field we access in the rollback_qp
    anyway.

    Fixes: 3050b9985024 ("IB/rxe: Fix race condition between requester and completer")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>