[crypto] qat - make qat_asym_algs.o depend on asn1 headers
Message-id: <20160802072929.GA13585@gondor.apana.org.au>
Patchwork-id: 156336
O-Subject: [RHEL7 PATCH] crypto: qat - make qat_asym_algs.o depend on asn1 headers
Bugzilla: 1351563
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jan Stancek <jstancek@redhat.com>

RHEL7 Bugzilla #1351563

https://brewweb.devel.redhat.com/taskinfo?taskID=11479719

Upstream commit: 81dc0365cfa7bc7c08a0e44d9ee04964df782e19

Parallel build can sporadically fail because asn1 headers may
not be built yet by the time qat_asym_algs.o is compiled:
  drivers/crypto/qat/qat_common/qat_asym_algs.c:55:32: fatal error: qat_rsapubkey-asn1.h: No such file or directory
   #include "qat_rsapubkey-asn1.h"

Cc: stable@vger.kernel.org
Signed-off-by: Jan Stancek <jstancek@redhat.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
Signed-off-by: Rafael Aquini <aquini@redhat.com>