[usb] xhci: free the correct ring
Message-id: <1489393527-9024-113-git-send-email-torez@redhat.com>
Patchwork-id: 173630
O-Subject: [RHEL7.4 PATCH BZ1383823 112/467] xhci: free the correct ring
Bugzilla: 1383823
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1383823
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12744255
Testing: on local desktop and Dell Precision 5510 laptop

commit f76a28a69a103b8789d2430a193af558f4c85364
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jun 30 14:26:17 2016 +0200

    xhci: free the correct ring

    gcc warns about what first looks like a reference to an uninitialized
    variable:

    drivers/usb/host/xhci-ring.c: In function 'handle_cmd_completion':
    drivers/usb/host/xhci-ring.c:753:4: error: 'ep_ring' may be used uninitialized in this function [-Werror=maybe-uninitialized]
        xhci_unmap_td_bounce_buffer(xhci, ep_ring, cur_td);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/usb/host/xhci-ring.c:647:20: note: 'ep_ring' was declared here
      struct xhci_ring *ep_ring;
                        ^~~~~~~

    It's clear to see that the list_empty() check means it can never be
    uninitialized, however it still looks wrong:

    When ep->cancelled_td_list contains more than one entry, the
    ep_ring variable will point to the ring that was retrieved
    from the last urb, and we have to look it up again in the
    second loop instead, which fixes the behavior and gets rid of the
    warning too.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: f9c589e142d0 ("xhci: TD-fragment, align the unsplittable case with a bounce buffer")
    Acked-by: Mathias Nyman <mathias.nyman@linux.intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>