[usb] usb/misc: fix chaoskey build, needs HW_RANDOM
Message-id: <1434576081-13393-351-git-send-email-dzickus@redhat.com>
Patchwork-id: 119714
O-Subject: [RHEL7 PATCH 350/376] usb/misc: fix chaoskey build, needs HW_RANDOM
Bugzilla: 1232920
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1232920

commit d9aab404e60d122ded979fa0b81db42fb680d867
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Thu Apr 2 17:10:55 2015 -0700

    usb/misc: fix chaoskey build, needs HW_RANDOM

    Fix build errors when HW_RANDOM is not enabled:

    drivers/built-in.o: In function `chaoskey_disconnect':
    chaoskey.c:(.text+0x5f3f00): undefined reference to `hwrng_unregister'
    drivers/built-in.o: In function `chaoskey_probe':
    chaoskey.c:(.text+0x5f42a6): undefined reference to `hwrng_register'

    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>