[tools] perf tests: Adding build test for having ending double slash
Message-id: <1455542356-29341-82-git-send-email-jolsa@redhat.com>
Patchwork-id: 134455
O-Subject: [PATCH RHEL7.3 BZ1306834 081/237] perf tests: Adding build test for having ending double slash
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1306834
https://bugzilla.redhat.com/show_bug.cgi?id=1306834

upstream
========
commit aa53c09e90a19c215549bd1ca970fddcb7c0c001
Author: Jiri Olsa <jolsa@redhat.com>
Date: Mon Jul 27 20:24:17 2015 +0200

description
===========
Pawel Moll reported build issue for having extra slash (/) at the end of
the prefix variable.

  $ make prefix=/usr/local/

    CC       tests/attr.o
  tests/attr.c: In function test__attr:
  tests/attr.c:168:50: error: expected ) before ; token
    snprintf(path_perf, PATH_MAX, "%s/perf", BINDIR);
                                                ^
  tests/attr.c:176:1: error: expected ; before } token
   }
   ^
  tests/attr.c:176:1: error: control reaches end of non-void function [-Werror=return-type]
   }
   ^
  cc1: all warnings being treated as errors

Adding automated test case for this.

Signed-off-by: Rafael Aquini <aquini@redhat.com>