[tools] perf/report: Use parse_options_usage() for -s option failure
Message-id: <1408462094-14194-254-git-send-email-jolsa@redhat.com>
Patchwork-id: 88212
O-Subject: [PATCH RHEL7.1 BZ1131394 253/325] perf report: Use parse_options_usage() for -s option failure
Bugzilla: 1131394
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1131394
https://bugzilla.redhat.com/show_bug.cgi?id=1131394

upstream
========
commit 91aba0a62e24ff7a567e13e1d88deab711df6f0f
Author: Namhyung Kim <namhyung.kim@lge.com>
Date: Fri Nov 1 16:33:13 2013 +0900

description
===========
The -s (--sort) option was processed after normal option parsing so that
it cannot call the parse_options_usage() automatically.  Currently it
calls usage_with_options() which shows entire help messages for event
option.  Fix it by showing just -s options.

  $ perf report -s help
    Error: Unknown --sort key: `help'

   usage: perf report [<options>]

      -s, --sort <key[,key2...]>
                            sort by key(s): pid, comm, dso, symbol, ...
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>