[acpi] fan: fix fan driver compile error when CONFIG_PM_SLEEP is undefined
Message-id: <1426083630-32074-4-git-send-email-prarit@redhat.com>
Patchwork-id: 107277
O-Subject: [RHEL7.2 PATCH BZ 1174059 03/12] ACPI / fan: fix fan driver compile error when CONFIG_PM_SLEEP is undefined
Bugzilla: 1174059
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1174059

commit b108e0ea94a33f85590959a7a7fbcfd6f8ea8ab6
Author: Shuah Khan <shuah.kh@samsung.com>
Date:   Wed Feb 12 20:19:08 2014 -0700

    ACPI / fan: fix fan driver compile error when CONFIG_PM_SLEEP is undefined

    The ACPI fan driver defines acpi_fan_suspend() and acpi_fan_resume()
    when CONFIG_PM_SLEEP is defined. This results in the following compile
    errors when CONFIG_PM_SLEEP is undefined:

    drivers/acpi/fan.c:60:8: error: 'acpi_fan_suspend' undeclared here (not in a function)
    drivers/acpi/fan.c:60:8: error: 'acpi_fan_resume' undeclared here (not in a function)

    Signed-off-by: Shuah Khan <shuah.kh@samsung.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Cc: Lenny Szubowicz <lszubowi@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>