[arm] fix nommu builds with 48be69a02 (ARM: move signal handlers into a vdso-like page)
Message-id: <1381413926-15908-294-git-send-email-vfalico@redhat.com>
Patchwork-id: 68885
O-Subject: [RHEL7 PATCH 293/820] ARM: fix nommu builds with 48be69a02 (ARM: move signal handlers into a vdso-like page)
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 8c0cc8a5d90bc7373a7a9e7f7a40eb41f51e03fc
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=8c0cc8a5d90bc7373a7a9e7f7a40eb41f51e03fc
Stable: 0a73f943a52c70cc33b29306433fb11cd9a854fc
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=0a73f943a52c70cc33b29306433fb11cd9a854fc

Description
----------------------------
Backport from linux-3.10.y stable.

From: Russell King <rmk+kernel@arm.linux.org.uk>
Subject: ARM: fix nommu builds with 48be69a02 (ARM: move signal handlers into a vdso-like page)

commit 8c0cc8a5d90bc7373a7a9e7f7a40eb41f51e03fc upstream.

Olof reports that noMMU builds error out with:

arch/arm/kernel/signal.c: In function 'setup_return':
arch/arm/kernel/signal.c:413:25: error: 'mm_context_t' has no member named 'sigpage'

This shows one of the evilnesses of IS_ENABLED().  Get rid of it here
and replace it with #ifdef's - and as no noMMU platform can make use
of sigpage, depend on CONIFG_MMU not CONFIG_ARM_MPU.

Reported-by: Olof Johansson <olof@lixom.net>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 0a73f943a52c70cc33b29306433fb11cd9a854fc)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>