[netdrv] liquidio: fix possible eeprom format string overflow
Message-id: <20170907193925.GA21539@felix-thinkpad.cavium.com>
Patchwork-id: 184309
O-Subject: [PATCH v2 RHEL7.5 153/202] liquidio: fix possible eeprom format string overflow
Bugzilla: 1451436
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1451436

Upstream Status: linux.git

commit 56c0da495a0b38f8ac0c0c0e3fcc750ea449daea
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 14 14:07:05 2017 +0200

    liquidio: fix possible eeprom format string overflow

    gcc reports that the temporary buffer for computing the
    string length may be too small here:

    drivers/net/ethernet/cavium/liquidio/lio_ethtool.c: In function 'lio_get_eeprom_len':
    /drivers/net/ethernet/cavium/liquidio/lio_ethtool.c:345:21: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
      len = sprintf(buf, "boardname:%s serialnum:%s maj:%lld min:%lld\n",
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/cavium/liquidio/lio_ethtool.c:345:6: note: 'sprintf' output between 35 and 167 bytes into a destination of size 128
      len = sprintf(buf, "boardname:%s serialnum:%s maj:%lld min:%lld\n",

    This extends it to 192 bytes, which is certainly enough. As far
    as I could tell, there are no other constraints that require a specific
    maximum size.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Felix Manlunas <fmanluna@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>