[tools] perf test: Add test cases for new data source encoding
Message-id: <20170905131504.32698-5-jolsa@redhat.com>
Patchwork-id: 184022
O-Subject: [PATCH RHEL7.5 BZ1485994 4/5] perf test: Add test cases for new data source encoding
Bugzilla: 1485994
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1485994
https://bugzilla.redhat.com/show_bug.cgi?id=1485994

upstream
========
commit 3067eaa7ce2dbcde89d87277cdbc91c211480060
Author: Andi Kleen <ak@linux.intel.com>
Date: Wed Aug 16 15:21:56 2017 -0700

RHEL7
=====
Conflict in test__mem prototype, RHEL7 does not have
text parameter backported yet.

description
===========
Add some simple tests to perf test to test data source printing.

v2: Make the tests actually checked for the correct name of Forward
v3: Adjust to new encoding

Committer notes:

Avoid the in place declaration to make this build with older compilers,
for instance, in Debian 7 we get:

  tests/mem.c: In function 'test__mem':
  tests/mem.c:30:5: error: missing initializer [-Werror=missing-field-initializers]
  tests/mem.c:30:5: error: (near initialization for '(anonymous).<anonymous>.mem_snoop') [-Werror=missing-field-initializers]

So just zero a struct, then go on building the unions as needed,
reusing settings from the previous test, i.e. local -> remote, etc.

Signed-off-by: Rafael Aquini <aquini@redhat.com>