[x86] perf/x86/uncore: Fix build on UP-IOAPIC configs
Message-id: <1460038562-19641-55-git-send-email-jolsa@redhat.com>
Patchwork-id: 140375
O-Subject: [PATCH RHEL7.3 BZ1323852 054/311] perf/x86/uncore: Fix build on UP-IOAPIC configs
Bugzilla: 1323852
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1323852
https://bugzilla.redhat.com/show_bug.cgi?id=1323852

upstream
========
commit 6f6e151692625e29810f2fe036b4f410540567c8
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Mar 3 09:12:27 2016 +0100

description
===========
Commit:

  cf6d445f6897 ("perf/x86/uncore: Track packages, not per CPU data")

reorganized the uncore code to track packages, and introduced a dependency
on MAX_APIC_ID. This constant is not available on UP-IOAPIC builds:

  arch/x86/events/intel/uncore.c:1350:44: error: 'MAX_LOCAL_APIC' undeclared here (not in a function)

Include asm/apicdef.h explicitly to pick it up.

Signed-off-by: Rafael Aquini <aquini@redhat.com>