[netdrv] mlx5e: Remove unused variable
Message-id: <1488853076-16738-302-git-send-email-ddutile@redhat.com>
Patchwork-id: 172015
O-Subject: [PATCH RHEL-7.4 301/340] net/mlx5e: Remove unused variable
Bugzilla: 1385330 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385330

commit ad05df399f3343b10664827a3860669a8a80782d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jan 19 10:33:29 2017 +0100

    net/mlx5e: Remove unused variable

    A cleanup removed the only user of this variable

    mlx5/core/en_ethtool.c: In function 'mlx5e_set_channels':
    mlx5/core/en_ethtool.c:546:6: error: unused variable 'ncv' [-Werror=unused-variable]

    Let's remove the declaration as well.

    Fixes: 639e9e94160e ("net/mlx5e: Remove unnecessary checks when setting num channels")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reviewed-by: Tariq Toukan <tariqt@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>