[pci] aer: include header file
Message-id: <1461247929-26697-131-git-send-email-dmilburn@redhat.com>
Patchwork-id: 141637
O-Subject: [RHEL7.3 PATCH BZ 1288601 v2 130/158] PCI/AER: include header file
Bugzilla: 1288601
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>

From: Sudip Mukherjee <sudipm.mukherjee@gmail.com>

We are having build failure with sparc allmodconfig with the error:

drivers/nvme/host/pci.c:15:0:
include/linux/aer.h: In function 'pci_enable_pcie_error_reporting':
include/linux/aer.h:49:10: error: 'EINVAL' undeclared (first use in this function)

The file aer.h is using the error values but they are defined in
errno.h. Include errno.h so that we have the definitions of the error
codes.

Fixes: a0a3408ee614 ("NVMe: Add pci error handlers")
Cc: Keith Busch <keith.busch@intel.com>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>
Signed-off-by: Jens Axboe <axboe@fb.com>
(cherry picked from commit c89e5b80245899fc51fb1d83880e2f5762fcf350)
Signed-off-by: David Milburn <dmilburn@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>