[infiniband] mlx4: Make buffer larger to avoid overflow warning
Message-id: <71f474d3a68d98917cb8378e7376a0da7c5a7fab.1410425016.git.avadai@redhat.com>
Patchwork-id: 93761
O-Subject: [Patch RHEL7.1 V1 099/197] mlx4_core: Make buffer larger to avoid overflow warning
Bugzilla: 1107617 1107618 1107619 1107620
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

From: Dan Carpenter <dan.carpenter@oracle.com>

My static checker complains that the sprintf() here can overflow.

	drivers/infiniband/hw/mlx4/main.c:1836 mlx4_ib_alloc_eqs()
	error: format string overflow. buf_size: 32 length: 69

This seems like a valid complaint.  The "dev->pdev->bus->name" string
can be 48 characters long.  I just made the buffer 80 characters instead
of 69 and I changed the sprintf() to snprintf().

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Roland Dreier <roland@purestorage.com>
(cherry picked from commit 4661bd798f1b58ee2755bfa04003638345802680)
Signed-off-by: Amir Vadai <avadai@redhat.com>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>