[tools] perf pmu: Fix misleadingly indented assignment (whitespace)
Message-id: <1463569977-29479-28-git-send-email-jolsa@redhat.com>
Patchwork-id: 145614
O-Subject: [PATCH RHEL7.3 BZ1336447 027/324] perf pmu: Fix misleadingly indented assignment (whitespace)
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit d85ce830eef6c10d1e9617172dea4681f02b8424
Author: Markus Trippelsdorf <markus@trippelsdorf.de>
Date: Mon Dec 14 16:44:40 2015 +0100

description
===========
One line in perf_pmu__parse_unit() is indented wrongly, leading to a
warning (=> error) from gcc 6:

  util/pmu.c:156:3: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]

    sret = read(fd, alias->unit, UNIT_MAX_LEN);
    ^~~~

  util/pmu.c:153:2: note: ...this 'if' clause, but it is not
    if (fd == -1)
    ^~

Fixes: 410136f5dd96 ("tools/perf/stat: Add event unit and scale support")
Signed-off-by: Rafael Aquini <aquini@redhat.com>