[tools] perf/probe: Fix --list option to show events only with uprobe events
Message-id: <1418163608-7772-192-git-send-email-jolsa@redhat.com>
Patchwork-id: 101402
O-Subject: [PATCH RHEL7.1 BZ1169436 191/359] perf probe: Fix --list option to show events only with uprobe events
Bugzilla: 1169436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1169436
https://bugzilla.redhat.com/show_bug.cgi?id=1169436

upstream
========
commit 5e45187cc94814d2a5324bc18af994efc4fb4f7c
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed Aug 13 16:12:48 2014 +0000

description
===========
Current perf probe --list doesn't work if only CONFIG_UPROBE_EVENTS=y
because it aborts when it fails to open kprobe_events file before
checking uprobe_events file.

This fixes --list option to show dynamic events if it can open either
kprobe_events or uprobe_events. Only if it failed to open both of them,
it shows an error message and aborts.

Without this patch, if we run perf probe -l on the kernel configured
with CONFIG_KPROBE_EVENTS=n and CONFIG_UPROBE_EVENTS=y,

  # perf probe -l
  /sys/kernel/debug/tracing/kprobe_events file does not exist - please rebuild ker
    Error: Failed to show event list.

With this patch,

  # perf probe -l
    probe_perf:alloc_event (on alloc_event@lib/traceevent/event-parse.c in /home/fedora/ksrc/linux-3/tools/perf/perf)

Changes in v2:
 - Use strerror_r instead of strerror.
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>