[kernel] rculist: list_first_or_null_rcu() should use list_entry_rcu()
Message-id: <1381413926-15908-657-git-send-email-vfalico@redhat.com>
Patchwork-id: 69212
O-Subject: [RHEL7 PATCH 656/820] rculist: list_first_or_null_rcu() should use list_entry_rcu()
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: c34ac00caefbe49d40058ae7200bd58725cebb45
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=c34ac00caefbe49d40058ae7200bd58725cebb45
Stable: 215840ab83bfdd15deca0a8b0f140369afab7f52
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=215840ab83bfdd15deca0a8b0f140369afab7f52

Description
----------------------------
Backport from linux-3.10.y stable.

From: Tejun Heo <tj@kernel.org>
Subject: rculist: list_first_or_null_rcu() should use list_entry_rcu()

commit c34ac00caefbe49d40058ae7200bd58725cebb45 upstream.

list_first_or_null() should test whether the list is empty and return
pointer to the first entry if not in a RCU safe manner.  It's broken
in several ways.

* It compares __kernel @__ptr with __rcu @__next triggering the
  following sparse warning.

  net/core/dev.c:4331:17: error: incompatible types in comparison expression (different address spaces)

* It doesn't perform rcu_dereference*() and computes the entry address
  using container_of() directly from the __rcu pointer which is
  inconsitent with other rculist interface.  As a result, all three
  in-kernel users - net/core/dev.c, macvlan, cgroup - are buggy.  They
  dereference the pointer w/o going through read barrier.

* While ->next dereference passes through list_next_rcu(), the
  compiler is still free to fetch ->next more than once and thus
  nullify the "__ptr != __next" condition check.

Fix it by making list_first_or_null_rcu() dereference ->next directly
using ACCESS_ONCE() and then use list_entry_rcu() on it like other
rculist accessors.

v2: Paul pointed out that the compiler may fetch the pointer more than
    once nullifying the condition check.  ACCESS_ONCE() added on
    ->next dereference.

v3: Restored () around macro param which was accidentally removed.
    Spotted by Paul.

Signed-off-by: Tejun Heo <tj@kernel.org>
Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Cc: Dipankar Sarma <dipankar@in.ibm.com>
Cc: "Paul E. McKenney" <paulmck@linux.vnet.ibm.com>
Cc: "David S. Miller" <davem@davemloft.net>
Cc: Li Zefan <lizefan@huawei.com>
Cc: Patrick McHardy <kaber@trash.net>
Signed-off-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 215840ab83bfdd15deca0a8b0f140369afab7f52)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>