[net] sctp: fix checkpatch errors with indent
Message-id: <0ca923a1ea989188bcd3a31c61bc1b26df557271.1468662840.git.lxin@redhat.com>
Patchwork-id: 155513
O-Subject: [RHEL7.3 net PATCH 2/8] sctp: fix checkpatch errors with indent
Bugzilla: 965453
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=965453
Upstream Status: net-next.git commit f7010e6

commit f7010e61442c80333b38aa026a551043a341fb8d
Author: wangweidong <wangweidong1@huawei.com>
Date:   Mon Dec 23 12:16:52 2013 +0800

    sctp: fix checkpatch errors with indent

    fix checkpatch errors below:
    ERROR: switch and case should be at the same inden
    ERROR: code indent should use tabs where possible

    Acked-by: Neil Horman <nhorman@tuxdriver.com>
    Signed-off-by: Wang Weidong <wangweidong1@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Conflicts: \
  - 90017acc is in rhel7 already, no need to add the part of
    sctp_packet_transmit()
  - b14878cc is in rhel7 already, will use asoc->ep->auth_enable
    in sctp_process_ext_param(), instead of net->sctp.auth_enable.

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>