[tools] perf trace: Add seccomp beautifier related defines for older systems
Message-id: <1474556776-20705-43-git-send-email-jolsa@redhat.com>
Patchwork-id: 158113
O-Subject: [PATCH RHEL7.3 BZ1373817 042/252] perf trace: Add seccomp beautifier related defines for older systems
Bugzilla: 1373817
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1373817
https://bugzilla.redhat.com/show_bug.cgi?id=1373817

upstream
========
commit 6fb35b9515c6300cb25022ac74f5f5617a349e18
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Apr 13 11:50:23 2016 -0300

description
===========
Were the detached tarball (make perf-tar-src-pkg) build was failing because
those definitions aren't available in the system headers.

On RHEL7, for instance:

  builtin-trace.c: In function syscall_arg__scnprintf_seccomp_op:
  builtin-trace.c:1069:7: error: SECCOMP_SET_MODE_STRICT undeclared (first use in this function)
    P_SECCOMP_SET_MODE_OP(STRICT);
         ^
  builtin-trace.c:1069:7: note: each undeclared identifier is reported only once for each function it appears in
  builtin-trace.c:1070:7: error: SECCOMP_SET_MODE_FILTER undeclared (first use in this function)
    P_SECCOMP_SET_MODE_OP(FILTER);
         ^
  builtin-trace.c: In function syscall_arg__scnprintf_seccomp_flags:
  builtin-trace.c:1091:14: error: SECCOMP_FILTER_FLAG_TSYNC undeclared (first use in this function)
    P_FLAG(TSYNC);
                ^

Signed-off-by: Rafael Aquini <aquini@redhat.com>