[netdrv] liquidio: fix implicit irq include causing build failures
Message-id: <20170907193956.GA21588@felix-thinkpad.cavium.com>
Patchwork-id: 184318
O-Subject: [PATCH v2 RHEL7.5 160/202] liquidio: fix implicit irq include causing build failures
Bugzilla: 1451436
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1451436

Upstream Status: net-next.git

commit ba3fb1022154d93fe71ee78e28e195207d511bc0
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Sun Jul 23 10:44:52 2017 -0400

    liquidio: fix implicit irq include causing build failures

    To fix

    In file included from drivers/net/ethernet/cavium/liquidio/octeon_mem_ops.c:24:0:
    drivers/net/ethernet/cavium/liquidio/octeon_device.h:216:2: error: expected specifier-qualifier-list before irqreturn_t
      irqreturn_t (*process_interrupt_regs)(void *);
      ^

    as seen on arm64 allmodconfig builds.

    Cc: Derek Chickles <derek.chickles@caviumnetworks.com>
    Cc: Satanand Burla <satananda.burla@caviumnetworks.com>
    Cc: Felix Manlunas <felix.manlunas@caviumnetworks.com>
    Cc: Raghu Vatsavayi <raghu.vatsavayi@caviumnetworks.com>
    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Felix Manlunas <fmanluna@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>