[sound] alsa: hda/ca0132: Limit values for chip addresses to 32-bit
Message-id: <1507829954160572-266-patchset-jkysela@redhat.com>
Patchwork-id: 192172
O-Subject: [RHEL 7.5 PATCH v2 0265/1088] ALSA: hda/ca0132: Limit values for chip addresses to 32-bit
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

With the previous unsigned long value clang generates warnings like
this:

sound/pci/hda/patch_ca0132.c:860:37: error: implicit conversion from
'unsigned long' to 'u32' (aka 'unsigned int') changes value from
18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
spec->curr_chip_addx = (res < 0) ? ~0UL : chip_addx;
~             ^~~~

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit d1600401faad4bc186bfdb291d8af644465e20bd)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>