[tools] perf/probe: Fix --del option to delete events only with uprobe events
Message-id: <1418163608-7772-193-git-send-email-jolsa@redhat.com>
Patchwork-id: 101403
O-Subject: [PATCH RHEL7.1 BZ1169436 192/359] perf probe: Fix --del option to delete events only with uprobe events
Bugzilla: 1169436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1169436
https://bugzilla.redhat.com/show_bug.cgi?id=1169436

upstream
========
commit 467ec08567483e3868f240b1ee03808970e06388
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed Aug 13 16:12:50 2014 +0000

description
===========
Current perf probe --del doesn't work if only CONFIG_UPROBE_EVENTS=y
because it aborts when it fails to open kprobe_events file before
checking uprobe_events file.

This fixes --del option to delete dynamic events if it can open either
kprobe_events or uprobe_events. Only if it failed to open both of them,
it shows an error message and aborts.

Without this patch, if we run perf probe -d on the kernel configured
with CONFIG_KPROBE_EVENTS=n and CONFIG_UPROBE_EVENTS=y,

  # perf probe -d \*
  kprobe_events file does not exist - please rebuild kernel with CONFIG_KPROBE_EVENTS.
    Error: Failed to delete events.

With this patch,

  # perf probe -d \*
  Removed event: probe_perf:alloc_event

Changes in v2:
 - Use strerror_r instead of strerror.
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>