[perf] probe: Find compilation directory path for lazy matching
Message-id: <1431774138-14330-314-git-send-email-jolsa@redhat.com>
Patchwork-id: 112534
O-Subject: [PATCH RHEL7.2 BZ1222189 313/327] perf probe: Find compilation directory path for lazy matching
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 09ed8975c4b13be4469899b210f0e0936021ee8f
Author: Naohiro Aota <naota@elisp.net>
Date: Fri Mar 13 14:18:40 2015 +0900

description
===========
If we use lazy matching, it failed to open a souce file if perf command
is invoked outside of compilation directory:

$ perf probe -a '__schedule;clear_*'
Failed to open kernel/sched/core.c: No such file or directory
  Error: Failed to add events. (-2)

OTOH, other commands like "probe -L" can solve the souce directory by
themselves. Let's make it possible for lazy matching too!

Signed-off-by: Rafael Aquini <aquini@redhat.com>