[base] regmap: Add missing header for !CONFIG_REGMAP stubs
Message-id: <1381413926-15908-387-git-send-email-vfalico@redhat.com>
Patchwork-id: 68994
O-Subject: [RHEL7 PATCH 386/820] regmap: Add missing header for !CONFIG_REGMAP stubs
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 49ccc142f9cbc33fdda18e8fa90c1c5b4a79c0ad
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=49ccc142f9cbc33fdda18e8fa90c1c5b4a79c0ad
Stable: 9300766810ffff36c2db8efc2fe7c7a6c0469129
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=9300766810ffff36c2db8efc2fe7c7a6c0469129

Description
----------------------------
Backport from linux-3.10.y stable.

From: Mateusz Krawczuk <m.krawczuk@partner.samsung.com>
Subject: regmap: Add missing header for !CONFIG_REGMAP stubs

commit 49ccc142f9cbc33fdda18e8fa90c1c5b4a79c0ad upstream.

regmap.h requires linux/err.h if CONFIG_REGMAP is not defined. Without it I get
error.
CC      drivers/media/platform/exynos4-is/fimc-reg.o
In file included from drivers/media/platform/exynos4-is/fimc-reg.c:14:0:
include/linux/regmap.h: In function 'regmap_write':
include/linux/regmap.h:525:10: error: 'EINVAL' undeclared (first use in this function)
include/linux/regmap.h:525:10: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Mateusz Krawczuk <m.krawczuk@partner.samsung.com>
Signed-off-by: Kyungmin Park <kyungmin.park@samsung.com>
Signed-off-by: Mark Brown <broonie@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 9300766810ffff36c2db8efc2fe7c7a6c0469129)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>