[net] ipv4: make snmp_mib_free static inline
Message-id: <1378198104-7223-37-git-send-email-amwang@redhat.com>
Patchwork-id: 66018
O-Subject: [RHEL7 PATCH net 36/36] net: make snmp_mib_free static inline
Bugzilla: 970585
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>

(cherry picked from commit 5a17a390de7bdbcfff9b8f344273a886ca4cf8bf)
	Fengguang reported:

	   net/built-in.o: In function `in6_dev_finish_destroy':
	   (.text+0x4ca7d): undefined reference to `snmp_mib_free'

	this is due to snmp_mib_free() is defined when CONFIG_INET is enabled,
	but in6_dev_finish_destroy() is now moved to core kernel.

	I think snmp_mib_free() is small enough to be inlined, so just make it
	static inline.

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Cong Wang <amwang@redhat.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Cong Wang <amwang@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>