[netdrv] ethernet/mellanox/mlx5/core/en_main.c: fix build with gcc-4.4.4
Message-id: <20171109065423.8574-81-ddutile@redhat.com>
Patchwork-id: 197059
O-Subject: [PATCH RHEL-7.5 v2 080/468] drivers/net/ethernet/mellanox/mlx5/core/en_main.c: fix build with gcc-4.4.4
Bugzilla: 1456694 1499362
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit 956327913c2e23048d7a586414bafe7ec0c2a887
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Fri Mar 31 13:09:38 2017 -0700

    drivers/net/ethernet/mellanox/mlx5/core/en_main.c: fix build with gcc-4.4.4

    drivers/net/ethernet/mellanox/mlx5/core/en_main.c: In function 'mlx5e_redirect_rqts':
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2210: error: unknown field 'rqn' specified in initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2211: warning: missing braces around initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2211: warning: (near initialization for 'direct_rrp.<anonymous>')
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c: In function 'mlx5e_redirect_rqts_to_channels':
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2227: error: unknown field 'rss' specified in initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2227: warning: missing braces around initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2227: warning: (near initialization for 'rrp.<anonymous>')
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2227: warning: initialization makes integer from pointer without a cast
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2228: error: unknown field 'rss' specified in initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2229: warning: excess elements in struct initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2229: warning: (near initialization for 'rrp')
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c: In function 'mlx5e_redirect_rqts_to_drop':
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2238: error: unknown field 'rqn' specified in initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2239: warning: missing braces around initializer
    drivers/net/ethernet/mellanox/mlx5/core/en_main.c:2239: warning: (near initialization for 'drop_rrp.<anonymous>')

    gcc-4.4.4 has issues with anonymous union initializers.  Work around this.

    Cc: Saeed Mahameed <saeedm@mellanox.com>
    Cc: Tariq Toukan <tariqt@mellanox.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456694

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>