[net] flow_dissector: Don't use bit fields.
Message-id: <973805293da3e1313d8505ad2844d0b13f607a27.1488930759.git.jtoppins@redhat.com>
Patchwork-id: 172758
O-Subject: [PATCH RHEL7.4 net 64/91] flow_dissector: Don't use bit fields.
Bugzilla: 1428557
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Just have a flags member instead.

   In file included from include/linux/linkage.h:4:0,
                    from include/linux/kernel.h:6,
                    from net/core/flow_dissector.c:1:
   In function 'flow_keys_hash_start',
       inlined from 'flow_hash_from_keys' at net/core/flow_dissector.c:553:34:
>> include/linux/compiler.h:447:38: error: call to '__compiletime_assert_459' declared with attribute error: BUILD_BUG_ON failed: FLOW_KEYS_HASH_OFFSET % sizeof(u32)

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 4b36993d3df0834eff3b4172962de0343a4d9123)
Bugzilla: 1428557
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12706028
Tested: compile tested

Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>