[iommu] intel-iommu: fix off-by-one in pagetable freeing
Message-id: <20140115023039.3637.17872.stgit@amt.stowe>
Patchwork-id: 74226
O-Subject: [RHEL7 PATCH] intel-iommu: fix off-by-one in pagetable freeing
Bugzilla: 1048955
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1048955
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=6872825
Upstream Status: Accepted by akpm, in linux-next awaiting 3.14
                 f81afd4d324c6cff7846dce5887ca09ddac29136 (linux-next)
Testing: Testing was done upstream and this is a simple one line
off-by-one fix.  As a precaution I did install and run on
hp-dl360gen8-01.rhts.eng.bos.redhat.com to assure there were no
regressions that would inhibit booting (or any obvious errors from
'dmesg').

commit f81afd4d324c6cff7846dce5887ca09ddac29136
Author: Alex Williamson <alex.williamson@redhat.com>
Date:   Fri Jan 10 01:40:45 2014

intel-iommu: fix off-by-one in pagetable freeing

dma_pte_free_level() has an off-by-one error when checking whether a pte
is completely covered by a range. Take for example the case of attempting
to free pfn 0x0 - 0x1ff, ie. 512 entries covering the first 2M superpage.
The level_size() is 0x200 and we test:

static void dma_pte_free_level(...
	...

	if (!(0 > 0 || 0x1ff < 0 + 0x200)) {
		...
	}

Clearly the 2nd test is true, which means we fail to take the branch to
clear and free the pagetable entry. As a result, we're leaking pagetables
and failing to install new pages over the range.

This was found with a PCI device assigned to a QEMU guest using vfio-pci
without a VGA device present. The first 1M of guest address space is
mapped with various combinations of 4K pages, but eventually the range is
entirely freed and replaced with a 2M contiguous mapping. intel-iommu
errors out with something like:

ERROR: DMA PTE for vPFN 0x0 already set (to 5c2b8003 not 849c00083)

In this case 5c2b8003 is the pointer to the previous leaf page that was
neither freed nor cleared and 849c00083 is the superpage entry that we're
trying to replace it with.

Signed-off-by: Alex Williamson <alex.williamson@redhat.com>
Cc: David Woodhouse <dwmw2@infradead.org>
Cc: Joerg Roedel <joro@8bytes.org>
Cc: <stable@vger.kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Jarod Wilson <jarod@redhat.com>