[net] netfilter: Fix build errors with xt_socket.c
Message-id: <20130913150858.21178.49142.stgit@dragon>
Patchwork-id: 67181
O-Subject: [RHEL7 net PATCH 11/40] netfilter: Fix build errors with xt_socket.c
Bugzilla: 1007439
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Amerigo Wang <amwang@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1007439

Backport of upstream commit: 1a5bbfc3d6b700178b75743a2ba1fd2e58a8f36f

 commit 1a5bbfc3d6b700178b75743a2ba1fd2e58a8f36f
 Author: David S. Miller <davem@davemloft.net>
 Date:   Thu Sep 5 14:38:03 2013 -0400

    netfilter: Fix build errors with xt_socket.c

    As reported by Randy Dunlap:

    ====================
    when CONFIG_IPV6=m
    and CONFIG_NETFILTER_XT_MATCH_SOCKET=y:

    net/built-in.o: In function `socket_mt6_v1_v2':
    xt_socket.c:(.text+0x51b55): undefined reference to `udp6_lib_lookup'
    net/built-in.o: In function `socket_mt_init':
    xt_socket.c:(.init.text+0x1ef8): undefined reference to `nf_defrag_ipv6_enable'
    ====================

    Like several other modules under net/netfilter/ we have to
    have a dependency "IPV6 disabled or set compatibly with this
    module" clause.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jesper Dangaard Brouer <brouer@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>