[char] tpm: select ANON_INODES for proxy driver
Message-id: <20170302161601.26456-45-jsnitsel@redhat.com>
Patchwork-id: 169232
O-Subject: [RHEL7.4 PATCH BZ1383554 44/80] tpm: select ANON_INODES for proxy driver
Bugzilla: 1383554
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1383554,1384800
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12570603
Testing: https://beaker.engineering.redhat.com/jobs/1721553

Upstream commit: a6885a53a3a2a61bf8f799712dc7a20fd2740adf
Original Author: Arnd Bergmann <arnd@arndb.de>
Commit Date:   Thu Apr 28 12:46:13 2016 +0200

The newly added vtpmx driver fails to build if CONFIG_ANON_INODES
is disabled:

drivers/char/built-in.o: In function `vtpmx_fops_ioctl':
(.text+0x97f8): undefined reference to `anon_inode_getfile'

This adds a Kconfig 'select' statement to ensure it's always there
when we need it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 794c38e01358 ("tpm: Proxy driver for supporting multiple emulated TPMs")
Acked-by: Stefan Berger <stefanb@linux.vnet.ibm.com>
Acked-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>

(imported from commit a6885a53a3a2a61bf8f799712dc7a20fd2740adf)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>