[redhat] spec: Update binutils version to 2.25
Message-id: <1488815482-17354-1-git-send-email-prarit@redhat.com>
Patchwork-id: 170921
O-Subject: [RHEL7.4 PATCH BZ 1429005] kernel.spec: Update binutils version to 2.25
Bugzilla: 1429005
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Mike Snitzer <snitzer@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1429005

Build info: see below

When building the latest RHEL tree on RHEL7.0 the build fails with

Pass 2
lib/raid6/recov_avx512.c:387:2: error: #warning "your version of binutils
lacks AVX512 support" [-Werror=cpp]
 #warning "your version of binutils lacks AVX512 support"
  ^
RHEL7.3 and future kernels will only build with version 2.25 because of
the requirement for AVX-512 instructions in binutils.

As expected, failed task when built with rhel-7.0-test

https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12692950

and successful task when built with rhel-7.3-test-pesign

https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12692757

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Cc: msnitzer@redhat.com
Cc: aquini@redhat.com
Signed-off-by: Rafael Aquini <aquini@redhat.com>