[tools] perf tools: Fix test build error when bindir contains double slash
Message-id: <1455060817-26852-357-git-send-email-jolsa@redhat.com>
Patchwork-id: 134146
O-Subject: [PATCH RHEL7.3 BZ1305882 356/360] perf tools: Fix test build error when bindir contains double slash
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 0927beeca5f9d1a7978f8da9c9d28647859816d3
Author: Pawel Moll <pawel.moll@arm.com>
Date: Tue Jul 28 15:10:13 2015 +0100

description
===========
When building with a prefix ending with a slash, for example:

	$ make prefix=/usr/local/

one of the perf tests fail to compile due to BUILD_STR macro mishandling
bindir_SQ string containing with two slashes:

	-DBINDIR="BUILD_STR(/usr/local//bin)"

with the following error:

	  CC       tests/attr.o
	tests/attr.c: In function test__attr:
	tests/attr.c:168:50: error: expected ) before ; token
	  snprintf(path_perf, PATH_MAX, "%s/perf", BINDIR);
                                                  ^
	tests/attr.c:176:1: error: expected ; before } token
	 }
	 ^
	tests/attr.c:176:1: error: control reaches end of non-void function [-Werror=return-type]
	 }
	 ^
	cc1: all warnings being treated as errors

This patch works around the problem by "cleaning" the bindir string
using make's abspath function.

Signed-off-by: Rafael Aquini <aquini@redhat.com>