[tools] perf/bench: Fix two warnings
Message-id: <1408462094-14194-235-git-send-email-jolsa@redhat.com>
Patchwork-id: 88199
O-Subject: [PATCH RHEL7.1 BZ1131394 234/325] perf bench: Fix two warnings
Bugzilla: 1131394
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1131394
https://bugzilla.redhat.com/show_bug.cgi?id=1131394

upstream
========
commit 32bf5bd181026fc99c0e15045abe409167285ba8
Author: Wei Yang <weiyang@linux.vnet.ibm.com>
Date: Sun Sep 22 16:49:24 2013 +0800

RHEL7
=====
Missing 2nd hunk, because it conflicts with patch:
  2100f778d44b perf tools: Fix bench/numa.c for 32-bit build
upstream solved this by Merge commit:
  2a3ede8cb2dd Merge branch 'perf/urgent' into perf/core to fix conflicts

description
===========
There are two warnings in bench/numa, when building this on 32-bit
machine.

The warning output is attached:

bench/numa.c:1113:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
bench/numa.c:1161:6: error: format '%lx' expects argument of t'long unsigned int', but argument 5 has type 'u64' [-Werror=format]

This patch fixes these two warnings.

Signed-off-by: Jarod Wilson <jarod@redhat.com>