[tools] cpupower: Fix build error in cpufreq-info
Message-id: <1457712232-4159-24-git-send-email-prarit@redhat.com>
Patchwork-id: 138339
O-Subject: [RHEL7.3 PATCH BZ 1316657 23/23] cpupower: Fix build error in cpufreq-info
Bugzilla: 1316657
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1316657

commit 38cb76a307821f76c7f9dff7449f73aeb014d5cc
Author: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
Date:   Mon Jan 18 20:44:43 2016 +0530

    cpupower: Fix build error in cpufreq-info

    Fix the following build error by including limits.h -

    utils/cpufreq-info.c: In function get_latency:
    utils/cpufreq-info.c:437:29: error: UINT_MAX undeclared (first use in
    this function)
      if (!latency || latency == UINT_MAX) {
                                 ^
    Signed-off-by: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
    Fixes: e98f033f94f3 (cpupower: fix how "cpupower frequency-info" interprets latency)
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Cc: Jacob Tanenbaum <jtanenba@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>