[fs] autofs: move inclusion of linux/limits.h to uapi
Message-id: <148877486054.7079.15130038657529007003.stgit@pluto.themaw.net>
Patchwork-id: 170769
O-Subject: [RHEL 7.4 BZ1413523 PATCH 55/66] autofs: move inclusion of linux/limits.h to uapi
Bugzilla: 1413523
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>

From: Tomohiro Kusumi <kusumi.tomohiro@gmail.com>

Buzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1413523
Upstream commit: linux.git f58b3c91f6
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=1247935

linux/limits.h should be included by uapi instead of linux/auto_fs.h
so as not to cause compile error in userspace.

 # cat << EOF > ./test1.c
 > #include <stdio.h>
 > #include <linux/auto_fs.h>
 > int main(void) {
 >     return 0;
 > }
 > EOF
 # gcc -Wall -g ./test1.c
 In file included from ./test1.c:2:0:
 /usr/include/linux/auto_fs.h:54:12: error: 'NAME_MAX' undeclared here (not in a function)
   char name[NAME_MAX+1];
             ^

Link: http://lkml.kernel.org/r/20160812024856.12352.24092.stgit@pluto.themaw.net
Signed-off-by: Tomohiro Kusumi <kusumi.tomohiro@gmail.com>
Signed-off-by: Ian Kent <ikent@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Rafael Aquini <aquini@redhat.com>