[scsi] qla2xxx: avoid unused-function warning
Message-id: <20171001042601.7988-8-hmadhani@redhat.com>
Patchwork-id: 187284
O-Subject: [RHEL 7.5 e-stor PATCH 07/23] scsi: qla2xxx: avoid unused-function warning
Bugzilla: 1316281
RH-Acked-by: Chris Leech <cleech@redhat.com>
RH-Acked-by: Ewan Milne <emilne@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

commit bcda771b2f7e4f2a7577eef62ddeb61394e03b69

When NVMe support is disabled, we get a couple of harmless warnings:

drivers/scsi/qla2xxx/qla_nvme.c:667:13: error: 'qla_nvme_unregister_remote_port' defined but not used [-Werror=unused-function]
drivers/scsi/qla2xxx/qla_nvme.c:634:13: error: 'qla_nvme_abort_all' defined but not used [-Werror=unused-function]
drivers/scsi/qla2xxx/qla_nvme.c:604:12: error: 'qla_nvme_wait_on_rport_del' defined but not used [-Werror=unused-function]

This replaces the preprocessor checks in the code with equivalent
compiler conditionals, which lets gcc drop the unused functions without
warning, and is nicer to read.

Fixes: e84067d74301 ("scsi: qla2xxx: Add FC-NVMe F/W initialization and transport registration")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Himanshu Madhani <himanshu.madhani@cavium.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked commit bcda771b2f7e4f2a7577eef62ddeb61394e03b69)

Signed-off-by: Rafael Aquini <aquini@redhat.com>

Conflicts:
	drivers/scsi/qla2xxx/Kconfig

[ hmadhani: Kconfig uses depends in upstream for SCSI_FC_ATTR while ]
[ RH source uses select for SCSI_FC_ATTR	]