[perf] probe: Warn if given uprobe event accesses memory on older kernel
Message-id: <1431774138-14330-158-git-send-email-jolsa@redhat.com>
Patchwork-id: 112378
O-Subject: [PATCH RHEL7.2 BZ1222189 157/327] perf probe: Warn if given uprobe event accesses memory on older kernel
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 79702f614187f652a814061e8f5875ddcc9e732d
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Sat Feb 28 11:53:29 2015 +0900

description
===========
Warn if given uprobe event accesses memory on older kernel.

Until 3.14, uprobe event only supports accessing registers so this warns
to upgrade kernel if uprobe-event returns -EINVAL and an argument of the
event accesses memory ($stack, @+offset, and +|-offs() symtax).

With this patch (on 3.10.0-123.13.2.el7.x86_64);
  -----
  # ./perf probe -x ./perf warn_uprobe_event_compat stack=-0\(%sp\)
  Added new event:
  Failed to write event: Invalid argument
  Please upgrade your kernel to at least 3.14 to have access to feature -0(%sp)
    Error: Failed to add events.
  -----

Signed-off-by: Rafael Aquini <aquini@redhat.com>