[sound] alsa: pcm: use "do {} while (0)" for empty macro
Message-id: <1507829954160572-12-patchset-jkysela@redhat.com>
Patchwork-id: 191920
O-Subject: [RHEL 7.5 PATCH v2 0011/1088] ALSA: pcm: use "do {} while (0)" for empty macro
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Recent compilers produce a harmless warning for the new pcm_call_notify()
macro when CONFIG_SND_PCM_OSS is disabled:

sound/core/pcm.c: In function 'snd_pcm_free':
sound/core/pcm.c:905:37: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]

This turns the empty macro into a 'do {} while (0)' statement to avoid
the warning.

Fixes: 58f30d650c7f ("ALSA: pcm: Build pcm notifier code conditionally")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 9aee03f39c13fc674f5973baa69d13e32b45b535)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>