[tools] perf jitdump: Add the right header to get the major()/minor() definitions
Message-id: <1477399629-8377-314-git-send-email-jolsa@redhat.com>
Patchwork-id: 159583
O-Subject: [PATCH RHEL7.4 BZ1387909 313/322] perf jitdump: Add the right header to get the major()/minor() definitions
Bugzilla: 1387909
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1387909
https://bugzilla.redhat.com/show_bug.cgi?id=1387909

upstream
========
commit 49a7f01064a94c4fd6afb6b4f7e3ccc37d0edf99
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Sat Aug 13 01:12:10 2016 -0300

description
===========
Noticed on Fedora Rawhide:

  $ gcc --version
  gcc (GCC) 6.1.1 20160721 (Red Hat 6.1.1-4)
  $ rpm -q glibc
  glibc-2.24.90-1.fc26.x86_64
  $

    CC       /tmp/build/perf/util/jitdump.o
  util/jitdump.c: In function 'jit_repipe_code_load':
  util/jitdump.c:428:2: error: '__major_from_sys_types' is deprecated:
    In the GNU C Library, `major' is defined by <sys/sysmacros.h>.
    For historical compatibility, it is currently defined by
    <sys/types.h> as well, but we plan to remove this soon.
    To use `major', include <sys/sysmacros.h> directly.
    If you did not intend to use a system-defined macro `major',
    you should #undef it after including <sys/types.h>.
    [-Werror=deprecated-declarations]
    event->mmap2.maj   = major(st.st_dev);
    ^~~~~
  In file included from /usr/include/features.h:397:0,
                   from /usr/include/sys/types.h:25,
                   from util/jitdump.c:1:
  /usr/include/sys/sysmacros.h:87:1: note: declared here
   __SYSMACROS_DEFINE_MAJOR (__SYSMACROS_FST_IMPL_TEMPL)

Fix it following that recomendation.

Signed-off-by: Rafael Aquini <aquini@redhat.com>