[netdrv] sfc: avoid -Wtype-limits warning
Message-id: <1472513700-9618-21-git-send-email-jarod@redhat.com>
Patchwork-id: 157429
O-Subject: [RHEL7 PATCH 21/32] net: sfc: avoid -Wtype-limits warning
Bugzilla: 1368201
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1368201

commit 17471c7ba5115ed724d624577b21c166d2194272
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jun 15 22:31:10 2016 +0200

    net: sfc: avoid -Wtype-limits warning

    When building with -Wextra, we get a harmless warning from the
    EFX_EXTRACT_OWORD32 macro:

    ethernet/sfc/farch.c: In function 'efx_farch_test_registers':
    ethernet/sfc/farch.c:119:30: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
    ethernet/sfc/farch.c:124:144: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
    ethernet/sfc/farch.c:124:392: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
    ethernet/sfc/farch.c:124:731: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]

    The macro and the caller are both correct, but we can avoid the
    warning by changing the index variable to a signed type.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Bert Kenward <bkenward@solarflare.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>