[include] usb: phy: add static inline wrapper for devm_usb_get_phy_by_node
Message-id: <1462578743-3088-36-git-send-email-torez@redhat.com>
Patchwork-id: 143270
O-Subject: [RHEL7 PATCH BZ1303955 035/364] usb: phy: add static inline wrapper for devm_usb_get_phy_by_node
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 307c858bc245da5229b30186546590e1d472fc8f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 28 16:08:02 2015 +0200

    usb: phy: add static inline wrapper for devm_usb_get_phy_by_node

    The newly introduced devm_usb_get_phy_by_node function only has
    an extern declaration, but no alternative for the case that
    CONFIG_USB_PHY is disabled, which leads to a build error when
    it is used anyway:

    drivers/power/twl4030_charger.c: In function 'twl4030_bci_probe':
    drivers/power/twl4030_charger.c:648:23: error: implicit declaration of function 'devm_usb_get_phy_by_node' [-Werror=implicit-function-declaration]
        bci->transceiver = devm_usb_get_phy_by_node(

    This adds the wrapper in the same way that we have one for
    all other usb-phy API functions.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: e842b84c8e7 ("usb: phy: Add interface to get phy give of device_node.")
    Signed-off-by: Felipe Balbi <balbi@ti.com>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>