[fs] nfs: do not initialise statics to 0
Message-id: <20170310150235.10315-11-steved@redhat.com>
Patchwork-id: 173194
O-Subject: [RHEL7.4 fs PATCH 010/167] nfs: do not initialise statics to 0
Bugzilla: 1349668
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Benjamin Coddington <bcodding@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>

From: Wei Tang <tangwei@cmss.chinamobile.com>

This patch fixes the checkpatch.pl error to nfs4sysctl.c:

ERROR: do not initialise statics to 0

Signed-off-by: Wei Tang <tangwei@cmss.chinamobile.com>
Signed-off-by: Trond Myklebust <trond.myklebust@primarydata.com>
(cherry picked from commit ed476752493bc997f1690516fdc0609ddcbaca82)
Bugzilla: 1349668
Signed-off-by: Rafael Aquini <aquini@redhat.com>