[x86] boot: Fix non-EFI build
Message-id: <1467128659-24486-26-git-send-email-lszubowi@redhat.com>
Patchwork-id: 154177
O-Subject: [RHEL 7.3 BZ 1310154 25/40] x86/boot: Fix non-EFI build
Bugzilla: 1310154
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Matt Fleming <matt.fleming@intel.com>

The kbuild test robot reported the following errors, introduced with
commit 54b52d872680 ("x86/efi: Build our own EFI services pointer
table"),

 arch/x86/boot/compressed/head_32.o: In function `efi32_config':
>> (.data+0x58): undefined reference to `efi_call_phys'

 arch/x86/boot/compressed/head_64.o: In function `efi64_config':
>> (.data+0x90): undefined reference to `efi_call6'

Wrap the efi*_config structures in #ifdef CONFIG_EFI_STUB so that we
don't make references to EFI functions if they're not compiled in.

Signed-off-by: Matt Fleming <matt.fleming@intel.com>

(cherry picked from commit 3db4cafdfd05717dc939780134e53023a3c1f15f)
For bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1310154
Signed-off-by: Lenny Szubowicz <lszubowi@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>