[infiniband] iser-target: Fix non negative ERR_PTR isert_device_get usage
Message-id: <1465597803-11831-879-git-send-email-ddutile@redhat.com>
Patchwork-id: 151314
O-Subject: [PATCH RHEL-7.3 0878/1003] iser-target: Fix non negative ERR_PTR isert_device_get usage
Bugzilla: 1169955 1259940 1262728 1275187 1275209 1275423 1275425 1289615 1291874 1292284 1292872 1296195 1296269 1296338 1296344 1298707 1302166 1310156
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Laurence Oberman <loberman@redhat.com>

From: Nicholas Bellinger <nab@linux-iscsi.org>

As reported by Dan, isert_create_device_ib_res() failure within
isert_device_get() can potentially return a postive value,
resulting in ERR_PTR() triggering a NULL pointer dereference.

Caught by the static checker:

     drivers/infiniband/ulp/isert/ib_isert.c:423 isert_device_get()
     error: passing non negative 1 to ERR_PTR

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Cc: Sagi Grimberg <sagig@mellanox.com>
Signed-off-by: Nicholas Bellinger <nab@linux-iscsi.org>
(cherry picked from commit 373a4cd7378220d3c5a69fd369b1d78fee3207b2)
Signed-off-by: Rafael Aquini <aquini@redhat.com>

Conflicts:
	drivers/infiniband/ulp/isert/ib_isert.c
Part of commit/patch hunk already in RHEL7.

Signed-off-by: Donald Dutile <ddutile@redhat.com>