[usb] usb-misc: sisusbvga: fix coding style: braces, parenthesis, comment
Message-id: <1465525749-9195-16-git-send-email-torez@redhat.com>
Patchwork-id: 150020
O-Subject: [RHEL7 BZ1332712 v2 015/196] usb-misc: sisusbvga: Fix coding style: braces, parenthesis, comment
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit f996c49d4fa4e8e33955eb59691e1b116b3d733b
Author: Peter Senna Tschudin <peter.senna@gmail.com>
Date:   Fri Jan 15 18:41:30 2016 +0100

    usb-misc: sisusbvga: Fix coding style: braces, parenthesis, comment

    The file drivers/usb/misc/sisusbvga/sisusb.c contained coding style
    issues reported by checkpatch. This patch fixes the following
    errors:
     - 12 WARNING: braces {} are not necessary for single statement blocks
     - 04 ERROR: return is not a function, parentheses are not required
     - 03 ERROR: do not initialise statics to 0
     - 1 WARNING: else is not generally useful after a break or return
     - 1 WARNING: braces {} are not necessary for any arm of this statement
     - 1 WARNING: Block comments use * on subsequent lines

    One case in which braces are not necessary is left unchanged as other
    patch of the series will fix it.

    Signed-off-by: Peter Senna Tschudin <peter.senna@collabora.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>