[tools] include: Fix strict-aliasing rules breakage
Message-id: <1456127829-13546-174-git-send-email-jolsa@redhat.com>
Patchwork-id: 135500
O-Subject: [PATCH BZ1308570 173/260] tools include: Fix strict-aliasing rules breakage
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit c95f3432118c6b7a3bde63aa6eb95ccd163119eb
Author: Jiri Olsa <jolsa@redhat.com>
Date: Tue Oct 13 10:52:14 2015 +0200

description
===========
Vinson reported build breakage with gcc 4.4 due to strict-aliasing.

   CC       util/annotate.o
 cc1: warnings being treated as errors
 util/annotate.c: In function disasm__purge:
 linux-next/tools/include/linux/compiler.h:66: error: dereferencing
 pointer res.41 does break strict-aliasing rules

The reason is READ_ONCE/WRITE_ONCE code we took from kernel sources.  They
intentionaly break aliasing rules. While this is ok for kernel because it's
built with -fno-strict-aliasing, it breaks perf which is build with
-Wstrict-aliasing=3.

Using extra __may_alias__ type to allow aliasing in this case.

Signed-off-by: Rafael Aquini <aquini@redhat.com>