[tools] Suppress request for warning options not existent in clang
Message-id: <20170807084247.7531-55-jolsa@redhat.com>
Patchwork-id: 181994
O-Subject: [PATCH RHEL7.5 54/94] tools: Suppress request for warning options not existent in clang
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 093b75ef5995ea35d7f6bdb6c7b32a42a1999813
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 10:34:35 2017 -0300

description
===========
To allow building with clang, avoiding:

  error: unknown warning option '-Wstrict-aliasing=3'; did you mean '-Wstring-plus-int'? [-Werror,-Wunknown-warning-option]

Signed-off-by: Rafael Aquini <aquini@redhat.com>