[iommu] provide of_xlate pointer unconditionally
Message-id: <20171009173625.17916-115-jsnitsel@redhat.com>
Patchwork-id: 190772
O-Subject: [RHEL7.5 PATCH 114/196] iommu: provide of_xlate pointer unconditionally
Bugzilla: 1411581
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Suravee Suthikulpanit <ssuthiku@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1411581

commit b70bb984489363aadd5ccc94d919629d9e264d36
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Mar 15 22:37:17 2016 +0100

    iommu: provide of_xlate pointer unconditionally

    iommu drivers that support the standard DT bindings use a of_xlate
    callback pointer, but that is only part of struct iommu_ops when
    CONFIG_OF_IOMMU is enabled, leading to build errors in randconfig
    builds when that is not provided:

    drivers/iommu/mtk_iommu.c:497:2: error: unknown field 'of_xlate' specified in initializer
      .of_xlate = mtk_iommu_of_xlate,
      ^
    drivers/iommu/mtk_iommu.c:497:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
      .of_xlate = mtk_iommu_of_xlate,
                  ^~~~~~~~~~~~~~~~~~
    drivers/iommu/mtk_iommu.c:497:14: note: (near initialization for 'mtk_iommu_ops.domain_get_attr')

    We can work around it by adding more #ifdefs in each driver, but
    it seems nicer to just allow setting the pointer even if it is
    unused. This makes the driver code look nicer, and it gives better
    compile-time coverage when test building on other architectures.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 0df4fabe208d ("iommu/mediatek: Add mt8173 IOMMU driver")
    Reviewed-by: Robin Murphy <robin.murphy@arm.com>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

Cc: Suravee Suthikulpanit <ssuthiku@redhat.com>
Cc: Myron Stowe <myron.stowe@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>