[fs] xfs: fix sparse inodes 32-bit compile failure
Message-id: <1456162346-7841-23-git-send-email-bfoster@redhat.com>
Patchwork-id: 135568
O-Subject: [RHEL7 PATCH 022/128] xfs: fix sparse inodes 32-bit compile failure
Bugzilla: 1298684
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

commit 3cdaa1898ff3b16f69619cb5df2f45158e104817
Author: Brian Foster <bfoster@redhat.com>
Date:   Thu Jun 4 13:03:34 2015 +1000

    xfs: fix sparse inodes 32-bit compile failure

    The kbuild test robot reports the following compilation failure with a
    32-bit kernel configuration:

    	fs/built-in.o: In function `xfs_ifree_cluster':
    	>> xfs_inode.c:(.text+0x17ac84): undefined reference to `__umoddi3'

    This is due to the use of the modulus operator on a 64-bit variable in
    the ASSERT() added as part of the following commit:

    	xfs: skip unallocated regions of inode chunks in xfs_ifree_cluster()

    This ASSERT() simply checks that the offset of the inode in a sparse
    cluster is appropriately aligned. Since the maximum inode record offset
    is 63 (for a 64 inode record) and the calculated offset here should be
    something less than that, just use a 32-bit variable to store the offset
    and call the do_mod() helper.

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Brian Foster <bfoster@redhat.com>
    Reviewed-by: Dave Chinner <dchinner@redhat.com>
    Signed-off-by: Dave Chinner <david@fromorbit.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>