[netdrv] ixgbe: use msleep for long delays
Message-id: <12f5f7d3b4093eaf21c73eba2c04b5b1603e7b6b.1464282996.git.jkc@redhat.com>
Patchwork-id: 147988
O-Subject: [RHEL7.3 BZ 1274174 152/161] ixgbe: use msleep for long delays
Bugzilla: 1274174
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1274174

commit d4f90d9dca26efef7a1112a8f4258c90b73bb37f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sat Apr 16 22:35:08 2016 +0200

    ixgbe: use msleep for long delays

    The newly added x550em_a support causes a link failure on ARM because of
    an overly long time passed into udelay():

    ERROR: "__bad_udelay" [drivers/net/ethernet/intel/ixgbe/ixgbe.ko] undefined!

    There are multiple variants of the ixgbe_acquire_swfw_sync_*() function,
    and the other ones all use msleep(), so we can safely assume that all
    callers are allowed to sleep, which makes msleep() a better replacement
    than mdelay().

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 49425dfc7451 ("ixgbe: Add support for x550em_a 10G MAC type")
    Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
    Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>

Signed-off-by: Ken Cox <jkc@redhat.com>

Cc: Ken Cox <jkc@redhat.com>
Cc: John Greene <jogreene@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>