[usb] phy: fix build breakage
Message-id: <1381413926-15908-521-git-send-email-vfalico@redhat.com>
Patchwork-id: 69231
O-Subject: [RHEL7 PATCH 520/820] usb: phy: fix build breakage
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 52d5b9aba1f5790ca3231c262979c2c3e26dd99b
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=52d5b9aba1f5790ca3231c262979c2c3e26dd99b
Stable: 2356788f31dee0b3c03b3ef594fd113a861b29c1
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=2356788f31dee0b3c03b3ef594fd113a861b29c1

Description
----------------------------
Backport from linux-3.10.y stable.

From: Anatolij Gustschin <agust@denx.de>
Subject: usb: phy: fix build breakage

commit 52d5b9aba1f5790ca3231c262979c2c3e26dd99b upstream.

Commit 94ae9843 (usb: phy: rename all phy drivers to phy-$name-usb.c)
renamed drivers/usb/phy/otg_fsm.h to drivers/usb/phy/phy-fsm-usb.h
but changed drivers/usb/phy/phy-fsm-usb.c to include not existing
"phy-otg-fsm.h" instead of new "phy-fsm-usb.h". This breaks building:
  ...
  drivers/usb/phy/phy-fsm-usb.c:32:25: fatal error: phy-otg-fsm.h: No such file or directory
  compilation terminated.
  make[3]: *** [drivers/usb/phy/phy-fsm-usb.o] Error 1

This commit also missed to modify drivers/usb/phy/phy-fsl-usb.h
to include new "phy-fsm-usb.h" instead of "otg_fsm.h" resulting
in another build breakage:
  ...
  In file included from drivers/usb/phy/phy-fsl-usb.c:46:0:
  drivers/usb/phy/phy-fsl-usb.h:18:21: fatal error: otg_fsm.h: No such file or directory
  compilation terminated.
  make[3]: *** [drivers/usb/phy/phy-fsl-usb.o] Error 1

Fix both issues.

Signed-off-by: Anatolij Gustschin <agust@denx.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 2356788f31dee0b3c03b3ef594fd113a861b29c1)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>