[netdrv] qed: avoid possible stack overflow in qed_ll2_acquire_connection
Message-id: <1488853076-16738-303-git-send-email-ddutile@redhat.com>
Patchwork-id: 171977
O-Subject: [PATCH RHEL-7.4 302/340] qed: avoid possible stack overflow in qed_ll2_acquire_connection
Bugzilla: 1275823 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1275823

commit 0629a330cf55454962168dd3ee46fad53a39323e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 18 15:52:52 2017 +0100

    qed: avoid possible stack overflow in qed_ll2_acquire_connection

    struct qed_ll2_info is rather large, so putting it on the stack
    can cause an overflow, as this warning tries to tell us:

    drivers/net/ethernet/qlogic/qed/qed_ll2.c: In function 'qed_ll2_start':
    drivers/net/ethernet/qlogic/qed/qed_ll2.c:2159:1: error: the frame size of 1056 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    qed_ll2_start_ooo() already uses a dynamic allocation for the structure
    to work around that problem, and we could do the same in qed_ll2_start()
    as well as qed_roce_ll2_start(), but since the structure is only
    used to pass a couple of initialization values here, it seems nicer
    to replace it with a different structure.

    Lacking any idea for better naming, I'm adding 'struct qed_ll2_conn',
    which now contains all the initialization data, and this now simply
    gets copied into struct qed_ll2_info rather than assigning all members
    one by one.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Yuval Mintz <Yuval.Mintz@cavium.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>