[netdrv] qede: hide 32-bit compile warning
Message-id: <1488583261-20374-75-git-send-email-hpatil@redhat.com>
Patchwork-id: 170250
O-Subject: [PATCH RHEL7.4 v2 074/154] qede: hide 32-bit compile warning
Bugzilla: 1391272
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ 1391272

upstream commit id 84fd1b191a9468dbb2e790fbc394378afc43462e

The addition of the per-queue statistics introduced a harmless warning
on all 32-bit architectures:

drivers/net/ethernet/qlogic/qede/qede_ethtool.c: In function 'qede_get_ethtool_stats':
drivers/net/ethernet/qlogic/qede/qede_ethtool.c:244:31: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      buf[cnt++] = QEDE_TQSTATS_DATA(edev,
                               ^
drivers/net/ethernet/qlogic/qede/qede_ethtool.c:244:22: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
      buf[cnt++] = QEDE_TQSTATS_DATA(edev,
                      ^
This changes the cast to 'void *' to shut up the warning, which
avoids the assumptions on the size of the pointer type.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 68db9ec2df07 ("qede: Add support for per-queue stats.")
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Rafael Aquini <aquini@redhat.com>