[tools] perf tools: Do not put a variable sized type not at the end of a struct
Message-id: <20170807084247.7531-62-jolsa@redhat.com>
Patchwork-id: 181999
O-Subject: [PATCH RHEL7.5 61/94] perf tools: Do not put a variable sized type not at the end of a struct
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 89896051f8dae5a04ada1f5fbeeaedc23f484f68
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 10:59:04 2017 -0300

description
===========
As this is a GNU extension and while harmless in this case, we can do
the same thing in a more clearer way by using an existing thread_map
constructor.

With this we avoid this while compiling with clang:

  util/parse-events.c:2024:21: error: field 'map' with variable sized type 'struct thread_map' not at the end of a struct or class is a GNU extension
        [-Werror,-Wgnu-variable-sized-type-not-at-end]
                  struct thread_map map;
                                  ^
  1 error generated.

Signed-off-by: Rafael Aquini <aquini@redhat.com>