[fs] libceph: fix old style declaration warnings
Message-id: <1507041730-18373-55-git-send-email-idryomov@redhat.com>
Patchwork-id: 187412
O-Subject: [RHEL7.5 fs PATCH 54/91] libceph: fix old style declaration warnings
Bugzilla: 1489426
RH-Acked-by: Sage Weil <sweil@redhat.com>
RH-Acked-by: Jeff Layton <jlayton@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

The new macros don't follow the usual style for declarations,
which we get a warning for with 'make W=1':

In file included from fs/ceph/mds_client.c:16:0:
include/linux/ceph/ceph_features.h:74:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

This moves the 'static' keyword to the front of the
declaration.

Fixes: f179d3ba8cb9 ("libceph: new features macros")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit e67ae2b7b23b283e657865b498b151e6a17b919d)
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>