[perf] data: Fix sentinel setting for data_cmds array
Message-id: <1431774138-14330-132-git-send-email-jolsa@redhat.com>
Patchwork-id: 112351
O-Subject: [PATCH RHEL7.2 BZ1222189 131/327] perf data: Fix sentinel setting for data_cmds array
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 1f924c29b5ab2257be88a2a4075d0800573d8479
Author: Yunlong Song <yunlong.song@huawei.com>
Date: Fri Feb 27 19:53:46 2015 +0800

description
===========
The recent new patch "perf tools: Add new 'perf data' command" (commit
2245bf14 in acme's git repo perf/core) has caused a building error when
compiling the source code of perf:

 cc1: warnings being treated as errors
 builtin-data.c:89: error: missing initializer
 builtin-data.c:89: error: (near initialization for data_cmds[1].summary)
 make[2]: *** [builtin-data.o] Error 1
 make[2]: *** Waiting for unfinished jobs....
   LD       bench/perf-in.o
   LD       tests/perf-in.o
 make[1]: *** [perf-in.o] Error 2
 make: *** [all] Error 2

This patch fixes the building error above.

[ .name == NULL ends the loop, use it instead of seting all fields to NULL ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>