[net] openvswitch: fix compilation when vxlan is a module
Message-id: <1463509420-12020-77-git-send-email-lrichard@redhat.com>
Patchwork-id: 145402
O-Subject: [RHEL7.3 net PATCH v2 076/232] openvswitch: fix compilation when vxlan is a module
Bugzilla: 1283886
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1283886
Upstream Status: linus commit 2661371ace963280f34fe583d4a6697afecd87d5
Conflicts: \
   - Minor, from previous RHEL backport commit:
     500b6f4ec48d92f0ff9b4b51cf88b31637c664df

commit 2661371ace963280f34fe583d4a6697afecd87d5
Author: Nicolas Dichtel <nicolas.dichtel@6wind.com>
Date:   Thu Jul 23 11:29:07 2015 +0200

    openvswitch: fix compilation when vxlan is a module

    With CONFIG_VXLAN=m and CONFIG_OPENVSWITCH=y, there was the following
    compilation error:
      LD      init/built-in.o
      net/built-in.o: In function `vxlan_tnl_create':
      .../net/openvswitch/vport-netdev.c:322: undefined reference to `vxlan_dev_create'
      make: *** [vmlinux] Error 1

    CC: Thomas Graf <tgraf@suug.ch>
    Fixes: 614732eaa12d ("openvswitch: Use regular VXLAN net_device device")
    Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
    Acked-by: Thomas Graf <tgraf@suug.ch>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Lance Richardson <lrichard@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>