[perf] evlist: Return the first evsel with an invalid filter in apply_filters()
Message-id: <1431774138-14330-262-git-send-email-jolsa@redhat.com>
Patchwork-id: 112482
O-Subject: [PATCH RHEL7.2 BZ1222189 261/327] perf evlist: Return the first evsel with an invalid filter in apply_filters()
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit 23d4aad48e31d3269af484dd2f9bd251278cd667
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Mar 24 19:23:47 2015 -0300

description
===========
Use of a bad filter currently generates the message:
 Error: failed to set filter with 22 (Invalid argument)

Add the event name to make it clear to which event the filter
failed to apply:
  Error: Failed to set filter "foo" on event sched:sg_lb_stats: 22: Invalid argument

To test it use something like:

 # perf record -e sched:sched_switch -e sched:*fork --filter parent_pid==1 -e sched:*wait* --filter bla usleep 1
  Error: failed to set filter "bla" on event sched:sched_stat_iowait with 22 (Invalid argument)
 #

Signed-off-by: Rafael Aquini <aquini@redhat.com>