[fs] libceph: use BUG() instead of BUG_ON(1)
Message-id: <1501080593-8623-15-git-send-email-idryomov@redhat.com>
Patchwork-id: 181250
O-Subject: [RHEL7.5 fs PATCH 112/184] libceph: use BUG() instead of BUG_ON(1)
Bugzilla: 1450262
RH-Acked-by: Sage Weil <sweil@redhat.com>
RH-Acked-by: Jeff Layton <jlayton@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

I ran into this compile warning, which is the result of BUG_ON(1)
not always leading to the compiler treating the code path as
unreachable:

    include/linux/ceph/osdmap.h: In function 'ceph_can_shift_osds':
    include/linux/ceph/osdmap.h:62:1: error: control reaches end of non-void function [-Werror=return-type]

Using BUG() here avoids the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit d24cdcd3e40a6825135498e11c20c7976b9bf545)
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>