[netdrv] liquidio: remove unnecessary variable assignment
Message-id: <20170907193754.GA21425@felix-thinkpad.cavium.com>
Patchwork-id: 184288
O-Subject: [PATCH v2 RHEL7.5 137/202] liquidio: remove unnecessary variable assignment
Bugzilla: 1451436
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1451436

Upstream Status: linux.git

commit ca1cb28da00448fdbddc99ee6d410f461bb619b5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 19 19:30:59 2017 +0200

    liquidio: remove unnecessary variable assignment

    gcc points out an useless assignment that was added during code refactoring:

    drivers/net/ethernet/cavium/liquidio/lio_ethtool.c: In function 'octnet_intrmod_callback':
    drivers/net/ethernet/cavium/liquidio/lio_ethtool.c:1315:59: error: parameter 'oct_dev' set but not used [-Werror=unused-but-set-parameter]

    This is harmless but can clearly be remove to avoid the warning.

    Fixes: 50c0add534d2 ("liquidio: refactor interrupt moderation code")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Felix Manlunas <fmanluna@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>