[virtio] virtio_balloon: include linux/virtio_types.h
Message-id: <1456859431-8482-16-git-send-email-lcapitulino@redhat.com>
Patchwork-id: 136444
O-Subject: [RHEL7.3 PATCH 15/15] include/uapi/linux/virtio_balloon.h: include linux/virtio_types.h
Bugzilla: 1263649
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Michael S. Tsirkin <mst@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>

From: Mikko Rapeli <mikko.rapeli@iki.fi>

Fixes userspace compilation error:

error: unknown type name __virtio16
  __virtio16 tag;

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>

Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
(cherry picked from commit 8a7b19d8b542b87bccc3eaaf81dcc90a5ca48aea)
Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>