[redhat] kernel.spec: fix building with "_without_debug 1"
Message-id: <5d7b7402d27c522eb0756b381f3b93bed73c6344.1364399113.git.jstancek@redhat.com>
Patchwork-id: 57814
O-Subject: [RHEL7 PATCH] [redhat] kernel.spec: fix building with "_without_debug 1"
RH-Acked-by: Josh Boyer <jwboyer@redhat.com>

When building kernel rpms with:
  rpmbuild -bb --define "_without_debug 1" rpmbuild/SPECS/kernel.spec

build fails because 'with_debug' contains extra spaces:
  + /usr/lib/rpm/redhat/brp-python-hardlink
  + /usr/lib/rpm/redhat/brp-java-repack-jars
  + '[' '     0 ' '!=' 0 ']'
  ++ head -1 configs/kernel-3.9.0-x86_64-debug.config
  ++ cut -b 3-
  + Arch=x86_64
  + rm -rf .tmp_versions
  + mv .tmp_versions.sign.debug .tmp_versions
  mv: cannot stat '.tmp_versions.sign.debug': No such file or directory
  error: Bad exit status from /var/tmp/rpm-tmp.qekbH0 (%install)

Since this variable is unlikely to be anything else than int,
change the condition to use "-ne", which does int comparison
and is more forgiving to extra whitespace.

Signed-off-by: Jan Stancek <jstancek@redhat.com>
Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>