[net] bridge: remove unnecessary check for vtbegin in br_fill_vlan_tinfo_range
Message-id: <20171013200423.15136-22-ivecera@redhat.com>
Patchwork-id: 193298
O-Subject: [RHEL7.5 net PATCH 21/57] bridge: remove unnecessary check for vtbegin in br_fill_vlan_tinfo_range
Bugzilla: 1500896
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1500896

Upstream commit(s):
commit a8cab863a75f2d353588d4c3c37dc37c77b96c83
Author: Roopa Prabhu <roopa@cumulusnetworks.com>
Date:   Tue Feb 7 06:43:23 2017 -0800

    bridge: remove unnecessary check for vtbegin in br_fill_vlan_tinfo_range

    vtbegin should not be NULL in this function, Its already checked by the
    caller.

    this should silence the below smatch complaint:
      net/bridge/br_netlink_tunnel.c:144 br_fill_vlan_tinfo_range()
        error: we previously assumed 'vtbegin' could be null (see line 130)

    net/bridge/br_netlink_tunnel.c
       129
       130      if (vtbegin && vtend && (vtend->vid - vtbegin->vid) > 0) {
                        ^^^^^^^
    Check for NULL.

    Fixes: efa5356b0d97 ("bridge: per vlan dst_metadata netlink support")
    Reported-By: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Roopa Prabhu <roopa@cumulusnetworks.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>