[tools] perf unwind: Fix a compile error
Message-id: <1455060817-26852-267-git-send-email-jolsa@redhat.com>
Patchwork-id: 134056
O-Subject: [PATCH RHEL7.3 BZ1305882 266/360] perf unwind: Fix a compile error
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit f005813afb89bae92faf254130c544dc68984c6b
Author: Hou Pengyang <houpengyang@huawei.com>
Date: Tue Jun 16 11:16:35 2015 +0000

description
===========
When libunwind is on, there is a compile error as :

  util/unwind-libunwind.c:363:21: error: 'dso' undeclared (first use in this function)
      dso__data_put_fd(dso);

This patch fixes it.

Fixes: 4bb11d012ab248d0 ("perf tools: Add dso__data_get/put_fd()")
Signed-off-by: Rafael Aquini <aquini@redhat.com>