[tools] objtool: Support CROSS_COMPILE
Message-id: <1605dfc617b8cfb8c50ee34c7eed68b91139f1bf.1464902826.git.jpoimboe@redhat.com>
Patchwork-id: 148908
O-Subject: [RHEL7.3 PATCH 15/64] objtool: Support CROSS_COMPILE
Bugzilla: 1320250
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

commit c1d45c3abd49b5bf9447e435099c1b000dcde752
Author: Josh Poimboeuf <jpoimboe@redhat.com>
Date:   Wed Mar 2 18:39:37 2016 -0600

    objtool: Support CROSS_COMPILE

    When building with CONFIG_STACK_VALIDATION on a ppc64le host with an x86
    cross-compiler, Stephen Rothwell saw the following objtool build errors:

        DESCEND  objtool
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/builtin-check.o
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/special.o
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/elf.o
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/objtool.o
        MKDIR    /home/sfr/next/x86_64_allmodconfig/tools/objtool/arch/x86/insn/
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/libstring.o
      elf.c:22:23: fatal error: sys/types.h: No such file or directory
      compilation terminated.
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/exec-cmd.o
        CC       /home/sfr/next/x86_64_allmodconfig/tools/objtool/help.o
      builtin-check.c:28:20: fatal error: string.h: No such file or directory
      compilation terminated.
      objtool.c:28:19: fatal error: stdio.h: No such file or directory
      compilation terminated.

    It fails to build because it tries to compile objtool with the
    cross-compiler instead of the host compiler.

    Ensure that it always uses the host compiler by ignoring CROSS_COMPILE.

    In order to do that properly, the libsubcmd.a library needs to be built
    in tools/objtool/ rather than tools/lib/subcmd/.  The latter directory
    contains the cross-compiled version which is needed for perf and
    possibly other tools.

    Note that cross-compiling for x86 on a _big_ endian system would result
    in a bunch of false positive objtool warnings during the kernel build
    because it isn't endian-aware.  But that's generally a rare edge case
    and there haven't been any reports of anybody needing that.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
    Cc: Michael Ellerman <mpe@ellerman.id.au>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Link: http://lkml.kernel.org/r/55b63eefc347f1bb28573f972d8d1adbf1f1c31d.1456962210.git.jpoimboe@redhat.com
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>