[net] inet: inet_timewait_sock.h missing semi-colon when KMEMCHECK is enabled
Message-id: <20140219204614.17627.73998.stgit@SandyE>
Patchwork-id: 77080
O-Subject: [RHEL7.0 net PATCH 08/13] netdev: inet_timewait_sock.h missing semi-colon when KMEMCHECK is enabled
Bugzilla: 1059721
RH-Acked-by: Veaceslav Falico <vfalico@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>

Bugzilla: 1059721

Backport of upstream commit: a5bb202b848c7962f942f81d93290a9ccdfb1a0f
 - Fix for previous backport efe4208f47 (ipv6: make lookups simpler and faster)
   a.k.a "TCP listener refactoring, part 4"

 commit a5bb202b848c7962f942f81d93290a9ccdfb1a0f
 Author: Randy Dunlap <rdunlap@infradead.org>
 Date:   Mon Oct 14 12:36:32 2013 -0700

    netdev: inet_timewait_sock.h missing semi-colon when KMEMCHECK is enabled

    Fix (a few hundred) build errors due to missing semi-colon when
    KMEMCHECK is enabled:

      include/net/inet_timewait_sock.h:139:2: error: expected ',', ';' or '}' before 'int'
      include/net/inet_timewait_sock.h:148:28: error: 'const struct inet_timewait_sock' has no member named 'tw_death_node'

    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jesper Dangaard Brouer <brouer@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>