[net] netfilter: bridge: fix nf_tables bridge dependencies with main core
Message-id: <88e98d3254d07e1c7ca970d09e2bfb944488315c.1384351728.git.jbenc@redhat.com>
Patchwork-id: 70819
O-Subject: [RHEL7 net PATCH 1/6] netfilter: bridge: fix nf_tables bridge dependencies with main core
Bugzilla: 1023123
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Daniel Borkmann <dborkman@redhat.com>
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1023123
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=6564482

commit 6e078bc2f2406ccbb986a9922cc80ae8ca7abca3
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Mon Oct 28 00:18:33 2013 +0100

    netfilter: bridge: fix nf_tables bridge dependencies with main core

    when CONFIG_NF_TABLES[_MODULE] is not enabled,
    but CONFIG_NF_TABLES_BRIDGE is enabled:

    net/bridge/netfilter/nf_tables_bridge.c: In function 'nf_tables_bridge_init_net':
    net/bridge/netfilter/nf_tables_bridge.c:24:5: error: 'struct net' has no member named 'nft'
    net/bridge/netfilter/nf_tables_bridge.c:25:9: error: 'struct net' has no member named 'nft'
    net/bridge/netfilter/nf_tables_bridge.c:28:2: error: 'struct net' has no member named 'nft'
    net/bridge/netfilter/nf_tables_bridge.c:30:34: error: 'struct net' has no member named 'nft'
    net/bridge/netfilter/nf_tables_bridge.c:35:11: error: 'struct net' has no member named 'nft'
    net/bridge/netfilter/nf_tables_bridge.c: In function 'nf_tables_bridge_exit_net':
    net/bridge/netfilter/nf_tables_bridge.c:41:27: error: 'struct net' has no member named 'nft'
    net/bridge/netfilter/nf_tables_bridge.c:42:11: error: 'struct net' has no member named 'nft'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>