[netdrv] bnx2x: fix format overflow warning
Message-id: <20171013151213.22245-15-mschmidt@redhat.com>
Patchwork-id: 193061
O-Subject: [RHEL7.5 PATCH 14/17] bnx2x: fix format overflow warning
Bugzilla: 1479145
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1479145

Upstream commit:
commit be9cdf1b97023cf5548bd4f6920bb546272ebabc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 14 14:07:02 2017 +0200

    bnx2x: fix format overflow warning

    gcc notices that large queue numbers would overflow the queue name
    string:

    drivers/net/ethernet/broadcom/bnx2x/bnx2x_ethtool.c: In function 'bnx2x_get_strings':
    drivers/net/ethernet/broadcom/bnx2x/bnx2x_ethtool.c:3165:25: error: '%d' directive writing between 1 and 10 bytes into a region of size 5 [-Werror=format-overflow=]
    drivers/net/ethernet/broadcom/bnx2x/bnx2x_ethtool.c:3165:25: note: directive argument in the range [0, 2147483647]
    drivers/net/ethernet/broadcom/bnx2x/bnx2x_ethtool.c:3165:5: note: 'sprintf' output between 2 and 11 bytes into a destination of size 5

    There is a hard limit in place that makes the number at most two
    digits, so the code is fine. This changes it to use snprintf()
    to truncate instead of overflowing, which shuts up that warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Rafael Aquini <aquini@redhat.com>