[tools] perf probe: Make --line checks validate C-style function name
Message-id: <1455060817-26852-124-git-send-email-jolsa@redhat.com>
Patchwork-id: 133913
O-Subject: [PATCH RHEL7.3 BZ1305882 123/360] perf probe: Make --line checks validate C-style function name
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 573709fdfd668423ba4202c4f1016e3cd7bdd134
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed May 6 21:46:47 2015 +0900

description
===========
Fix --line to check valid C-style function name and returns
a semantic error if it is not.

For example, previously, --line doesn't support lazy pattern
but it doesn't recognized as a semantic error.

  ----
  # perf probe -L 'func;return*:0-10'
  Specified source line is not found.
    Error: Failed to show lines.
  ----

With this patch, it is correctly handled as a semantic error.
  ----
  # perf probe -L 'func;return*:0-10'
  Semantic error :'func;return*' is not a valid function name.
  ...
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>