[usb] add HAS_IOMEM dependency to USB_OHCI_HCD
Message-id: <1465525749-9195-95-git-send-email-torez@redhat.com>
Patchwork-id: 150053
O-Subject: [RHEL7 BZ1332712 v2 094/196] usb: add HAS_IOMEM dependency to USB_OHCI_HCD
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 1043960c982b7478d3f235767632c752370aa95e
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:51 2016 +0100

    usb: add HAS_IOMEM dependency to USB_OHCI_HCD

    drivers/built-in.o: In function `ohci_platform_probe':
    /home/vegard/linux/drivers/usb/host/ohci-platform.c:246: undefined reference to `devm_ioremap_resource'

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>