[net] netfilter: fix xt_TEE and xt_TPROXY dependencies
Message-id: <d8bda2ab474150818c6f26a143c6cad1a48c3392.1465290494.git.pabeni@redhat.com>
Patchwork-id: 149283
O-Subject: [RHEL7.3 net PATCH 123/165] netfilter: fix xt_TEE and xt_TPROXY dependencies
Bugzilla: 1331757
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1331757
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11141575
Tested: nftables test-suite and basic functional tests

Upstream commit:
commit 74ec4d55c4d243330d93fc52e23e37d2e76548ba
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Nov 10 13:22:15 2015 +0100

    netfilter: fix xt_TEE and xt_TPROXY dependencies

    Kconfig is too smart for its own good: a Kconfig line that states

    	select NF_DEFRAG_IPV6 if IP6_NF_IPTABLES

    means that if IP6_NF_IPTABLES is set to 'm', then NF_DEFRAG_IPV6 will
    also be set to 'm', regardless of the state of the symbol from which
    it is selected. When the xt_TEE driver is built-in and nothing else
    forces NF_DEFRAG_IPV6 to be built-in, this causes a link-time error:

    net/built-in.o: In function `tee_tg6':
    net/netfilter/xt_TEE.c:46: undefined reference to `nf_dup_ipv6'

    This works around that behavior by changing the dependency to
    'if IP6_NF_IPTABLES != n', which is interpreted as boolean expression
    rather than a tristate and causes the NF_DEFRAG_IPV6 symbol to
    be built-in as well.

    The bug only occurs once in thousands of 'randconfig' builds and
    does not really impact real users. From inspecting the other
    surrounding Kconfig symbols, I am guessing that NETFILTER_XT_TARGET_TPROXY
    and NETFILTER_XT_MATCH_SOCKET have the same issue. If not, this
    change should still be harmless.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>