[netdrv] qed: add qed_int_sb_init() stub function
Message-id: <20171111045127.10299-96-ddutile@redhat.com>
Patchwork-id: 197662
O-Subject: [PATCH RHEL-7.5 095/251] qed: add qed_int_sb_init() stub function
Bugzilla: 1499363 1462433
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit 2f3ca449a4f9a54d2bf39c873269e68ad5f34acb
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 9 12:37:35 2017 +0200

    qed: add qed_int_sb_init() stub function

    When CONFIG_QED_SRIOV is disabled, we get a build error:

    drivers/net/ethernet/qlogic/qed/qed_int.c: In function 'qed_int_sb_init':
    drivers/net/ethernet/qlogic/qed/qed_int.c:1499:4: error: implicit declaration of function 'qed_vf_set_sb_info'; did you mean 'qed_mcp_get_resc_info'? [-Werror=implicit-function-declaration]

    All the other declarations have a 'static inline' stub as an alternative
    here, so this adds one more for qed_int_sb_init.

    Fixes: 50a207147fce ("qed: Hold a single array for SBs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Yuval Mintz <Yuval.Mintz@cavium.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=14662433

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>