[infiniband] rdma/hfi1: Avoid redeclaration error
Message-id: <20171011200214.23764-26-ddutile@redhat.com>
Patchwork-id: 191362
O-Subject: [PATCH RHEL-7.5 v2 025/233] RDMA/hfi1: Avoid redeclaration error
Bugzilla: 1385309 1385649 1386645 1409099 1456667 1456687
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385309

commit 38e8b671bf04af09fc8de74ea857f920285bd211
Author: Leon Romanovsky <leonro@mellanox.com>
Date:   Sun Sep 4 14:30:32 2016 +0300

    RDMA/hfi1: Avoid redeclaration error

    Move hfi1 ioctl definitions to a new header which can be included by
    both the hfi1 and qib drivers to avoid a duplicate enum definition
    as shown in this build error for qib:

      CC [M] drivers/infiniband/hw/qib/qib_sysfs.o
    In file included from ./include/uapi/rdma/rdma_user_ioctl.h:39:0,
                     from include/uapi/rdma/ib_user_mad.h:38,
                     from include/rdma/ib_mad.h:43,
                     from include/rdma/ib_pma.h:38,
                     from drivers/infiniband/hw/qib/qib_mad.h:37,
                     from drivers/infiniband/hw/qib/qib_init.c:49:
    ./include/uapi/rdma/hfi/hfi1_user.h:370:2: error: redeclaration of
    enumerator ur_rcvhdrtail
      ur_rcvhdrtail = 0,

    Move hfi1 structures to separate file to avoid this failure.

    The actual move of the ioctl definitions comes in a follow on patch.

    Signed-off-by: Matan Barak <matanb@mellanox.com>
    Signed-off-by: Haggai Eran <haggaie@mellanox.com>
    Signed-off-by: Leon Romanovsky <leonro@mellanox.com>
    Reviewed-by: Jason Gunthorpe <jgunthorpe@obsidianresearch.com>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>