[net] sched: cls_flower: reduce fl_change stack size
Message-id: <f90e4447c631f465d3d295a505a3058623ae62d1.1490136269.git.jtoppins@redhat.com>
Patchwork-id: 174985
O-Subject: [RHEL7.4 net v4 53/59] net/sched: cls_flower: reduce fl_change stack size
Bugzilla: 1393375
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

The new ARP support has pushed the stack size over the edge on ARM,
as there are two large objects on the stack in this function (mask
and tb) and both have now grown a bit more:

net/sched/cls_flower.c: In function 'fl_change':
net/sched/cls_flower.c:928:1: error: the frame size of 1072 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

We can solve this by dynamically allocating one or both of them.
I first tried to do it just for the mask, but that only saved
152 bytes on ARM, while this version just does it for the 'tb'
array, bringing the stack size back down to 664 bytes.

Fixes: 99d31326cbe6 ("net/sched: cls_flower: Support matching on ARP")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Jiri Pirko <jiri@mellanox.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 39b7b6a6247568f99df059e8a4c9bd674f6b99ac)
Bugzilla: 1393375
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12825917
Tested: compile tested

Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>