[usb] host: st: fix ehci/ohci driver selection
Message-id: <1457470219-37147-283-git-send-email-dzickus@redhat.com>
Patchwork-id: 137829
O-Subject: [RHEL7 PATCH 282/423] USB: host: st: fix ehci/ohci driver selection
Bugzilla: 1303209
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303209

commit 905e300e1043f5ff513840d342df5c985b3dc08c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 29 14:54:34 2014 +0200

    USB: host: st: fix ehci/ohci driver selection

    The newly added sti ehci and ohci drivers come with a single
    Kconfig entry that does not depend on either of the base drivers,
    which leads to a link error when they are disabled:

    drivers/built-in.o: In function `ohci_platform_init':
    :(.init.text+0x14788): undefined reference to `ohci_init_driver'

    To fix that, this patch introduces two separate Kconfig options
    with proper dependencies, which avoids the problem and is also
    more consistent with the other glue drivers.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: d115837259ada ("usb: host: ohci-st: Add OHCI driver support for ST STB devices")
    Cc: Peter Griffin <peter.griffin@linaro.org>
    Acked-by: Alan Stern <stern@rowland.harvard.edu>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>