[tools] perf probe: Show the error reason comes from invalid DSO
Message-id: <1455060817-26852-207-git-send-email-jolsa@redhat.com>
Patchwork-id: 133996
O-Subject: [PATCH RHEL7.3 BZ1305882 206/360] perf probe: Show the error reason comes from invalid DSO
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 419e87382873b11b17cb31e2f21859570a32e0d1
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed May 27 17:37:18 2015 +0900

description
===========
Show the reason of error when dso__load* fails. This shows when user
gives wrong kernel image or wrong path.

Without this, perf probe shows an obscure message:

  ----
  $ perf probe -k ~/kbin/linux-3.x86_64/vmlinux -L vfs_read
  Failed to find path of kernel module.
    Error: Failed to show lines.
  ----

With this, perf shows appropriate error message:

  ----
  $ perf probe -k ~/kbin/linux-3.x86_64/vmlinux -L vfs_read
  Failed to find the path for kernel: Mismatching build id
    Error: Failed to show lines.
  ----

And:

  ----
  $ perf probe -k /non-exist/kernel/vmlinux -L vfs_read
  Failed to find the path for kernel: No such file or directory
    Error: Failed to show lines.
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>