[net] check net.core.somaxconn sysctl values
Message-id: <1381413926-15908-574-git-send-email-vfalico@redhat.com>
Patchwork-id: 69122
O-Subject: [RHEL7 PATCH 573/820] net: check net.core.somaxconn sysctl values
Bugzilla: 1006938
RH-Acked-by: Vlad Yasevich <vyasevic@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

RHBZ: 1006938
Upstream: 5f671d6b4ec3e6d66c2a868738af2cdea09e7509
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=5f671d6b4ec3e6d66c2a868738af2cdea09e7509
Stable: 4691236cedfb12e2644f4c84b4b14a6882e1fd7b
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=4691236cedfb12e2644f4c84b4b14a6882e1fd7b

Description
----------------------------
Backport from linux-3.10.y stable.

From: Roman Gushchin <klamm@yandex-team.ru>
Subject: net: check net.core.somaxconn sysctl values

[ Upstream commit 5f671d6b4ec3e6d66c2a868738af2cdea09e7509 ]

It's possible to assign an invalid value to the net.core.somaxconn
sysctl variable, because there is no checks at all.

The sk_max_ack_backlog field of the sock structure is defined as
unsigned short. Therefore, the backlog argument in inet_listen()
shouldn't exceed USHRT_MAX. The backlog argument in the listen() syscall
is truncated to the somaxconn value. So, the somaxconn value shouldn't
exceed 65535 (USHRT_MAX).
Also, negative values of somaxconn are meaningless.

before:
$ sysctl -w net.core.somaxconn=256
net.core.somaxconn = 256
$ sysctl -w net.core.somaxconn=65536
net.core.somaxconn = 65536
$ sysctl -w net.core.somaxconn=-100
net.core.somaxconn = -100

after:
$ sysctl -w net.core.somaxconn=256
net.core.somaxconn = 256
$ sysctl -w net.core.somaxconn=65536
error: "Invalid argument" setting key "net.core.somaxconn"
$ sysctl -w net.core.somaxconn=-100
error: "Invalid argument" setting key "net.core.somaxconn"

Based on a prior patch from Changli Gao.

Signed-off-by: Roman Gushchin <klamm@yandex-team.ru>
Reported-by: Changli Gao <xiaosuo@gmail.com>
Suggested-by: Eric Dumazet <edumazet@google.com>
Acked-by: Eric Dumazet <edumazet@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 4691236cedfb12e2644f4c84b4b14a6882e1fd7b)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>