[infiniband] ocrdma: Fix compiler warning
Message-id: <1392903233-3268-7-git-send-email-prarit@redhat.com>
Patchwork-id: 77117
O-Subject: [RHEL7.0 PATCH BZ 1006333 6/9] infiniband, ocrdma, Fix compiler warning
Bugzilla: 1006333
RH-Acked-by: Doug Ledford <dledford@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1006333

Sent upstream here: http://marc.info/?l=linux-rdma&m=139284033730371&w=2

drivers/infiniband/hw/ocrdma/ocrdma_verbs.c: In function '_ocrdma_modify_qp':
drivers/infiniband/hw/ocrdma/ocrdma_verbs.c:1299:31: error: 'old_qps' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  status = ocrdma_mbx_modify_qp(dev, qp, attr, attr_mask, old_qps);

ocrdma_mbx_modify_qp() (and subsequent calls) doesn't appear to use old_qps
so it doesn't need to be passed on.  Removing the variable results in the
warning going away.

Signed-off-by: Prarit Bhargava <prarit@redhat.com>

Cc: Doug Ledford <dledford@redhat.com>
Cc: Jay Fenlason <fenlason@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>