[powerpc] make lorax work again
Message-id: <20131030194111.41406.75400.sendpatchset@ibm-p7r2-01.lab.bos.redhat.com>
Patchwork-id: 69960
O-Subject: [PATCH RHEL7.0 BZ1022797] powerpc: make lorax work again
Bugzilla: 1022797

RHBZ#:
------
https://bugzilla.redhat.com/show_bug.cgi?id=1022797

Description:
------------
This patch fixes a bug introduced by commit 0c9fa29149d3726e14262aeb0c8461a948cc9d56
(powerpc/zImage: make the "OF" wrapper support ePAPR boot).

This is a compose blocker.

populating output tree and building boot images
2013-10-23 15:22:29,650: running ppc.tmpl
running ppc.tmpl
/var/tmp/lorax.srpHp5/installroot/usr/lib64/kernel-wrapper/of.o: In function `platform_init':
/builddir/build/BUILD/kernel-3.10.0-35.el7/linux-3.10.0-35.el7.ppc64/arch/powerpc/boot/of.c:95: undefined reference to `epapr_platform_init'
2013-10-23 15:24:05,352: template command error in ppc.tmpl:
template command error in ppc.tmpl:
2013-10-23 15:24:05,352:   runcmd /var/tmp/lorax.srpHp5/installroot/usr/sbin/wrapper -p of -D /var/tmp/lorax.srpHp5/installroot/usr/lib64/kernel-wrapper -i /mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/initrd.img /mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/vmlinuz -o /mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/images/netboot/ppc64.img
  runcmd /var/tmp/lorax.srpHp5/installroot/usr/sbin/wrapper -p of -D /var/tmp/lorax.srpHp5/installroot/usr/lib64/kernel-wrapper -i /mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/initrd.img /mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/vmlinuz -o /mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/images/netboot/ppc64.img
2013-10-23 15:24:05,354:   CalledProcessError: Command '['/var/tmp/lorax.srpHp5/installroot/usr/sbin/wrapper', '-p', 'of', '-D', '/var/tmp/lorax.srpHp5/installroot/usr/lib64/kernel-wrapper', '-i', '/mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/initrd.img', '/mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/vmlinuz', '-o', '/mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/images/netboot/ppc64.img']' returned non-zero exit status 1
  CalledProcessError: Command '['/var/tmp/lorax.srpHp5/installroot/usr/sbin/wrapper', '-p', 'of', '-D', '/var/tmp/lorax.srpHp5/installroot/usr/lib64/kernel-wrapper', '-i', '/mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/initrd.img', '/mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/ppc/ppc64/vmlinuz', '-o', '/mnt/redhat/rel-eng/RHEL-7.0-20131023.0/work/ppc64/buildinstall/images/netboot/ppc64.img']' returned non-zero exit status 1

I talked to Benjamin Herrenschmidt and his description of the solution is below.
Ok, lorax tries to create a "pure" of wrapper rather than a pseries one (which *could* be
problematic with some IBM OFW versions) and my upstream patch overlooked that case.

RHEL Version Found:
-------------------
RHEL 7.0

Brew:
-----
http://brewweb.devel.redhat.com/brew/taskinfo?taskID=6473135

Upstream:
---------
Benjamin Herrenschmidt will posted upstream after we have confirmed
RHEL compose works correctly again.

I'll provide Jarod with the upstream commit once it has been accepted
upstream. Benjamin Herrenschmidt is the powerpc maintainer upstream, so
upstream acceptance shouldn't be an issue.

Test Status:
------------
Currently we don't have a good process to test a compose and Linda Wang
asked me to post this now, since the way we do compose is that if one
fails they all fail.

---------------------------------------------------------------
Steve Best
IBM on-site partner

Proposed Patch:
---------------

Signed-off-by: Jarod Wilson <jarod@redhat.com>