[tools] perf: Fix include for non x86 architectures
Message-id: <165792b8756d361088f35aa45aec7a10a3d67e1f.1392204023.git.ffusco@redhat.com>
Patchwork-id: 76282
O-Subject: [RHEL7 PATCH net 25/29] perf tools: Fix include for non x86 architectures
Bugzilla: 1057099
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Flavio Leitner <fbl@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1057099
Upstream Status: 6a02652df511029127406cf8fa89cdf5e987f963
Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=7025692
Tested: verified on x86_64

Upstream Commit:
commit 6a02652df511029127406cf8fa89cdf5e987f963
Author: Francesco Fusco <ffusco@redhat.com>
Date:   Mon Jan 27 14:39:13 2014 +0100

    perf tools: Fix include for non x86 architectures

    Commit 71ae8aac ("lib: introduce arch optimized hash library") added an
    include to <linux/hash.h> for setting up an architecture specific fast
    hash.

    Since perf includes directly the non-uapi kernel header, it cannot find
    <asm/hash.h> on non-x86 and thus prevents perf to be compiled on every
    architecture other than x86.

    The problem is the inclusion of <asm/hash.h> in hash.h that results in
    the following error originating from util/evlist.c:

      fatal error: asm/hash.h: No such file or directory

    This commit simply adds an empty <asm/hash.h> stub/file to fix the
    compile issue on non-x86 architectures.

    As perf does not use any of these new functions, it fixes the
    compilation and therefore seems to be the most appropriate solution to
    go with.

    Signed-off-by: Francesco Fusco <ffusco@redhat.com>
    Link: http://lkml.kernel.org/r/2cf8143aad65a6aa6fe30325ef8a65847141afa2.1390829373.git.ffusco@redhat.com
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Francesco Fusco <ffusco@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>