[mmc] MMC_USDHI6ROL0 should depend on HAS_DMA
Message-id: <1463503488-149391-327-git-send-email-dzickus@redhat.com>
Patchwork-id: 144874
O-Subject: [RHEL7 PATCH 326/725] mmc: MMC_USDHI6ROL0 should depend on HAS_DMA
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 1ef94740483da84fd7de0b52442514cf6bf8c2e8
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed Jul 9 20:52:42 2014 +0200

    mmc: MMC_USDHI6ROL0 should depend on HAS_DMA

    If NO_DMA=y:

        drivers/built-in.o: In function `usdhi6_dma_setup':
        usdhi6rol0.c:(.text+0x5c35fc): undefined reference to `dma_map_sg'
        drivers/built-in.o: In function `usdhi6_dma_stop_unmap':
        usdhi6rol0.c:(.text+0x5c3738): undefined reference to `dma_unmap_sg'

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>