[tools] perf probe: Skip kernel symbols which is out of .text
Message-id: <1455060817-26852-125-git-send-email-jolsa@redhat.com>
Patchwork-id: 133914
O-Subject: [PATCH RHEL7.3 BZ1305882 124/360] perf probe: Skip kernel symbols which is out of .text
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 5a51fcd1f30c0f93bb54cec7201a3690032470cb
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed May 6 21:46:49 2015 +0900

description
===========
Skip the kernel symbols which is out of .text, e.g. the functions
in .inittext. Those are found in debuginfo/kallsyms, but already
freed from memory.

e.g.
  ----
  # perf probe vfs_caches_init
  vfs_caches_init+0 is out of .text, skip it.
  Probe point 'vfs_caches_init' not found.
    Error: Failed to add events.
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>