[tools] perf trace: Fix build when DWARF unwind isn't available
Message-id: <1474556776-20705-116-git-send-email-jolsa@redhat.com>
Patchwork-id: 158180
O-Subject: [PATCH RHEL7.3 BZ1373817 115/252] perf trace: Fix build when DWARF unwind isn't available
Bugzilla: 1373817
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1373817
https://bugzilla.redhat.com/show_bug.cgi?id=1373817

upstream
========
commit ccd62a896ffe3dbd60f3b7570a2b74e4fe030ed6
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Sat Apr 16 09:36:32 2016 -0300

description
===========
The variable is initialized and then conditionally set to a different
value, but not used when DWARF unwinding is not available, bummer, write
1000 times: "Run make -C tools/perf build-test"...

  builtin-trace.c: In function cmd_trace:
  builtin-trace.c:3112:6: error: variable max_stack_user_set set but not
  used [-Werror=unused-but-set-variable]
    bool max_stack_user_set = true;
        ^
  cc1: all warnings being treated as err

Fix it by marking it as __maybe_unused.

Fixes: 056149932602 ("perf trace: Make --(min,max}-stack imply "--call-graph dwarf"")
Signed-off-by: Rafael Aquini <aquini@redhat.com>