[tools] perf callchains: Fix unw_word_t pointer casts
Message-id: <1456127829-13546-172-git-send-email-jolsa@redhat.com>
Patchwork-id: 135476
O-Subject: [PATCH BZ1308570 171/260] perf callchains: Fix unw_word_t pointer casts
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit 186c6cfb32beae66140bc3c3fe4a519ee0234e33
Author: Rabin Vincent <rabin.vincent@axis.com>
Date: Sun Sep 27 20:37:55 2015 +0200

description
===========
unw_word_t is uint64_t even on 32-bit MIPS.  Cast it to uintptr_t before
the cast to void *p to get rid of the following errors:

  util/unwind-libunwind.c: In function 'access_mem':
  util/unwind-libunwind.c:464:4: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  util/unwind-libunwind.c:475:2: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  cc1: all warnings being treated as errors
  make[3]: *** [util/unwind-libunwind.o] Error 1

Signed-off-by: Rafael Aquini <aquini@redhat.com>