[char] drivers/xen-tpmfront: Fix compile issue with missing option
Message-id: <1429193116-49113-8-git-send-email-jarod@redhat.com>
Patchwork-id: 110654
O-Subject: [RHEL7 PATCH 07/95] drivers/xen-tpmfront: Fix compile issue with missing option.
Bugzilla: 1182709
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1182709

commit 713efcabca1fffbbb253a33ff0f8fda532633064
Author: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
Date:   Fri Aug 30 09:02:27 2013 -0400

    drivers/xen-tpmfront: Fix compile issue with missing option.

    Randy reports:

    x86_64:

    drivers/built-in.o: In function `xen_tpmfront_init':
    xen-tpmfront.c:(.init.text+0x257c): undefined reference to `xenbus_register_frontend'

    This is nicely fixed by selecting the XenBus frontend module.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>