[fs] cifs: Fix build warning
Message-id: <1374766419-8738-38-git-send-email-sprabhu@redhat.com>
Patchwork-id: 64514
O-Subject: [RHEL 7 bz988398 37/53] [CIFS] Fix build warning
Bugzilla: 988398
RH-Acked-by: Jeff Layton <jlayton@redhat.com>

Fix build warning in Shirish's recent SMB3 signing patch
which occurs when SMB2 support is disabled in Kconfig.

fs/built-in.o: In function `cifs_setup_session':
>> (.text+0xa1767): undefined reference to `generate_smb3signingkey'

Pointed out by: automated 0-DAY kernel build testing backend
Intel Open Source Technology Center

CC: Shirish Pargaonkar <shirishpargaonkar@gmail.com>
Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit e65a5cb41718e0eb17a470bc3acf2c3b2f00f1d0)

Signed-off-by: Sachin Prabhu <sprabhu@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>