[tools] perf: Fix build errors with O and DESTDIR make vars set
Message-id: <1374260844-2396-66-git-send-email-jolsa@redhat.com>
Patchwork-id: 63320
O-Subject: [PATCH RHEL7.0 BZ984998 65/85] perf tools: Fix build errors with O and DESTDIR make vars set
Bugzilla: 984998
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 984998
https://bugzilla.redhat.com/show_bug.cgi?id=984998

upstream status
===============
commit 107de3724eff5a6fa6474a4d2aa5460b63749ebf
Author: Robert Richter <robert.richter@linaro.org>
Date:   Tue Jun 11 17:22:38 2013 +0200

description
===========
Fixing build errors with O and DESTDIR make vars set:

 $ make prefix=/usr/local O=$builddir DESTDIR=$destdir -C tools/ perf
 ...
 make[1]: Entering directory `.../.source/perf/tools/perf'
     CC .../.build/perf/perf/util/parse-events.o
 util/parse-events.c:14:32: fatal error: parse-events-bison.h: No such file or directory
 compilation terminated.
 make[1]: *** [.../.build/perf/perf/util/parse-events.o] Error 1
 ...

and:

     LINK /.../.build/perf/perf/perf
 gcc: error: /.../.build/perf/perf//.../.source/perf/tools/lib/lk/liblk.a: No such file or directory

Signed-off-by: Jarod Wilson <jarod@redhat.com>