[scsi] lpfc: code cleanups in NVME initiator discovery
Message-id: <1507670879-17640-31-git-send-email-dkennedy@redhat.com>
Patchwork-id: 191054
O-Subject: [RHEL7.5 e-stor PATCH 030/170] lpfc: code cleanups in NVME initiator discovery
Bugzilla: 1385844 1461977 1387768
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Dick Kennedy <dick.kennedy@avagotech.com>

Submitted by jsmart2021 () jsmart2021.()@emulex.comSubmitted by James Smart James.Smart@emulex.com

From: James Smart jsmart2021@gmail.com

This patch addresses the smatch issues identified by Dan Carpenter
in http://www.spinics.net/lists/linux-scsi/msg105665.html

The issues are:

drivers/scsi/lpfc/lpfc_ct.c:943 lpfc_cmpl_ct_cmd_gft_id()
error: we previously assumed 'ndlp' could be null (see line 928)

Action: moved under if check

drivers/scsi/lpfc/lpfc_nvmet.c:1694 lpfc_nvmet_unsol_issue_abort()
error: we previously assumed 'ndlp' could be null (see line 1690)

Action: conditionalized arg in printf stmt

drivers/scsi/lpfc/lpfc_nvmet.c:1792 lpfc_nvmet_sol_fcp_issue_abort()
error: we previously assumed 'ndlp' could be null (see line 1788)

Action: conditionalized arg in printf stmt

Signed-off-by: Dick Kennedy dick.kennedy@broadcom.com
Signed-off-by: James Smart james.smart@broadcom.com

(cherry picked from commit b5ccc7d61c76006f839b41c6f15876342b46cb02)
Signed-off-by: Rafael Aquini <aquini@redhat.com>