[net] netfilter: nf_dup{4, 6}: fix build error when nf_conntrack disabled
Message-id: <65e5ce2c39bcaf7f98aa5b238a79fddffe046f24.1465290494.git.pabeni@redhat.com>
Patchwork-id: 149297
O-Subject: [RHEL7.3 net PATCH 120/165] netfilter: nf_dup{4, 6}: fix build error when nf_conntrack disabled
Bugzilla: 1331757
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1331757
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11141575
Tested: nftables test-suite and basic functional tests

Upstream commit:
commit a82b0e63917f597c546cd479acc938e08ac54f2d
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Wed Sep 2 20:54:02 2015 +0200

    netfilter: nf_dup{4, 6}: fix build error when nf_conntrack disabled

    While testing various Kconfig options on another issue, I found that
    the following one triggers as well on allmodconfig and nf_conntrack
    disabled:

      net/ipv4/netfilter/nf_dup_ipv4.c: In function 'nf_dup_ipv4':
      net/ipv4/netfilter/nf_dup_ipv4.c:72:20: error: 'nf_skb_duplicated' undeclared (first use in this function)
        if (this_cpu_read(nf_skb_duplicated))
      [...]
      net/ipv6/netfilter/nf_dup_ipv6.c: In function 'nf_dup_ipv6':
      net/ipv6/netfilter/nf_dup_ipv6.c:66:20: error: 'nf_skb_duplicated' undeclared (first use in this function)
        if (this_cpu_read(nf_skb_duplicated))

    Fix it by including directly the header where it is defined.

    Fixes: bbde9fc1824a ("netfilter: factor out packet duplication for IPv4/IPv6")
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>