[tools] perf/build: Fix feature-libunwind-debug-frame handling
Message-id: <1408462094-14194-310-git-send-email-jolsa@redhat.com>
Patchwork-id: 88291
O-Subject: [PATCH RHEL7.1 BZ1131394 309/325] tools/perf/build: Fix feature-libunwind-debug-frame handling
Bugzilla: 1131394
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1131394
https://bugzilla.redhat.com/show_bug.cgi?id=1131394

upstream
========
commit e310718d0e83aeb9969264dc577c45db16d9104d
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Nov 14 08:25:24 2013 +0100

description
===========
Set feature-libunwind-debug-frame. We don't want it in
CORE_FEATURE_TESTS because it's not the generic case, but we
need to set it in the !feature-libunwind case.

Also, because x86 distributions typically don't have
dwarf_find_debug_frame() unwinding method:

  test-libunwind-debug-frame.c:(.text+0x31): undefined reference to `_Ux86_64_dwarf_find_debug_frame'

Restrict this new API to ARM for the time being.

With this patch test-all.c works again, so repeat perf builds
are  fast again:

  comet:~/tip> perf stat --null --repeat 5 make -C tools/perf/
  [...]

       0,452899660 seconds time elapsed                                          ( +-  0,11% )

While with before it was:

  comet:~/tip> perf stat --null --repeat 5 make -C tools/perf/
  [...]

       1,674001829 seconds time elapsed                                          ( +-  0,16% )

[ Includes fix to config/feature-checks/Makefile from Will Deacon. ]
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>