[drm] imx-drm-core: Export imx_drm_encoder_get_mux_id
Message-id: <1381413926-15908-571-git-send-email-vfalico@redhat.com>
Patchwork-id: 69163
O-Subject: [RHEL7 PATCH 570/820] imx-drm: imx-drm-core: Export imx_drm_encoder_get_mux_id
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: ea8d15832016b0d07a8121159904e6b1d21b5b8b
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ea8d15832016b0d07a8121159904e6b1d21b5b8b
Stable: 2ac13a8f46246a8a3773bfca0a003f0524cf7cf0
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=2ac13a8f46246a8a3773bfca0a003f0524cf7cf0

Description
----------------------------
Backport from linux-3.10.y stable.

From: Fabio Estevam <fabio.estevam@freescale.com>
Subject: imx-drm: imx-drm-core: Export imx_drm_encoder_get_mux_id

commit ea8d15832016b0d07a8121159904e6b1d21b5b8b upstream.

When building imx_v6_v7_defconfig with imx-drm drivers selected as modules, we
get the following build error:

ERROR: "imx_drm_encoder_get_mux_id" [drivers/staging/imx-drm/imx-ldb.ko] undefined!

Export the required function to avoid this problem.

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Acked-by: Sascha Hauer <s.hauer@pengutronix.de>
Acked-by: Philipp Zabel <p.zabel@pengutronix.de>
Cc: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 2ac13a8f46246a8a3773bfca0a003f0524cf7cf0)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>