[thermal] cpu_cooling: fix stub function
Message-id: <1381413926-15908-133-git-send-email-vfalico@redhat.com>
Patchwork-id: 68698
O-Subject: [RHEL7 PATCH 132/820] thermal: cpu_cooling: fix stub function
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: e8d39240d635ed9bcaddbec898b1c9f063c5dbb2
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=e8d39240d635ed9bcaddbec898b1c9f063c5dbb2
Stable: d8724a91bc631690af241588936971214e55927e
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=d8724a91bc631690af241588936971214e55927e

Description
----------------------------
Backport from linux-3.10.y stable.

From: Arnd Bergmann <arnd@arndb.de>
Subject: thermal: cpu_cooling: fix stub function

commit e8d39240d635ed9bcaddbec898b1c9f063c5dbb2 upstream.

The function stub for cpufreq_cooling_get_level introduced
in 57df81069 "Thermal: exynos: fix cooling state translation"
is not syntactically correct C and needs to be fixed to avoid
this error:

In file included from drivers/thermal/db8500_thermal.c:20:0:
 include/linux/cpu_cooling.h: In function 'cpufreq_cooling_get_level':
include/linux/cpu_cooling.h:57:1:
 error: parameter name omitted  unsigned long cpufreq_cooling_get_level(unsigned int, unsigned int)  ^
 include/linux/cpu_cooling.h:57:1: error: parameter name omitted

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Eduardo Valentin <eduardo.valentin@ti.com>
Cc: Zhang Rui <rui.zhang@intel.com>
Cc: Amit Daniel kachhap <amit.daniel@samsung.com>
Signed-off-by: Eduardo Valentin <eduardo.valentin@ti.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit d8724a91bc631690af241588936971214e55927e)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>