[tools] perf probe: Allow probing on kmodules without dwarf
Message-id: <1456127829-13546-144-git-send-email-jolsa@redhat.com>
Patchwork-id: 135387
O-Subject: [PATCH BZ1308570 143/260] perf probe: Allow probing on kmodules without dwarf
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit 1a8ac29cbffc261f6d7c92e573878110a7dcbd94
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Fri Oct 2 21:58:32 2015 +0900

description
===========
Allow probing on kernel modules when 'perf' is built without debuginfo
support.

Currently perf-probe --module requires linking with libdw, but this
doesn't make sense.

E.g.
  ----
  # make NO_DWARF=1
  # ./perf probe -m pcspkr pcspkr_event%return
    Error: unknown switch `m'
  ----

With this patch
  ----
  # ./perf probe -m pcspkr pcspkr_event%return
  Added new event:
    probe:pcspkr_event   (on pcspkr_event%return in pcspkr)

  You can now use it in all perf tools, such as:

          perf record -e probe:pcspkr_event -aR sleep 1
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>