[netdrv] qed: select ZLIB_INFLATE
Message-id: <1465316705-7370-15-git-send-email-hpatil@redhat.com>
Patchwork-id: 149527
O-Subject: [PATCH v2 RHEL 7.3 014/107] qed: select ZLIB_INFLATE
Bugzilla: 1275807 1275811
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ 1275807

net commit id 4bdb96cb69d9e4c6038a976fa9def9f8ae024ff8

The newly added qlogic qed driver uses the zlib library, but
misses the dependency:

drivers/built-in.o: In function `qed_alloc_stream_mem':
drivers/net/ethernet/qlogic/qed/qed_main.c:707: undefined reference to `zlib_inflate_workspacesize'
drivers/built-in.o: In function `qed_unzip_data':
drivers/net/ethernet/qlogic/qed/qed_main.c:675: undefined reference to `zlib_inflateInit2'

This changes Kconfig to always select zlib when needed.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: fe56b9e6a8d9 ("qed: Add module with basic common support")
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Rafael Aquini <aquini@redhat.com>