[fs] cifs: Fix build failure with smb2
Message-id: <20170928031610.17150-2-lsahlber@redhat.com>
Patchwork-id: 186928
O-Subject: [RHEL7.5 BZ 1496637 fs 1/6] CIFS: Fix build failure with smb2
Bugzilla: 1496637
RH-Acked-by: Sachin Prabhu <sprabhu@redhat.com>
RH-Acked-by: Benjamin Coddington <bcodding@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Tobias Regnery <tobias.regnery@gmail.com>

Bugzilla: 1496637
Build: 14134876

I saw the following build error during a randconfig build:

fs/cifs/smb2ops.c: In function 'smb2_new_lease_key':
fs/cifs/smb2ops.c:1104:2: error: implicit declaration of function 'generate_random_uuid' [-Werror=implicit-function-declaration]

Explicit include the right header to fix this issue.

Signed-off-by: Tobias Regnery <tobias.regnery@gmail.com>
Reviewed-by: Aurelien Aptel <aaptel@suse.com>
Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit 4fa8e504e5c0d7db9280ac96a4ac92192f1041f5)
Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>