[include] net: cdc_ncm: fix 64bit division build error
Message-id: <9c2e9e7b40af1ec2eb95aeac7fff85b0ad76745a.1456166879.git.linville@tuxdriver.com>
Patchwork-id: 135681
O-Subject: [RHEL7 PATCH 41/51] net: cdc_ncm: fix 64bit division build error
Bugzilla: 1260556
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1260556

The upper timer_interval limit is arbitrary and much higher
than anything usable in the real world.  Reducing it from 15s
to ~4s to make the timer_interval fit in an u32 does not make
much difference.  The limit is still outside the practical
bounds.

This eliminates the need for a 64bit timer_interval, fixing a
build error related to 64bit division:

 drivers/built-in.o: In function `cdc_ncm_get_coalesce':
 ak8975.c:(.text+0x1ac994): undefined reference to `__aeabi_uldivmod'

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Bjrn Mork <bjorn@mork.no>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 7d10d2610cc02d432168ca0c5d964cd9e85c1b06)

Signed-off-by: John W. Linville <linville@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>