[netdrv] netvsc: don't access netdev->num_rx_queues directly
Message-id: <1506532134-23248-65-git-send-email-mgamal@redhat.com>
Patchwork-id: 186750
O-Subject: [RHEL7.5 PATCH v3 64/69] [netdrv] netvsc: don't access netdev->num_rx_queues directly
Bugzilla: 1465469
RH-Acked-by: Eduardo Otubo <otubo@redhat.com>
RH-Acked-by: Vitaly Kuznetsov <vkuznets@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Cathy Avery <cavery@redhat.com>

commit b92b7d3312033a08cae2c879b9243c42ad7de94b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jun 22 00:16:37 2017 +0200

    netvsc: don't access netdev->num_rx_queues directly

    This structure member is hidden behind CONFIG_SYSFS, and we
    get a build error when that is disabled:

    drivers/net/hyperv/netvsc_drv.c: In function 'netvsc_set_channels':
    drivers/net/hyperv/netvsc_drv.c:754:49: error: 'struct net_device' has no member named 'num_rx_queues'; did you mean 'num_tx_queues'?
    drivers/net/hyperv/netvsc_drv.c: In function 'netvsc_set_rxfh':
    drivers/net/hyperv/netvsc_drv.c:1181:25: error: 'struct net_device' has no member named 'num_rx_queues'; did you mean 'num_tx_queues'?

    As the value is only set once to the argument of alloc_netdev_mq(),
    we can compare against that constant directly.

    Fixes: ff4a44199012 ("netvsc: allow get/set of RSS indirection table")
    Fixes: 2b01888d1b45 ("netvsc: allow more flexible setting of number of channels")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Haiyang Zhang <haiyangz@microsoft.com>
    Signed-off-by: Stephen Hemminger <sthemmin@microsoft.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Mohammed Gamal <mgamal@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>