[ata] ahci, msix: Fix build error for !PCI_MSI
Message-id: <1463595206-12588-26-git-send-email-dmilburn@redhat.com>
Patchwork-id: 146426
O-Subject: [RHEL7.3 PATCH BZ 1286946 25/61] ahci, msix: Fix build error for !PCI_MSI
Bugzilla: 1286946
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Robert Richter <robert.richter@caviumnetworks.com>

It turned out the irq vector of the msix can be obtained from struct
msix_entry. This makes the lookup function for msi_desc obsolete.

This fixes a build error if PCI_MSI is unset:

 drivers/ata/ahci.c: In function msix_get_desc:
 drivers/ata/ahci.c:1210:2: error: struct pci_dev has no member named msi_list

Catched by Fengguang's build bot.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Robert Richter <rrichter@cavium.com>
Signed-off-by: Tejun Heo <tj@kernel.org>
(cherry picked from commit 34c56932ce5278b8bbae13936f9df05cd59e3193)
Signed-off-by: David Milburn <dmilburn@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>