[bluetooth] btqcomsmd: fix compile-test dependency
Message-id: <1508766319-11470-12-git-send-email-gtiwari@redhat.com>
Patchwork-id: 194675
O-Subject: [RHEL7.5 PATCH BZ 1457085 11/35] Bluetooth: btqcomsmd: fix compile-test dependency
Bugzilla: 1457085
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1457085

commit 6e9e6cc8f4e4f2cd67931510c9f39abf3d9e0d3b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 20 15:31:10 2017 -0700

    Bluetooth: btqcomsmd: fix compile-test dependency

    compile-testing fails when QCOM_SMD is a loadable module:

    drivers/bluetooth/built-in.o: In function `btqcomsmd_send':
    btqca.c:(.text+0xa8): undefined reference to `qcom_smd_send'
    drivers/bluetooth/built-in.o: In function `btqcomsmd_probe':
    btqca.c:(.text+0x3ec): undefined reference to `qcom_wcnss_open_channel'
    btqca.c:(.text+0x46c): undefined reference to `qcom_smd_set_drvdata'

    This clarifies the dependency to allow compile-testing only when
    SMD is completely disabled, otherwise the dependency on QCOM_SMD
    will make sure we can link against it.

    Fixes: e27ee2b16bad ("Bluetooth: btqcomsmd: Allow driver to build if COMPILE_TEST is enabled")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    [bjorn: Restructure and clarify dependency to QCOM_WCNSS_CTRL]
    Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
    Acked-by: Marcel Holtmann <marcel@holtmann.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>