[include] usb: usb_phy_gen: refine conditional declaration of usb_nop_xceiv_register
Message-id: <1457470219-37147-86-git-send-email-dzickus@redhat.com>
Patchwork-id: 137733
O-Subject: [RHEL7 PATCH 085/423] usb: usb_phy_gen: refine conditional declaration of usb_nop_xceiv_register
Bugzilla: 1303209
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303209

commit 94468783cd960aa14b22503dd59afd14efb785aa
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Wed Oct 16 19:18:41 2013 -0700

    usb: usb_phy_gen: refine conditional declaration of usb_nop_xceiv_register

    Commit 3fa4d734 (usb: phy: rename nop_usb_xceiv => usb_phy_gen_xceiv)
    changed the conditional around the declaration of usb_nop_xceiv_register
    from
    	#if defined(CONFIG_NOP_USB_XCEIV) ||
    		(defined(CONFIG_NOP_USB_XCEIV_MODULE) && defined(MODULE))
    to
    	#if IS_ENABLED(CONFIG_NOP_USB_XCEIV)

    While that looks the same, it is semantically different. The first expression
    is true if CONFIG_NOP_USB_XCEIV is built as module and if the including
    code is built as module. The second expression is true if code depending on
    CONFIG_NOP_USB_XCEIV if built as module or into the kernel.

    As a result, the arm:allmodconfig build fails with

    arch/arm/mach-omap2/built-in.o: In function `omap3_evm_init':
    arch/arm/mach-omap2/board-omap3evm.c:703: undefined reference to
    	`usb_nop_xceiv_register'

    Fix the problem by reverting to the old conditional.

    Cc: Josh Boyer <jwboyer@redhat.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>