[fs] nfsd: eliminate NFSD_DEBUG
Message-id: <64569f9e13dbc1007c2734007b9bd67fe9d8864f.1435240313.git.bcodding@redhat.com>
Patchwork-id: 120717
O-Subject: [RHEL7.2 PATCH fs BZ1235634 3/7] nfsd: eliminate NFSD_DEBUG
Bugzilla: 1235634
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>
RH-Acked-by: Steve Dickson <SteveD@redhat.com>

From: Mark Salter <msalter@redhat.com>

Commit f895b252d4edf ("sunrpc: eliminate RPC_DEBUG") introduced
use of IS_ENABLED() in a uapi header which leads to a build
failure for userspace apps trying to use <linux/nfsd/debug.h>:

   linux/nfsd/debug.h:18:15: error: missing binary operator before token "("
  #if IS_ENABLED(CONFIG_SUNRPC_DEBUG)
                ^

Since this was only used to define NFSD_DEBUG if CONFIG_SUNRPC_DEBUG
is enabled, replace instances of NFSD_DEBUG with CONFIG_SUNRPC_DEBUG.

Cc: stable@vger.kernel.org
Fixes: f895b252d4edf "sunrpc: eliminate RPC_DEBUG"
Signed-off-by: Mark Salter <msalter@redhat.com>
Reviewed-by: Jeff Layton <jlayton@primarydata.com>
Signed-off-by: J. Bruce Fields <bfields@redhat.com>
Upstream Id: 135dd002c23054aaa056ea3162c1e0356905c195
Bugzilla: 1235634
Signed-off-by: Benjamin Coddington <bcodding@redhat.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>