[c6x] mm: include "asm/uaccess.h" to pass compiling
Message-id: <1381413926-15908-47-git-send-email-vfalico@redhat.com>
Patchwork-id: 68617
O-Subject: [RHEL7 PATCH 046/820] arch: c6x: mm: include "asm/uaccess.h" to pass compiling
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: fe74650166dd6905b0cf66594eb79222dc9d7109
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=fe74650166dd6905b0cf66594eb79222dc9d7109
Stable: 14a1d6afc622566a7dcb961a183010ec83bea009
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=14a1d6afc622566a7dcb961a183010ec83bea009

Description
----------------------------
Backport from linux-3.10.y stable.

From: Chen Gang <gang.chen@asianux.com>
Subject: arch: c6x: mm: include "asm/uaccess.h" to pass compiling

commit fe74650166dd6905b0cf66594eb79222dc9d7109 upstream.

Need include "asm/uaccess.h" to pass compiling.

The related error (with allmodconfig):

  arch/c6x/mm/init.c: In function `paging_init':
  arch/c6x/mm/init.c:46:2: error: implicit declaration of function `set_fs' [-Werror=implicit-function-declaration]
  arch/c6x/mm/init.c:46:9: error: `KERNEL_DS' undeclared (first use in this function)
  arch/c6x/mm/init.c:46:9: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Chen Gang <gang.chen@asianux.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 14a1d6afc622566a7dcb961a183010ec83bea009)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>