[netdrv] be2net: make hwmon interface optional
Message-id: <1434391368-21520-62-git-send-email-ivecera@redhat.com>
Patchwork-id: 119009
O-Subject: [RHEL7.2 PATCH 61/63] be2net: make hwmon interface optional
Bugzilla: 1182733
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ: #1182733

Upstream commit(s):
commit 9a03259c3d30d4b1b582072211dc571a68340054
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon May 18 23:06:45 2015 +0200

    be2net: make hwmon interface optional

    The hwmon interface in the be2net driver causes a link error when
    be2net is built-in while the hwmon subsystem is a loadable module:

    drivers/built-in.o: In function `be_probe':
    drivers/net/ethernet/emulex/benet/be_main.c:5761: undefined reference to `devm_hwmon_device_register_with_groups'

    This adds a new Kconfig symbol, following the example of multiple
    other drivers that have the same problem. The new CONFIG_BE2NET_HWMON
    will not be available when (BE2NET=y && HWMON=m) to avoid this
    problem.

    We have to also mark be_hwmon_show_temp as 'static' to ensure the
    compiler can optimize out all the unused code.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 29e9122b3a ("be2net: Export board temperature using hwmon-sysfs interface.")
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>