[kernel] hugetlb: fix compile error on tile
Message-id: <20160729175048.16035-94-jmoyer@redhat.com>
Patchwork-id: 156203
O-Subject: [RHEL7 PATCH 093/139] hugetlb: fix compile error on tile
Bugzilla: 1346083 1346084 1346445 1346449 1346472 1347091 1359806
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

From: Dan Williams <dan.j.williams@intel.com>

BZ: 1346445, 1346449, 1346472, 1359806, 1346083, 1346084, 1347091

commit 888cdbc2c9a76a0e450f533b1957cdbfe7d483d5
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Fri Jan 15 16:56:32 2016 -0800

    hugetlb: fix compile error on tile

    Inlude asm/pgtable.h to get the definition for pud_t to fix:

      include/linux/hugetlb.h:203:29: error: unknown type name 'pud_t'

    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
    Cc: Liviu Dudau <liviu.dudau@arm.com>
    Cc: Sudeep Holla <sudeep.holla@arm.com>
    Cc: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Cc: David Howells <dhowells@redhat.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>