[infiniband] i40iw: Fixes for static checker warnings
Message-id: <20171115131435.24570-18-sassmann@redhat.com>
Patchwork-id: 198143
O-Subject: [RHEL7.5 PATCH 17/33] i40iw: Fixes for static checker warnings
Bugzilla: 1466401
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

From: Shiraz Saleem <shiraz.saleem@intel.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1466401
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14547222

Remove NULL check for cm_node->listener in i40iw_accept
as listener is always present at this point.

Remove the check for cm_node->accept_pend and related code
in i40iw_cm_event_connected as the cm_node in this context
is only pertinent to active node and cm_node->accept_pend
is always 0.

This fixes the following smatch warnings,

drivers/infiniband/hw/i40iw/i40iw_cm.c:3691 i40iw_accept()
error: we previously assumed 'cm_node->listener' could be null

drivers/infiniband/hw/i40iw/i40iw_cm.c:4061 i40iw_cm_event_connected()
error: we previously assumed 'cm_node->listener' could be null

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Shiraz Saleem <shiraz.saleem@intel.com>
Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Stefan Assmann <sassmann@redhat.com>
(cherry picked from commit 83fb1c89e7ee5bb16397b294ccfbd65a9a22e402)
Signed-off-by: Rafael Aquini <aquini@redhat.com>