[netdrv] mlxfw: select CONFIG_XZ_DEC
Message-id: <20171111045127.10299-47-ddutile@redhat.com>
Patchwork-id: 197613
O-Subject: [PATCH RHEL-7.5 046/251] net/mlxfw: select CONFIG_XZ_DEC
Bugzilla: 1499363 1466367
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit 9831724a08f06f9560fcc3f1132cbd290e5f9149
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 30 11:26:14 2017 +0200

    net/mlxfw: select CONFIG_XZ_DEC

    The new mlxfw code fails to build without the xz library:

    drivers/net/ethernet/mellanox/mlxfw/mlxfw_mfa2.o: In function `mlxfw_mfa2_xz_dec_run':
    :(.text.mlxfw_mfa2_xz_dec_run+0x8): undefined reference to `xz_dec_run'
    drivers/net/ethernet/mellanox/mlxfw/mlxfw_mfa2.o: In function `mlxfw_mfa2_file_component_get':
    :(.text.mlxfw_mfa2_file_component_get+0x218): undefined reference to `xz_dec_init'
    :(.text.mlxfw_mfa2_file_component_get+0x2c0): undefined reference to `xz_dec_end'

    This adds a Kconfig 'select' statement for it, which is also what
    the other user of that library has.

    Fixes: 410ed13cae39 ("Add the mlxfw module for Mellanox firmware flash process")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Yotam Gigi <yotamg@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1466367

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>