[net] sched: have stub for tcf_destroy_chain in case NET_CLS is not configured
Message-id: <20171008224128.1458-310-ivecera@redhat.com>
Patchwork-id: 190392
O-Subject: [RHEL7.5 net PATCH 309/466] sched: have stub for tcf_destroy_chain in case NET_CLS is not configured
Bugzilla: 1445420
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ#1445420

Upstream commit(s):
commit 8ae70032552a8082734d0b8550848cf6bf92e1d5
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Wed Feb 15 11:57:50 2017 +0100

    sched: have stub for tcf_destroy_chain in case NET_CLS is not configured

    This fixes broken build for !NET_CLS:

    net/built-in.o: In function `fq_codel_destroy':
    /home/sab/linux/net-next/net/sched/sch_fq_codel.c:468: undefined reference to `tcf_destroy_chain'

    Fixes: cf1facda2f61 ("sched: move tcf_proto_destroy and tcf_destroy_chain helpers into cls_api")
    Reported-by: Sabrina Dubroca <sd@queasysnail.net>
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Tested-by: Sabrina Dubroca <sd@queasysnail.net>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>