[fs] btrfs: Fix compile error when CONFIG_SECURITY is not set
Message-id: <1427388544-10392-176-git-send-email-sandeen@redhat.com>
Patchwork-id: 108571
O-Subject: [RHEL7.2 PATCH 175/273] [fs] btrfs: Fix compile error when CONFIG_SECURITY is not set.
Bugzilla: 1205873
RH-Acked-by: Zach Brown <zab@redhat.com>
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>

Bugzilla: 1205873
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=8905085
Tested: Locally with fstests

Backport of the following upstream commit:

    commit a43bb39b5c710e79e921fb76341bacc418cfde78
    Author: Qu Wenruo <quwenruo@cn.fujitsu.com>
    Date:   Wed Oct 8 10:19:08 2014 +0800

    btrfs: Fix compile error when CONFIG_SECURITY is not set.

    Fix the following compile error when CONFIG_SECURITY is not set:

    error: 'struct security_mnt_opts' has no member named 'num_mnt_opts'

    Signed-off-by: Qu Wenruo <quwenruo@cn.fujitsu.com>
    Signed-off-by: Chris Mason <clm@fb.com>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>