[md] dm-cache: avoid conflicting remove_mapping() in mq policy
Message-id: <1379974247-11937-13-git-send-email-snitzer@redhat.com>
Patchwork-id: 67661
O-Subject: [RHEL7.0 PATCH 12/44] dm cache: avoid conflicting remove_mapping() in mq policy
Bugzilla: 1010437
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Mikulas Patocka <mpatocka@redhat.com>

BZ: 1010437

Upstream commit b936bf8b785f0fbe083d203049e4da1c56ec788f
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Fri Jul 26 09:57:31 2013 +0200

    dm cache: avoid conflicting remove_mapping() in mq policy

    On sparc32, which includes <linux/swap.h> from <asm/pgtable_32.h>:

    drivers/md/dm-cache-policy-mq.c:962:13: error: conflicting types for 'remove_mapping'
    include/linux/swap.h:285:12: note: previous declaration of 'remove_mapping' was here

    As mq_remove_mapping() already exists, and the local remove_mapping() is
    used only once, inline it manually to avoid the conflict.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>
    Signed-off-by: Alasdair Kergon <agk@redhat.com>
    Acked-by: Joe Thornber <ejt@redhat.com>

Signed-off-by: Jarod Wilson <jarod@redhat.com>