[tools] perf evsel: Do not put a variable sized type not at the end of a struct
Message-id: <20170807084247.7531-64-jolsa@redhat.com>
Patchwork-id: 182003
O-Subject: [PATCH RHEL7.5 63/94] perf evsel: Do not put a variable sized type not at the end of a struct
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit c24ae6d96112b10ef703a58d7d74583716d2ce69
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 10:59:04 2017 -0300

description
===========
As this is a GNU extension and while harmless in this case, we can do
the same thing in a more clearer way by using a existing thread_map and
cpu_map constructors:

With this we avoid this while compiling with clang:

  util/evsel.c:1659:17: error: field 'map' with variable sized type 'struct cpu_map' not at the end of a struct or class is a GNU extension
        [-Werror,-Wgnu-variable-sized-type-not-at-end]
          struct cpu_map map;
                         ^
  util/evsel.c:1667:20: error: field 'map' with variable sized type 'struct thread_map' not at the end of a struct or class is a GNU extension
        [-Werror,-Wgnu-variable-sized-type-not-at-end]
          struct thread_map map;
                            ^

Signed-off-by: Rafael Aquini <aquini@redhat.com>