[tools] perf: Fix -ldw/-lelf link test when static linking
Message-id: <20130722125522.GA22713@krava.brq.redhat.com>
Patchwork-id: 63366
O-Subject: [PATCHv2 RHEL7.0 BZ984998 82/85] perf tools: Fix -ldw/-lelf link test when static linking
Bugzilla: 984998
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

On Mon, Jul 22, 2013 at 06:36:45AM -0400, Tony Camuso wrote:
> On 07/19/2013 03:07 PM, Jiri Olsa wrote:
> > Bugzilla: 984998
> > https://bugzilla.redhat.com/show_bug.cgi?id=984998
> >
> > upstream status
> > ===============
> > commit d14c496588733ec1b586ec068932c1db228dd770
> > Author: Mike Frysinger <vapier@chromium.org>
> > Date:   Thu May 9 00:17:44 2013 -0400
> >
>
> Jiri,
>
> Upstream patch has the following hunk which is missing from your patch.
> Explanation?

ugh, I wonder how that one happened, attaching v2..
brewing it in here:
http://brewweb.devel.redhat.com/brew/taskinfo?taskID=6065902

thanks,
jirka

---
Bugzilla: 984998
https://bugzilla.redhat.com/show_bug.cgi?id=984998

upstream status
===============
commit d14c496588733ec1b586ec068932c1db228dd770
Author: Mike Frysinger <vapier@chromium.org>
Date:   Thu May 9 00:17:44 2013 -0400

description
===========
Since libelf sometimes uses libpthread, we have to list that after -lelf
when someone tries to build statically.  Else things go boom:

Makefile:479: *** No libelf.h/libelf found, please install \
	libelf-dev/elfutils-libelf-devel.  Stop.

Similarly, the -ldw test fails as it often uses -lz:

Makefile:462: No libdw.h found or old libdw.h found or elfutils is older \
	than 0.138, disables dwarf support. Please install new elfutils-devel/libdw-dev

And if we add debugging to try-cc, we see:
+ echo '#include <dwarf.h>

int main(void)
{
        Dwarf *dbg = dwarf_begin(0, DWARF_C_READ);
        return (long)dbg;
}'
+ i686-pc-linux-gnu-gcc -x c - -O2 -pipe -march=atom -mtune=atom -mfpmath=sse -g \
	-D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE \
	-ldw -lelf -static -lpthread -lrt -lelf -lm -o .24368
/usr/lib/libdw.a(dwarf_begin_elf.o):function check_section.isra.1: error: undefined reference to 'inflateInit_'
/usr/lib/libdw.a(dwarf_begin_elf.o):function check_section.isra.1: error: undefined reference to 'inflate'
/usr/lib/libdw.a(dwarf_begin_elf.o):function check_section.isra.1: error: undefined reference to 'inflateReset'
/usr/lib/libdw.a(dwarf_begin_elf.o):function check_section.isra.1: error: undefined reference to 'inflateEnd'

+ echo '#include <libelf.h>

int main(void)
{
        Elf *elf = elf_begin(0, ELF_C_READ, 0);
        return (long)elf;
}'
+ i686-pc-linux-gnu-gcc -x c - -O2 -pipe -march=atom -mtune=atom -mfpmath=sse -g \
	-D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE \
	-static -lpthread -lrt -lelf -lm -o .19216
/usr/lib/libelf.a(elf_begin.o):function file_read_elf: error: undefined reference to 'pthread_rwlock_init'
/usr/lib/libelf.a(elf_begin.o):function __libelf_read_mmaped_file: error: undefined reference to 'pthread_rwlock_init'
/usr/lib/libelf.a(elf_begin.o):function __libelf_read_mmaped_file: error: undefined reference to 'pthread_rwlock_init'
/usr/lib/libelf.a(elf_begin.o):function read_file: error: undefined reference to 'pthread_rwlock_init'
/usr/lib/libelf.a(elf_begin.o):function lock_dup_elf.8072: error: undefined reference to 'pthread_rwlock_unlock'
/usr/lib/libelf.a(elf_begin.o):function lock_dup_elf.8072: error: undefined reference to 'pthread_rwlock_wrlock'
/usr/lib/libelf.a(elf_begin.o):function elf_begin: error: undefined reference to 'pthread_rwlock_rdlock'
/usr/lib/libelf.a(elf_begin.o):function elf_begin: error: undefined reference to 'pthread_rwlock_unlock'
---
 tools/lib/lk/Makefile      | 2 +-
 tools/perf/config/Makefile | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

Signed-off-by: Jarod Wilson <jarod@redhat.com>