[usb] Fix warnings in chaoskey driver
Message-id: <1434576081-13393-350-git-send-email-dzickus@redhat.com>
Patchwork-id: 119712
O-Subject: [RHEL7 PATCH 349/376] usb: Fix warnings in chaoskey driver
Bugzilla: 1232920
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1232920

commit 8b86ed078a65433a60ff59091a136d23724bd6d3
Author: Keith Packard <keithp@keithp.com>
Date:   Thu Mar 26 16:49:38 2015 -0700

    usb: Fix warnings in chaoskey driver

    >    drivers/usb/misc/chaoskey.c: In function 'chaoskey_read':
    > >> drivers/usb/misc/chaoskey.c:412:3: error: implicit declaration of function 'copy_to_user'
    > >> [-Werror=implicit-function-declaration]
    >       remain = copy_to_user(buffer, dev->buf + dev->used, this_time);

    I was unable to reproduce this locally, but added an explicit

    	#include <linux/uaccess.h>

    which should ensure the definition on all architectures.

    > sparse warnings: (new ones prefixed by >>)
    >
    > >> drivers/usb/misc/chaoskey.c:117:30: sparse: incorrect type in assignment (different base types)
    >    drivers/usb/misc/chaoskey.c:117:30:    expected int [signed] size
    >    drivers/usb/misc/chaoskey.c:117:30:    got restricted __le16 [usertype] wMaxPacketSize

    Switched the code to using the USB descriptor accessor functions.

    Signed-off-by: Keith Packard <keithp@keithp.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>