[perf] Fix building warning on ARM 32
Message-id: <1428672113-29331-150-git-send-email-jolsa@redhat.com>
Patchwork-id: 109784
O-Subject: [PATCH RHEL7.2 BZ1209607 149/220] perf: Fix building warning on ARM 32
Bugzilla: 1209607
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1209607
https://bugzilla.redhat.com/show_bug.cgi?id=1209607

upstream
========
commit ac931f87a647ca156f65a4c00e7297165e4fa2d8
Author: Wang Nan <wangnan0@huawei.com>
Date: Tue Dec 16 14:19:06 2014 +0800

description
===========
Commit 85c116a6cb91 ("perf callchain: Make get_srcline fall back to sym+offset")
introduces asprintf() call and matches '%ld' to a u64 argument, which is
incorrect on ARM:

   CC       /home/wn/util/srcline.o
 util/srcline.c: In function 'get_srcline':
 util/srcline.c:297:6: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'u64' [-Werror=format]
 cc1: all warnings being treated as errors
 make[1]: *** [/home/wn/util/srcline.o] Error 1

In addition, all users of get_srcline() use u64 addr, and libbfd
also use 64 bit bfd_vma as address. This patch also fix
prototype of get_srcline() and addr2line() to use u64 addr
instead of unsigned long.

Signed-off-by: Rafael Aquini <aquini@redhat.com>