[powerpc] opal: Add missing include
Message-id: <1410545655-205645-401-git-send-email-dzickus@redhat.com>
Patchwork-id: 94344
O-Subject: [RHEL7 PATCH 400/626] powerpc/opal: Add missing include
Bugzilla: 1127366
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1127366

commit bfd25d72abc62a89f9c9c41417da998adcf2578e
Author: Michael Neuling <mikey@neuling.org>
Date:   Tue Mar 25 11:43:08 2014 +1100

    powerpc/opal: Add missing include

    next-20140324 currently fails compiling celleb_defconfig with:

    arch/powerpc/include/asm/opal.h:894:42: error: 'struct notifier_block' declared inside parameter list [-Werror]
    arch/powerpc/include/asm/opal.h:894:42: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
    arch/powerpc/include/asm/opal.h:896:14: error: 'struct notifier_block' declared inside parameter list [-Werror]

    This is due to a missing include which is added here.

    Signed-off-by: Michael Neuling <mikey@neuling.org>
    Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>