[perf] tools: Improve feature test debuggability
Message-id: <1431774138-14330-156-git-send-email-jolsa@redhat.com>
Patchwork-id: 112376
O-Subject: [PATCH RHEL7.2 BZ1222189 155/327] perf tools: Improve feature test debuggability
Bugzilla: 1222189
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1222189
https://bugzilla.redhat.com/show_bug.cgi?id=1222189

upstream
========
commit b49f1a4be701c2386ccc7496dc8442cf26424d5c
Author: Ingo Molnar <mingo@kernel.org>
Date: Sat Feb 28 10:16:27 2015 +0100

description
===========
Certain feature tests fail with link errors:

  triton:~/tip/tools/perf/config/feature-checks> make test-libbabeltrace.bin
  gcc -MD  -o test-libbabeltrace.bin test-libbabeltrace.c # -lbabeltrace provided by
  /tmp/cc6dRSqd.o: In function `main':
  test-libbabeltrace.c:(.text+0xf): undefined reference to `bt_ctf_stream_class_get_packet_context_type'

although they should already fail with a build error due to lack of a
proper prototype for the function. Due to this I first tried to find
which library was missing - while it was the whole feature that was
missing from the .h file already.

To solve this, propagate -Wall -Werror to all testcases and remove them
from testcase Makefile rules that used them explicitly.

A missing feature now outputs:

  triton:~/tip/tools/perf/config/feature-checks> make test-libbabeltrace.bin
  gcc -MD  -Wall -Werror -o test-libbabeltrace.bin test-libbabeltrace.c  # -lbabeltrace provided by
  test-libbabeltrace.c: In function main:
  test-libbabeltrace.c:6:2: error: implicit declaration of function bt_ctf_stream_class_get_packet_context_type [-Werror=implicit-function-declaration]

Signed-off-by: Rafael Aquini <aquini@redhat.com>