[powerpc] powernv: Replace CONFIG_POWERNV_MSI with just CONFIG_PPC_POWERNV
Message-id: <1410545655-205645-208-git-send-email-dzickus@redhat.com>
Patchwork-id: 94188
O-Subject: [RHEL7 PATCH 207/626] powerpc/powernv: Replace CONFIG_POWERNV_MSI with just CONFIG_PPC_POWERNV
Bugzilla: 1127366
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1127366

commit 66c29da6782b9861b17f9fc81746e30315e039c2
Author: Michael Ellerman <michael@ellerman.id.au>
Date:   Thu Sep 26 17:52:17 2013 +1000

    powerpc/powernv: Replace CONFIG_POWERNV_MSI with just CONFIG_PPC_POWERNV

    We currently have a user visible CONFIG_POWERNV_MSI option, but it
    doesn't actually disable MSI for powernv. The MSI code is always built,
    what it does disable is the inclusion of the MSI bitmap code, which
    leads to a build error.

    eg, with PPC_POWERNV=y and POWERNV_MSI=n we get:

      arch/powerpc/platforms/built-in.o: In function `.pnv_teardown_msi_irqs':
      pci.c:(.text+0x3558): undefined reference to `.msi_bitmap_free_hwirqs'

    We don't really need a POWERNV_MSI symbol, just have the MSI bitmap code
    depend directly on PPC_POWERNV.

    Signed-off-by: Michael Ellerman <michael@ellerman.id.au>
    Reviewed-by: Gavin Shan <shangw@linux.vnet.ibm.com>
    Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>