[tools] perf stat: Fix recort_usage typo
Message-id: <1460038562-19641-284-git-send-email-jolsa@redhat.com>
Patchwork-id: 140600
O-Subject: [PATCH RHEL7.3 BZ1323852 283/311] perf stat: Fix recort_usage typo
Bugzilla: 1323852
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1323852
https://bugzilla.redhat.com/show_bug.cgi?id=1323852

upstream
========
commit 8a59f3ccbc11fcb222b046a64929dd473f7dff54
Author: Jiri Olsa <jolsa@kernel.org>
Date: Tue Jan 12 10:35:29 2016 +0100

description
===========
Markus reported gcc 6 complains when compiling perf stat command:

  builtin-stat.c:1591:27: error: recort_usage defined but not used
  [-Werror=unused-const-variable]
   static const char * const recort_usage[] = {
                             ^~~~~~~~~~~~

I fixed the typo and realized we already export record_usage, so I also
prefixed it with stat (and included report_usage).

Signed-off-by: Rafael Aquini <aquini@redhat.com>