[powerpc] Added __cmpdi2 for signed 64bit comparision
Message-id: <1410545655-205645-88-git-send-email-dzickus@redhat.com>
Patchwork-id: 94121
O-Subject: [RHEL7 PATCH 087/626] powerpc: Added __cmpdi2 for signed 64bit comparision
Bugzilla: 1127366
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1127366

commit 41b93b238ab394c8cf0935ec3ba31c700a2b3b25
Author: Bharat Bhushan <r65777@freescale.com>
Date:   Wed Oct 9 10:41:17 2013 +0530

    powerpc: Added __cmpdi2 for signed 64bit comparision

    This was missing on powerpc and I am getting compilation error
    drivers/vfio/pci/vfio_pci_rdwr.c:193: undefined reference to `__cmpdi2'
    drivers/vfio/pci/vfio_pci_rdwr.c:193: undefined reference to `__cmpdi2'

    Signed-off-by: Bharat Bhushan <bharat.bhushan@freescale.com>
    Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>