[tools] perf probe: Improve error message when %return is on inlined function
Message-id: <1456127829-13546-134-git-send-email-jolsa@redhat.com>
Patchwork-id: 135367
O-Subject: [PATCH BZ1308570 133/260] perf probe: Improve error message when %return is on inlined function
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1308570
https://bugzilla.redhat.com/show_bug.cgi?id=1308570

upstream
========
commit 6cca13bdf5a5d561a855259689874e0c7266eec3
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Thu Oct 1 01:41:37 2015 +0900

description
===========
perf probe shows more precisely message when it finds given
%return target function is inlined.

Without this fix:
  ----
  # ./perf probe -V getname_flags%return
  Return probe must be on the head of a real function.
  Debuginfo analysis failed.
    Error: Failed to show vars.
  ----

With this fix:
  ----
  # ./perf probe -V getname_flags%return
  Failed to find "getname_flags%return",
   because getname_flags is an inlined function and has no return point.
  Debuginfo analysis failed.
    Error: Failed to show vars.
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>