[tools] perf/probe: Do not use dwfl_module_addrsym if dwarf_diename finds symbol name
Message-id: <1418163608-7772-274-git-send-email-jolsa@redhat.com>
Patchwork-id: 101484
O-Subject: [PATCH RHEL7.1 BZ1169436 273/359] perf probe: Do not use dwfl_module_addrsym if dwarf_diename finds symbol name
Bugzilla: 1169436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1169436
https://bugzilla.redhat.com/show_bug.cgi?id=1169436

upstream
========
commit 664fee3dc37939bb8010906913fa9dbc52abb587
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed Sep 17 08:41:01 2014 +0000

description
===========
Do not use dwfl_module_addrsym if dwarf_diename can find the symbol
name, since dwfl_module_addrsym can be failed on shared libraries.

Without this patch
  ----
  $ perf probe -x ../lib/traceevent/libtraceevent.so -V create_arg_op
  Failed to find symbol at 0x11df1
  Failed to find the address of create_arg_op
    Error: Failed to show vars.
  ----
With this patch
  ----
  $ perf probe -x ../lib/traceevent/libtraceevent.so -V create_arg_op
  Available variables at create_arg_op
          @<create_arg_op+0>
                  enum filter_op_type     btype
                  struct filter_arg*      arg
  ----

This bug was reported on linux-perf-users@vger.kernel.org.

Link: http://permalink.gmane.org/gmane.linux.kernel.perf.user/1691
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>