[tools] perf/scripting/perl: Fix build error on Fedora 12
Message-id: <1389109877-9395-219-git-send-email-jolsa@redhat.com>
Patchwork-id: 73522
O-Subject: [PATCH RHEL7.0 BZ1036665 218/226] perf scripting perl: Fix build error on Fedora 12
Bugzilla: 1036665
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1036665
https://bugzilla.redhat.com/show_bug.cgi?id=1036665

upstream
========
commit 3b16ff89676d9902dc39976aee3cb0314ee37d93
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Oct 14 18:25:12 2013 -0300

description
===========
Cast __u64 to u64 to silence this warning on older distros, such as
Fedora 12:

    CC       /tmp/build/perf/util/scripting-engines/trace-event-perl.o
  cc1: warnings being treated as errors
  util/scripting-engines/trace-event-perl.c: In function 'perl_process_tracepoint':
  util/scripting-engines/trace-event-perl.c:285: error: format '%lu' expects type 'long unsigned int', but argument 2 has type '__u64'
  make[1]: *** [/tmp/build/perf/util/scripting-engines/trace-event-perl.o] Error 1
  make: *** [install] Error 2
  make: Leaving directory `/home/acme/git/linux/tools/perf'
  [acme@fedora12 linux]$

Signed-off-by: Jarod Wilson <jarod@redhat.com>