[infiniband] xprtrdma: Squelch kbuild sparse complaint
Message-id: <20171011200214.23764-209-ddutile@redhat.com>
Patchwork-id: 191552
O-Subject: [PATCH RHEL-7.5 v2 208/233] xprtrdma: Squelch kbuild sparse complaint
Bugzilla: 1385309 1385649 1386645 1409099 1456667 1456687
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit eed50879d64ab1b9f76445dbab822e43a098b309
Author: Chuck Lever <chuck.lever@oracle.com>
Date:   Sat Mar 11 15:52:47 2017 -0500

    xprtrdma: Squelch kbuild sparse complaint

    New complaint from kbuild for 4.9.y:

    net/sunrpc/xprtrdma/verbs.c:489:19: sparse: incompatible types in
        comparison expression (different type sizes)

    verbs.c:
    489     max_sge = min(ia->ri_device->attrs.max_sge, RPCRDMA_MAX_SEND_SGES);

    I can't reproduce this running sparse here. Likewise, "make W=1
    net/sunrpc/xprtrdma/verbs.o" never indicated any issue.

    A little poking suggests that because the range of its values is
    small, gcc can make the actual width of RPCRDMA_MAX_SEND_SGES
    smaller than the width of an unsigned integer.

    Fixes: 16f906d66cd7 ("xprtrdma: Reduce required number of send SGEs")
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>
    Cc: stable@kernel.org
    Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>