[usb] console/font: Refactor font support code selection logic
Message-id: <1457470219-37147-12-git-send-email-dzickus@redhat.com>
Patchwork-id: 137614
O-Subject: [RHEL7 PATCH 011/423] console/font: Refactor font support code selection logic
Bugzilla: 1303209
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303209

commit d1e183c8dd38bfdd07e38a79577fe78124e63ab1
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed May 15 13:26:20 2013 +0200

    console/font: Refactor font support code selection logic

    The current Makefile rules to build font support are messy and buggy.
    Replace them by Kconfig rules:
      - Introduce CONFIG_FONT_SUPPORT, which controls the building of all font
        code,
      - Select CONFIG_FONT_SUPPORT for all drivers that use fonts,
      - Select CONFIG_FONT_8x16 for all drivers that default to the VGA8x16
        font,
      - Drop the bogus console dependency for CONFIG_VIDEO_VIVI,
      - Always process drivers/video/console/Makefile, as some drivers need
        fonts even if CONFIG_VT is not set.

    This fixes (if CONFIG_SOLO6X10=y and there are no built-in console
    drivers):

    drivers/built-in.o: In function `solo_osd_print':
    drivers/staging/media/solo6x10/solo6x10-enc.c:144: undefined reference to `.find_font'

    This fixes (if CONFIG_VT=n):

    drivers/built-in.o: In function `vivi_init':
    vivi.c:(.init.text+0x1a3da): undefined reference to `find_font'

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Hans Verkuil <hans.verkuil@cisco.com> [original part]
    Acked-by: Randy Dunlap <rdunlap@infradead.org> [drivers/video/Makefile]

Notes: usb only
Signed-off-by: Rafael Aquini <aquini@redhat.com>