[virtio] virtio_balloon: prevent uninitialized variable use
Message-id: <20170421130241.27560-8-david@redhat.com>
Patchwork-id: 177020
O-Subject: [RHEL7.4 virtio PATCH 7/7] virtio_balloon: prevent uninitialized variable use
Bugzilla: 1439570
RH-Acked-by: Ladi Prosek <lprosek@redhat.com>
RH-Acked-by: Michael S. Tsirkin <mst@redhat.com>

Bugzilla: BZ 1439570
Upstream: linux.git f0bb2d50dfcc519f06f901aac88502be6ff1df2c

commit f0bb2d50dfcc519f06f901aac88502be6ff1df2c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Mar 28 18:46:59 2017 +0200

    virtio_balloon: prevent uninitialized variable use

    The latest gcc-7.0.1 snapshot reports a new warning:

    virtio/virtio_balloon.c: In function 'update_balloon_stats':
    virtio/virtio_balloon.c:258:26: error: 'events[2]' is used uninitialized in this function [-Werror=uninitialized]
    virtio/virtio_balloon.c:260:26: error: 'events[3]' is used uninitialized in this function [-Werror=uninitialized]
    virtio/virtio_balloon.c:261:56: error: 'events[18]' is used uninitialized in this function [-Werror=uninitialized]
    virtio/virtio_balloon.c:262:56: error: 'events[17]' is used uninitialized in this function [-Werror=uninitialized]

    This seems absolutely right, so we should add an extra check to
    prevent copying uninitialized stack data into the statistics.
    >From all I can tell, this has been broken since the statistics code
    was originally added in 2.6.34.

    Fixes: 9564e138b1f6 ("virtio: Add memory statistics reporting to the balloon driver (V4)")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ladi Prosek <lprosek@redhat.com>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

Signed-off-by: David Hildenbrand <david@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>