[netdrv] mlxsw: switchib: add MLXSW_PCI dependency
Message-id: <20170411143300.8140-217-ivecera@redhat.com>
Patchwork-id: 176608
O-Subject: [RHEL7.4 PATCH v2 216/232] mlxsw: switchib: add MLXSW_PCI dependency
Bugzilla: 1414400
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1414400

Upstream commit(s):
commit 67ea7ef19bddaf75c842f56181deba89e4ea62a2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 28 15:26:04 2016 +0100

    mlxsw: switchib: add MLXSW_PCI dependency

    The newly added switchib driver fails to link if MLXSW_PCI=m:

    drivers/net/ethernet/mellanox/mlxsw/mlxsw_switchib.o: In function^Cmlxsw_sib_module_exit':
    switchib.c:(.exit.text+0x8): undefined reference to `mlxsw_pci_driver_unregister'
    switchib.c:(.exit.text+0x10): undefined reference to `mlxsw_pci_driver_unregister'
    drivers/net/ethernet/mellanox/mlxsw/mlxsw_switchib.o: In function `mlxsw_sib_module_init':
    switchib.c:(.init.text+0x28): undefined reference to `mlxsw_pci_driver_register'
    switchib.c:(.init.text+0x38): undefined reference to `mlxsw_pci_driver_register'
    switchib.c:(.init.text+0x48): undefined reference to `mlxsw_pci_driver_unregister'

    The other two such sub-drivers have a dependency, so add the same one
    here. In theory we could allow this driver if MLXSW_PCI is disabled,
    but it's probably not worth it.

    Fixes: d1ba52638456 ("mlxsw: switchib: Introduce SwitchIB and SwitchIB silicon driver")
    Reviewed-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>