[netdrv] qlcnic: don't set unused function argument
Message-id: <1471561585-12856-2-git-send-email-hpatil@redhat.com>
Patchwork-id: 157176
O-Subject: [PATCH RHEL 7.3 1/7] net: qlcnic: don't set unused function argument
Bugzilla: 1367116
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ 1367116

net commit id 287debd6aac5b9f60113d45931a53da0cd4adc94

We get a warning for qlcnic_83xx_get_mac_address when building with
"make W=1":

drivers/net/ethernet/qlogic/qlcnic/qlcnic_83xx_hw.c: In function 'qlcnic_83xx_get_mac_address':
drivers/net/ethernet/qlogic/qlcnic/qlcnic_83xx_hw.c:2156:8: error: parameter 'function' set but not used [-Werror=unused-but-set-parameter]

Clearly this is harmless, but there is also no point for setting
the variable, so we can simply remove the assignment.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Rajesh Borundia <rajesh.borundia@qlogic.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Rafael Aquini <aquini@redhat.com>