[perf] bitops: Fix signedness of compile-time hweight implementations
Message-id: <1428672113-29331-146-git-send-email-jolsa@redhat.com>
Patchwork-id: 109809
O-Subject: [PATCH RHEL7.2 BZ1209607 145/220] bitops: Fix signedness of compile-time hweight implementations
Bugzilla: 1209607
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1209607
https://bugzilla.redhat.com/show_bug.cgi?id=1209607

upstream
========
commit c32fa99f0b4252633aa464e28d1cb925bd2a79df
Author: Paul Walmsley <pwalmsley@nvidia.com>
Date: Wed Dec 18 05:02:14 2013 -0800

description
===========
Enabling '-Wsign-compare' compiler warnings on code that includes
include/linux/bitops.h can generate the following warning:

  In file included from include/linux/kernel.h:10:0,
                    from <random filename>:48:
  include/linux/bitops.h: In function 'hweight_long':
  include/linux/bitops.h:77:26: error: signed and unsigned type in conditional expression [-Werror=sign-compare]

(converted to an error with -Werror)

This is due to the use of the logical negation operator '!' in the
__const_hweight8 macro in include/asm-generic/bitops/const_hweight.h.
The use of that operator here results in a signed value.

Fix by explicitly casting the __const_hweight8 macro expansion to
'unsigned int'.  While here, clean up several checkpatch.pl warnings.

Signed-off-by: Rafael Aquini <aquini@redhat.com>