[net] sctp: fix checkpatch errors with (foo*)|foo * bar|foo* bar
Message-id: <ffd10ef25a2f4aec241457dd30410bf3e89d82c9.1465943899.git.mleitner@redhat.com>
Patchwork-id: 153211
O-Subject: [RHEL7.3 PATCH net 17/55] sctp: fix checkpatch errors with (foo*)|foo * bar|foo* bar
Bugzilla: 1337639
RH-Acked-by: Xin Long <lxin@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1337639
Backport of upstream commit: 26ac8e5fe1562831e68ccd9f7057aade37aab2a3

 commit 26ac8e5fe1562831e68ccd9f7057aade37aab2a3
 Author: wangweidong <wangweidong1@huawei.com>
 Date:   Mon Dec 23 12:16:51 2013 +0800

    sctp: fix checkpatch errors with (foo*)|foo * bar|foo* bar

    fix checkpatch errors below:
    ERROR: "(foo*)" should be "(foo *)"
    ERROR: "foo * bar" should be "foo *bar"
    ERROR: "foo* bar" should be "foo *bar"

    Signed-off-by: Wang Weidong <wangweidong1@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>