[netdrv] bnx2x: add a separate GENEVE Kconfig symbol
Message-id: <1465311336-2883-50-git-send-email-mschmidt@redhat.com>
Patchwork-id: 149408
O-Subject: [RHEL7.3 PATCH 49/60] bnx2x: add a separate GENEVE Kconfig symbol
Bugzilla: 1275795
RH-Acked-by: Ken Cox <jkc@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1275795

Upstream commit:
commit 4fee7dab07bb2c7dfc3369e0f0e28e3fd4fc00c4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 23 11:36:02 2016 +0100

    bnx2x: add a separate GENEVE Kconfig symbol

    When CONFIG_GENEVE is built as a loadable module, and bnx2x is built-in,
    we get this link error:

    drivers/net/built-in.o: In function `bnx2x_open':
    :(.text+0x33322): undefined reference to `geneve_get_rx_port'
    drivers/net/built-in.o: In function `bnx2x_sp_rtnl_task':
    :(.text+0x3e632): undefined reference to `geneve_get_rx_port'

    This avoids the problem by adding a separate Kconfig symbol named
    CONFIG_BNX2X_GENEVE that is only enabled when the code is
    reachable from the driver.

    This is the same trick that BNX2X does for VXLAN support, and
    is similar to how I40E handles both.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 883ce97d25b0 ("bnx2x: Add Geneve inner-RSS support")
    Acked-By: Yuval Mintz <Yuval.Mintz@qlogic.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Rafael Aquini <aquini@redhat.com>