[fs] btrfs: Add missing include file
Message-id: <1459456505-5012-129-git-send-email-billodo@redhat.com>
Patchwork-id: 139646
O-Subject: [RHEL7.3 PATCH V2 BZ 1298680 128/525] [fs] btrfs: Add missing include file
Bugzilla: 1298680
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

Bugzilla: 1298680
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=10759031
Tested: Locally with fstests

Backport of the following upstream commit:

    commit 4a3d1caf8a2c16c55424a0768eade54ee0922341
    Author: Guenter Roeck <linux@roeck-us.net>
    Date:   Fri Mar 13 01:58:46 2015 -0700

    fs: btrfs: Add missing include file

    Building alpha:allmodconfig fails with

    fs/btrfs/inode.c: In function 'check_direct_IO':
    fs/btrfs/inode.c:8050:2: error: implicit declaration of function 'iov_iter_alignment'

    due to a missing include file.

    Fixes: 3737c63e1fb0 ("fs: move struct kiocb to fs.h")
    Cc: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: David Sterba <dsterba@suse.cz>
    Signed-off-by: Chris Mason <clm@fb.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>