[base] regmap: Add another missing header for !CONFIG_REGMAP stubs
Message-id: <1381413926-15908-546-git-send-email-vfalico@redhat.com>
Patchwork-id: 69302
O-Subject: [RHEL7 PATCH 545/820] regmap: Add another missing header for !CONFIG_REGMAP stubs
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 3f0fa9a808f98fa10a18ba2a73f13d65fda990fb
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=3f0fa9a808f98fa10a18ba2a73f13d65fda990fb
Stable: f1179e006ed4315834bdbf0982b40f7029cf0977
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=f1179e006ed4315834bdbf0982b40f7029cf0977

Description
----------------------------
Backport from linux-3.10.y stable.

From: Kevin Hilman <khilman@linaro.org>
Subject: regmap: Add another missing header for !CONFIG_REGMAP stubs

commit 3f0fa9a808f98fa10a18ba2a73f13d65fda990fb upstream.

The use of WARN_ON() needs the definitions from bug.h, without it
you can get:

include/linux/regmap.h: In function 'regmap_write':
include/linux/regmap.h:525:2: error: implicit declaration of function 'WARN_ONCE' [-Werror=implicit-function-declaration]

Signed-off-by: Kevin Hilman <khilman@linaro.org>
Signed-off-by: Mark Brown <broonie@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit f1179e006ed4315834bdbf0982b40f7029cf0977)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>