[tools] tools string: Use __fallthrough in perf_atoll()
Message-id: <20170807084247.7531-35-jolsa@redhat.com>
Patchwork-id: 181959
O-Subject: [PATCH RHEL7.5 34/94] tools string: Use __fallthrough in perf_atoll()
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 94bdd5edb34e472980d1e18b4600d6fb92bd6b0a
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Feb 8 17:01:46 2017 -0300

description
===========
The implicit fall through case label here is intended, so let us inform
that to gcc >= 7:

    CC       /tmp/build/perf/util/string.o
  util/string.c: In function 'perf_atoll':
  util/string.c:22:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
      if (*p)
         ^
  util/string.c:24:3: note: here
     case '\0':
     ^~~~

Signed-off-by: Rafael Aquini <aquini@redhat.com>