[pci] Move pci_set_flags() from asm-generic/pci-bridge.h to linux/pci.h
Message-id: <20170105184329.6036.89587.stgit@amt.stowe>
Patchwork-id: 162122
O-Subject: [RHEL7.4 PATCH 1/2] PCI: Move pci_set_flags() from asm-generic/pci-bridge.h to linux/pci.h
Bugzilla: 1392577
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1392577
Upstream Status: 5bbe029ff7bc8ff82ef31d3480d68c95642a3c7a

commit 5bbe029ff7bc8ff82ef31d3480d68c95642a3c7a
Author: Bjorn Helgaas <bhelgaas@google.com>
Date:   Fri Feb 5 14:57:47 2016 -0600

    PCI: Move pci_set_flags() from asm-generic/pci-bridge.h to linux/pci.h

    The PCI flag management constants and functions were previously declared in
    include/asm-generic/pci-bridge.h.  But they are not specific to bridges,
    and arches did not include pci-bridge.h consistently.

    Move the following interfaces and related constants to include/linux/pci.h
    and remove pci-bridge.h:

      pci_set_flags()
      pci_add_flags()
      pci_clear_flags()
      pci_has_flag()

    This fixes these warnings when building for some arches:

      drivers/pci/host/pcie-designware.c:562:20: error: 'PCI_PROBE_ONLY' undeclared (first use in this function)
      drivers/pci/host/pcie-designware.c:562:7: error: implicit declaration of function 'pci_has_flag' [-Werror=implicit-function-declaration]

    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>