[net] bonding: bond_sysfs.c checkpatch cleanup
Message-id: <1416574342-24493-16-git-send-email-nikolay@redhat.com>
Patchwork-id: 100431
O-Subject: [RHEL7.2 PATCH BZ 1166647 015/336] bonding: bond_sysfs.c checkpatch cleanup
Bugzilla: 1166647
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>

From: dingtianhong <dingtianhong@huawei.com>

net/bonding/bond_sysfs.c:1302: ERROR: else should follow close brace '}'
net/bonding/bond_sysfs.c:1314: ERROR: else should follow close brace '}'

Signed-off-by: Ding Tianhong <dingtianhong@huawei.com>
Cc: Jay Vosburgh <fubar@us.ibm.com>
Cc: Andy Gospodarek <andy@greyhouse.net>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 38c4916a7874aff9dc07a68bf8e7e4136b00f8dd)

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>