[fs] btrfs: incremental send, fix clone operations for compressed extents
Message-id: <1459456505-5012-223-git-send-email-billodo@redhat.com>
Patchwork-id: 140094
O-Subject: [RHEL7.3 PATCH V2 BZ 1298680 222/525] [fs] Btrfs: incremental send, fix clone operations for compressed extents
Bugzilla: 1298680
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

Bugzilla: 1298680
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=10759031
Tested: Locally with fstests

Backport of the following upstream commit:

    commit 619d8c4ef7c5dd346add55da82c9179cd2e3387e
    Author: Filipe Manana <fdmanana@suse.com>
    Date:   Sun May 3 01:56:00 2015 +0100

    Btrfs: incremental send, fix clone operations for compressed extents

    Marc reported a problem where the receiving end of an incremental send
    was performing clone operations that failed with -EINVAL. This happened
    because, unlike for uncompressed extents, we were not checking if the
    source clone offset and length, after summing the data offset, falls
    within the source file's boundaries.

    So make sure we do such checks when attempting to issue clone operations
    for compressed extents.

    Problem reproducible with the following steps:

      $ mkfs.btrfs -f /dev/sdb
      $ mount -o compress /dev/sdb /mnt
      $ mkfs.btrfs -f /dev/sdc
      $ mount -o compress /dev/sdc /mnt2

      # Create the file with a single extent of 128K. This creates a metadata file
      # extent item with a data start offset of 0 and a logical length of 128K.
      $ xfs_io -f -c "pwrite -S 0xaa 64K 128K" -c "fsync" /mnt/foo

      # Now rewrite the range 64K to 112K of our file. This will make the inode's
      # metadata continue to point to the 128K extent we created before, but now
      # with an extent item that points to the extent with a data start offset of
      # 112K and a logical length of 16K.
      # That metadata file extent item is associated with the logical file offset
      # at 176K and covers the logical file range 176K to 192K.
      $ xfs_io -c "pwrite -S 0xbb 64K 112K" -c "fsync" /mnt/foo

      # Now rewrite the range 180K to 12K. This will make the inode's metadata
      # continue to point the the 128K extent we created earlier, with a single
      # extent item that points to it with a start offset of 112K and a logical
      # length of 4K.
      # That metadata file extent item is associated with the logical file offset
      # at 176K and covers the logical file range 176K to 180K.
      $ xfs_io -c "pwrite -S 0xcc 180K 12K" -c "fsync" /mnt/foo

      $ btrfs subvolume snapshot -r /mnt /mnt/snap1

      $ touch /mnt/bar
      # Calls the btrfs clone ioctl.
      $ ~/xfstests/src/cloner -s $((176 * 1024)) -d $((176 * 1024)) \
        -l $((4 * 1024)) /mnt/foo /mnt/bar

      $ btrfs subvolume snapshot -r /mnt /mnt/snap2

      $ btrfs send /mnt/snap1 | btrfs receive /mnt2
      At subvol /mnt/snap1
      At subvol snap1

      $ btrfs send -p /mnt/snap1 /mnt/snap2 | btrfs receive /mnt2
      At subvol /mnt/snap2
      At snapshot snap2
      ERROR: failed to clone extents to bar
      Invalid argument

    A test case for fstests follows soon.

    Reported-by: Marc MERLIN <marc@merlins.org>
    Tested-by: Marc MERLIN <marc@merlins.org>
    Signed-off-by: Filipe Manana <fdmanana@suse.com>
    Tested-by: David Sterba <dsterba@suse.cz>
    Tested-by: Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
    Signed-off-by: Chris Mason <clm@fb.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>