[tools] perf tools: Remove duplicate typedef config_term_func_t definition
Message-id: <1463569977-29479-166-git-send-email-jolsa@redhat.com>
Patchwork-id: 145843
O-Subject: [PATCH RHEL7.3 BZ1336447 165/324] perf tools: Remove duplicate typedef config_term_func_t definition
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit 58de6ed0a9a32e4b1cf22cc0c46ca16056763f19
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Feb 19 19:51:13 2016 -0300

description
===========
Older compilers don't like this, for instance, on RHEL6.7:

    CC       /tmp/build/perf/util/parse-events.o
  util/parse-events.c:844: error: redefinition of typedef config_term_func_t
  util/parse-events.c:353: note: previous declaration of config_term_func_t was here

So remove the second definition, that should've been just moved in 43d0b97817a4
("perf tools: Enable config and setting names for legacy cache events"), not copied.

Fixes: 43d0b97817a4 ("perf tools: Enable config and setting names for legacy cache events")
Signed-off-by: Rafael Aquini <aquini@redhat.com>