[virt] kvm: Fix indentation in kvm_main.c
Message-id: <1457546986-23318-47-git-send-email-pbonzini@redhat.com>
Patchwork-id: 138135
O-Subject: [RHEL7.3 PATCH 046/200] KVM: Fix indentation in kvm_main.c
Bugzilla: 1301888
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
RH-Acked-by: Bandan Das <bsd@redhat.com>
RH-Acked-by: Radim Krcmar <rkrcmar@redhat.com>

From: Xiubo Li <lixiubo@cmss.chinamobile.com>

ERROR: code indent should use tabs where possible
+                                 const struct kvm_io_range *r2)$

WARNING: please, no spaces at the start of a line
+                                 const struct kvm_io_range *r2)$

This patch fixes this ERROR & WARNING to reduce noise when checking new
patches in kvm_main.c.

Signed-off-by: Xiubo Li <lixiubo@cmss.chinamobile.com>
Signed-off-by: Marcelo Tosatti <mtosatti@redhat.com>
(cherry picked from commit 20e87b72244f922f420d83b0b15b42d17b92acae)
Signed-off-by: Rafael Aquini <aquini@redhat.com>