[cpufreq] intel_pstate: fix intel_pstate_exit_perf_limits() prototype
Message-id: <1504119829-27117-130-git-send-email-prarit@redhat.com>
Patchwork-id: 183837
O-Subject: [RHEL7.5 BZ 1465349 129/179 v2] cpufreq: intel_pstate: fix intel_pstate_exit_perf_limits() prototype
Bugzilla: 1465349
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1465349

commit 7a3ba767f6bf9d98f1c823417908719af4a22a65
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 25 17:50:20 2016 +0100

    cpufreq: intel_pstate: fix intel_pstate_exit_perf_limits() prototype

    The addition of the generic governor support marked the
    intel_pstate_exit_perf_limits as inline(), which fixed a warning,
    but it introduced another warning:

    drivers/cpufreq/intel_pstate.c: In function intel_pstate_exit_perf_limits:
    drivers/cpufreq/intel_pstate.c:483:1: error: no return statement in function returning non-void [-Werror=return-type]

    This changes it back to a 'void' return type, and changes the
    corresponding intel_pstate_init_acpi_perf_limits() function to
    be inline as well for consistency.

    Fixes: 001c76f05b01 (cpufreq: intel_pstate: Generic governors support)
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Cc: Lenny Szubowicz <lszubowi@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>