[redhat] makefile: Fix uapi version.h build dependency
Message-id: <1486392900-6800-1-git-send-email-prarit@redhat.com>
Patchwork-id: 165054
O-Subject: [RHEL7.4 PATCH BZ 1419011] Makefile: Fix uapi version.h build dependency
Bugzilla: 1419011
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Josh Poimboeuf <jpoimboe@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1419011
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=12491404

RHEL_only.

Compiling RHEL7 latest with 'make -j32' results in the following error

/scripts/mod/modpost.c:23:56: fatal error:
../../include/generated/uapi/linux/version.h: No such file or directory

uapi version.h file must be a requirement of the scripts portion of the
build.

Weekend compilations of gcc between RHEL7.2, RHEL7.3, and RHEL7.4-latest
does not show an increase in build times, so this is likely something we
just happened to trip over.

Fixes: 9af8c39 ("[kernel] modules: add rhelversion MODULE_INFO tag")
Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Cc: Artem Savkov <asavkov@redhat.com>

Cc: Rafael Aquini <aquini@redhat.com>
Cc: Josh Poimboeuf <jpoimboe@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>