[tools] perf tests: Use perf_evlist__strerror_open() to provide hints about max_freq
Message-id: <1463569977-29479-147-git-send-email-jolsa@redhat.com>
Patchwork-id: 145739
O-Subject: [PATCH RHEL7.3 BZ1336447 146/324] perf tests: Use perf_evlist__strerror_open() to provide hints about max_freq
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit 6880bbf96930ec6f8b40b5b93f21973f3297672a
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Feb 18 13:40:57 2016 -0300

description
===========
Before:

  # perf test -v "code reading" 2>&1 | tail -4
  perf_evlist__open failed
  test child finished with -1
  ---- end ----
  Test object code reading: FAILED!
  #

After:

  # perf test -v "code reading" 2>&1 | tail -7
  perf_evlist__open() failed!
  Error: Invalid argument.
  Hint:  Check /proc/sys/kernel/perf_event_max_sample_rate.
  Hint:  The current value is 1000 and 4000 is being requested.
  test child finished with -1
  ---- end ----
  Test object code reading: FAILED!
  #

Signed-off-by: Rafael Aquini <aquini@redhat.com>