[netdrv] mlx5e: add CONFIG_INET dependency
Message-id: <20171109065423.8574-425-ddutile@redhat.com>
Patchwork-id: 197399
O-Subject: [PATCH RHEL-7.5 v2 424/468] mlx5e: add CONFIG_INET dependency
Bugzilla: 1462433 1499362
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit 2432a3fb5cff026005aaad24e42226402f7fd0aa
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 13:27:49 2017 +0200

    mlx5e: add CONFIG_INET dependency

    We now reference the arp_tbl, which requires IPv4 support to be
    enabled in the kernel, otherwise we get a link error:

    drivers/net/built-in.o: In function `mlx5e_tc_update_neigh_used_value':
    (.text+0x16afec): undefined reference to `arp_tbl'
    drivers/net/built-in.o: In function `mlx5e_rep_neigh_init':
    en_rep.c:(.text+0x16c16d): undefined reference to `arp_tbl'
    drivers/net/built-in.o: In function `mlx5e_rep_netevent_event':
    en_rep.c:(.text+0x16cbb5): undefined reference to `arp_tbl'

    This adds a Kconfig dependency for it.

    Fixes: 232c001398ae ("net/mlx5e: Add support to neighbour update flow")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1462433

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>