[scsi] lpfc: code cleanups in NVME initiator base
Message-id: <1492091988-25096-1-git-send-email-emilne@redhat.com>
Patchwork-id: 176721
O-Subject: [RHEL7.4 PATCH e-stor 60/59] scsi: lpfc: code cleanups in NVME initiator base
Bugzilla: 1384922
RH-Acked-by: Tomas Henzl <thenzl@redhat.com>
RH-Acked-by: Rob Evers <revers@redhat.com>
RH-Acked-by: Maurizio Lombardi <mlombard@redhat.com>

(Adding this additional patch to the series to fix a hang uncovered during
FCoE testing, this was caused by the use of nested spin_lock/unlock_irq()
in lpfc_sli4_dequeue_nport_iocbs() and was fixed by this patch.)

From upstream linux-scsi, branch 4.11/scsi-fixes
commit 2ade92ae6d6572858acb2bde6d3664af3ad592e2

Tested by Ewan D. Milne using 2 systems with NVMe cards and NVMe-capable
HBAs connected in a back-to-back Initiator & Target configuration.

This patch addresses the smatch issues identified by Dan Carpenter
in http://www.spinics.net/lists/linux-scsi/msg105663.html

The issues are:

drivers/scsi/lpfc/lpfc_hbadisc.c:316 lpfc_dev_loss_tmo_handler()
warn: we tested 'vport->load_flag & 2' before and it was 'false'

Action: removed item from test

drivers/scsi/lpfc/lpfc_hbadisc.c:701 lpfc_work_done()
warn: test_bit() takes a bit number

Action: changed definition so bit number

drivers/scsi/lpfc/lpfc_hbadisc.c:2206 lpfc_mbx_cmpl_fcf_scan_read_fcf_rec()
error: uninitialized symbol 'vlan_id'.
drivers/scsi/lpfc/lpfc_hbadisc.c:2582 lpfc_mbx_cmpl_fcf_rr_read_fcf_rec()
error: uninitialized symbol 'vlan_id'.
drivers/scsi/lpfc/lpfc_hbadisc.c:2683 lpfc_mbx_cmpl_read_fcf_rec() error:
uninitialized symbol 'vlan_id'.

Action: initilized value

drivers/scsi/lpfc/lpfc_hbadisc.c:4025 lpfc_register_remote_port()
error: we previously assumed 'rdata' could be null (see line 4023)

Action: refactored check block

drivers/scsi/lpfc/lpfc_hbadisc.c:4613 lpfc_sli4_dequeue_nport_iocbs()
error: double unlock 'irq:'

Action: removed inner irq reference

Signed-off-by: Dick Kennedy <dick.kennedy@broadcom.com>
Signed-off-by: James Smart <james.smart@broadcom.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

(Modified for RHEL7 -- merge differences)

Signed-off-by: Ewan D. Milne <emilne@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>