[uapi] smc_diag.h: fix include from userland
Message-id: <20171109065423.8574-417-ddutile@redhat.com>
Patchwork-id: 197401
O-Subject: [PATCH RHEL-7.5 v2 416/468] smc_diag.h: fix include from userland
Bugzilla: 1499362
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit ea6819e1f2d6c30624ea067f4b3a50a3cca79d8a
Author: Nicolas Dichtel <nicolas.dichtel@6wind.com>
Date:   Mon Mar 27 14:20:14 2017 +0200

    smc_diag.h: fix include from userland

    This patch prepares the uapi export by fixing the following error:

    .../linux/smc_diag.h:6:27: fatal error: rdma/ib_verbs.h: No such file or directory
     #include <rdma/ib_verbs.h>

    Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
    Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>

RHEL-7 NOTE:
Dropped smc_diag.h since smc not supported in RHEL-7.

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>