[tools] perf trace: Validate syscall list passed via -e argument
Message-id: <1455060817-26852-308-git-send-email-jolsa@redhat.com>
Patchwork-id: 134097
O-Subject: [PATCH RHEL7.3 BZ1305882 307/360] perf trace: Validate syscall list passed via -e argument
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit d0cc439b30be638c3a606767e9469c300d397433
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Jun 25 19:32:33 2015 -0300

description
===========
The 'trace' tool was accepting any names passed and just looking if
syscalls returned via the raw_syscalls:* tracepoints were in that list,
leading to it accepting perf events and then never finding any, as those
are not valid syscall names, confusing users.

Fix it by checking each entry in the list using audit_name_to_syscall,
telling the user which entries are invalid and suggesting where to look
for valid syscall names.

E.g:

  [root@zoo ~]# trace -e open,foo,bar,close,baz
  Error: Invalid syscall bar, baz, foo
  Hint:	 try 'perf list syscalls:sys_enter_*'
  Hint:	 and: 'man syscalls'
  [root@zoo ~]#

Signed-off-by: Rafael Aquini <aquini@redhat.com>