[virt] tools/virtio: fix missing kmemleak_ignore symbol
Message-id: <1406112611-9862-3-git-send-email-brueckner@redhat.com>
Patchwork-id: 86317
O-Subject: [RHEL7.1 PATCH 02/23] [virt] tools/virtio: fix missing kmemleak_ignore symbol
Bugzilla: 1088554
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Description
-----------
commit 6abb2dd92868927c1d680546b9d13f208373d517
Author: Joel Stanley <joel@jms.id.au>
Date:   Thu Feb 13 15:03:46 2014 +1030

    tools/virtio: fix missing kmemleak_ignore symbol

    In commit bb478d8b167 virtio_ring: plug kmemleak false positive,
    kmemleak_ignore was introduced. This broke compilation of virtio_test:

      cc -g -O2 -Wall -I. -I ../../usr/include/ -Wno-pointer-sign
        -fno-strict-overflow -fno-strict-aliasing -fno-common -MMD
        -U_FORTIFY_SOURCE   -c -o virtio_ring.o ../../drivers/virtio/virtio_ring.c
      ../../drivers/virtio/virtio_ring.c: In function 'vring_add_indirect':
      ../../drivers/virtio/virtio_ring.c:177:2: warning: implicit declaration
      of function 'kmemleak_ignore' [-Wimplicit-function-declaration]
        kmemleak_ignore(desc);
        ^
      cc   virtio_test.o virtio_ring.o   -o virtio_test
      virtio_ring.o: In function `vring_add_indirect':
      tools/virtio/../../drivers/virtio/virtio_ring.c:177:
      undefined reference to `kmemleak_ignore'

    Add a dummy header for tools/virtio, and add #incldue <linux/kmemleak.h>
    to drivers/virtio/virtio_ring.c so it is picked up by the userspace
    tools.

    Signed-off-by: Joel Stanley <joel@jms.id.au>
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

Bugzilla
--------
BZ 1088554
https://bugzilla.redhat.com/show_bug.cgi?id=1088554

Upstream status of the patch
----------------------------
The patch is upstream as of kernel version
http://git.kernel.org/?p=linux/kernel/git/torvalds/linux-2.6.git;a=commitdiff;h=6abb2dd92868927c1d680546b9d13f208373d517

Brew
----
https://brewweb.devel.redhat.com/taskinfo?taskID=7725759

Test status
-----------
The patch has been tested and fixes the problem.
The fix has been verified by the IBM test department.

Signed-off-by: Jarod Wilson <jarod@redhat.com>