[net] tcp: tcp_conn_request: fix build error when IPv6 is disabled
Message-id: <1421064408-18421-149-git-send-email-fwestpha@redhat.com>
Patchwork-id: 102788
O-Subject: [PATCH 148/153] [RHEL7.2 net] tcp: tcp_conn_request: fix build error when IPv6 is disabled
Bugzilla: 1151756
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Daniel Borkmann <dborkman@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Hannes Frederic Sowa <hannes@redhat.com>

obviously this isn't strictly required but automated regression-find
scripts then flag this one as missing in rhel7.

commit 4135ab8208048a1586385fae1298726d7dacfc26
Author: Octavian Purdila <octavian.purdila@intel.com>
Date:   Sat Jun 28 21:20:54 2014 +0300

    tcp: tcp_conn_request: fix build error when IPv6 is disabled

    Fixes build error introduced by commit 1fb6f159fd21c64 (tcp: add
    tcp_conn_request):

    net/ipv4/tcp_input.c: In function 'pr_drop_req':
    net/ipv4/tcp_input.c:5889:130: error: 'struct sock_common' has no member named 'skc_v6_daddr'

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Octavian Purdila <octavian.purdila@intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>