[redhat] don't allow localized date output when running in non english locale
Message-id: <1460036947-30074-1-git-send-email-herton@redhat.com>
Patchwork-id: 140324
O-Subject: [RHEL7 PATCH INTERNAL] [redhat] don't allow localized date output when running in non english locale
Bugzilla:
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Aristeu Rozanski <aris@redhat.com>

If we run the rh-release etc. target on a system with a non english locale, we
can have a localized output from date added to the kernel spec changelog, which
is not what we want, and later on causes this type of failure:

error: bad date in %changelog: Qua Abr 06 2016 Herton R. Krzesinski (...)

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>