[tools] perf probe: Show better error message when failed to find variable
Message-id: <1455060817-26852-157-git-send-email-jolsa@redhat.com>
Patchwork-id: 133946
O-Subject: [PATCH RHEL7.3 BZ1305882 156/360] perf probe: Show better error message when failed to find variable
Bugzilla: 1305882
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1305882
https://bugzilla.redhat.com/show_bug.cgi?id=1305882

upstream
========
commit 7d5eaba9b33682b734e3a79c21c4a9a5f91624b1
Author: He Kuang <hekuang@huawei.com>
Date: Mon May 11 09:25:04 2015 +0000

description
===========
Indicate to check variable location range in error message when we got
failed to find the variable.

Before this patch:

  $ perf probe --add 'generic_perform_write+118 bytes'
  Failed to find the location of bytes at this address.
   Perhaps, it has been optimized out.
    Error: Failed to add events.

After this patch:

  $ perf probe --add 'generic_perform_write+118 bytes'
  Failed to find the location of the 'bytes' variable at this address.
   Perhaps it has been optimized out.
   Use -V with the --range option to show 'bytes' location range.
    Error: Failed to add events.

[ Improve the error message based on lkml thread ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>