[netdrv] i40e: fix misleading indentation
Message-id: <20170303145441.4217-18-sassmann@redhat.com>
Patchwork-id: 169694
O-Subject: [RHEL7.4 PATCH 017/211] i40e: fix misleading indentation
Bugzilla: 1374546 1390452 1390449 1385344 1384456 1378964 1371500 1348490 1383521
RH-Acked-by: Ken Cox <jkc@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1383521
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12678252

Newly added code in i40e_vc_config_promiscuous_mode_msg() is indented
in a way that gcc rightly complains about:

drivers/net/ethernet/intel/i40e/i40e_virtchnl_pf.c: In function 'i40e_vc_config_promiscuous_mode_msg':
drivers/net/ethernet/intel/i40e/i40e_virtchnl_pf.c:1543:4: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
    if (f->vlan >= 0 && f->vlan <= I40E_MAX_VLANID)
    ^~
drivers/net/ethernet/intel/i40e/i40e_virtchnl_pf.c:1550:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
     aq_err = pf->hw.aq.asq_last_status;

>From the context, it looks like the aq_err assignment was meant to be
inside of the conditional expression, so I'm adding the appropriate
curly braces now.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 5676a8b9cd9a ("i40e: Add VF promiscuous mode driver support")
Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
Signed-off-by: Stefan Assmann <sassmann@redhat.com>
(cherry picked from commit ce927db48721235b3a08142b6d9f9a906e4e626f)
Signed-off-by: Rafael Aquini <aquini@redhat.com>