[tools] perf cpumap: Introduce cpu_map__snprint_mask()
Message-id: <20170830160540.26618-33-jolsa@redhat.com>
Patchwork-id: 183448
O-Subject: [PATCH RHEL7.5 BZ1480522 032/248] perf cpumap: Introduce cpu_map__snprint_mask()
Bugzilla: 1480522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1480522
https://bugzilla.redhat.com/show_bug.cgi?id=1480522

upstream
========
commit 4400ac8a9a900318f8516dc0fb94075cb3fdb50d
Author: Namhyung Kim <namhyung@kernel.org>
Date: Fri Feb 24 10:12:49 2017 +0900

description
===========
The cpu_map__snprint_mask() generates a string representation of a
cpumask bitmap.  For cpu 0 to 11, it'll return "fff".

Committer notes:

Fix compiler warning on some toolchains:

    19 fedora:24-x-ARC-uClibc: FAIL

    CC       /tmp/build/perf/util/cpumap.o
  util/cpumap.c: In function 'hex_char':
  util/cpumap.c:679:2: error: comparison is always true due to limited range of data type [-Werror=type-limits]
    if (0 <= val && val <= 9)
    ^
  cc1: all warnings being treated as errors

Applying patch from Namhyung that makes function receive an 'unsigned
char', that is what the callers are passing to this function.

Signed-off-by: Rafael Aquini <aquini@redhat.com>