[netdrv] cxgb4: hide unused warnings
Message-id: <1505751877-18598-7-git-send-email-avynipad@redhat.com>
Patchwork-id: 185501
O-Subject: [RHEL7.5 PATCHv2 BZ 1458296 06/31] cxgb4: hide unused warnings
Bugzilla: 1458296
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1458296

commit 0a327889f64619ac3ec886208644191cd87de525
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 18 15:52:51 2017 +0100

    cxgb4: hide unused warnings

    The two new variables are only used inside of an #ifdef and cause
    harmless warnings when that is disabled:

    drivers/net/ethernet/chelsio/cxgb4/cxgb4_main.c: In function 'init_one':
    drivers/net/ethernet/chelsio/cxgb4/cxgb4_main.c:4646:9: error: unused variable 'port_vec' [-Werror=unused-variable]
    drivers/net/ethernet/chelsio/cxgb4/cxgb4_main.c:4646:6: error: unused variable 'v' [-Werror=unused-variable]

    This adds another #ifdef around the declarations.

    Fixes: 96fe11f27b70 ("cxgb4: Implement ndo_get_phys_port_id for mgmt dev")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Sai Vemuri <svemuri@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Arjun Vynipadath <avynipad@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>