[tools] tools lib subcmd: Make it an error to pass a signed value to OPTION_UINTEGER
Message-id: <20170807084247.7531-57-jolsa@redhat.com>
Patchwork-id: 181996
O-Subject: [PATCH RHEL7.5 56/94] tools lib subcmd: Make it an error to pass a signed value to OPTION_UINTEGER
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit b98897166280c4cfb9bc5a6c1b5682528eb4abff
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 13:55:40 2017 -0300

description
===========
Options marked OPTION_UINTEGER or OPTION_U64 clearly indicates that an
unsigned value is expected, so just error out when a negative value is
passed, instead of returning something undesired to the tool.

E.g.:

  # perf bench futex hash -t -4
  # Running 'futex/hash' benchmark:
   Error: switch `t' expects an unsigned numerical value
   Usage: perf bench futex hash <options>

      -t, --threads <n>     Specify amount of threads
  #

Signed-off-by: Rafael Aquini <aquini@redhat.com>