[alsa] jack: fix a randconfig build issue
Message-id: <143386227049-689-patchset-jkysela@redhat.com>
Patchwork-id: 116864
O-Subject: [RHEL 7.2 PATCH 688/763] ALSA: jack: fix a randconfig build issue
Bugzilla: 1197064
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Building errors reported such as below when 'CONFIG_INPUT=m':
...undefined reference to `input_xxx'...

Here change to enable SND_JACK selectively to fix the issue.

Also remove the config 'SND_HDA_INPUT_JACK' which won't be
used anymore.

Signed-off-by: Jie Yang <yang.jie@intel.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>
Signed-off-by: Jaroslav Kysela <perex@perex.cz>

(picked from kernel: 973109cafc9d11e41be4d64667ff2165bf79d948)
rhbz#1197064
Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>