[tools] perf tools: Fix build on older systems
Message-id: <1463569977-29479-165-git-send-email-jolsa@redhat.com>
Patchwork-id: 145721
O-Subject: [PATCH RHEL7.3 BZ1336447 164/324] perf tools: Fix build on older systems
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit 2c97b0d4a757eec7b83acfe3895d94ad4db13827
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Feb 19 19:47:04 2016 -0300

description
===========
In RHEL 6.7:

  CC       /tmp/build/perf/util/parse-events.o
  cc1: warnings being treated as errors
  util/parse-events.c: In function parse_events_add_cache:
  util/parse-events.c:366: error: declaration of error shadows a global declaration
  util/util.h:136: error: shadowed declaration is here

Rename it to 'err'.

Fixes: 43d0b97817a4 ("perf tools: Enable config and setting names for legacy cache events")
Signed-off-by: Rafael Aquini <aquini@redhat.com>