[tools] tools strfilter: Use __fallthrough
Message-id: <20170807084247.7531-36-jolsa@redhat.com>
Patchwork-id: 181969
O-Subject: [PATCH RHEL7.5 35/94] tools strfilter: Use __fallthrough
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit d64b721d27aef3fbeb16ecda9dd22ee34818ff70
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Feb 8 17:01:46 2017 -0300

description
===========
The implicit fall through case label here is intended, so let us inform
that to gcc >= 7:

  util/strfilter.c: In function 'strfilter_node__sprint':
  util/strfilter.c:270:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (len < 0)
        ^
  util/strfilter.c:272:2: note: here
    case '!':
    ^~~~
  cc1: all warnings being treated as errors

Signed-off-by: Rafael Aquini <aquini@redhat.com>