[usb] host: Host drivers relying on DMA should depend on HAS_DMA
Message-id: <1465525749-9195-117-git-send-email-torez@redhat.com>
Patchwork-id: 150090
O-Subject: [RHEL7 BZ1332712 v2 116/196] usb: host: Host drivers relying on DMA should depend on HAS_DMA
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit cf34be7a223b7702e61668e0e3e64ceab4fdd06e
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Sun Feb 21 22:48:47 2016 +0100

    usb: host: Host drivers relying on DMA should depend on HAS_DMA

    If NO_DMA=y:

        ERROR: "bad_dma_ops" [drivers/usb/host/xhci-plat-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/xhci-mtk.ko] undefined!
        ERROR: "dma_pool_destroy" [drivers/usb/host/xhci-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/xhci-hcd.ko] undefined!
        ERROR: "dma_pool_free" [drivers/usb/host/xhci-hcd.ko] undefined!
        ERROR: "dma_pool_alloc" [drivers/usb/host/xhci-hcd.ko] undefined!
        ERROR: "dma_pool_create" [drivers/usb/host/xhci-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/ohci-platform.ko] undefined!
        ERROR: "dma_pool_destroy" [drivers/usb/host/ohci-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/ohci-hcd.ko] undefined!
        ERROR: "dma_pool_free" [drivers/usb/host/ohci-hcd.ko] undefined!
        ERROR: "dma_pool_alloc" [drivers/usb/host/ohci-hcd.ko] undefined!
        ERROR: "dma_pool_create" [drivers/usb/host/ohci-hcd.ko] undefined!
        ERROR: "dma_pool_create" [drivers/usb/host/fotg210-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/fotg210-hcd.ko] undefined!
        ERROR: "dma_pool_destroy" [drivers/usb/host/fotg210-hcd.ko] undefined!
        ERROR: "dma_pool_alloc" [drivers/usb/host/fotg210-hcd.ko] undefined!
        ERROR: "dma_pool_free" [drivers/usb/host/fotg210-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/ehci-platform.ko] undefined!
        ERROR: "dma_pool_destroy" [drivers/usb/host/ehci-hcd.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/usb/host/ehci-hcd.ko] undefined!
        ERROR: "dma_pool_free" [drivers/usb/host/ehci-hcd.ko] undefined!
        ERROR: "dma_pool_alloc" [drivers/usb/host/ehci-hcd.ko] undefined!
        ERROR: "dma_pool_create" [drivers/usb/host/ehci-hcd.ko] undefined!

    Add dependencies on HAS_DMA to fix this.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>