[tools] perf symbols: Fix mismatched declarations for elf_getphdrnum
Message-id: <1455542356-29341-77-git-send-email-jolsa@redhat.com>
Patchwork-id: 134454
O-Subject: [PATCH RHEL7.3 BZ1306834 076/237] perf symbols: Fix mismatched declarations for elf_getphdrnum
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1306834
https://bugzilla.redhat.com/show_bug.cgi?id=1306834

upstream
========
commit f785f2357673d520a0b7b468973cdd197f336494
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Jul 28 12:01:33 2015 -0300

description
===========
When HAVE_ELF_GETPHDRNUM_SUPPORT is false we trip on this problem:

    CC       /tmp/build/perf/util/symbol-elf.o
  util/symbol-elf.c:41:12: error: static declaration of elf_getphdrnum follows non-static declaration
   static int elf_getphdrnum(Elf *elf, size_t *dst)
            ^
  In file included from util/symbol.h:19:0,
                   from util/symbol-elf.c:8:
  /usr/include/libelf.h:206:12: note: previous declaration of elf_getphdrnum was here
   extern int elf_getphdrnum (Elf *__elf, size_t *__dst);
            ^
    MKDIR    /tmp/build/perf/bench/
  /home/git/linux/tools/build/Makefile.build:68: recipe for target '/tmp/build/perf/util/symbol-elf.o' failed
  make[3]: *** [/tmp/build/perf/util/symbol-elf.o] Error 1

Fix it.

Signed-off-by: Rafael Aquini <aquini@redhat.com>