[netdrv] qed: Fix uninitialized data in aRFS infrastructure
Message-id: <20171109065423.8574-424-ddutile@redhat.com>
Patchwork-id: 197398
O-Subject: [PATCH RHEL-7.5 v2 423/468] qed: Fix uninitialized data in aRFS infrastructure
Bugzilla: 1462433 1499362
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit aa4ad88cfcd4ee45f527fb982140576711e3b501
Author: Mintz, Yuval <Yuval.Mintz@cavium.com>
Date:   Sun May 14 12:21:23 2017 +0300

    qed: Fix uninitialized data in aRFS infrastructure

    Current memset is using incorrect type of variable, causing the
    upper-half of the strucutre to be left uninitialized and causing:

      ethernet/qlogic/qed/qed_init_fw_funcs.c: In function 'qed_set_rfs_mode_disable':
      ethernet/qlogic/qed/qed_init_fw_funcs.c:993:3: error: '*((void *)&ramline+4)' is used uninitialized in this function [-Werror=uninitialized]

    Fixes: d51e4af5c209 ("qed: aRFS infrastructure support")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Yuval Mintz <Yuval.Mintz@cavium.com>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1462433

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>