[tools] perf probe: Fix to show correct error message for $vars and $params
Message-id: <1477399629-8377-233-git-send-email-jolsa@redhat.com>
Patchwork-id: 159742
O-Subject: [PATCH RHEL7.4 BZ1387909 232/322] perf probe: Fix to show correct error message for $vars and $params
Bugzilla: 1387909
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1387909
https://bugzilla.redhat.com/show_bug.cgi?id=1387909

upstream
========
commit f6eb0518f325ef0d6557fbef5c7ebe48a81e74db
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Tue Jul 12 19:04:34 2016 +0900

description
===========
Fix to show correct error messages for $vars and $params because
those special variables requires debug information to find the
real variables or function parameters.

E.g. without this fix;
  ----
  # perf probe -x /lib64/libc-2.23.so getaddrinfo \$params
  Failed to write event: Invalid argument
  Please upgrade your kernel to at least 3.14 to have access to feature $params
    Error: Failed to add events.
  ----

Perf ends up with an error, but the message is not correct.  With this
fix, perf shows correct error message as below.

  ----
  # perf probe -x /lib64/libc-2.23.so getaddrinfo \$params
  The /usr/lib64/libc-2.23.so file has no debug information.
  Rebuild with -g, or install an appropriate debuginfo package.
    Error: Failed to add events.
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>