[scripts] objtool: Detect and warn if libelf is missing and don't break the build
Message-id: <35d11ae65559ae6aad4e82f30bc97c4d4aa5c4be.1468525413.git.jpoimboe@redhat.com>
Patchwork-id: 155287
O-Subject: [RHEL7.3 PATCH v4 16/64] objtool: Detect and warn if libelf is missing and don't break the build
Bugzilla: 1320250
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>
RH-Acked-by: Bandan Das <bsd@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit 3b27a0c85d7068130ed8e3977a2e977ade986841
Author: Josh Poimboeuf <jpoimboe@redhat.com>
Date:   Thu Mar 3 11:39:30 2016 -0600

    objtool: Detect and warn if libelf is missing and don't break the build

    With CONFIG_STACK_VALIDATION enabled, if the host system doesn't have
    a development version of libelf installed, the build fails with errors
    like:

      elf.h:22:18: fatal error: gelf.h: No such file or directory compilation terminated.

    Instead of failing to build, instead just print a warning and disable
    stack validation.

    Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: linux-next@vger.kernel.org
    Cc: linux@roeck-us.net
    Cc: live-patching@vger.kernel.org
    Link: http://lkml.kernel.org/r/8c27fe00face60f42e888ddb3142c97e45223165.1457026550.git.jpoimboe@redhat.com
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>