[netdrv] netronome: don't access real_num_rx_queues directly
Message-id: <1a719612b5a29cafb83842a35e3fa56523429250.1489603003.git.linville@tuxdriver.com>
Patchwork-id: 174348
O-Subject: [RHEL7 PATCH 25/48] netronome: don't access real_num_rx_queues directly
Bugzilla: 1406197
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1406197

The netdev->real_num_rx_queues setting is only available if CONFIG_SYSFS
is enabled, so we now get a build failure when that is turned off:

netronome/nfp/nfp_net_common.c: In function 'nfp_net_ring_swap_enable':
netronome/nfp/nfp_net_common.c:2489:18: error: 'struct net_device' has no member named 'real_num_rx_queues'; did you mean 'real_num_tx_queues'?

As far as I can tell, the check here is only used as an optimization that
we can skip in order to fix the compilation. If sysfs is disabled,
the following netif_set_real_num_rx_queues() has no effect.

Fixes: 164d1e9e5d52 ("nfp: add support for ethtool .set_channels")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 08348995c47ec0e6ad3712c08eb88fb4df2e8180)
Signed-off-by: John W. Linville <linville@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>