[mmc] rtsx: fix possible linking error if built-in
Message-id: <1463503488-149391-277-git-send-email-dzickus@redhat.com>
Patchwork-id: 144756
O-Subject: [RHEL7 PATCH 276/725] mmc: rtsx: fix possible linking error if built-in
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit b677b8850322b210a81b72ffcc7de85a3df395c5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 8 10:27:54 2014 +0200

    mmc: rtsx: fix possible linking error if built-in

    rtsx_usb_sdmmc module uses the LED classdev if available, but the code
    failed to consider the situation that it is built-in and the LED classdev is a
    module, leading to following linking error:

       LD      init/built-in.o
    drivers/built-in.o: In function `rtsx_usb_sdmmc_drv_remove':
    rtsx_usb_sdmmc.c:(.text+0x2a018e): undefined reference to
    `led_classdev_unregister'
    drivers/built-in.o: In function `rtsx_usb_sdmmc_drv_probe':
    rtsx_usb_sdmmc.c:(.text+0x2a197e): undefined reference to
    `led_classdev_register'

    Fix by excluding such condition when defining macro RTSX_USB_USE_LEDS_CLASS.

    Signed-off-by: Roger Tseng <rogerable@realtek.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
    Signed-off-by: Chris Ball <chris@printf.net>

Signed-off-by: Rafael Aquini <aquini@redhat.com>