[nvme] fix build with gcc-4.4.4
Message-id: <1507192397-86938-9-git-send-email-dmilburn@redhat.com>
Patchwork-id: 188869
O-Subject: [RHEL7.5 PATCH v3 008/206] drivers/block/nvme-core.c: fix build with gcc-4.4.4
Bugzilla: 1457880 1456486 1454365
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit e44ac588cd61c960226d61c379e2873a95544a51
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Sat Jun 27 12:20:34 2015 -0600

    drivers/block/nvme-core.c: fix build with gcc-4.4.4

    gcc-4.4.4 (and possibly other versions) fail the compile when initializers
    are used with anonymous unions.  Work around this.

    drivers/block/nvme-core.c: In function 'nvme_identify_ctrl':
    drivers/block/nvme-core.c:1163: error: unknown field 'identify' specified in initializer
    drivers/block/nvme-core.c:1163: warning: missing braces around initializer
    drivers/block/nvme-core.c:1163: warning: (near initialization for 'c.<anonymous>')
    drivers/block/nvme-core.c:1164: error: unknown field 'identify' specified in initializer
    drivers/block/nvme-core.c:1164: warning: excess elements in struct initializer
    drivers/block/nvme-core.c:1164: warning: (near initialization for 'c')
    ...

    This patch has no effect on text size with gcc-4.8.2.

    Fixes: d29ec8241c10eac ("nvme: submit internal commands through the block layer")
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Jens Axboe <axboe@fb.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Jens Axboe <axboe@fb.com>

The upstream patch was prior to moving the code to drivers/nvme/host/core.c,
also since we already have RHEL commit 380975b69bedd (nvme: use symbolic constants
for CNS values), use NVME_ID_CNS_CTRL.

BZ 1454365
BZ 1456486
BZ 1457880

Signed-off-by: David Milburn <dmilburn@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>