[net] sched: cls_flower: Fix compile error
Message-id: <8543557561389c0b167dd96f8f6b8f97fb2d5da9.1490136269.git.jtoppins@redhat.com>
Patchwork-id: 174937
O-Subject: [RHEL7.4 net v4 03/59] cls_flower: Fix compile error
Bugzilla: 1393375
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

Fix compile error in net/sched/cls_flower.c

    net/sched/cls_flower.c: In function 'fl_set_key':
    net/sched/cls_flower.c:240:3: error: implicit declaration of
     function 'tcf_change_indev' [-Werror=implicit-function-declaration]
       err = tcf_change_indev(net, tb[TCA_FLOWER_INDEV]);

Introduced in 77b9900ef53ae

Fixes: 77b9900ef53ae ("tc: introduce Flower classifier")
Signed-off-by: Brian Haley <brian.haley@hp.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit dd3aa3b5fbf61adb0ef5d44a6753646b767b9c77)
Bugzilla: 1393375
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12825917
Tested: compile tested

Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>