[tools] perf evlist: Handle -EINVAL for sample_freq > max_sample_rate in strerror_open()
Message-id: <1463569977-29479-146-git-send-email-jolsa@redhat.com>
Patchwork-id: 145835
O-Subject: [PATCH RHEL7.3 BZ1336447 145/324] perf evlist: Handle -EINVAL for sample_freq > max_sample_rate in strerror_open()
Bugzilla: 1336447
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1336447
https://bugzilla.redhat.com/show_bug.cgi?id=1336447

upstream
========
commit d9aade7fd27a604bbffd363e6a68416ef51bab88
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Feb 18 13:34:09 2016 -0300

description
===========
When running the "code reading" test we get:

  # perf test -v "code reading" 2>&1 | tail -5
  Parsing event 'cycles:u'
  perf_evlist__open failed
  test child finished with -1
  ---- end ----
  Test object code reading: FAILED!
  #

And with -vv we get the errno value, -22, i.e. -EINVAL, but we can do
better and handle the case at hand, with this patch it becomes:

  # perf test -v "code reading" 2>&1 | tail -7
  perf_evlist__open() failed!
  Error: Invalid argument.
  Hint:  Check /proc/sys/kernel/perf_event_max_sample_rate.
  Hint:  The current value is 1000 and 4000 is being requested.
  test child finished with -1
  ---- end ----
  Test object code reading: FAILED!
  #

Next patch will make this 'perf test' entry to use perf_evlist__strerror()

Signed-off-by: Rafael Aquini <aquini@redhat.com>