[net] vxlan: hide unused local variable
Message-id: <bb7fced1cb9502ef53767c5ca9e76b354c670e4c.1507200047.git.jbenc@redhat.com>
Patchwork-id: 189106
O-Subject: [RHEL7.5 net 13/59] vxlan: hide unused local variable
Bugzilla: 1467280
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1467280

commit 4053ab1bf98dd128344b9e67ef139f931a967ae1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 7 22:09:07 2016 +0100

    vxlan: hide unused local variable

    A bugfix introduced a harmless warning in v4.9-rc4:

    drivers/net/vxlan.c: In function 'vxlan_group_used':
    drivers/net/vxlan.c:947:21: error: unused variable 'sock6' [-Werror=unused-variable]

    This hides the variable inside of the same #ifdef that is
    around its user. The extraneous initialization is removed
    at the same time, it was accidentally introduced in the
    same commit.

    Fixes: c6fcc4fc5f8b ("vxlan: avoid using stale vxlan socket.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Jiri Benc <jbenc@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>