[sound] alsa: pcm: Protect call to dma_mmap_coherent() by check for HAS_DMA
Message-id: <1507829954160572-312-patchset-jkysela@redhat.com>
Patchwork-id: 192221
O-Subject: [RHEL 7.5 PATCH v2 0311/1088] ALSA: pcm: Protect call to dma_mmap_coherent() by check for HAS_DMA
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

If NO_DMA=y:

sound/core/pcm_native.o: In function `snd_pcm_lib_default_mmap':
pcm_native.c:(.text+0x144c): undefined reference to `bad_dma_ops'
pcm_native.c:(.text+0x1474): undefined reference to `dma_common_mmap'

Add a check for HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit abe594c2cf55b46d4feb61c01fe9063afff2e50c)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>