[infiniband] uapi: fix rdma/mlx5-abi.h userspace compilation errors
Message-id: <20171011200214.23764-219-ddutile@redhat.com>
Patchwork-id: 191566
O-Subject: [PATCH RHEL-7.5 v2 218/233] uapi: fix rdma/mlx5-abi.h userspace compilation errors
Bugzilla: 1385309 1385649 1386645 1409099 1456667 1456687
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit 812755d69efcf7c12fded57983d456647a0bbadd
Author: Dmitry V. Levin <ldv@altlinux.org>
Date:   Fri Feb 24 03:28:13 2017 +0300

    uapi: fix rdma/mlx5-abi.h userspace compilation errors

    Consistently use types from linux/types.h to fix the following
    rdma/mlx5-abi.h userspace compilation errors:

    /usr/include/rdma/mlx5-abi.h:69:25: error: 'u64' undeclared here (not in a function)
      MLX5_LIB_CAP_4K_UAR = (u64)1 << 0,
    /usr/include/rdma/mlx5-abi.h:69:29: error: expected ',' or '}' before numeric constant
      MLX5_LIB_CAP_4K_UAR = (u64)1 << 0,

    Include <linux/if_ether.h> to fix the following rdma/mlx5-abi.h
    userspace compilation error:

    /usr/include/rdma/mlx5-abi.h:286:12: error: 'ETH_ALEN' undeclared here (not in a function)
      __u8 dmac[ETH_ALEN];

    Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>