[perf] list: Fix --raw-dump option
Message-id: <1428672113-29331-156-git-send-email-jolsa@redhat.com>
Patchwork-id: 109811
O-Subject: [PATCH RHEL7.2 BZ1209607 155/220] perf list: Fix --raw-dump option
Bugzilla: 1209607
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1209607
https://bugzilla.redhat.com/show_bug.cgi?id=1209607

upstream
========
commit b3505208804f3b59150cd77719f01c8b0023a865
Author: Taesoo Kim <tsgatesv@gmail.com>
Date: Tue Dec 30 22:36:55 2014 -0500

description
===========
Currently, 'perf list --raw-dump' requires extra arguments
(e.g., hw) to invoke, which breaks bash/zsh completion
(perf-completion.sh).

  $ perf list --raw-dump
    Error: unknown option `raw-dump'

     usage: perf list [hw|sw|cache|tracepoint|pmu|event_glob]

After,

  $ perf list --raw-dump
  cpu-cycles instructions cache-references cache-misses ...

Signed-off-by: Rafael Aquini <aquini@redhat.com>