[usb] add HAS_IOMEM dependency to USB_XHCI_MVEBU
Message-id: <1465525749-9195-87-git-send-email-torez@redhat.com>
Patchwork-id: 150004
O-Subject: [RHEL7 BZ1332712 v2 086/196] usb: add HAS_IOMEM dependency to USB_XHCI_MVEBU
Bugzilla: 1332712
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1332712
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11164417
Testing: on local desktop, Dell Berlinetta-P laptop, and, on some customer
    platforms.

commit 828638e91915e347f0721ae2a2cb137c910dc592
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Wed Feb 10 15:29:39 2016 +0100

    usb: add HAS_IOMEM dependency to USB_XHCI_MVEBU

    drivers/usb/host/xhci-mvebu.c: In function xhci_mvebu_mbus_init_quirk:
    drivers/usb/host/xhci-mvebu.c:58:2: error: implicit declaration of function ioremap [-Werror=implicit-function-declaration]
      base = ioremap(res->start, resource_size(res));
      ^
    drivers/usb/host/xhci-mvebu.c:58:7: warning: assignment makes pointer from integer without a cast [enabled by default]
      base = ioremap(res->start, resource_size(res));
           ^
    drivers/usb/host/xhci-mvebu.c:69:2: error: implicit declaration of function iounmap [-Werror=implicit-function-declaration]
      iounmap(base);
      ^

    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Acked-by: Gregory CLEMENT <gregory.clement@free-electrons.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>