[kernel] kexec: fix build error when hugetlbfs is disabled
Message-id: <1408087644-31621-4-git-send-email-bhe@redhat.com>
Patchwork-id: 87784
O-Subject: [PATCH 3/3] kexec: fix build error when hugetlbfs is disabled
Bugzilla: 1115240
RH-Acked-by: Vivek Goyal <vgoyal@redhat.com>
RH-Acked-by: Chao WANG <chaowang@redhat.com>

Resolves: bz1115240
https://bugzilla.redhat.com/show_bug.cgi?id=1115240

This is back ported from upstream.

commit 3a1122d26c62d4e8c61ef9a0eaba6e21c0862c77
Author: David Rientjes <rientjes@google.com>
Date:   Wed Jul 30 19:05:55 2014 -0700

    kexec: fix build error when hugetlbfs is disabled

    free_huge_page() is undefined without CONFIG_HUGETLBFS and there's no
    need to filter PageHuge() page is such a configuration either, so avoid
    exporting the symbol to fix a build error:

       In file included from kernel/kexec.c:14:0:
       kernel/kexec.c: In function 'crash_save_vmcoreinfo_init':
       kernel/kexec.c:1623:20: error: 'free_huge_page' undeclared (first use in this function)
         VMCOREINFO_SYMBOL(free_huge_page);
                           ^

    Introduced by commit 8f1d26d0e59b ("kexec: export free_huge_page to
    VMCOREINFO")

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Acked-by: Olof Johansson <olof@lixom.net>
    Cc: Atsushi Kumagai <kumagai-atsushi@mxc.nes.nec.co.jp>
    Cc: Baoquan He <bhe@redhat.com>
    Cc: Vivek Goyal <vgoyal@redhat.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: David Rientjes <rientjes@google.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Brew build:
https://brewweb.devel.redhat.com/taskinfo?taskID=7844251

Test: Passed on kvm guest.

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>