[tools] perf: Fix build on gcc 4.4.7
Message-id: <1418163608-7772-143-git-send-email-jolsa@redhat.com>
Patchwork-id: 101350
O-Subject: [PATCH RHEL7.1 BZ1169436 142/359] perf tools: Fix build on gcc 4.4.7
Bugzilla: 1169436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1169436
https://bugzilla.redhat.com/show_bug.cgi?id=1169436

upstream
========
commit 0524798cc3d74546e83ebd795e9a5ed44481eaa6
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Jul 23 18:15:09 2014 -0300

description
===========
[acme@sandy linux]$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[acme@sandy linux]$ make O=/tmp/build/perf -C tools/perf install-bin
<SNIP>
  CC       /tmp/build/perf/builtin-trace.o
builtin-trace.c: In function 'perf_evlist__add_pgfault':
builtin-trace.c:1997: error: unknown field 'sample_period' specified in initializer
make[1]: *** [/tmp/build/perf/builtin-trace.o] Error 1
make: *** [install-bin] Error 2
make: Leaving directory `/home/acme/git/linux/tools/perf'
[acme@sandy linux]$ make O=/tmp/build/perf -C tools/perf install-bin
make O=/tmp/build/perf -C tools/perf install-bin
make: Entering directory `/home/acme/git/linux/tools/perf'

Signed-off-by: Rafael Aquini <aquini@redhat.com>