[tools] perf: Fix arm64 build error
Message-id: <1418163608-7772-153-git-send-email-jolsa@redhat.com>
Patchwork-id: 101356
O-Subject: [PATCH RHEL7.1 BZ1169436 152/359] perf tools: Fix arm64 build error
Bugzilla: 1169436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1169436
https://bugzilla.redhat.com/show_bug.cgi?id=1169436

upstream
========
commit 7d885749b6de2c9a1168d566e2380207b9177108
Author: Mark Salter <msalter@redhat.com>
Date: Fri Jul 25 18:02:46 2014 -0400

description
===========
I'm seeing the following build error on arm64:

  In file included from util/event.c:3:0:
  util/event.h:95:17: error: 'PERF_REGS_MAX' undeclared here (not in a function)
    u64 cache_regs[PERF_REGS_MAX];
                 ^

This patch adds a PERF_REGS_MAX definition for arm64.
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>