[x86] include/linux/property.h: fix build issues with gcc-4.4.4
Message-id: <1467295392-9015-69-git-send-email-prarit@redhat.com>
Patchwork-id: 154444
O-Subject: [RHEL7.3 PATCH BZ 1331018 068/104] include/linux/property.h: fix build issues with gcc-4.4.4
Bugzilla: 1331018
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1331018

commit d76eebfa175e86383324ad2bbaf472866950398b
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Fri Jan 1 02:07:09 2016 +0100

    include/linux/property.h: fix build issues with gcc-4.4.4

    gcc-4.4.4 has problems with initialization of anonymous unions:

    drivers/mfd/intel-lpss-acpi.c:30: error: unknown field 'value' specified in initializer

    work around this by crafting the initializers in a manner which the
    compiler can handle.

    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>