[include] revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
Message-id: <1463503488-149391-164-git-send-email-dzickus@redhat.com>
Patchwork-id: 145012
O-Subject: [RHEL7 PATCH 163/725] Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 9d731e7539713acc0ec7b67a5a91357c455d2334
Author: Chris Ball <cjb@laptop.org>
Date:   Fri Sep 6 07:29:05 2013 -0400

    Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"

    This reverts commit 3af9d15c719017feb63fa99f89ac6009a5a3d467, which
    causes a build failure:

    drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer

Signed-off-by: Rafael Aquini <aquini@redhat.com>