[infiniband] rdma/hfi1: select CRC32
Message-id: <20160614194205.23159.14424.stgit@dhcp187-101.khw.lab.eng.bos.redhat.com>
Patchwork-id: 152862
O-Subject: [RHEL-7.3 BZs 1273170 1272062 PATCH 345/431] staging/rdma/hfi1: select CRC32
Bugzilla: 1272062 1273170
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Markus Bhme <markus.boehme@mailbox.org>

Bugzilla: 1273170
Upstream: (imported from commit 6d79b6c761dd76b947505340adb07c8b90296a9e)

The function parse_platform_config in firmware.c calls crc32_le.
Building without CRC32 selected causes a link error:

drivers/built-in.o: In function `parse_platform_config':
(.text+0x92ffa): undefined reference to `crc32_le'

Signed-off-by: Markus Bhme <markus.boehme@mailbox.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Rafael Aquini <aquini@redhat.com>