[net] openvswitch: Fix dependency on IPv6 defrag
Message-id: <1449101219-686-34-git-send-email-cascardo@redhat.com>
Patchwork-id: 128088
O-Subject: [RHEL7.3 net PATCH 33/49] openvswitch: Fix dependency on IPv6 defrag.
Bugzilla: 1274845
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Hannes Frederic Sowa <hannes@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Flavio Leitner <fbl@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1274845
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10183050
Tests: Great QE team ran all kinds of regression tests,
       Cascardo tested the feature itself

   commit 38c089d1d8d058f5dff018a811568aa8e8bc47fc
   Author: Joe Stringer <joestringer@nicira.com>
   Date:   Fri Sep 11 15:01:16 2015 -0700

   openvswitch: Fix dependency on IPv6 defrag.

   When NF_CONNTRACK is built-in, NF_DEFRAG_IPV6 is a module, and
   OPENVSWITCH is built-in, the following build error would occur:

   net/built-in.o: In function `ovs_ct_execute':
   (.text+0x10f587): undefined reference to `nf_ct_frag6_gather'

   Fixes: 7f8a436eaa2c ("openvswitch: Add conntrack action")
   Reported-by: Jim Davis <jim.epost@gmail.com>
   Signed-off-by: Joe Stringer <joestringer@nicira.com>
   Acked-by: Pravin B Shelar <pshelar@nicira.com>
   Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Flavio Leitner <fbl@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>