[fs] xfs: fix compile error when libxfs header used in C++ code
Message-id: <1426691250-14369-64-git-send-email-bfoster@redhat.com>
Patchwork-id: 107643
O-Subject: [RHEL7.2 PATCH 063/183] xfs: fix compile error when libxfs header used in C++ code
Bugzilla: 1184177
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>

- Modified to incorporate upstream merge conflict resolution with finobt
  bits. Resolved in upstream merge commit:

	0d907a3bb4a7 Merge branch 'xfs-misc-fixes-2-for-3.16' into for-next

commit 376c2f3a5f0706868b08ccf043bf3532936a03b1
Author: Roger Willcocks <roger@filmlight.ltd.uk>
Date:   Tue May 20 08:52:21 2014 +1000

    xfs: fix compile error when libxfs header used in C++ code

    xfs_ialloc.h:102: error: expected ',' or '...' before 'delete'

    Simple parameter rename, no changes to behaviour.

    Signed-off-by: Roger Willcocks <roger@filmlight.ltd.uk>
    Reviewed-by: Dave Chinner <dchinner@redhat.com>
    Signed-off-by: Dave Chinner <david@fromorbit.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>