[tools] perf probe: Ignore vmlinux buildid if offline kernel is given
Message-id: <1482322582-7586-75-git-send-email-jolsa@redhat.com>
Patchwork-id: 161801
O-Subject: [PATCH RHEL7.4 BZ1405101 074/197] perf probe: Ignore vmlinux buildid if offline kernel is given
Bugzilla: 1405101
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1405101
https://bugzilla.redhat.com/show_bug.cgi?id=1405101

upstream
========
commit 428aff82e92a29da0e4276623180f9a98f2d5b16
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Fri Aug 26 01:24:42 2016 +0900

description
===========
Ignore the buildid of running kernel when both of --definition and
--vmlinux is given because that kernel should be off-line.

This also skips post-processing of kprobe event for relocating symbol
and checking blacklist, because it can not be done on off-line kernel.

E.g. without this fix perf shows an error as below
  ----
  $ perf probe --vmlinux=./vmlinux-arm --definition do_sys_open
  ./vmlinux-arm with build id 7a1f76dd56e9c4da707cd3d6333f50748141434b not found, continuing without symbols
  Failed to find symbol do_sys_open in kernel
    Error: Failed to add events.
  ----
with this fix, we can get the definition
  ----
  $ perf probe --vmlinux=./vmlinux-arm --definition do_sys_open
  p:probe/do_sys_open do_sys_open+0
  ----

Signed-off-by: Rafael Aquini <aquini@redhat.com>