[mm] fs/proc/meminfo.c: include cma info in proc/meminfo
Message-id: <1507672821-21963-3-git-send-email-spopovyc@redhat.com>
Patchwork-id: 191190
O-Subject: [RHEL-7.5 kernel 2/2] fs/roc/meminfo.c: include cma info in proc/meminfo
Bugzilla: 1430990
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

commit 47f8f9297d2247d65ee46d8403a73b30f8d0249b
Author: Pintu Kumar <pintu.k@samsung.com>
Date:   Thu Dec 18 16:17:18 2014 -0800

    fs/proc/meminfo.c: include cma info in proc/meminfo

    This patch include CMA info (CMATotal, CMAFree) in /proc/meminfo.
    Currently, in a CMA enabled system, if somebody wants to know the total
    CMA size declared, there is no way to tell, other than the dmesg or
    /var/log/messages logs.

    With this patch we are showing the CMA info as part of meminfo, so that it
    can be determined at any point of time.  This will be populated only when
    CMA is enabled.

    Below is the sample output from a ARM based device with RAM:512MB and CMA:16MB.

      MemTotal:         471172 kB
      MemFree:          111712 kB
      MemAvailable:     271172 kB
      .
      .
      .
      CmaTotal:          16384 kB
      CmaFree:            6144 kB

    This patch also fix below checkpatch errors that were found during these changes.

      ERROR: space required after that ',' (ctx:ExV)
      199: FILE: fs/proc/meminfo.c:199:
      +       ,atomic_long_read(&num_poisoned_pages) << (PAGE_SHIFT - 10)
              ^

      ERROR: space required after that ',' (ctx:ExV)
      202: FILE: fs/proc/meminfo.c:202:
      +       ,K(global_page_state(NR_ANON_TRANSPARENT_HUGEPAGES) *
              ^

      ERROR: space required after that ',' (ctx:ExV)
      206: FILE: fs/proc/meminfo.c:206:
      +       ,K(totalcma_pages)
              ^

      total: 3 errors, 0 warnings, 2 checks, 236 lines checked

    Signed-off-by: Pintu Kumar <pintu.k@samsung.com>
    Signed-off-by: Vishnu Pratap Singh <vishnu.ps@samsung.com>
    Acked-by: Michal Nazarewicz <mina86@mina86.com>
    Cc: Rafael Aquini <aquini@redhat.com>
    Cc: Jerome Marchand <jmarchan@redhat.com>
    Cc: Marek Szyprowski <m.szyprowski@samsung.com>
    Cc: Joonsoo Kim <iamjoonsoo.kim@lge.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Serhii Popovych <spopovyc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>

Conflicts:
    fs/proc/meminfo.c

Conflicts were due to missing upstream commit aa488c26ca9f (CMA: generalize
CMA reserved area management functionality) and it's dependencies.

Signed-off-by: Serhii Popovych <spopovyc@redhat.com>