[virt] kvm/ppc/Book3S: Fix compile error in XICS emulation
Message-id: <1381413926-15908-633-git-send-email-vfalico@redhat.com>
Patchwork-id: 69141
O-Subject: [RHEL7 PATCH 632/820] KVM: PPC: Book3S: Fix compile error in XICS emulation
Bugzilla: 1006938
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 7bfa9ad55d691f2b836b576769b11eca2cf50816
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=7bfa9ad55d691f2b836b576769b11eca2cf50816
Stable: faa94b0365522a939cd10d05d526a355a7eeaadf
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=faa94b0365522a939cd10d05d526a355a7eeaadf

Description
----------------------------
Backport from linux-3.10.y stable.

From: Paul Mackerras <paulus@samba.org>
Subject: KVM: PPC: Book3S: Fix compile error in XICS emulation

commit 7bfa9ad55d691f2b836b576769b11eca2cf50816 upstream.

Commit 8e44ddc3f3 ("powerpc/kvm/book3s: Add support for H_IPOLL and
H_XIRR_X in XICS emulation") added a call to get_tb() but didn't
include the header that defines it, and on some configs this means
book3s_xics.c fails to compile:

arch/powerpc/kvm/book3s_xics.c: In function 'kvmppc_xics_hcall':
arch/powerpc/kvm/book3s_xics.c:812:3: error: implicit declaration of function 'get_tb' [-Werror=implicit-function-declaration]

Signed-off-by: Paul Mackerras <paulus@samba.org>
Signed-off-by: Alexander Graf <agraf@suse.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit faa94b0365522a939cd10d05d526a355a7eeaadf)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>