[x86] efi: parse_efi_setup() build fix
Message-id: <1400726607-13717-29-git-send-email-dyoung@redhat.com>
Patchwork-id: 80129
O-Subject: [RHEL7.1 PATCH 28/35] x86/efi: parse_efi_setup() build fix
Bugzilla: 1080109
RH-Acked-by: Chao WANG <chaowang@redhat.com>
RH-Acked-by: Vivek Goyal <vgoyal@redhat.com>

Resolves: bz1080109

Brew build:
https://brewweb.devel.redhat.com/taskinfo?taskID=7480539

Test: Tested kexec/kdump on HP workstation and qemu.

Minor tuning the code line offset because there's no
efi early console and efi mixed mode support.

Upstream commit:
commit 5c12af0c41e3417e1939095325920463b5f8e726
Author: Dave Young <dyoung@redhat.com>
Date:   Fri Jan 3 11:56:49 2014 +0800

    x86/efi: parse_efi_setup() build fix

    In case without CONFIG_EFI, there will be below build error:

       arch/x86/built-in.o: In function `setup_arch':
      (.init.text+0x9dc): undefined reference to `parse_efi_setup'

    Thus fix it by adding blank inline function in asm/efi.h
    Also remove an unused declaration for variable efi_data_len.

    Signed-off-by: Dave Young <dyoung@redhat.com>
    Signed-off-by: Matt Fleming <matt.fleming@intel.com>

Signed-off-by: Jarod Wilson <jarod@redhat.com>