[x86] unwind: Fix oprofile module link error
Message-id: <95d941b78e9606609fa5c66ed66a6dc1155d9924.1509586025.git.jpoimboe@redhat.com>
Patchwork-id: 195695
O-Subject: [RHEL7.5 PATCH v2 132/141] x86/unwind: Fix oprofile module link error
Bugzilla: 1430637
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Joe Lawrence <joe.lawrence@redhat.com>

commit cfee9eddcd61e28b73468647fc4aa7ff2d706254
Author: Josh Poimboeuf <jpoimboe@redhat.com>
Date:   Thu Oct 6 00:28:40 2016 -0500

    x86/unwind: Fix oprofile module link error

    When compiling on x86 with CONFIG_OPROFILE=m and CONFIG_FRAME_POINTER=n,
    the oprofile module fails to link:

      ERROR: ftrace_graph_ret_addr" [arch/x86/oprofile/oprofile.ko] undefined!

    The problem was introduced when oprofile was converted to use the new
    x86 unwinder.  When frame pointers are disabled, the "guess" unwinder's
    unwind_get_return_address() is an inline function which calls
    ftrace_graph_ret_addr(), which is not exported.

    Fix it by converting the "guess" version of unwind_get_return_address()
    to an exported out-of-line function, just like its frame pointer
    counterpart.

    Reported-by: Karl Beldan <karl.beldan@gmail.com>
    Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
    Cc: Andy Lutomirski <luto@kernel.org>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Brian Gerst <brgerst@gmail.com>
    Cc: Denys Vlasenko <dvlasenk@redhat.com>
    Cc: Frederic Weisbecker <fweisbec@gmail.com>
    Cc: H. Peter Anvin <hpa@zytor.com>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Fixes: ec2ad9ccf12d ("oprofile/x86: Convert x86_backtrace() to use the new unwinder")
    Link: http://lkml.kernel.org/r/be08d589f6474df78364e081c42777e382af9352.1475731632.git.jpoimboe@redhat.com
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>