[tools] perf python: Filter out -specs=/a/b/c from the python binding cc options
Message-id: <20170807084247.7531-75-jolsa@redhat.com>
Patchwork-id: 182013
O-Subject: [PATCH RHEL7.5 74/94] perf python: Filter out -specs=/a/b/c from the python binding cc options
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 4be92cf018c391c4ecc5fd091fae8c152de3692f
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Feb 15 21:36:48 2017 -0300

description
===========
The -spec=/path/to/file can be used to change what gcc puts in the cc,
ld, etc command lines, but this is not present in clang, filter it out
at the setup.py file by changing python2's internal variable where it
keeps its initial CFLAGS value.

With this all of perf can be built in at least Fedora 25, fixing this
problem:

    GEN      /tmp/build/perf/python/perf.so
    CC       /tmp/build/perf/builtin-buildid-list.o
  clang-4.0: error: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1' [-Werror,-Wunused-command-line-argument]
  clang-4.0: error: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1' [-Werror,-Wunused-command-line-argument]
  error: command 'clang' failed with exit status 1

Now I need to change all the containers where I have clang to build
perf with it, so that we can check that in other distros (opensuse, debian,
ubuntu, etc) this also works.

Signed-off-by: Rafael Aquini <aquini@redhat.com>