[net] openvswitch: Export lockdep_ovsl_is_held to modules
Message-id: <b9c684eeef5dd22fe03a1af6d39cca5ccb72c9be.1434713811.git.jbenc@redhat.com>
Patchwork-id: 120116
O-Subject: [RHEL7.2 net PATCH 038/110] openvswitch: Export lockdep_ovsl_is_held to modules.
Bugzilla: 1156461 1211348
RH-Acked-by: Flavio Leitner <fbl@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1211348
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1156461

commit 2c6c49ded7a7209fe8618423c457b8000ee528a4
Author: David S. Miller <davem@davemloft.net>
Date:   Tue Oct 28 17:27:23 2014 -0400

    openvswitch: Export lockdep_ovsl_is_held to modules.

    ERROR: "lockdep_ovsl_is_held" [net/openvswitch/vport-gre.ko] undefined!

    Reported-by: Alexei Starovoitov <alexei.starovoitov@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>