[fs] btrfs: fix send issuing outdated paths for utimes, chown and chmod
Message-id: <1407179109-13714-207-git-send-email-sandeen@redhat.com>
Patchwork-id: 87120
O-Subject: [RHEL7.1 PATCH 206/422] Btrfs: fix send issuing outdated paths for utimes, chown and chmod
Bugzilla: 1071179
RH-Acked-by: Zach Brown <zab@redhat.com>

From: Filipe Manana <fdmanana@gmail.com>

commit bf0d1f441d1679136c25e6141dd7e66cc7a14218
Author: Filipe Manana <fdmanana@gmail.com>
Date:   Fri Feb 21 00:01:32 2014 +0000

    Btrfs: fix send issuing outdated paths for utimes, chown and chmod

    When doing an incremental send, if we had a directory pending a move/rename
    operation and none of its parents, except for the immediate parent, were
    pending a move/rename, after processing the directory's references, we would
    be issuing utimes, chown and chmod intructions against am outdated path - a
    path which matched the one in the parent root.

    This change also simplifies a bit the code that deals with building a path
    for a directory which has a move/rename operation delayed.

    Steps to reproduce:

        $ mkfs.btrfs -f /dev/sdb3
        $ mount /dev/sdb3 /mnt/btrfs
        $ mkdir -p /mnt/btrfs/a/b/c/d/e
        $ mkdir /mnt/btrfs/a/b/c/f
        $ chmod 0777 /mnt/btrfs/a/b/c/d/e
        $ btrfs subvolume snapshot -r /mnt/btrfs /mnt/btrfs/snap1
        $ btrfs send /mnt/btrfs/snap1 -f /tmp/base.send
        $ mv /mnt/btrfs/a/b/c/f /mnt/btrfs/a/b/f2
        $ mv /mnt/btrfs/a/b/c/d/e /mnt/btrfs/a/b/f2/e2
        $ mv /mnt/btrfs/a/b/c /mnt/btrfs/a/b/c2
        $ mv /mnt/btrfs/a/b/c2/d /mnt/btrfs/a/b/c2/d2
        $ chmod 0700 /mnt/btrfs/a/b/f2/e2
        $ btrfs subvolume snapshot -r /mnt/btrfs /mnt/btrfs/snap2
        $ btrfs send -p /mnt/btrfs/snap1 /mnt/btrfs/snap2 -f /tmp/incremental.send

        $ umount /mnt/btrfs
        $ mkfs.btrfs -f /dev/sdb3
        $ mount /dev/sdb3 /mnt/btrfs
        $ btrfs receive /mnt/btrfs -f /tmp/base.send
        $ btrfs receive /mnt/btrfs -f /tmp/incremental.send

    The second btrfs receive command failed with:

        ERROR: chmod a/b/c/d/e failed. No such file or directory

    A test case for xfstests follows.

    Signed-off-by: Filipe David Borba Manana <fdmanana@gmail.com>
    Signed-off-by: Josef Bacik <jbacik@fb.com>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>