[include] define DIV_ROUND_UP for userland
Message-id: <1459266986-31005-109-git-send-email-ivecera@redhat.com>
Patchwork-id: 139434
O-Subject: [RHEL7.3 net PATCH 108/113] uapi: define DIV_ROUND_UP for userland
Bugzilla: 1268334
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: John Greene <jogreene@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ: #1268334

Upstream commit(s):
commit b5d3755a22e0cc4c369c0985aef0c52c2477c1e7
Author: Nicolas Dichtel <nicolas.dichtel@6wind.com>
Date:   Fri Mar 4 11:52:16 2016 +0100

    uapi: define DIV_ROUND_UP for userland

    DIV_ROUND_UP is defined in linux/kernel.h only for the kernel.
    When ethtool.h is included by a userland app, we got the following error:

    include/linux/ethtool.h:1218:8: error: variably modified 'queue_mask' at file scope
      __u32 queue_mask[DIV_ROUND_UP(MAX_NUM_QUEUE, 32)];
            ^

    Let's add a common definition in uapi and use it everywhere.

    Fixes: ac2c7ad0e5d6 ("net/ethtool: introduce a new ioctl for per queue setting")
    Suggested-by: Ben Hutchings <ben@decadent.org.uk>
    Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>