[net] netfilter: nf_conntrack: make nf_ct_zone_dflt built-in
Message-id: <1449101219-686-18-git-send-email-cascardo@redhat.com>
Patchwork-id: 128074
O-Subject: [RHEL7.3 net PATCH 17/49] netfilter: nf_conntrack: make nf_ct_zone_dflt built-in
Bugzilla: 1274845
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Hannes Frederic Sowa <hannes@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Flavio Leitner <fbl@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1274845
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10183050
Tests: Great QE team ran all kinds of regression tests,
       Cascardo tested the feature itself

Conflicts: \
	net/netfilter/core.c

   commit 62da98656b62a5ca57f22263705175af8ded5aa1
   Author: Daniel Borkmann <daniel@iogearbox.net>
   Date:   Thu Sep 3 01:26:07 2015 +0200

   netfilter: nf_conntrack: make nf_ct_zone_dflt built-in

   Fengguang reported, that some randconfig generated the following linker
   issue with nf_ct_zone_dflt object involved:

   [...]
   CC      init/version.o
   LD      init/built-in.o
   net/built-in.o: In function `ipv4_conntrack_defrag':
   nf_defrag_ipv4.c:(.text+0x93e95): undefined reference to `nf_ct_zone_dflt'
   net/built-in.o: In function `ipv6_defrag':
   nf_defrag_ipv6_hooks.c:(.text+0xe3ffe): undefined reference to `nf_ct_zone_dflt'
   make: *** [vmlinux] Error 1

   Given that configurations exist where we have a built-in part, which is
   accessing nf_ct_zone_dflt such as the two handlers nf_ct_defrag_user()
   and nf_ct6_defrag_user(), and a part that configures nf_conntrack as a
   module, we must move nf_ct_zone_dflt into a fixed, guaranteed built-in
   area when netfilter is configured in general.

   Therefore, split the more generic parts into a common header under
   include/linux/netfilter/ and move nf_ct_zone_dflt into the built-in
   section that already holds parts related to CONFIG_NF_CONNTRACK in the
   netfilter core. This fixes the issue on my side.

   Fixes: 308ac9143ee2 ("netfilter: nf_conntrack: push zone object into functions")
   Reported-by: Fengguang Wu <fengguang.wu@intel.com>
   Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
   Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Flavio Leitner <fbl@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>