[net] sched: select cls when cls_act is enabled
Message-id: <20171008224128.1458-360-ivecera@redhat.com>
Patchwork-id: 190444
O-Subject: [RHEL7.5 net PATCH 359/466] net: sched: select cls when cls_act is enabled
Bugzilla: 1445420
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ#1445420

Upstream commit(s):
commit 8ec1507dc9d16ecd9ada2f67efa95f8d586335fb
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Sun Jun 4 18:49:28 2017 +0200

    net: sched: select cls when cls_act is enabled

    It really makes no sense to have cls_act enabled without cls. In that
    case, the cls_act code is dead. So select it.

    This also fixes an issue recently reported by kbuild robot:
    [linux-next:master 1326/4151] net/sched/act_api.c:37:18: error: implicit declaration of function 'tcf_chain_get'

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>