[net] netfilter: xt_TEE: use IS_ENABLED(CONFIG_NF_DUP_IPV6)
Message-id: <0bdc6b662cb83cc5667b2996ecd5b2bc0c89db93.1465290494.git.pabeni@redhat.com>
Patchwork-id: 149345
O-Subject: [RHEL7.3 net PATCH 122/165] netfilter: xt_TEE: use IS_ENABLED(CONFIG_NF_DUP_IPV6)
Bugzilla: 1331757
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Jakub Sitnicki <jkbs@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1331757
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=11141575
Tested: nftables test-suite and basic functional tests

Upstream commit:
commit 116984a316c3a3200f8a7912110cc4a6d6c0989e
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Fri Aug 21 21:34:08 2015 +0200

    netfilter: xt_TEE: use IS_ENABLED(CONFIG_NF_DUP_IPV6)

    Instead of IS_ENABLED(CONFIG_IPV6), otherwise we hit:

    et/built-in.o: In function `tee_tg6':
    >> xt_TEE.c:(.text+0x6cd8c): undefined reference to `nf_dup_ipv6'

    when:

     CONFIG_IPV6=y
     CONFIG_NF_DUP_IPV4=y
     # CONFIG_NF_DUP_IPV6 is not set
     CONFIG_NETFILTER_XT_TARGET_TEE=y

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>