[infiniband] rdma/iw_cxgb4: Use kfree_skb instead of kfree
Message-id: <1485815854-24569-428-git-send-email-ddutile@redhat.com>
Patchwork-id: 164180
O-Subject: [PATCH RHEL-7.4 427/575] RDMA/iw_cxgb4: Use kfree_skb instead of kfree
Bugzilla: 1385866 1417284
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 56b2eca3fea8ea4fb6ec732b98470a09385cb1eb
Author: Hariprasad S <hariprasad@chelsio.com>
Date:   Thu Jun 30 11:44:33 2016 +0530

    RDMA/iw_cxgb4: Use kfree_skb instead of kfree

    The commit 0f8ab0b6e91b4d53 ("RDMA/iw_cxgb4: Low resource fixes for Memory
    registration") from Jun 10, 2016, leads to the following static checker
    warning:

            drivers/infiniband/hw/cxgb4/mem.c:612 c4iw_alloc_mw()
            error: use kfree_skb() here instead of kfree(mhp->dereg_skb)

    Also fixes skb leak in c4iw_dealloc_mw

    Fixes: 0f8ab0b6e91b4d53 ("RDMA/iw_cxgb4: Low resource fixes for Memory registration")

    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Steve Wise <swise@opengridcomputing.com>
    Signed-off-by: Hariprasad Shenai <hariprasad@chelsio.com>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417284
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385866

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>