[fs] btrfs: fix send attempting to rmdir non-empty directories
Message-id: <1407179109-13714-205-git-send-email-sandeen@redhat.com>
Patchwork-id: 87122
O-Subject: [RHEL7.1 PATCH 204/422] Btrfs: fix send attempting to rmdir non-empty directories
Bugzilla: 1071179
RH-Acked-by: Zach Brown <zab@redhat.com>

From: Filipe Manana <fdmanana@gmail.com>

commit 9dc442143b9874ba677fc83bf8c60744ec642998
Author: Filipe Manana <fdmanana@gmail.com>
Date:   Wed Feb 19 14:31:44 2014 +0000

    Btrfs: fix send attempting to rmdir non-empty directories

    The incremental send algorithm assumed that it was possible to issue
    a directory remove (rmdir) if the the inode number it was currently
    processing was greater than (or equal) to any inode that referenced
    the directory's inode. This wasn't a valid assumption because any such
    inode might be a child directory that is pending a move/rename operation,
    because it was moved into a directory that has a higher inode number and
    was moved/renamed too - in other words, the case the following commit
    addressed:

        9f03740a956d7ac6a1b8f8c455da6fa5cae11c22
        (Btrfs: fix infinite path build loops in incremental send)

    This made an incremental send issue an rmdir operation before the
    target directory was actually empty, which made btrfs receive fail.
    Therefore it needs to wait for all pending child directory inodes to
    be moved/renamed before sending an rmdir operation.

    Simple steps to reproduce this issue:

        $ mkfs.btrfs -f /dev/sdb3
        $ mount /dev/sdb3 /mnt/btrfs
        $ mkdir -p /mnt/btrfs/a/b/c/x
        $ mkdir /mnt/btrfs/a/b/y
        $ btrfs subvolume snapshot -r /mnt/btrfs /mnt/btrfs/snap1
        $ btrfs send /mnt/btrfs/snap1 -f /tmp/base.send
        $ mv /mnt/btrfs/a/b/y /mnt/btrfs/a/b/YY
        $ mv /mnt/btrfs/a/b/c/x /mnt/btrfs/a/b/YY
        $ rmdir /mnt/btrfs/a/b/c
        $ btrfs subvolume snapshot -r /mnt/btrfs /mnt/btrfs/snap2
        $ btrfs send -p /mnt/btrfs/snap1 /mnt/btrfs/snap2 -f /tmp/incremental.send

        $ umount /mnt/btrfs
        $ mkfs.btrfs -f /dev/sdb3
        $ mount /dev/sdb3 /mnt/btrfs
        $ btrfs receive /mnt/btrfs -f /tmp/base.send
        $ btrfs receive /mnt/btrfs -f /tmp/incremental.send

    The second btrfs receive command failed with:

        ERROR: rmdir o259-6-0 failed. Directory not empty

    A test case for xfstests follows.

    Signed-off-by: Filipe David Borba Manana <fdmanana@gmail.com>
    Signed-off-by: Josef Bacik <jbacik@fb.com>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>