[ethernet] bna: Fix build due to missing use of dma_unmap_len_set()
Message-id: <1389099039-16850-20-git-send-email-ivecera@redhat.com>
Patchwork-id: 73295
O-Subject: [RHEL7 PATCH 19/19] bna: Fix build due to missing use of dma_unmap_len_set()
Bugzilla: 1030679
RH-Acked-by: Nikolay Aleksandrov <nikolay@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ: #1030679

Upstream commit:
commit ecca6a968fc454da641cda7aece35c4e103ad633
Author: David S. Miller <davem@davemloft.net>
Date:   Mon Jan 6 20:37:41 2014 -0500

    bna: Fix build due to missing use of dma_unmap_len_set()

    > as reported for linux-next of Dec.20, 2013
    > when CONFIG_NEED_DMA_MAP_STATE is not enabled:
    >
    > drivers/net/ethernet/brocade/bna/bnad.c: In function 'bnad_start_xmit':
    > drivers/net/ethernet/brocade/bna/bnad.c:3074:26: error: 'struct bnad_tx_vector' has no member named 'dma_len'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>