[net] pkt_sched: fq: prefetch() fix
Message-id: <1435930181-19698-3-git-send-email-sdubroca@redhat.com>
Patchwork-id: 121515
O-Subject: [RHEL7.2 net 02/28] pkt_sched: fq: prefetch() fix
Bugzilla: 1235102
RH-Acked-by: Phil Sutter <psutter@redhat.com>
RH-Acked-by: Hannes Frederic Sowa <hannes@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1235102
Upstream Status: 08f89b981b0e6b46058dae2957241d4099129521
Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=9450079
Tested: on beaker

Upstream Commit:
commit 08f89b981b0e6b46058dae2957241d4099129521
Author: Eric Dumazet <edumazet@google.com>
Date:   Fri Aug 30 09:46:43 2013 -0700

    pkt_sched: fq: prefetch() fix

    kbuild bot reported following m68k build error :

      net/sched/sch_fq.c: In function 'fq_dequeue':
    >> net/sched/sch_fq.c:491:2: error: implicit declaration of function
    'prefetch' [-Werror=implicit-function-declaration]
       cc1: some warnings being treated as errors

    While we are fixing this, move this prefetch() call a bit earlier.

    Reported-by: Wu Fengguang <fengguang.wu@intel.com>
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Sabrina Dubroca <sdubroca@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>