[tools] perf/tests: Fix compile failure on do_sort_something
Message-id: <1389109877-9395-139-git-send-email-jolsa@redhat.com>
Patchwork-id: 73438
O-Subject: [PATCH RHEL7.0 BZ1036665 138/226] perf tests: Fix compile failure on do_sort_something
Bugzilla: 1036665
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1036665
https://bugzilla.redhat.com/show_bug.cgi?id=1036665

upstream
========
commit 309b5185047c5309bbc576025f6c5e257edd9f69
Author: David Ahern <dsahern@gmail.com>
Date: Tue Aug 13 22:32:12 2013 -0600

description
===========
Commit b55ae0a9 added code-reading.c which fails to compile on Fedora 16
with compiler version:
$ gcc --version
gcc (GCC) 4.6.3 20120306 (Red Hat 4.6.3-2)

Failure message is:

tests/code-reading.c: In function 'do_sort_something':
tests/code-reading.c:305:13: error: stack protector not protecting local variables: variable length buffer [-Werror=stack-protector]
cc1: all warnings being treated as errors
make: *** [/tmp/junk/tests/code-reading.o] Error 1
make: *** Waiting for unfinished jobs....

v2: as Adrian noticed changed sizeof to ARRAY_SIZE
Signed-off-by: Jarod Wilson <jarod@redhat.com>