[net] ip_tunnel: Move ip_tunnel_get_stats64 into ip_tunnel_core.c
Message-id: <de85099a9151f18d9b0f2ed6d175a07e99fd3a86.1432658084.git.mleitner@redhat.com>
Patchwork-id: 113738
O-Subject: [RHEL7.2 net PATCH v2 026/137] ip_tunnel: Move ip_tunnel_get_stats64 into ip_tunnel_core.c
Bugzilla: 1206570
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Alexander Duyck <alexander.h.duyck@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1206570
Backport of upstream commit: ebe44f350e15d6142d4d74cbaec0dad976c36753

 commit ebe44f350e15d6142d4d74cbaec0dad976c36753
 Author: David S. Miller <davem@davemloft.net>
 Date:   Thu Feb 20 02:14:23 2014 -0500

    ip_tunnel: Move ip_tunnel_get_stats64 into ip_tunnel_core.c

    net/built-in.o:(.rodata+0x1707c): undefined reference to `ip_tunnel_get_stats64'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>