[infiniband] lx5e: add IPV6 dependency
Message-id: <20171011200214.23764-206-ddutile@redhat.com>
Patchwork-id: 191549
O-Subject: [PATCH RHEL-7.5 v2 205/233] net/mlx5e: add IPV6 dependency
Bugzilla: 1385309 1385649 1386645 1409099 1456667 1456687
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit 0253f2681f4445e9003fb27dc743ef7d25e8f3b9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 28 22:12:04 2017 +0100

    net/mlx5e: add IPV6 dependency

    The ethernet support now calls directly into the ipv6 core code, which
    fails if IPV6 is a loadable module but mlx5 is built-in:

    drivers/net/ethernet/mellanox/mlx5/core/en_tc.o: In function `mlx5e_create_encap_header_ipv6':
    en_tc.c:(.text.mlx5e_create_encap_header_ipv6+0x110): undefined reference to `ip6_route_output_flags'

    This adds a dependency to ensure that MLX5_CORE_EN can only be built
    if we are able link the kernel successfully. The downside is that the
    ethernet option can be hidden. Alternatively we could make MLX5_CORE
    depend on "IPV6 || !IPV6", which would force MLX5_CORE to be a module
    when IPV6 is, including in configurations where we don't use the ethernet
    support at all.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>