[fs] btrfs: scrub: set error stats when tree block spanning stripes
Message-id: <1459456505-5012-480-git-send-email-billodo@redhat.com>
Patchwork-id: 140107
O-Subject: [RHEL7.3 PATCH V2 BZ 1298680 479/525] [fs] btrfs: scrub: set error stats when tree block spanning stripes
Bugzilla: 1298680
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

Bugzilla: 1298680
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=10759031
Tested: Locally with fstests

Backport of the following upstream commit:

    commit 9799d2c32bef6fba098fbef763002bc8d4851a2c
    Author: Zhao Lei <zhaolei@cn.fujitsu.com>
    Date:   Tue Aug 25 21:31:40 2015 +0800

    btrfs: scrub: set error stats when tree block spanning stripes

    It is better to show error stats to user when we found tree block
    spanning stripes.

    On a btrfs created by old version of btrfs-convert:
    Before patch:
      # btrfs scrub start -B /dev/vdh
      scrub done for 8b342d35-2904-41ab-b3cb-2f929709cf47
              scrub started at Tue Aug 25 21:19:09 2015 and finished after 00:00:00
              total bytes scrubbed: 53.54MiB with 0 errors
      # dmesg
      ...
      [  128.711434] BTRFS error (device vdh): scrub: tree block 27054080 spanning stripes, ignored. logical=27000832
      [  128.712744] BTRFS error (device vdh): scrub: tree block 27054080 spanning stripes, ignored. logical=27066368
      ...

    After patch:
      # btrfs scrub start -B /dev/vdh
      scrub done for ff7f844b-7a4e-4b1a-88a9-8252ab25be1b
              scrub started at Tue Aug 25 21:42:29 2015 and finished after 00:00:00
              total bytes scrubbed: 53.60MiB with 2 errors
              error details:
              corrected errors: 0, uncorrectable errors: 2, unverified errors: 0
      ERROR: There are uncorrectable errors.
      # dmesg
      ...omit...
      #

    Signed-off-by: Zhao Lei <zhaolei@cn.fujitsu.com>
    Signed-off-by: Chris Mason <clm@fb.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>