[infiniband] ocrdma: fix double free on pd
Message-id: <1435579444-27641-52-git-send-email-honli@redhat.com>
Patchwork-id: 120861
O-Subject: [RHEL-7.2 PATCH 51/65] RDMA/ocrdma: fix double free on pd
Bugzilla: 1229265
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Colin Ian King <colin.king@canonical.com>

A reorganisation of the PD allocation and deallocation in commit
9ba1377daa ("RDMA/ocrdma: Move PD resource management to driver.")
introduced a double free on pd, as detected by static analysis by
smatch:

drivers/infiniband/hw/ocrdma/ocrdma_verbs.c:682 ocrdma_alloc_pd()
  error: double free of 'pd'^

The original call to ocrdma_mbx_dealloc_pd() (which does not kfree
pd) was replaced with a call to _ocrdma_dealloc_pd() (which does
kfree pd).  The kfree following this call causes the double free,
so just remove it to fix the problem.

Fixes: 9ba1377daa ("RDMA/ocrdma: Move PD resource management to driver.")
Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-By: Devesh Sharma <devesh.sharma@avagotech.com>
Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 4dc544427991e3cef38ce3ae124b7e6557063bd3)
Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>