[mmc] MMC_GOLDFISH should depend on HAS_DMA
Message-id: <1463503488-149391-674-git-send-email-dzickus@redhat.com>
Patchwork-id: 145264
O-Subject: [RHEL7 PATCH 673/725] mmc: MMC_GOLDFISH should depend on HAS_DMA
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 3d35877294005911da54c36e2ab4d7b72d5e9331
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Mon Nov 9 10:36:01 2015 +0100

    mmc: MMC_GOLDFISH should depend on HAS_DMA

    If NO_DMA=y:

        ERROR: dma_unmap_sg [drivers/mmc/host/android-goldfish.ko] undefined!
        ERROR: dma_alloc_coherent [drivers/mmc/host/android-goldfish.ko] undefined!
        ERROR: dma_map_sg [drivers/mmc/host/android-goldfish.ko] undefined!
        ERROR: dma_free_coherent [drivers/mmc/host/android-goldfish.ko] undefined!

    Add a dependency on HAS_DMA to fix this.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>