[fs] btrfs: don't invalidate root dentry when subvolume deletion fails
Message-id: <1489475245-12948-73-git-send-email-ebiederm@redhat.com>
Patchwork-id: 174126
O-Subject: [RHEL7.4 BZ1247935 v2 073/104] Btrfs: don't invalidate root dentry when subvolume deletion fails
Bugzilla: 1247935
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Ian Kent <ikent@redhat.com>
RH-Acked-by: Miklos Szeredi <mszeredi@redhat.com>

From: "Eric W. Biederman" <ebiederm@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1247935
Upstream Status: linux.git 64ad6c488975d7516230cf7849190a991fd615ae
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=12742028
Testing: https://beaker.engineering.redhat.com/jobs/1757657

commit 64ad6c488975d7516230cf7849190a991fd615ae
Author: Omar Sandoval <osandov@osandov.com>
Date:   Tue Jun 2 17:31:00 2015 -0700

    Btrfs: don't invalidate root dentry when subvolume deletion fails

    Since commit bafc9b754f75 ("vfs: More precise tests in d_invalidate"),
    mounted subvolumes can be deleted because d_invalidate() won't fail.
    However, we run into problems when we attempt to delete the default
    subvolume while it is mounted as the root filesystem:

    	# btrfs subvol list /
    	ID 257 gen 306 top level 5 path rootvol
    	ID 267 gen 334 top level 5 path snap1
    	# btrfs subvol get-default /
    	ID 267 gen 334 top level 5 path snap1
    	# btrfs inspect-internal rootid /
    	267
    	# mount -o subvol=/ /dev/vda1 /mnt
    	# btrfs subvol del /mnt/snap1
    	Delete subvolume (no-commit): '/mnt/snap1'
    	ERROR: cannot delete '/mnt/snap1' - Operation not permitted
    	# findmnt /
    	findmnt: can't read /proc/mounts: No such file or directory
    	# ls /proc
    	#

    Markus reported that this same scenario simply led to a kernel oops.

    This happens because in btrfs_ioctl_snap_destroy(), we call
    d_invalidate() before we check may_destroy_subvol(), which means that we
    detach the submounts and drop the dentry before erroring out. Instead,
    we should only invalidate the dentry once the deletion has succeeded.
    Additionally, the shrink_dcache_sb() isn't necessary; d_invalidate()
    will prune the dcache for the deleted subvolume.

    Cc: <stable@vger.kernel.org>
    Fixes: bafc9b754f75 ("vfs: More precise tests in d_invalidate")
    Reported-by: Markus Schauler <mschauler@gmail.com>
    Signed-off-by: Omar Sandoval <osandov@osandov.com>
    Signed-off-by: Chris Mason <clm@fb.com>

Signed-off-by: Eric W. Biederman <ebiederm@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>