[tools] perf/build: Fix O=/some/dir perf.o type of targets
Message-id: <1408462094-14194-83-git-send-email-jolsa@redhat.com>
Patchwork-id: 88112
O-Subject: [PATCH RHEL7.1 BZ1131394 082/325] tools/perf/build: Fix O=/some/dir perf.o type of targets
Bugzilla: 1131394
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1131394
https://bugzilla.redhat.com/show_bug.cgi?id=1131394

upstream
========
commit 1f7c645ab4b8326fef5afcd842795e071ecce9df
Author: Ingo Molnar <mingo@kernel.org>
Date: Fri Oct 4 12:14:59 2013 +0200

description
===========
If someone specifies a single target, mixed with O=, the following way:

    hubble:~/tip/tools/perf> make O=/tmp/perf util/stat.o
    BUILD: Doing 'make -j8' parallel build
    gcc  -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k [...]

The build might even fail, if a target depends on other targets:

    hubble:~/tip/tools/perf> make O=/tmp/perf perf.o
    ...
    perf.c: In function 'handle_options':
    perf.c:155:21: error: 'PERF_HTML_PATH' undeclared (first use in this function)

The correct way to invoke such targets is:

    hubble:~/tip/tools/perf> make O=/tmp/perf /tmp/perf/perf.o
    BUILD: Doing 'make -j8' parallel build
    GEN /tmp/perf/common-cmds.h
    CC /tmp/perf/perf.o

But that's unnecessary typing and it's also easy to mistakenly build into the
source directory.

To fix this remove the generic suffix rules and add redirection to $(OUTPUT)
for the most popular .o targets.

Signed-off-by: Jarod Wilson <jarod@redhat.com>