[fs] xfs: remove dax code from object file when disabled
Message-id: <20170929161032.20614-20-bfoster@redhat.com>
Patchwork-id: 187079
O-Subject: [RHEL7.5 PATCH 19/62] xfs: remove dax code from object file when disabled
Bugzilla: 1479473
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

commit f021bd071f06b545926b1031348873b05442139f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 22 09:50:55 2016 +1000

    xfs: remove dax code from object file when disabled

    We check IS_DAX(inode) before calling either xfs_file_dax_read or
    xfs_file_dax_write, and this will lead the call being optimized out at
    compile time when CONFIG_FS_DAX is disabled.

    However, the two functions are marked STATIC, so they become global
    symbols when CONFIG_XFS_DEBUG is set, leaving us with two unused global
    functions that call into an undefined function and a broken "allmodconfig"
    build:

    fs/built-in.o: In function `xfs_file_dax_read':
    fs/xfs/xfs_file.c:348: undefined reference to `dax_do_io'
    fs/built-in.o: In function `xfs_file_dax_write':
    fs/xfs/xfs_file.c:758: undefined reference to `dax_do_io'

    Marking the two functions 'static noinline' instead of 'STATIC' will let
    the compiler drop the symbols when there are no callers but avoid the
    implicit inlining.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 16d4d43595b4 ("xfs: split direct I/O and DAX path")
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Dave Chinner <david@fromorbit.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>