[fs] btrfs: fix btrfs_no_printk stub helper
Message-id: <20170307000403.5752-441-billodo@redhat.com>
Patchwork-id: 171673
O-Subject: [RHEL7.4 PATCH BZ 1399590 440/485] btrfs: fix btrfs_no_printk stub helper
Bugzilla: 1399590
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

Bugzilla: 1399590
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=12695624
Tested: Locally with fstests

Backport of the following upstream commit:

    commit 2fd57fcb16483d718043940fd6dfeb176d4dc09c
    Author: Arnd Bergmann <arnd@arndb.de>
    Date:   Fri Sep 23 18:05:21 2016 +0200

    btrfs: fix btrfs_no_printk stub helper

    The addition of btrfs_no_printk() caused a build failure when
    CONFIG_PRINTK is disabled:

    fs/btrfs/send.c: In function 'send_rename':
    fs/btrfs/ctree.h:3367:2: error: implicit declaration of function 'btrfs_no_printk' [-Werror=implicit-function-declaration]

    This moves the helper outside of that #ifdef so it is always
    defined, and changes the existing #ifdef to refer to that
    helper as well for consistency.

    Fixes: 47c57058ff2c ("btrfs: btrfs_debug should consume fs_info when DEBUG is not defined")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: David Sterba <dsterba@suse.com>
    Signed-off-by: David Sterba <dsterba@suse.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>