[sound] alsa: x86: mark hdmi suspend/resume functions as __maybe_unused
Message-id: <1507829954160572-438-patchset-jkysela@redhat.com>
Patchwork-id: 192338
O-Subject: [RHEL 7.5 PATCH v2 0437/1088] ALSA: x86: mark hdmi suspend/resume functions as __maybe_unused
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The two functions are unused when CONFIG_PM_SLEEP is disabled:

sound/x86/intel_hdmi_audio.c:1633:12: error: 'hdmi_lpe_audio_resume' defined but not used [-Werror=unused-function]
sound/x86/intel_hdmi_audio.c:1622:12: error: 'hdmi_lpe_audio_suspend' defined but not used [-Werror=unused-function]

Marking them as __maybe_unused avoids the warning without introducing an
ugly #ifdef.

Fixes: 182cdf23dbf6 ("ALSA: x86: Implement runtime PM")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 1df989242d3d790aec79e72d12874bf763c958e1)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>