[tools] perf bench numa: Make sure dprintf() is not defined
Message-id: <20170807084247.7531-59-jolsa@redhat.com>
Patchwork-id: 181990
O-Subject: [PATCH RHEL7.5 58/94] perf bench numa: Make sure dprintf() is not defined
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 6aa4d8264003eb4f91fb09831ad25f059113f7b2
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 14 14:19:34 2017 -0300

description
===========
When building with clang we get this error:

  bench/numa.c:46:9: error: 'dprintf' macro redefined [-Werror,-Wmacro-redefined]
  #define dprintf(x...) do { if (g && g->p.show_details >= 1) printf(x); } while (0)
          ^
  /usr/include/bits/stdio2.h:145:12: note: previous definition is here
  #   define dprintf(fd, ...) \
             ^
    CC       /tmp/build/perf/tests/parse-no-sample-id-all.o
  1 error generated.

So, make sure it is undefined before using that name.

Signed-off-by: Rafael Aquini <aquini@redhat.com>