[powerpc] Fix unused function warning 'lmb_to_memblock'
Message-id: <1488806430-19116-28-git-send-email-thuth@redhat.com>
Patchwork-id: 170821
O-Subject: [RHEL7.4 kvm PATCH 27/41] powerpc: Fix unused function warning 'lmb_to_memblock'
Bugzilla: 1323417
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

From: Alastair D'Silva <alastair@d-silva.org>

This patch fixes the following warning:
arch/powerpc/platforms/pseries/hotplug-memory.c:323:29: error: 'lmb_to_memblock' defined but not used [-Werror=unused-function]
static struct memory_block *lmb_to_memblock(struct of_drconf_cell *lmb)
                           ^~~~~~~~~~~~~~~

The only consumer of this function is 'dlpar_remove_lmb', which is
enabled with CONFIG_MEMORY_HOTREMOVE, so move it into the same
ifdef block.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 9dc512819e4b723856773f5a018865c20441072f)
Signed-off-by: Rafael Aquini <aquini@redhat.com>