[tools] perf symbols: No need to check if sym->name is NULL
Message-id: <20170807084247.7531-52-jolsa@redhat.com>
Patchwork-id: 181989
O-Subject: [PATCH RHEL7.5 51/94] perf symbols: No need to check if sym->name is NULL
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit a7c3899c06865c75f8887f33d9043f6e8e780e71
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Feb 13 16:52:15 2017 -0300

description
===========
As it is an array, so will always evaluate to 'true', as reported by
clang:

  builtin-sched.c:2070:19: error: address of array 'sym->name' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
                  if (sym && sym->name) {
                          ~~ ~~~~~^~~~
  1 warning generated.

So just ditch all those useless checks.

Signed-off-by: Rafael Aquini <aquini@redhat.com>