[char] tpm: xen-tpmfront: fix missing declaration of xen_domain
Message-id: <1429193116-49113-12-git-send-email-jarod@redhat.com>
Patchwork-id: 110658
O-Subject: [RHEL7 PATCH 11/95] tpm: xen-tpmfront: fix missing declaration of xen_domain
Bugzilla: 1182709
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1182709

commit 8702c675319b838346a4fbaf4bbb783a563fa9a6
Author: Rob Herring <rob.herring@calxeda.com>
Date:   Thu Oct 10 14:38:27 2013 +0000

    tpm: xen-tpmfront: fix missing declaration of xen_domain

    xen-tpmfront fails to build on arm64 with the following error:

    drivers/char/tpm/xen-tpmfront.c: In function xen_tpmfront_init:
    drivers/char/tpm/xen-tpmfront.c:422:2: error: implicit declaration of function xen_domain [-Werror=implicit-function-declaration]

    Add include of xen/xen.h to fix this.

    Signed-off-by: Rob Herring <rob.herring@calxeda.com>
    Signed-off-by: Stefano Stabellini <stefano.stabellini@eu.citrix.com>
    Reviewed-by: Ashley Lai <adlai@linux.vnet.ibm.com>
    Acked-by: Ashley Lai <adlai@linux.vnet.ibm.com>
    Cc: Leonidas Da Silva Barbosa <leosilva@linux.vnet.ibm.com>
    Cc: Rajiv Andrade <mail@srajiv.net>
    Cc: Marcel Selhorst <tpmdd@selhorst.net>
    Cc: Sirrix AG <tpmdd@sirrix.com>
    Cc: tpmdd-devel@lists.sourceforge.net
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>