[nvdimm] use 'u64' for pfn flags
Message-id: <20160729175048.16035-128-jmoyer@redhat.com>
Patchwork-id: 156209
O-Subject: [RHEL7 PATCH 127/139] nvdimm: use 'u64' for pfn flags
Bugzilla: 1346083 1346084 1346445 1346449 1346472 1347091 1359806
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>
RH-Acked-by: David Milburn <dmilburn@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ: 1346445, 1346449, 1346472, 1359806, 1346083, 1346084, 1347091

commit c45442055dfdeb265cc20c9eeaa9fd11a75fbf51
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 22 22:58:34 2016 +0100

    nvdimm: use 'u64' for pfn flags

    A recent bugfix changed pfn_t to always be 64-bit wide, but did not
    change the code in pmem.c, which is now broken on 32-bit architectures
    as reported by gcc:

    In file included from ../drivers/nvdimm/pmem.c:28:0:
    drivers/nvdimm/pmem.c: In function 'pmem_alloc':
    include/linux/pfn_t.h:15:17: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
     #define PFN_DEV (1ULL << (BITS_PER_LONG_LONG - 3))

    This changes the intermediate pfn_flags in struct pmem_device to
    be 64 bit wide as well, so they can store the flags correctly.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: db78c22230d0 ("mm: fix pfn_t vs highmem")
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>