[virt] kvm: fix error: do not initialise statics to 0 or NULL in kvm_main.c
Message-id: <1457546986-23318-43-git-send-email-pbonzini@redhat.com>
Patchwork-id: 138102
O-Subject: [RHEL7.3 PATCH 042/200] KVM: Fix ERROR: do not initialise statics to 0 or NULL in kvm_main.c
Bugzilla: 1301888
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
RH-Acked-by: Bandan Das <bsd@redhat.com>
RH-Acked-by: Radim Krcmar <rkrcmar@redhat.com>

From: Xiubo Li <lixiubo@cmss.chinamobile.com>

ERROR: do not initialise statics to 0 or NULL
+static int kvm_usage_count = 0;

The kvm_usage_count will be placed to .bss segment when linking, so
not need to set it to 0 here obviously.

This patch fixes this ERROR to reduce noise when checking new patches
in kvm_main.c.

Signed-off-by: Xiubo Li <lixiubo@cmss.chinamobile.com>
Signed-off-by: Marcelo Tosatti <mtosatti@redhat.com>
(cherry picked from commit f4fee93270abbf862aab268111ac1e12934130c4)
Signed-off-by: Rafael Aquini <aquini@redhat.com>