[dax] use correct dev_t value
Message-id: <20170316214650.5449-74-jmoyer@redhat.com>
Patchwork-id: 174506
O-Subject: [RHEL7 PATCH 073/107] dax: use correct dev_t value
Bugzilla: 1383489
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ: 1383489
Brew: 12787010

commit bc0a0fe94f33dd15edf2ed555bfc4d6dbb5e1995
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Sep 8 15:53:28 2016 +0200

    dax: use correct dev_t value

    The dev_t variable in devm_create_dax_dev() is used before it's
    first set:

    drivers/dax/dax.c: In function 'devm_create_dax_dev':
    drivers/dax/dax.c:205:39: error: 'dev_t' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      inode = iget5_locked(dax_superblock, hash_32(devt + DAXFS_MAGIC, 31),
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/dax/dax.c:688:8: note: 'dev_t' was declared here

    This reorders the code to how it looks correct to me.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 3bc52c45bac2 ("dax: define a unified inode/address_space for device-dax mappings")
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>