[tools] perf symbols: dso->name is an array, no need to check it against NULL
Message-id: <20170807084247.7531-54-jolsa@redhat.com>
Patchwork-id: 181991
O-Subject: [PATCH RHEL7.5 53/94] perf symbols: dso->name is an array, no need to check it against NULL
Bugzilla: 1478485
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1478485
https://bugzilla.redhat.com/show_bug.cgi?id=1478485

upstream
========
commit 5eae7d842510d33d4410c062280eda6c935403dd
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Feb 13 17:11:03 2017 -0300

description
===========
As it will always evaluate to 'true', as reported by clang:

  util/map.c:390:36: error: address of array 'map->dso->name' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
          if (map && map->dso && (map->dso->name || map->dso->long_name)) {
                                  ~~~~~~~~~~^~~~ ~~
  util/map.c:393:22: error: address of array 'map->dso->name' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
                  else if (map->dso->name)
                     ~~  ~~~~~~~~~~^~~~

Signed-off-by: Rafael Aquini <aquini@redhat.com>