[tools] revert "perf symbols: Fix mismatched declarations for elf_getphdrnum"
Message-id: <1455542356-29341-228-git-send-email-jolsa@redhat.com>
Patchwork-id: 134600
O-Subject: [PATCH RHEL7.3 BZ1306834 227/237] Revert "perf symbols: Fix mismatched declarations for elf_getphdrnum"
Bugzilla: 1306834
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1306834
https://bugzilla.redhat.com/show_bug.cgi?id=1306834

upstream
========
commit 179f36dde3cec0f9f05a757b68f6a58e4edbcc95
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Sep 17 11:30:20 2015 -0300

description
===========
This reverts commit f785f2357673d520a0b7b468973cdd197f336494.

We have a test to check if elf_getphdrnum() is present, so, if it fails,
we'll get:

  [acme@rhel5 linux]$ cat /tmp/build/perf/feature/test-libelf-getphdrnum.make.output
  cc1: warnings being treated as errors
  test-libelf-getphdrnum.c: In function main:
  test-libelf-getphdrnum.c:7: warning: implicit declaration of function elf_getphdrnum
  [acme@rhel5 linux]$

And this block will not be compiled:

  #ifndef HAVE_ELF_GETPHDRNUM_SUPPORT
  static int elf_getphdrnum(Elf *elf, size_t *dst)
  ...
  #endif

So, if elf_getphdrnum() is being defined somewhere, there is a problem
with the test that is not detecting that function, go fix it.

Signed-off-by: Rafael Aquini <aquini@redhat.com>