[acpi] x86: Export 'boot_cpu_physical_apicid' to modules
Message-id: <1408594432-28006-13-git-send-email-ruwang@redhat.com>
Patchwork-id: 88489
O-Subject: [PATCH RHEL7.1 BZ1076655 12/17] x86: Export 'boot_cpu_physical_apicid' to modules
Bugzilla: 1076655
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: "Chen, Gong" <gong.chen@linux.intel.com>

Backport of:
Original commit: cc08e04c3fdcaab767b8db27527002b2b4d758cb
Original Author: David Rientjes <rientjes@google.com>
Original Date: Thu, 14 Nov 2013 15:05:32 -0800

	Commit 9ebddac7ea2a "ACPI, x86: Fix extended error log driver to depend on
	CONFIG_X86_LOCAL_APIC" fixed a build error when CONFIG_X86_LOCAL_APIC was not
	selected and !CONFIG_SMP.

	However, since CONFIG_ACPI_EXTLOG is tristate, there is a second build error:

	  ERROR: "boot_cpu_physical_apicid" [drivers/acpi/acpi_extlog.ko] undefined!

	The symbol needs to be exported for it to be available.

Signed-off-by: Chen, Gong <gong.chen@linux.intel.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>