[virtio] virtio-pci: move probe/remove code to common
Message-id: <1434102153-8864-106-git-send-email-jasowang@redhat.com>
Patchwork-id: 118010
O-Subject: [RHEL7.2 PATCH V2 105/145] virtio_pci: move probe/remove code to common
Bugzilla: 1227339
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Michael S. Tsirkin <mst@redhat.com>

From: "Michael S. Tsirkin" <mst@redhat.com>

Notes: a build warning (error in RHEL7) will be met with this patch.

drivers/virtio/virtio_pci_common.c: In function virtio_pci_remove:
drivers/virtio/virtio_pci_common.c:538:2: error: passing argument 1 of
virtio_pci_legacy_remove from incompatible pointer type [-Werror]
  virtio_pci_legacy_remove(pci_dev);
  ^
In file included from drivers/virtio/virtio_pci_common.c:20:0:
drivers/virtio/virtio_pci_common.h:131:6: note: expected struct
virtio_pci_device * but argument is of type struct pci_dev *
 void virtio_pci_legacy_remove(struct virtio_pci_device *);
      ^
cc1: all warnings being treated as errors

This will be fixed in patch "virtio_pci: modern driver".

Most of initialization is device-independent.
Let's move it to common.

Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
(cherry picked from commit ff31d2e28549c84d53252b3c36b6f0ba18b78697)
Signed-off-by: Rafael Aquini <aquini@redhat.com>