[netdrv] mlx5e: skip loopback selftest with !CONFIG_INET
Message-id: <1488853076-16738-128-git-send-email-ddutile@redhat.com>
Patchwork-id: 171838
O-Subject: [PATCH RHEL-7.4 127/340] net/mlx5e: skip loopback selftest with !CONFIG_INET
Bugzilla: 1386660 1385330 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385330
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1386660

commit d709b2a186761bc038c99c2f744c7218f2d249bd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Nov 30 22:05:39 2016 +0100

    net/mlx5e: skip loopback selftest with !CONFIG_INET

    When CONFIG_INET is disabled, the new selftest results in a link
    error:

    drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.o: In function `mlx5e_test_loopback':
    en_selftest.c:(.text.mlx5e_test_loopback+0x2ec): undefined reference to `ip_send_check'
    en_selftest.c:(.text.mlx5e_test_loopback+0x34c): undefined reference to `udp4_hwcsum'

    This hides the specific test in that configuration.

    Fixes: 0952da791c97 ("net/mlx5e: Add support for loopback selftest")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>