[netdrv] cxgb4/cxgb4vf/csiostor: Add T4/T5 PCI ID Table
Message-id: <1439248404-16674-25-git-send-email-svemuri@redhat.com>
Patchwork-id: 123196
O-Subject: [PATCH 024/118] cxgb4/cxgb4vf/csiostor: Add T4/T5 PCI ID Table
Bugzilla: 1251611
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1251611

    commit 3fedeab10b3bb09744a6467fe7cd157f055137c3
    Author: Hariprasad Shenai <hariprasad@chelsio.com>
    Date:   Tue Nov 25 08:33:58 2014 +0530

        cxgb4/cxgb4vf/csiostor: Add T4/T5 PCI ID Table

        Add a new file t4_pci_id_tbl.h that contains T4/T5 PCI ID Table so that for all
        drivers that uses T4/T5 PCI functions changes can be done in one place.

        checkpatch.pl script reports following error, which if tried to fix ends up in
        compilation error.

        	ERROR: Macros with complex values should be enclosed in parentheses
        	+#define CH_PCI_DEVICE_ID_TABLE_DEFINE_END \
        	+		{ 0, } \
        	+	}

        	WARNING: added, moved or deleted file(s), does MAINTAINERS need updating?
        	new file mode 100644

        	ERROR: Macros with complex values should be enclosed in parentheses
        	+#define CH_PCI_ID_TABLE_FENTRY(devid) \
        	+	CH_PCI_ID_TABLE_ENTRY((devid) | \
        	+			      ((CH_PCI_DEVICE_ID_FUNCTION) << 8)), \
        	+	CH_PCI_ID_TABLE_ENTRY((devid) | \
        	+			      ((CH_PCI_DEVICE_ID_FUNCTION2) << 8))

        	ERROR: Macros with complex values should be enclosed in parentheses
        	+#define CH_PCI_DEVICE_ID_TABLE_DEFINE_END { 0, } }

        	ERROR: Macros with complex values should be enclosed in parentheses
        	+#define CH_PCI_DEVICE_ID_TABLE_DEFINE_END { 0, } }

        Signed-off-by: Hariprasad Shenai <hariprasad@chelsio.com>
        Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Rafael Aquini <aquini@redhat.com>