[media] v4l2: added missing mutex.h include to v4l2-ctrls.h
Message-id: <1381413926-15908-691-git-send-email-vfalico@redhat.com>
Patchwork-id: 69146
O-Subject: [RHEL7 PATCH 690/820] media: v4l2: added missing mutex.h include to v4l2-ctrls.h
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: a19dec6ea94c036af68c31930c1c92681f55af41
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a19dec6ea94c036af68c31930c1c92681f55af41
Stable: cd08ebc07c7cb27785b94a09e4b441e021ce302f
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=cd08ebc07c7cb27785b94a09e4b441e021ce302f

Description
----------------------------
Backport from linux-3.10.y stable.

From: Andrzej Hajda <a.hajda@samsung.com>
Subject: media: v4l2: added missing mutex.h include to v4l2-ctrls.h

commit a19dec6ea94c036af68c31930c1c92681f55af41 upstream.

This patch fixes following error:
include/media/v4l2-ctrls.h:193:15: error: field '_lock' has incomplete type
include/media/v4l2-ctrls.h: In function 'v4l2_ctrl_lock':
include/media/v4l2-ctrls.h:570:2: error: implicit declaration of
	function 'mutex_lock' [-Werror=implicit-function-declaration]
include/media/v4l2-ctrls.h: In function 'v4l2_ctrl_unlock':
include/media/v4l2-ctrls.h:579:2: error: implicit declaration of
	function 'mutex_unlock' [-Werror=implicit-function-declaration]

Signed-off-by: Andrzej Hajda <a.hajda@samsung.com>
Signed-off-by: Kyungmin Park <kyungmin.park@samsung.com>
Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
Signed-off-by: Mauro Carvalho Chehab <m.chehab@samsung.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit cd08ebc07c7cb27785b94a09e4b441e021ce302f)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>