[net] ethtool: define INT_MAX for userland
Message-id: <1459266986-31005-101-git-send-email-ivecera@redhat.com>
Patchwork-id: 139396
O-Subject: [RHEL7.3 net PATCH 100/113] ethtool.h: define INT_MAX for userland
Bugzilla: 1268334
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: John Greene <jogreene@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ: #1268334

Upstream commit(s):
commit 14e2037902d65213842b4e40305ff54a64abbcb6
Author: Nicolas Dichtel <nicolas.dichtel@6wind.com>
Date:   Fri Mar 4 11:52:19 2016 +0100

    ethtool.h: define INT_MAX for userland

    INT_MAX needs limits.h in userland.
    When ethtool.h is included by a userland app, we got the following error:

    .../usr/include/linux/ethtool.h: In function 'ethtool_validate_speed':
    .../usr/include/linux/ethtool.h:1471:18: error: 'INT_MAX' undeclared (first use in this function)
      return speed <= INT_MAX || speed == SPEED_UNKNOWN
                      ^

    Fixes: e02564ee334a ("ethtool: make validate_speed accept all speeds between 0 and INT_MAX")
    Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
    Acked-by: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>