[tools] perf tools: Fix build with ARCH=x86_64
Message-id: <20170830160540.26618-247-jolsa@redhat.com>
Patchwork-id: 183699
O-Subject: [PATCH RHEL7.5 BZ1480522 246/248] perf tools: Fix build with ARCH=x86_64
Bugzilla: 1480522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1480522
https://bugzilla.redhat.com/show_bug.cgi?id=1480522

upstream
========
commit 7a759cd8e8272ee18922838ee711219c7c796a31
Author: Jiada Wang <jiada_wang@mentor.com>
Date: Sun Apr 9 20:02:37 2017 -0700

description
===========
With commit: 0a943cb10ce78 (tools build: Add HOSTARCH Makefile variable)
when building for ARCH=x86_64, ARCH=x86_64 is passed to perf instead of
ARCH=x86, so the perf build process searchs header files from
tools/arch/x86_64/include, which doesn't exist.

The following build failure is seen:

  In file included from util/event.c:2:0:
    tools/include/uapi/linux/mman.h:4:27: fatal error: uapi/asm/mman.h: No such file or directory
    compilation terminated.

Fix this issue by using SRCARCH instead of ARCH in perf, just like the
main kernel Makefile and tools/objtool's.

Fixes: 0a943cb10ce7 ("tools build: Add HOSTARCH Makefile variable")

RHEL7
=====
Ommiting the BPF and clang hunks, because it's not backported in RHEL7.

Signed-off-by: Rafael Aquini <aquini@redhat.com>