[drm] amdgpu: initialize amdgpu_cgs_acpi_eval_object result value
Message-id: <1471546882-2828-43-git-send-email-rclark@redhat.com>
Patchwork-id: 157121
O-Subject: [RHEL7 drm 42/74] drm/amdgpu: initialize amdgpu_cgs_acpi_eval_object result value
Bugzilla: 1348329 1349064
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Lyude Paul <cpaul@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>

Upstream: since v4.6.5
RHBZ: 1348329

commit 3d14a5756dfc1a50a8615efa55bdf1a32be88781

Author:     Nicolas Iooss <nicolas.iooss_linux@m4x.org>
AuthorDate: Sat Jun 18 22:55:00 2016 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Wed Jul 27 08:42:17 2016 -0700

    drm/amdgpu: initialize amdgpu_cgs_acpi_eval_object result value

    commit 29b9c528b8c295911e8b1e515273e89a2b7fa2d8 upstream.

    amdgpu_cgs_acpi_eval_object() returned the value of variable "result"
    without initializing it first.

    This bug has been found by compiling the kernel with clang.  The
    compiler complained:

        drivers/gpu/drm/amd/amdgpu/amdgpu_cgs.c:972:14: error: variable
        'result' is used uninitialized whenever 'for' loop exits because its
        condition is false [-Werror,-Wsometimes-uninitialized]
                for (i = 0; i < count; i++) {
                            ^~~~~~~~~
        drivers/gpu/drm/amd/amdgpu/amdgpu_cgs.c:1011:9: note: uninitialized
        use occurs here
                return result;
                       ^~~~~~
        drivers/gpu/drm/amd/amdgpu/amdgpu_cgs.c:972:14: note: remove the
        condition if it is always true
                for (i = 0; i < count; i++) {
                            ^~~~~~~~~
        drivers/gpu/drm/amd/amdgpu/amdgpu_cgs.c:864:12: note: initialize the
        variable 'result' to silence this warning
                int result;
                          ^
                           = 0

    Fixes: 3f1d35a03b3c ("drm/amdgpu: implement new cgs interface for acpi
    function")
    Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>