[tools] perf probe: Return errno when not hitting any event
Message-id: <20170830160540.26618-68-jolsa@redhat.com>
Patchwork-id: 183488
O-Subject: [PATCH RHEL7.5 BZ1480522 067/248] perf probe: Return errno when not hitting any event
Bugzilla: 1480522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1480522
https://bugzilla.redhat.com/show_bug.cgi?id=1480522

upstream
========
commit 70946723eeb859466f026274b29c6196e39149c4
Author: Kefeng Wang <wangkefeng.wang@huawei.com>
Date: Fri Mar 17 16:16:32 2017 +0800

description
===========
On old perf, when using 'perf probe -d' to delete an inexistent event,
it returns errno, eg,

  -bash-4.3# perf probe -d xxx  || echo $?
  Info: Event "*:xxx" does not exist.
    Error: Failed to delete events.
  255

But now perf_del_probe_events() will always set ret = 0, different from
previous del_perf_probe_events(). After this, it returns errno again,
eg,

  -bash-4.3# ./perf probe -d xxx  || echo $?
  "xxx" does not hit any event.
    Error: Failed to delete events.
  254

And it is more appropriate to return -ENOENT instead of -EPERM.

Fixes: dddc7ee32fa1 ("perf probe: Fix an error when deleting probes successfully")
Signed-off-by: Rafael Aquini <aquini@redhat.com>