[mmc] MMC_SH_MMCIF should depend on HAS_DMA
Message-id: <1463503488-149391-326-git-send-email-dzickus@redhat.com>
Patchwork-id: 144872
O-Subject: [RHEL7 PATCH 325/725] mmc: MMC_SH_MMCIF should depend on HAS_DMA
Bugzilla: 1127975 1277866 1280133 1286932 1297039
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit 0e7d43786886b0f8419012800f4f1237ae409170
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed Jul 9 20:52:41 2014 +0200

    mmc: MMC_SH_MMCIF should depend on HAS_DMA

    If NO_DMA=y:

        drivers/built-in.o: In function `sh_mmcif_start_dma_tx':
        sh_mmcif.c:(.text+0x5a3286): undefined reference to `dma_map_sg'
        drivers/built-in.o: In function `sh_mmcif_start_dma_rx':
        sh_mmcif.c:(.text+0x5a33fc): undefined reference to `dma_map_sg'
        drivers/built-in.o: In function `sh_mmcif_end_cmd':
        sh_mmcif.c:(.text+0x5a3668): undefined reference to `dma_unmap_sg'

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>