[fs] rbd: silence bogus uninitialized use warning in rbd_acquire_lock()
Message-id: <1507041730-18373-72-git-send-email-idryomov@redhat.com>
Patchwork-id: 187514
O-Subject: [RHEL7.5 fs PATCH 71/91] rbd: silence bogus uninitialized use warning in rbd_acquire_lock()
Bugzilla: 1489426
RH-Acked-by: Sage Weil <sweil@redhat.com>
RH-Acked-by: Jeff Layton <jlayton@redhat.com>

From: Kefeng Wang <wangkefeng.wang@huawei.com>

  drivers/block/rbd.c: In function 'rbd_acquire_lock':
  drivers/block/rbd.c:3602:44: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Silence the warning, found it when built old kernel(3.10) with
OBS(opensuse build service).

Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit 37f13252579389a659ae3ceec8c60f15bdf70f0c)
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>