[net] netfilter: Add dependency on IPV6 for NF_TABLES_INET
Message-id: <5acc1d3f5db1cd578162d342cd9d4660819e93e8.1392916469.git.jbenc@redhat.com>
Patchwork-id: 77158
O-Subject: [RHEL7 net PATCH 41/57] netfilter: Add dependency on IPV6 for NF_TABLES_INET
Bugzilla: 1034791
RH-Acked-by: Jesper Brouer <jbrouer@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1034791
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=7085329

commit 419331d8ff0ff2b009db5cbc2de9e8731828dc49
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Mon Jan 13 13:01:10 2014 -0500

    netfilter: Add dependency on IPV6 for NF_TABLES_INET

    Commit 1d49144c0aa ("netfilter: nf_tables: add "inet" table for
    IPv4/IPv6") allows creation of non-IPV6 enabled .config files that
    will fail to configure/link as follows:

    warning: (NF_TABLES_INET) selects NF_TABLES_IPV6 which has unmet direct dependencies (NET && INET && IPV6 && NETFILTER && NF_TABLES)
    warning: (NF_TABLES_INET) selects NF_TABLES_IPV6 which has unmet direct dependencies (NET && INET && IPV6 && NETFILTER && NF_TABLES)
    warning: (NF_TABLES_INET) selects NF_TABLES_IPV6 which has unmet direct dependencies (NET && INET && IPV6 && NETFILTER && NF_TABLES)
    net/built-in.o: In function `nft_reject_eval':
    nft_reject.c:(.text+0x651e8): undefined reference to `nf_ip6_checksum'
    nft_reject.c:(.text+0x65270): undefined reference to `ip6_route_output'
    nft_reject.c:(.text+0x656c4): undefined reference to `ip6_dst_hoplimit'
    make: *** [vmlinux] Error 1

    Since the feature is to allow for a mixed IPV4 and IPV6 table, it
    seems sensible to make it depend on IPV6.

    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Acked-by: Patrick McHardy <kaber@trash.net>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>