[fs] btrfs: qgroup: allow to remove qgroup which has parent but no child
Message-id: <1459456505-5012-163-git-send-email-billodo@redhat.com>
Patchwork-id: 139884
O-Subject: [RHEL7.3 PATCH V2 BZ 1298680 162/525] [fs] btrfs: qgroup: allow to remove qgroup which has parent but no child.
Bugzilla: 1298680
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

Bugzilla: 1298680
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=10759031
Tested: Locally with fstests

Backport of the following upstream commit:

    commit f5a6b1c53bdd44f79e3904c0f5e59f956b49b2c8
    Author: Dongsheng Yang <yangds.fnst@cn.fujitsu.com>
    Date:   Mon Nov 24 10:27:09 2014 -0500

    btrfs: qgroup: allow to remove qgroup which has parent but no child.

    When a qgroup has parents but no child, it should be removable in
    Theory I think. But currently, we can not remove it when it has
    either parent or child.

    Example:
        # btrfs quota enable /mnt
        # btrfs qgroup create 1/0 /mnt
        # btrfs qgroup create 2/0 /mnt
        # btrfs qgroup assign 1/0 2/0 /mnt
        # btrfs qgroup show -pcre /mnt
    qgroupid rfer  excl  max_rfer max_excl parent  child
    -------- ----  ----  -------- -------- ------  -----
    0/5      16384 16384 0        0        ---     ---
    1/0      0     0     0        0        2/0     ---
    2/0      0     0     0        0        ---     1/0

    At this time, there is no subvol or qgroup depending on it.
    Just a qgroup 2/0 is its parent, but 2/0 can work well without
    1/0. So I think 1/0 should be removalbe. But:
        # btrfs qgroup destroy 1/0 /mnt
    ERROR: unable to destroy quota group: Device or resource busy

    This patch remove the check of qgroup->parent in removing it,
    then we can remove a qgroup when it has a parent.

    Signed-off-by: Dongsheng Yang <yangds.fnst@cn.fujitsu.com>
    Signed-off-by: Chris Mason <clm@fb.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>