[x86] tools: Fix up compiler warnings
Message-id: <1467128659-24486-25-git-send-email-lszubowi@redhat.com>
Patchwork-id: 154175
O-Subject: [RHEL 7.3 BZ 1310154 24/40] x86, tools: Fix up compiler warnings
Bugzilla: 1310154
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Matt Fleming <matt.fleming@intel.com>

The kbuild test robot reported the following errors that were introduced
with commit 993c30a04e20 ("x86, tools: Consolidate #ifdef code"),

  arch/x86/boot/tools/build.c: In function 'update_pecoff_setup_and_reloc':
>> arch/x86/boot/tools/build.c:252:1: error: parameter name omitted
    static inline void update_pecoff_setup_and_reloc(unsigned int) {}
    ^
  arch/x86/boot/tools/build.c: In function 'update_pecoff_text':
>> arch/x86/boot/tools/build.c:253:1: error: parameter name omitted
    static inline void update_pecoff_text(unsigned int, unsigned int) {}
    ^
>> arch/x86/boot/tools/build.c:253:1: error: parameter name omitted

   arch/x86/boot/tools/build.c: In function 'main':
>> arch/x86/boot/tools/build.c:372:2: warning: implicit declaration of function 'efi_stub_entry_update' [-Wimplicit-function-declaration]
    efi_stub_entry_update();
    ^
Signed-off-by: Matt Fleming <matt.fleming@intel.com>

(cherry picked from commit b663a685831905066e3efcb4c173cd8b3f46228b)
For bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1310154
Signed-off-by: Lenny Szubowicz <lszubowi@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>

Conflicts:
	arch/x86/boot/tools/build.c
	RHEL 7 already includes subsequent commits to this file
	which causes differences when a prior commit is applied
	out of order.