[firmware] efi: Work around ia64 build problem with ESRT driver
Message-id: <1497970330-2166-7-git-send-email-prarit@redhat.com>
Patchwork-id: 179957
O-Subject: [RHEL7.4 BZ 1380812 6/9] efi: Work around ia64 build problem with ESRT driver
Bugzilla: 1380812
RH-Acked-by: John Shortt <jshortt@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1380812

Conflicts: This also adds the RHEL x86_64 config file to build the ESRT
driver.  This results these options for x86_64:

|#
|# EFI (Extensible Firmware Interface) Support
|#
|CONFIG_EFI_VARS=y
|CONFIG_EFI_ESRT=y
|CONFIG_EFI_VARS_PSTORE=y
|CONFIG_EFI_VARS_PSTORE_DEFAULT_DISABLE=y
|CONFIG_EFI_RUNTIME_MAP=y
|CONFIG_UEFI_CPER=y

commit 3846c15820a1841225d0245afda4875af23dfbbe
Author: Peter Jones <pjones@redhat.com>
Date:   Fri Jun 5 15:14:54 2015 -0400

    efi: Work around ia64 build problem with ESRT driver

    So, I'm told this problem exists in the world:

     > Subject: Build error in -next due to 'efi: Add esrt support'
     >
     > Building ia64:defconfig ... failed
     > --------------
     > Error log:
     >
     > drivers/firmware/efi/esrt.c:28:31: fatal error: asm/early_ioremap.h: No such file or directory
     >

    I'm not really sure how it's okay that we have things in asm-generic on
    some platforms but not others - is having it the same everywhere not the
    whole point of asm-generic?

    That said, ia64 doesn't have early_ioremap.h .  So instead, since it's
    difficult to imagine new IA64 machines with UEFI 2.5, just don't build
    this code there.

    To me this looks like a workaround - doing something like:

    generic-y += early_ioremap.h

    in arch/ia64/include/asm/Kbuild would appear to be more correct, but
    ia64 has its own early_memremap() decl in arch/ia64/include/asm/io.h ,
    and it's a macro.  So adding the above /and/ requiring that asm/io.h be
    included /after/ asm/early_ioremap.h in all cases would fix it, but
    that's pretty ugly as well.  Since I'm not going to spend the rest of my
    life rectifying ia64 headers vs "generic" headers that aren't generic,
    it's much simpler to just not build there.

    Note that I've only actually tried to build this patch on x86_64, but
    esrt.o still gets built there, and that would seem to demonstrate that
    the conditional building is working correctly at all the places the code
    built before.  I no longer have any ia64 machines handy to test that the
    exclusion actually works there.

    Signed-off-by: Peter Jones <pjones@redhat.com>
    Acked-by: Tony Luck <tony.luck@intel.com>
    Reviewed-by: Guenter Roeck <linux@roeck-us.net>
    (Compile-)Tested-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Matt Fleming <matt.fleming@intel.com>

Cc: Xunlei Pang <xlpang@redhat.com>
Cc: Dave Young <dyoung@redhat.com>
Cc: Peter Jones <pjones@redhat.com>
Cc: Lenny Szubowicz <lszubowi@redhat.com>
Cc: Myron Stowe <mstowe@redhat.com>
Cc: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>