[s390] Fix broken build
Message-id: <1381413926-15908-466-git-send-email-vfalico@redhat.com>
Patchwork-id: 69005
O-Subject: [RHEL7 PATCH 465/820] s390: Fix broken build
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: 215b28a5308f3d332df2ee09ef11fda45d7e4a92
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=215b28a5308f3d332df2ee09ef11fda45d7e4a92
Stable: 9234930d6e89a7671042e6e35e318480d6b82e5f
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=9234930d6e89a7671042e6e35e318480d6b82e5f

Description
----------------------------
Backport from linux-3.10.y stable.

From: Guenter Roeck <linux@roeck-us.net>
Subject: s390: Fix broken build

commit 215b28a5308f3d332df2ee09ef11fda45d7e4a92 upstream.

Fix this build error:

  In file included from fs/exec.c:61:0:
  arch/s390/include/asm/tlb.h:35:23: error: expected identifier or '(' before 'unsigned'
  arch/s390/include/asm/tlb.h:36:1: warning: no semicolon at end of struct or union [enabled by default]
  arch/s390/include/asm/tlb.h: In function 'tlb_gather_mmu':
  arch/s390/include/asm/tlb.h:57:5: error: 'struct mmu_gather' has no member named 'end'

Broken due to commit 2b047252d0 ("Fix TLB gather virtual address range
invalidation corner cases").

Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
[ Oh well. We had build testing for ppc amd um, but no s390  - Linus ]
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 9234930d6e89a7671042e6e35e318480d6b82e5f)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>