[usb] hub: remove assignment from if condition
Message-id: <1462578743-3088-121-git-send-email-torez@redhat.com>
Patchwork-id: 143349
O-Subject: [RHEL7 PATCH BZ1303955 120/364] usb: hub: remove assignment from if condition
Bugzilla: 1303955
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1303955
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=10980762
Testing: on local desktops and laptop systems, and, on some customer platforms.

commit 088a3daeadf6f4123f54d5208b0ec7cbbfc8853f
Author: Kris Borer <kborer@gmail.com>
Date:   Tue Aug 11 11:12:45 2015 -0400

    usb: hub: remove assignment from if condition

    Fix one occurrence of the checkpatch.pl error:

    ERROR: do not use assignment in if condition

    The semantic patch that makes this change is:

    // <smpl>
    @@
    identifier i;
    expression E, E2, E3;
    statement S1, S2;
    binary operator b;
    @@

    + i = E;
      if (
    - (i = E)
    + i
      b
      ... && E2 && E3 ) S1 else S2
    // </smpl>

    Signed-off-by: Kris Borer <kborer@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>