[net] openvswitch: Fix build failure
Message-id: <7d8ec171f588db1218e73504c0e35bbb259a73bc.1434713811.git.jbenc@redhat.com>
Patchwork-id: 120164
O-Subject: [RHEL7.2 net PATCH 058/110] openvswitch: Fix build failure.
Bugzilla: 1156461 1211348
RH-Acked-by: Flavio Leitner <fbl@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1211348
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1156461

commit 8cd4313aa775537f724486d5b7503b4d46c9f012
Author: Pravin B Shelar <pshelar@nicira.com>
Date:   Thu Nov 13 22:21:30 2014 -0800

    openvswitch: Fix build failure.

    Add dependency on INET to fix following build error. I have also
    fixed MPLS dependency.

    ERROR: "ip_route_output_flow" [net/openvswitch/openvswitch.ko]
    undefined!
    make[1]: *** [__modpost] Error 1

    Reported-by: Jim Davis <jim.epost@gmail.com>
    Signed-off-by: Pravin B Shelar <pshelar@nicira.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>