[net] sch_mqprio: Fix build with older gcc.
Message-id: <20171008224128.1458-134-ivecera@redhat.com>
Patchwork-id: 190215
O-Subject: [RHEL7.5 net PATCH 133/466] sch_mqprio: Fix build with older gcc.
Bugzilla: 1445420
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ#1445420

Upstream commit(s):
commit 241deec94425b5e962e2bf8a929d563afda045f7
Author: David S. Miller <davem@davemloft.net>
Date:   Tue Mar 1 17:44:59 2016 -0500

    sch_mqprio: Fix build with older gcc.

      CC [M]  net/sched/sch_mqprio.o
    net/sched/sch_mqprio.c: In function ?mqprio_init?:
    net/sched/sch_mqprio.c:145: error: unknown field ?tc? specified in initializer
    net/sched/sch_mqprio.c:145: warning: missing braces around initializer
    net/sched/sch_mqprio.c:145: warning: (near initialization for ?tc.<anonymous>?)
    make[2]: *** [net/sched/sch_mqprio.o] Error 1
    make[1]: *** [net/sched] Error 2
    make: *** [net] Error 2

    Several people reported this, surround the unnamed union
    member initialization with braces to fix.

    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>