[ethernet] qlcnic: Fix build failure due to undefined reference to `vxlan_get_rx_port'
Message-id: <1408626422-3941-102-git-send-email-cdupuis@redhat.com>
Patchwork-id: 88664
O-Subject: [PATCH RHEL 7.1 101/138] qlcnic: Fix build failure due to undefined reference to `vxlan_get_rx_port'
Bugzilla: 1089352
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Shahed Shaikh <shahed.shaikh@qlogic.com>

Bug 1089352 (https://bugzilla.redhat.com/show_bug.cgi?id=1089352)

net commit id 7f1f6056f2f7293d5108eda905af42df58b78370

Commit 2b3d7b758c687("qlcnic: Add VXLAN Rx offload support") uses
vxlan_get_rx_port() which caused build failure when VXLAN=m.

This patch fixes the build failure by adding dependency on VXLAN
in Kconfig of qlcnic module and use vxlan_get_rx_port() and support
code accordingly.

Signed-off-by: Shahed Shaikh <shahed.shaikh@qlogic.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>