[usb] typec: include linux/device.h in ucsi.h
Message-id: <1508513955-9512-9-git-send-email-torez@redhat.com>
Patchwork-id: 194631
O-Subject: [RHEL7.5 PATCH BZ1456565 08/10] usb: typec: include linux/device.h in ucsi.h
Bugzilla: 1456565
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1456565
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14308538
Testing: on local desktop, Dell Precision 5510 laptop and HP ZBook 15 G3/80D5

commit 86be7f7b2d940ddc18143061e77989b017d93bf8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 30 17:46:16 2017 +0200

    usb: typec: include linux/device.h in ucsi.h

    The new driver causes a build failure in some configurations:

    In file included from /git/arm-soc/drivers/usb/typec/ucsi/trace.h:9:0,
                     from /git/arm-soc/drivers/usb/typec/ucsi/trace.c:2:
    drivers/usb/typec/ucsi/ucsi.h:331:39: error: 'struct device' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

    This includes the required header file.

    Fixes: c1b0bc2dabfa ("usb: typec: Add support for UCSI interface")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
    Reviewed-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>