[net] netfilter: tproxy: fix build with IP6_NF_IPTABLES=n
Message-id: <252020ce2cf90b236360e0ee56835c2a15a7a6cd.1386953959.git.jbenc@redhat.com>
Patchwork-id: 72035
O-Subject: [RHEL7 net PATCH 3/4] netfilter: tproxy: fix build with IP6_NF_IPTABLES=n
Bugzilla: 1035295
RH-Acked-by: Jesper Brouer <jbrouer@redhat.com>
RH-Acked-by: Daniel Borkmann <dborkman@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1035295
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=6727898
Testing: modprobe and rmmod

commit d8b3bfc253d8063fcce9c447ecc4cf3b1735b13a
Author: Florian Westphal <fw@strlen.de>
Date:   Sun Aug 4 11:37:29 2013 +0200

    netfilter: tproxy: fix build with IP6_NF_IPTABLES=n

    after commit 93742cf (netfilter: tproxy: remove nf_tproxy_core.h)

    CONFIG_IPV6=y
    CONFIG_IP6_NF_IPTABLES=n

    gives us:

    net/netfilter/xt_TPROXY.c: In function 'nf_tproxy_get_sock_v6':
    net/netfilter/xt_TPROXY.c:178:4: error: implicit declaration of function 'inet6_lookup_listener'

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>