[sound] alsa: asoc: intel: sst: Remove unused function sst_restore_shim64()
Message-id: <1507829954160572-639-patchset-jkysela@redhat.com>
Patchwork-id: 193119
O-Subject: [RHEL 7.5 PATCH v2 0638/1088] ALSA: ASoC: Intel: sst: Remove unused function sst_restore_shim64()
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Looks like the function has never been used since it was added by commit
b0d94acd634a ("ASoC: Intel: mrfld - add shim save restore"). Removing it
fixes the following warning when building with clang:

sound/soc/intel/atom/sst/sst.c:360:20: error: unused function
'sst_restore_shim64' [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 9a075265c6dc040e2946d21f4f9d082495bd5460)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>