[sound] alsa: pcm: Adjust nine function calls together with a variable assignment
Message-id: <1507829954160572-90-patchset-jkysela@redhat.com>
Patchwork-id: 192007
O-Subject: [RHEL 7.5 PATCH v2 0089/1088] ALSA: pcm: Adjust nine function calls together with a variable assignment
Bugzilla: 1463624
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix the affected source code places.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit c8da9be4a75f1f63024a16b976c5be47405c13dc)
Bugzilla: 1463624
Signed-off-by: Rafael Aquini <aquini@redhat.com>