[netdrv] liquidio: fix build errors when linux/phy*.h is removed from dsa.h
Message-id: <20170907193548.GA21292@felix-thinkpad.cavium.com>
Patchwork-id: 184272
O-Subject: [PATCH v2 RHEL7.5 118/202] net: liquidio: fix build errors when linux/phy*.h is removed from net/dsa.h
Bugzilla: 1451436
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1451436

Upstream Status: linux.git

commit e3bfc6e7baaac3992f62754228128427ac955e3a
Author: Russell King <rmk+kernel@armlinux.org.uk>
Date:   Tue Feb 7 15:03:03 2017 -0800

    net: liquidio: fix build errors when linux/phy*.h is removed from net/dsa.h

    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:30: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:30: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:30: error: type defaults to 'int' in declaration of 'MODULE_AUTHOR'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:30: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:31: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:31: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:31: error: type defaults to 'int' in declaration of 'MODULE_DESCRIPTION'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:31: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:32: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:32: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:32: error: type defaults to 'int' in declaration of 'MODULE_LICENSE'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:32: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:33: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:33: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:33: error: type defaults to 'int' in declaration of 'MODULE_VERSION'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:33: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:36: error: expected ')' before 'int'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:37: error: expected ')' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:325: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:325: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:325: warning: parameter names (without types) in function declaration
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:3250: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:3250: error: type defaults to 'int' in declaration of 'module_init'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:3250: warning: parameter names (without types) in function declaration
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:3251: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:3251: error: type defaults to 'int' in declaration of 'module_exit'
    drivers/net/ethernet/cavium/liquidio/lio_vf_main.c:3251: warning: parameter names (without types) in function declaration
    drivers/net/ethernet/cavium/liquidio/lio_main.c:36: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:36: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:36: error: type defaults to 'int' in declaration of 'MODULE_AUTHOR'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:36: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:37: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:37: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:37: error: type defaults to 'int' in declaration of 'MODULE_DESCRIPTION'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:37: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:38: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:38: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:38: error: type defaults to 'int' in declaration of 'MODULE_LICENSE'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:38: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:39: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:39: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:39: error: type defaults to 'int' in declaration of 'MODULE_VERSION'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:39: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:40: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:40: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:40: error: type defaults to 'int' in declaration of 'MODULE_FIRMWARE'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:40: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:41: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:41: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:41: error: type defaults to 'int' in declaration of 'MODULE_FIRMWARE'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:41: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:42: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:42: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:42: error: type defaults to 'int' in declaration of 'MODULE_FIRMWARE'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:42: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:43: error: expected declaration specifiers or '...' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:43: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:43: error: type defaults to 'int' in declaration of 'MODULE_FIRMWARE'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:43: error: function declaration isn't a prototype
    drivers/net/ethernet/cavium/liquidio/lio_main.c:46: error: expected ')' before 'int'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:48: error: expected ')' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:53: error: expected ')' before 'int'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:54: error: expected ')' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:57: error: expected ')' before 'sizeof'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:58: error: expected ')' before string constant
    drivers/net/ethernet/cavium/liquidio/lio_main.c:498: warning: data definitionhas no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:498: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:498: warning: parameter names (without types) in function declaration
    drivers/net/ethernet/cavium/liquidio/lio_main.c: In function 'octeon_recv_vf_drv_notice':
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4393: error: implicit declaration of function 'try_module_get'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4400: error: implicit declaration of function 'module_put'
    drivers/net/ethernet/cavium/liquidio/lio_main.c: At top level:
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4670: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4670: error: type defaults to 'int' in declaration of 'module_init'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4670: warning: parameter names (without types) in function declaration
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4671: warning: data definition has no type or storage class
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4671: error: type defaults to 'int' in declaration of 'module_exit'
    drivers/net/ethernet/cavium/liquidio/lio_main.c:4671: warning: parameter names (without types) in function declaration

    Add linux/module.h to both these files.

    drivers/net/ethernet/cavium/liquidio/octeon_console.c:40:31: error: expected ')' before 'int'
    drivers/net/ethernet/cavium/liquidio/octeon_console.c:42:4: error: expected ')' before string constant

    Add linux/moduleparam.h to this file.

    Signed-off-by: Russell King <rmk+kernel@armlinux.org.uk>
    Acked-by: Felix Manlunas <felix.manlunas@cavium.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Felix Manlunas <fmanluna@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>