[perf] evlist: Remove extraneous 'was' on error message
Message-id: <1428672113-29331-169-git-send-email-jolsa@redhat.com>
Patchwork-id: 109799
O-Subject: [PATCH RHEL7.2 BZ1209607 168/220] perf evlist: Remove extraneous 'was' on error message
Bugzilla: 1209607
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1209607
https://bugzilla.redhat.com/show_bug.cgi?id=1209607

upstream
========
commit 267b677eec06de178558337f0074e30ec3d11d9b
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Jan 19 11:54:06 2015 -0300

description
===========
  [acme@mica ~]$ trace -p 3330
  Error:  Unable to find debugfs
  Hint:   Was your kernel was compiled with debugfs support?
                          ^^^
                          ^^^
  Hint:   Is the debugfs filesystem mounted?
  Hint:   Try 'sudo mount -t debugfs nodev /sys/kernel/debug'

Fix it.

Signed-off-by: Rafael Aquini <aquini@redhat.com>