[tools] perf/probe: Fix build when DWARF support libraries not present
Message-id: <1408953210-26343-253-git-send-email-jolsa@redhat.com>
Patchwork-id: 89028
O-Subject: [PATCH RHEL7.1 BZ1133083 252/322] perf probe: Fix build when DWARF support libraries not present
Bugzilla: 1133083
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1133083
https://bugzilla.redhat.com/show_bug.cgi?id=1133083

upstream
========
commit 1d027ee9b80c30e83769ef306ccfafe483dd1672
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Jan 13 15:15:25 2014 -0300

description
===========
On a freshly installed system, after libelf-dev is installed we get:

    CC       /tmp/build/perf/util/probe-event.o
  util/probe-event.c: In function 'try_to_find_probe_trace_events':
  util/probe-event.c:753:46: error: unused parameter 'target' [-Werror=unused-parameter]
       int max_tevs __maybe_unused, const char *target)
                                                ^
    CC       /tmp/build/perf/util/cgroup.o
  util/probe-event.c: At top level:
  util/probe-event.c:193:12: error: 'get_text_start_address' defined but not used [-Werror=unused-function]
   static int get_text_start_address(const char *exec, unsigned long *address)
            ^
  cc1: all warnings being treated as errors
  make[1]: *** [/tmp/build/perf/util/probe-event.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  make: *** [install] Error 2

Fix it by enclosing functions only used when those libraries are installed
under the suitable preprocessor define and using __maybe_unused to a function
that is only built when DWARF support is disabled.

Problem introduced in this changeset:

  commit fb7345bbf7fad9bf72ef63a19c707970b9685812
  Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
  Date:   Thu Dec 26 05:41:53 2013 +0000

      perf probe: Support basic dwarf-based operations on uprobe events

Signed-off-by: Jarod Wilson <jarod@redhat.com>