[edac] pnd2_edac: Fix !EDAC_DEBUG build
Message-id: <20170918182911.192244482@redhat.com>
Patchwork-id: 185533
O-Subject: [RHEL7.5 PATCH 02/11] EDAC, pnd2_edac: Fix !EDAC_DEBUG build
Bugzilla: 1479627 1273769
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ#1273769
BZ#1479627
beaker: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14062537
Tested: by me on a beaker system
Upstream status: cd1be315ac9766fe83e4fb788d5d9fe032a9b877

commit cd1be315ac9766fe83e4fb788d5d9fe032a9b877
Author: Borislav Petkov <bp@suse.de>
Date:   Sat Mar 18 18:26:34 2017 +0100

    EDAC, pnd2_edac: Fix !EDAC_DEBUG build

    Provide debugfs function stubs when EDAC_DEBUG is not enabled so that we
    don't fail the build:

      drivers/edac/pnd2_edac.c: In function 'pnd2_init':
      drivers/edac/pnd2_edac.c:1521:2: error: implicit declaration of function 'setup_pnd2_debug' [-Werror=implicit-function-declaration]
	setup_pnd2_debug();
	^
      drivers/edac/pnd2_edac.c: In function 'pnd2_exit':
      drivers/edac/pnd2_edac.c:1529:2: error: implicit declaration of function 'teardown_pnd2_debug' [-Werror=implicit-function-declaration]
	teardown_pnd2_debug();
	^

    Signed-off-by: Borislav Petkov <bp@suse.de>

Signed-off-by: Rafael Aquini <aquini@redhat.com>