[fs] btrfs: incremental send, don't rename a directory too soon
Message-id: <1459456505-5012-70-git-send-email-billodo@redhat.com>
Patchwork-id: 140076
O-Subject: [RHEL7.3 PATCH V2 BZ 1298680 069/525] [fs] Btrfs: incremental send, don't rename a directory too soon
Bugzilla: 1298680
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

Bugzilla: 1298680
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=10759031
Tested: Locally with fstests

Backport of the following upstream commit:
    commit 84471e2429ed82fdbac0c56d5b2a18d450f99f6a
    Author: Filipe Manana <fdmanana@suse.com>
    Date:   Sat Feb 28 22:29:22 2015 +0000

    Btrfs: incremental send, don't rename a directory too soon

    There's one more case where we can't issue a rename operation for a
    directory as soon as we process it. We used to delay directory renames
    only if they have some ancestor directory with a higher inode number
    that got renamed too, but there's another case where we need to delay
    the rename too - when a directory A is renamed to the old name of a
    directory B but that directory B has its rename delayed because it
    has now (in the send root) an ancestor with a higher inode number that
    was renamed. If we don't delay the directory rename in this case, the
    receiving end of the send stream will attempt to rename A to the old
    name of B before B got renamed to its new name, which results in a
    "directory not empty" error. So fix this by delaying directory renames
    for this case too.

    Steps to reproduce:

      $ mkfs.btrfs -f /dev/sdb
      $ mount /dev/sdb /mnt

      $ mkdir /mnt/a
      $ mkdir /mnt/b
      $ mkdir /mnt/c
      $ touch /mnt/a/file

      $ btrfs subvolume snapshot -r /mnt /mnt/snap1

      $ mv /mnt/c /mnt/x
      $ mv /mnt/a /mnt/x/y
      $ mv /mnt/b /mnt/a

      $ btrfs subvolume snapshot -r /mnt /mnt/snap2

      $ btrfs send /mnt/snap1 -f /tmp/1.send
      $ btrfs send -p /mnt/snap1 /mnt/snap2 -f /tmp/2.send

      $ mkfs.btrfs -f /dev/sdc
      $ mount /dev/sdc /mnt2
      $ btrfs receive /mnt2 -f /tmp/1.send
      $ btrfs receive /mnt2 -f /tmp/2.send
      ERROR: rename b -> a failed. Directory not empty

    A test case for xfstests follows soon.

    Reported-by: Ames Cornish <ames@cornishes.net>
    Signed-off-by: Filipe Manana <fdmanana@suse.com>
    Signed-off-by: Chris Mason <clm@fb.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>