[hid] wacom: Have wacom_tpc_irq guard against possible NULL dereference
Message-id: <20171016134346.374771230@redhat.com>
Patchwork-id: 193789
O-Subject: [RHEL7.5 PATCH 63/81] HID: wacom: Have wacom_tpc_irq guard against possible NULL dereference
Bugzilla: 1475409 1462363
RH-Acked-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1462363
BZ#1475409
brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14264975
Tested: by myself with ExpressKeys remote

commit 2ac97f0f6654da14312d125005c77a6010e0ea38
Author: Jason Gerecke <killertofu@gmail.com>
Date:   Tue Apr 25 11:29:56 2017 -0700

    HID: wacom: Have wacom_tpc_irq guard against possible NULL dereference

    The following Smatch complaint was generated in response to commit
    2a6cdbd ("HID: wacom: Introduce new 'touch_input' device"):

        drivers/hid/wacom_wac.c:1586 wacom_tpc_irq()
                 error: we previously assumed 'wacom->touch_input' could be null (see line 1577)

    The 'touch_input' and 'pen_input' variables point to the 'struct input_dev'
    used for relaying touch and pen events to userspace, respectively. If a
    device does not have a touch interface or pen interface, the associated
    input variable is NULL. The 'wacom_tpc_irq()' function is responsible for
    forwarding input reports to a more-specific IRQ handler function. An
    unknown report could theoretically be mistaken as e.g. a touch report
    on a device which does not have a touch interface. This can be prevented
    by only calling the pen/touch functions are called when the pen/touch
    pointers are valid.

    Fixes: 2a6cdbd ("HID: wacom: Introduce new 'touch_input' device")
    Signed-off-by: Jason Gerecke <jason.gerecke@wacom.com>
    Reviewed-by: Ping Cheng <ping.cheng@wacom.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Rafael Aquini <aquini@redhat.com>