[tools] lib/lk: Uninclude linux/magic.h in debugfs.c
Message-id: <1381413926-15908-783-git-send-email-vfalico@redhat.com>
Patchwork-id: 69393
O-Subject: [RHEL7 PATCH 782/820] tools lib lk: Uninclude linux/magic.h in debugfs.c
Bugzilla: 1006938
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ: 1006938
Upstream: ce7eebe5c3deef8e19c177c24ee75843256e69ca
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ce7eebe5c3deef8e19c177c24ee75843256e69ca
Stable: 655325c7e4f62ece9bea61e5b24d8118d6e09ef1
http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=655325c7e4f62ece9bea61e5b24d8118d6e09ef1

Description
----------------------------
Backport from linux-3.10.y stable.

From: Vinson Lee <vlee@twitter.com>
Subject: tools lib lk: Uninclude linux/magic.h in debugfs.c

commit ce7eebe5c3deef8e19c177c24ee75843256e69ca upstream.

The compilation only looks for linux/magic.h from the default include
paths, which does not include the source tree. This results in a build
error if linux/magic.h is not available or not installed.

For example, this build error occurs on CentOS 5.

$ make -C tools/lib/lk V=1
[...]
gcc -o debugfs.o -c -ggdb3 -Wall -Wextra -std=gnu99 -Werror -O6
-D_FORTIFY_SOURCE=2 -Wbad-function-cast -Wdeclaration-after-statement
-Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations
-Wmissing-prototypes -Wnested-externs -Wno-system-headers
-Wold-style-definition -Wpacked -Wredundant-decls -Wshadow
-Wstrict-aliasing=3 -Wstrict-prototypes -Wswitch-default -Wswitch-enum
-Wundef -Wwrite-strings -Wformat  -fPIC  -D_LARGEFILE64_SOURCE
-D_FILE_OFFSET_BITS=64 debugfs.c
debugfs.c:8:25: error: linux/magic.h: No such file or directory

The only symbol from linux/magic.h needed by debugfs.c is DEBUGFS_MAGIC,
and that is already defined in debugfs.h. linux/magic.h isn't providing
any extra symbols and can unincluded. This is similar to the approach by
perf, which has its own magic.h wrapper at
tools/perf/util/include/linux/magic.h

Signed-off-by: Vinson Lee <vlee@twitter.com>
Acked-by: Borislav Petkov <bp@suse.de>
Cc: Borislav Petkov <bp@suse.de>
Cc: Vinson Lee <vlee@freedesktop.org>
Link: http://lkml.kernel.org/r/1379546200-17028-1-git-send-email-vlee@freedesktop.org
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit 655325c7e4f62ece9bea61e5b24d8118d6e09ef1)
---

Signed-off-by: Jarod Wilson <jarod@redhat.com>